### ISSUE TITLE
Examples sync with "localhost:10102" but don't say what that is

### ISSUE THREAD

**Issue by jaredly** [pubkey/rxdb#11]
Is that just a locally running couchdb instance? And if it is, maybe put that in the Readmes?

**Comment by pubkey** [comment]
Its a local running [pouchdb-server](https://github.com/pouchdb/pouchdb-server).

I dont think this must be written in the readme because the other things that happen at ```npm start``` are also not written down. The examples exist that people can dig into a definitely working code.
