### ISSUE TITLE
Interest in adding `standard-version` and `commititzen` for commit message and automate changelog?

### ISSUE THREAD

**Issue by phil-lgr** [pubkey/rxdb#1104]
## Case
Interest in adding `standard-version` and `commititzen` for commit message and automate changelog?

## Issue
I want to help improve the repo, the commit messages could be standardized

## Code

In my repos I use [standard-version](https://www.npmjs.com/package/standard-version) to automate changelog generation and [commitizen](https://www.npmjs.com/package/commitizen)  to format all commit messages

The scripts could look like this:

```json
{
    "commit": "git-cz",
    "changelog": "standard-version",
    "release": "git push --follow-tags"
}
```

so you commit with 
```bash
npm run commit

# output
[git] committing with git-cz
cz-cli@3.1.1, cz-conventional-changelog@2.1.0


Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing: (Use arrow keys)
❯ feat:     A new feature 
  fix:      A bug fix 
  docs:     Documentation only changes 
  style:    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc) 
  refactor: A code change that neither fixes a bug nor adds a feature 
  perf:     A code change that improves performance 
  test:     Adding missing tests or correcting existing tests 
(Move up and down to reveal more choices)
```

which is a great DX IMO 🔥 

when a few fixes or features have been merged in master, you do:

```bash
npm run changelog
npm run release
```

which update the package.json version according to SemVer and also the CHANGELOG.md and push commits and tags.

if you want me to prepare a PR with those I'd be happy to do so!

**Comment by phil-lgr** [comment]
what I like with this setup is that it's not 100% automatic, you can review the changelog and add more human friendly information before publishing the changelog looks like this:

![image](https://user-images.githubusercontent.com/9644867/57232022-c2eebe00-6fe9-11e9-8efa-f6b51286fb8f.png)

**Comment by pubkey** [comment]
Hi @phil-lgr thank you for your effort.
I know commititzen and think it is realy helpfull for projects with many developer who tend to have a different commit-style.

However RxDB is mostly developed by a single person so this is solving a problem we do not have.
Also I do not want to increase the hurdle for new contributors.

I think adapting these standards is good for big projects and I would do that on my day-job. But for an open-source-project the complexity is not worth it.
