### ISSUE TITLE
Docs question: col.query() undocumented?

### ISSUE THREAD

**Issue by rdworth** [pubkey/rxdb#113]
## Case
Docs question

## Issue
Not sure why .query() is now undocumented (as of 9b4f838481bfd3344f7192b81bff27bbab8c2d91) if it still exists. I encountered it in the VanillaJS example (https://github.com/pubkey/rxdb/blob/master/examples/vanilla/main.js#L62) and wasn't sure what it did since I hadn't seen it in the docs. Went looking for it in https://github.com/pubkey/rxdb/blob/master/docs/RxCollection.md and saw that it had recently been removed.

What's the story? Thanks.

**Comment by pubkey** [comment]
Hi @rdworth 
`query()` was removed since it does exactly the same as `find()`. 
I pushed [290f88f](https://github.com/pubkey/rxdb/commit/290f88fa8f8fdd74953f92778d637ddcba11c943) which remoes the remaining usage.
