### ISSUE TITLE
Allow multiple databases on the same port

### ISSUE THREAD

**Issue by josiahruddell** [pubkey/rxdb#1141]
## Case

Enhancement

## Issue

Cannot connect multiple databases to the same server/app running the same port through rxdb.

## Info
  - Environment: Node.js
  - Adapter: All
  - Stack: Typescript

## Code

```typescript
const db1 = await DB.create({
  name: 'db1',
})

// add some collections to db1

const db2 = await DB.create({
  name: 'db2',
})

// add some collections to db2
```

Create a server on the nodeJS side...

```typescript

db1.server({
  path: `/${db1}`,
  port: 3000,
})


db2.server({ // throws port in use
  path: `/${db2}`,
  port: 3000,
})

```

The feature request is to allow multiple calls to `db.server` with the same port and different paths.

**Comment by josiahruddell** [comment]
I was looking through the code and would be happy to put up a PR but want to get the convo going here first.

**Comment by pubkey** [comment]
Hi @josiahruddell great idea.
I think we should make it possible to pass any express-instance when calling `RxDatabase.server()`. by this people could also run the rxdb-server and the rest-endpoint on the same port.

To serve two rxdb-databases on the same port, we could then do

```js

const server1 = db1.server({
  path: `/${db1}`,
  port: 3000,
})


db2.server({
  path: `/${db2}`,
  express: server1.app
})
```

What do you think?

**Comment by pubkey** [comment]
@josiahruddell have you started on this?
Coincidentally I also need this feature for my project. So I would implement it if you haven't.

**Comment by josiahruddell** [comment]
Yeah I'll open a PR there are some TODOs still

**Comment by pubkey** [comment]
Closed see https://github.com/pubkey/rxdb/pull/1156#issuecomment-517942797
