### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by chovy** [pubkey/rxdb#116]
```
async function createDb(){
  const RxDB = require('rxdb');
  RxDB.plugin(require('pouchdb-adapter-websql'));
  const db = await RxDB.create({
    name: 'testdb',
    adapter: 'websql',
    password: 'asdfasdf', // optional
    multiInstance: true                  // default: true
  });

  const mySchema = {
    disableKeyCompression: true,
    version: 0,
    title: 'things schema',
    type: 'object',
    properties: {
      title: {
        type: 'string'
      },
      link: {
        type: 'string'
      },
      date: {
        type: 'date'
      }
    },
    required: ['title', 'link']
  };

  return await db.collection({name: 'things', schema: mySchema});    // create collection
}

```

I get an error when running this: `ReferenceError: regeneratorRuntime is not defined`

I'm using node v7.7

**Comment by pubkey** [comment]
I think you forgot the polyfills
```js
require("babel-polyfill");
```

**Comment by chovy** [comment]
Do I need that? I only want to use native node v7.

**Comment by pubkey** [comment]
You are right. I will inspect.

**Comment by pubkey** [comment]
Btw Websql does not work in nodejs. You need another adapter here

**Comment by chovy** [comment]
I'm new, just following the getting started. What adapter should I use with node.js?

**Comment by chovy** [comment]
I think we need a node.js example: https://github.com/pubkey/rxdb/tree/master/examples

I'm confused. Does this library not work with node.js?

**Comment by pubkey** [comment]
Yes, this lib works with nodejs. All tests run in nodejs and the browsers :)
Yes we need a nodejs example.
To play around I recommend the memory-adapter. For persistent storage use the leveldb-adapter.


leveldown = require('leveldown');
leveldb = require('pouchdb-adapter-leveldb');
RxDB.plugin(leveldb);

**Comment by pubkey** [comment]
@chovy I inspected the issue. I'm sorry, but for some reason you need the `babel-polyfill` at the moment, the build does not include the runtime-regenerators.

Here is a working example with rxdb and leveldown.

```bash
npm i rxdb rxjs babel-polyfill pouchdb-adapter-leveldb leveldown --save
```

```javascript
require('babel-polyfill');

const RxDB = require('rxdb');
RxDB.plugin(require('pouchdb-adapter-leveldb'));
const leveldown = require('leveldown');

async function createDb() {
    const db = await RxDB.create({
        name: './testdb',
        adapter: leveldown, // leveldb-adapter must be passed directly instead of the name
        password: 'asdfasdf', // optional
        multiInstance: true // default: true
    });

    const mySchema = {
        disableKeyCompression: true,
        version: 0,
        title: 'things schema',
        type: 'object',
        properties: {
            title: {
                type: 'string'
            },
            link: {
                type: 'string'
            },
            date: {
                type: 'date'
            }
        },
        required: ['title', 'link']
    };


    await db.collection({
        name: 'things',
        schema: mySchema
    }); // create collection

    console.dir(db.things);

    return;
}

async function run(){
  await createDb();
}

run();

```

**Comment by chovy** [comment]
I have a question. I have a pouchdb server, can I point to that? When I run this example code it seems to create its own database in the current directory.

**Comment by pubkey** [comment]
I'm sorry, but you can not just use the same folder. If you want to use pouch-server-data with rxdb, you have to [sync](https://github.com/pubkey/rxdb/blob/master/docs/RxCollection.md#sync).
