### ISSUE TITLE
collection.insert() does not throw a RxError, it throws a PouchDB error

### ISSUE THREAD

**Issue by phil-lgr** [pubkey/rxdb#1162]
## Case
Inserting a document

## Issue

when there is an existing document (409)
```js
db.collection.insert(doc)
```
 does not throw a RxError, it throws a PouchDB error.

we have `COL1` error for this case: https://github.com/pubkey/rxdb/blob/master/dist/es/plugins/error-messages.js#L44

## Info
  - Environment: browser
  - Adapter: IndexedDB

## Code

we should add error handling on https://github.com/pubkey/rxdb/blob/master/src/rx-collection.js#L364 so we return RxError instead of plain PouchDB errors (which are not documented AFAIK)

**Comment by pubkey** [comment]
This means that we have to parse all pouchdb-errors and map them to the correct RxError. I do not know if this is worth the work.

**Comment by phil-lgr** [comment]
What is not clear: 

 - where do we have RxErrors
 - where do we have plain PouchDB errors

IMO since RxDB is a layer (and a good one) on top of PouchDB, we should aim to provide a consistent interface

**Comment by pubkey** [comment]
The `RxError` was introduced to split out the error-messages which where hard to compress and therefore increased the build-size. At this point in time I just replaced all errors thrown in RxDB with an `RxError`.
I do not think that parsing pouchdb errors is maintainable. I think this would mean we have to run regexes over the thrown error.

**Comment by phil-lgr** [comment]
yea, I don't like that PouchDB errors are not really documented anywhere, maybe I missed it?
