### ISSUE TITLE
Querying an encrypted field with an unencrypted value doesn't return matching records

### ISSUE THREAD

**Issue by rmisio** [pubkey/rxdb#1173]
## Case
It's a bug.

## Issue
Steps to reproduce:

- create a collection with an encrypted field
- insert a record
- attempt to query filtering the result set based on the encrypted field. For example, if the encrypted field is `color` and your record has a value of `orange`, attempt to query the record via `db.collections.myCol.find({ color: { $eq: 'orange' } })`.

Observed:

- the record is not returned

Expected:

- the record is returned.

NOTES:

-  querying via an unencrypted field works as expected.
- it's possible if I query the encrypted field via the *encrypted* value, it would work... but what type of UX would that be?

## Info
  - Environment: browser
  - Adapter: IndexedDB
  - Stack: React

## Code

Here is a test which reproduces the issue:

https://github.com/rmisio/rxdb/blob/bug-cant-find-via-encryptd-field/test/unit/find-encrypted-field.test.js

**Comment by pubkey** [comment]
You cannot query over encrypted fields. I think this information is missing in the docs.
You could use the [in-memory-collection](https://rxdb.info/in-memory.html#encryption) which decrypted the fields and makes them queryable.

**Comment by rmisio** [comment]
@pubkey Should I be able to query an in-memory field that is encrypted and indexed?

Because I can't. If I update the field so it's not indexed, then I find it.

**Comment by pubkey** [comment]
@rmisio I added this to the docs, you cannot run queries over encrypted fields.
This should work in the in-memory-collection. Please open another issue if it does not.
