### ISSUE TITLE
leader election work wrong

### ISSUE THREAD

**Issue by mccoysc** [pubkey/rxdb#1185]
1，======================================
start server using the following code:
const RxDB = require("rxdb");
RxDB.plugin(require("rxdb/plugins/server"));
RxDB.plugin(require('pouchdb-adapter-node-websql'));
RxDB.create({
    name: 'heroesdb',
    adapter: "websql",
    QueryChangeDetection: true,
}).then(function (db) {
    global.dbState = db.server({
        path: "/",
        port: 10102,
        cors: true
    });
});

2、==========================
in browser:
RxDB
    .create({
        name: 'heroesdb',
        adapter: 'idb',
        password: 'myLongAndStupidPassword'
    })
    .then(function (db) {
        db.waitForLeadership().then(function () {
            console.log("as leader!!!");
        });
        return db.collection({
            name: 'hero',
            schema: heroSchema
        });
    }).then(function(col){
           col.sync({remote:"http://127.0.0.1:10102/"});
    });;

3，=================================
run the code in browser A and then run the code in browser B(not 2 tabs of the same browser,but 2 tabs in 2 different bowsers).

4，====================================
the all 2 tabs in 2 different browsers would all get "leader-ship".

in fact,it's the example of https://github.com/pubkey/rxdb/tree/master/examples/vanilla,it just work well in 2 tabs of the same browser,but not in 2 tabs of 2 differente browsers.

**Comment by pubkey** [comment]
The leader election is implemented via the  [broadcast-channel module](https://github.com/pubkey/broadcast-channel#using-the-leaderelection).
The leader is elected between different processes on the same javascript-runtime. Like multiple tabs in the same browser or mupltiple NodeJs-processes on the same machine. It will not run between different replicated instances.

I updated the docs to make this clear.
