### ISSUE TITLE
Aggregate functions

### ISSUE THREAD

**Issue by Xrymz** [pubkey/rxdb#123]
Does anyone know how to create aggregate functions, for example count, avg, sum, max and min in RxDB or any examples of map/reduce? i try to get count of all docs in collection and count of docs in filtered query

**Comment by pubkey** [comment]
Hi, @Xrymz there is currently no build-in support for aggregate functions.
You would have to build them by your self.
```js
const count$ = myCollection.find().where('age').gt(10).$
  .filter(results => results !=null)
  .map(results => results.length)
```

**Comment by tonyxiao** [comment]
@pubkey have there been any alternatives since then?

**Comment by tonyxiao** [comment]
Also, are there any performance advantage in terms of either IO or memory by integrating with the underlying `query` api for map reduce in pouchdb, as oppose to retrieving all the raw documents just to aggregate a sum / count?

**Comment by pubkey** [comment]
@tonyxiao 
You can now use the [ORM](https://rxdb.info/orm.html) functions of a `RxCollection` or you can create your own [plugins](https://rxdb.info/plugins.html) which adds the functions to RxDB.

There might be some performance benefits with plain pouchdb, depending on what your function does.
But you have to test that careful. For example pouchdb with the indexeddb-adapter will likely not be faster. The full document has to be retrieved to check if it matches the query and only then it can be counted.

**Comment by tonyxiao** [comment]
Got it. Is there a way to stream documents when doing aggregation so the entire dataset doesn't need to be kept in memory?

**Comment by pubkey** [comment]
No there is no streaming over query results. Queries use map-reduce imternally and for the reduce-part, the whole dataset must be known. You can use the limit- and skip-operator for pagination and then batch the query output.
