### ISSUE TITLE
React example dont work

### ISSUE THREAD

**Issue by LestaD** [pubkey/rxdb#124]
## Case
I can't run react example

## Info
- Environment: Node.js v7.7.4

## Steps
```bash
git clone git@github.com:pubkey/rxdb.git
cd rxdb/examples/react
npm install
npm start
```

![image](https://cloud.githubusercontent.com/assets/5620073/24446691/1537d3b6-1477-11e7-9de1-7bed4acff5ff.png)

**Comment by pubkey** [comment]
I think you forgot step 2 and 3 of the [readme](https://github.com/pubkey/rxdb/tree/master/examples/react)

Please reopen if this does not help

**Comment by LestaD** [comment]
Oh yes. Thank you
