### ISSUE TITLE
How to define {id: obj} schema ?

### ISSUE THREAD

**Issue by leozale** [pubkey/rxdb#1267]
## Issue
How to define {id: obj} schema ?
## Code

example
```js
{
     nodes: {
            "id_001": node1,  // node is a RXDocument 
            "id_abc": node2,
             "id_obj":  node3  
     }
}
```

**Comment by pubkey** [comment]
I do not understand the problem. The primary key must be a string so it is sortable and unique.

Plese look at the issue template:

>   If you have a common question which cannot be solved with a PR, ask it at one of these places:
>   - https://stackoverflow.com/
>   - https://gitter.im/pubkey/rxdb
