### ISSUE TITLE
Conditionally allow inserts to bypass schema validation

### ISSUE THREAD

**Issue by jaredly** [pubkey/rxdb#13]
I have the case where I want to have a "singleton" document within my collection - something that is different from the other documents in the collection, but ought to (for authentication reasons) be closely associated with the collection.
In normal pouch/couch, I would just insert the document with a fixed ID, say `settings` or something. I'd love to be able to do that in rxdb as well.
Without this functionality, I'll be forced to just define an essentially empty schema, which loses a lot of the benefits :/

**Comment by pubkey** [comment]
Hi @jaredly You can use the underlaying pouchdb directly. Example:

```js
myRxCollection.put({_id: 'settings'});
```

But be carefull because col.find() etc. would also find your custom document.

**Comment by jaredly** [comment]
thanks!
