### ISSUE TITLE
RxDB change handlers do not fire on bulkDocs() operations

### ISSUE THREAD

**Issue by rmisio** [pubkey/rxdb#1303]
## Case
bug

## Issue
When you make `bulkDocs()` changes to insert or update documents the pouchDb change handlers fire, but RxDB ones do not.

```
        db.heroes.pouch
            .changes({
                live: true,
                since: 'now',
            })
            .on('change', () => {
                // this fires
            });

        db.heroes.$.subscribe(() => {
            // this does not fire
        });

        db.heroes.pouch.bulkDocs(data);
```

Here's a test showing the issue:

https://github.com/rmisio/rxdb/blob/bug-change-event-buk-docs/test/unit/bulkdocs-change-event.test.js

## Info
  - Environment: browser
  - Adapter: IndexedDB
  - Stack: React, VanillaJS

**Comment by pubkey** [comment]
https://rxdb.info/custom-build.html#watch-for-changes

**Comment by rmisio** [comment]
Good to know. Thanks.
