### ISSUE TITLE
Browser 6 connection limit?

### ISSUE THREAD

**Issue by jefbarn** [pubkey/rxdb#132]
Hi,
I'm investigating using rxdb for my app because is really fits in with my current stack (pouch/couch + angular).  My first concern is I notice that you save each collection as a separate couch/pouch database. How do you get around the problem of having more than 6 collections would lock your browser because it couldn't create any more replication connections?
I guess the obvious answer is to use socket-pouch?

**Comment by pubkey** [comment]
Please do not create issues for support-requests.
If something has no chance to result in a pull-request, do not open an issue for it.

For basic support, please use our [gitter-channel](https://gitter.im/pubkey/rxdb).
