### ISSUE TITLE
[docs] Clarify how to clear data

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#133]
## Case
docs

## Issue
I've changed a schema and deleted data from couchdb, but not sure how to delete it locally in pouchdb so it will reset. Docs don't really point to interacting with that (just migration).

**Comment by pubkey** [comment]
Hi @natew 
If you want to delete all documents when you change the schema, you can do this by creating a migration-strategy which says `delete all docs`

See [here](https://github.com/pubkey/rxdb/blob/master/docs/DataMigration.md)
> If the strategy returns null, the document will be removed instead of migrated.

Example code:

```js
myDatabase.collection({
  name: 'messages',
  schema: messageSchemaV1,
  migrationStrategies: {
    // 1 means, this transforms data from version 0 to version 1
    1: function(oldDoc){
      return null; // remove the document
    }
  }
});
```
