### ISSUE TITLE
Published RxDB not up to date

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#134]
## Case
bug

## Issue
npm published version 3.0.7, file: `dist/lib/RxDatabase.js` is not the same as shown in the repo.

## Code
To reproduce just import and try and use the new collection object style:

```js
db.collection({ name: 'test', schema: {} })
```

Error is: `name.charAt doesn't exist`. If you look in the repo here it should be `args.name.charAt`, guessing you just need to publish new version.

**Comment by natew** [comment]
This may be a build issue on my machine, checking

**Comment by pubkey** [comment]
Please tell me the status when you found the problem.

**Comment by natew** [comment]
Was a complex thing, build system was looking up tree erroneously and found earlier version of rxdb, thanks for reply!
