### ISSUE TITLE
Docs for sorts

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#139]
## Case
Making it a bit easier to figure out indexing with RxDB

## Issue
Been trying to create an index and sort by that index for a while with no luck.

I've tried a variety of things like this:

```js
DB._adminPouch.createIndex({ index: { fields: ['doc4.created_at'] }}).then(console.log)
```

And then querying that collection using:

```js
DB.collection({ ... }).then(col => col.find().sort({ created_at: 'asc' })).exec()).then(console.log)
```

With no luck so far, doing everything client side in the browser.

**Comment by natew** [comment]
Ahh figured this out,

```js
DB.collection.pouch.addIndex
```

Also, I saw a post somewhere that auto-index adding was a thing. What are downsides of adding that?

Also generally docs on accessing pouch through collections would be 👍

**Comment by pubkey** [comment]
Yes. The `_adminPouch` is used internally and you have to touch `myCollection.pouch` for the pouchdb-instance of a collection.
To add a index, you can set `index: true` in the schema, see [here](https://github.com/pubkey/rxdb/blob/master/test/helper/schemas.js#L28)

It looks like this is missing in the docs, I'm sorry for that.

`TODO add index and compound-index to docs`
