### ISSUE TITLE
Issue with validate-z-schema

### ISSUE THREAD

**Issue by alex-english-desiclabs** [pubkey/rxdb#1391]
Hello,

I am using RxDb in a cordova application, which requires validate-z-schema because of the eval-unsafe issue. I have noticed errors showing up in the console. In /dist/es/plugins/validate.js line 70, it calls _getValidator without any arguments, which the validate-z-schema plugin doesn't seem to handle very well.

I have tried adding the following line to dist/es/plugins/validate-z-schema.js, line 23:

## Code

```js
function _getValidator(rxSchema) {
  if (!rxSchema) rxSchema = this;
  var schemaPath = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : '';
  var hash = rxSchema.hash;
  if (!validatorsCache[hash]) validatorsCache[hash] = {};
```

Please let me know if I should do a pull request, or if this is sufficient.

**Comment by pubkey** [comment]
Yes a PR would be nice. But we should start with a test-case that reproduces the problem.

**Comment by pubkey** [comment]
Any update? Your issues does not make clear what is not working.

**Comment by pubkey** [comment]
I'm closing this. The given information does not make it clear what must be fixed.
