### ISSUE TITLE
Firebase offline database

### ISSUE THREAD

**Issue by hamzahio** [pubkey/rxdb#14]
Good Day all,

I was wondering if this library can work with firebase as backend as offline storage.

**Comment by pubkey** [comment]
@hamzahio I'm sorry but there is currently no ready-to-use interface to connect firebase with RxDB or pouchdb.

**Comment by hamzahio** [comment]
@pubkey can you point to me how to create plugin or sync library for this amazing library RxDB.

I will do the implementation just need for points.

Thanks.

**Comment by pubkey** [comment]
@hamzahio Are you still looking for a solution?

I think a good aproach would be to create a pouchdb-firebase-sync-plugin which than could easily be used with RxDB.
