### ISSUE TITLE
Option to disable schema validation

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#140]
## Issue
When working locally and iterating fast, having to write migrations or clear data for every schema change is painful. Would be nice to have option to disable the validation.

**Comment by pubkey** [comment]
Hi @natew 
My workflow was to delete the database locally on each schema-change. This then does not require migration-strategies when developing.

I don't think it would be helpfull to not validate the schema on dev-mode and work with documents other then on production.

**Comment by natew** [comment]
My case isn't to do it by default, but just to allow some mode. Maybe set localStorage RxDB.ignoreSchema, so you can play around with schema changes quickly. But it's a super minor thing, ok to close.
