### ISSUE TITLE
ANNOUNCEMENT: Help me to improve RxDB by answering a few questions (<1minute)

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#1411]
If you use RxDB or have used it in the past, please help me to improve RxDB by filling out a small user survey. It has only 6 questions and can be filled in **less then one minute**.

Survey Link: https://forms.gle/y9d73Npyu8h84Ep29

**Comment by tonyxiao** [comment]
Done. Thank you for the amazing work.

**Comment by pubkey** [comment]
Thank you all for participating in the survey.
It helps a lot to know how the users use RxDB and where to focus on improving.

Here some interesting insights of the survey:
- 50% of the users use RxDB in a full-time project
- 60% of the users use the CouchDB replication
- 40% use RxDB with React, 23% with Vue and 23% with Angular

When I created the survey I had the idea in mind that RxDB could become more
then an open source project. Maybe something like a company where I create
premium plugins and sell them to the users which earn money with their RxDB based
project.
But this time is not yet. There are enough companies out there which
use RxDB in their projects but I am not sure if that is enough at the moment.

I recreated the patreon page where you can support RxDB to be healthy and sustainable:
[https://www.patreon.com/rxdb](https://www.patreon.com/rxdb)
