### ISSUE TITLE
Installs jest also :D

### ISSUE THREAD

**Issue by kenshyx** [pubkey/rxdb#1415]
## Case
After installing the rxdb lib, my existing jest test configuration gets overwritten.

## Issue
The problem is a dependency, express-pouchdb. It installs jest-23.6.0 which also has a lot of security issues. 

## Info
  - Environment: node
  - Adapter: IndexedDB
  - Stack: Typescript, React, Lerna

**Comment by kenshyx** [comment]
Opened an issue also on https://github.com/pouchdb/pouchdb-server/issues/412

**Comment by pubkey** [comment]
It is planned to move express-pouchdb to the `peerDependencies` in the next major release. [See](https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md#move-pouchdb-server-to-devdependencies-so-the-build-will-not-run-on-each-install-issue)
