### ISSUE TITLE
GraphQL batch push

### ISSUE THREAD

**Issue by tonyxiao** [pubkey/rxdb#1425]
Right now the GraphQL push replication only pushes one document at a time. This is both really inefficient especially when large number of documents are changed at once. Is there any reason batch pushing is not supported, other than than bandwidth? And can you give some pointers on how to go about implementing batch push?

**Comment by pubkey** [comment]
See [here](https://github.com/pubkey/rxdb/blob/master/src/plugins/replication-graphql/index.js#L265)
Pushing only one document on each requests makes it easy to handle errors.
When multpile documents would be send with a single request which fails, RxDB could not know which documents have to be send again.

This can be solved by having transactions at the server-side and then we could make `queryBuilder` return a single `pushObj` when multiple doucments come in.

**Comment by pubkey** [comment]
I'm closing this because I do not think I will implement the batch-push in the near future.

**Comment by techdragon** [comment]
@pubkey - Are you able to provide any more guidance on this? (and possibly reopen the ticket) as lack of any "batching" mechanism could be a serious impediment to people looking to use this new capability. While you may not be interested in implementing it in the near future, someone else might be able to step up if they need it, and a closed issue ticket can be a deterrent to some potential contributors.

**Comment by pubkey** [comment]
@techdragon yes.

At the moment the function [runPush](https://github.com/pubkey/rxdb/blob/8f44c4b40091e6017d0c1f8cb975a4724d09aa60/src/plugins/replication-graphql/index.ts#L246) will query a batch of unpushed documents from the database.
Then, for each of the documents, we create one GraphQL-Query [here](https://github.com/pubkey/rxdb/blob/8f44c4b40091e6017d0c1f8cb975a4724d09aa60/src/plugins/replication-graphql/index.ts#L282).
If the GraphQL-Query failed for any reason, it will re-run [here](https://github.com/pubkey/rxdb/blob/8f44c4b40091e6017d0c1f8cb975a4724d09aa60/src/plugins/replication-graphql/index.ts#L286).
This implementation handles all kind of errors. The server crashes, the user is offline or there is a timeout, and so on.

When implementing a batch-push, you would create a GraphQL-Query with the full batch of documents and send them to the server. If there is an error with one document, you cannot be sure what happened to the other documents.

Also keep in mind that the pull-replication runs in batches already.
