### ISSUE TITLE
definition of CollectionCreator#methods

### ISSUE THREAD

**Issue by rweng** [pubkey/rxdb#144]
In the current version, the `CollectionCreator` interface requires `statics` and `methods` to be an object with numbers as keys: https://github.com/pubkey/rxdb/blob/83bee8b693d385a80e56b7942f1d275be3f4466d/src/index.d.ts#L78

I guess that is a bug, because in the docs (and mongoose as far as I remember), this is the method name.

**Comment by pubkey** [comment]
Yes this is a bug. `key: string` is what we need.
Also the `function[]` at the migration-strategies is wrong, there we need the number-keys.

**Comment by pubkey** [comment]
Fixed in [#147](https://github.com/pubkey/rxdb/pull/147)
