### ISSUE TITLE
RxDB server path option problem

### ISSUE THREAD

**Issue by dstudzinski** [pubkey/rxdb#1447]
## Case
Bug

## Issue
path option for server is broken. You can't start server with path other than default

## Info
  - Environment: Node.js, rxdb v8.4.0
  - Adapter: websql
  - Stack: ES6

## Code

When you start server like this
```js
return db.server({
    path: '/db2', // (optional)
    port,  // (optional)
    cors: true   // (optional), enable CORS-headers
  });
```
You can access express-pouchdb url `/db2` but you can't access collections urls like `/db2/mycollectionname` because of error
```
{
  "error": "not_found",
  "reason": "no_db_file"
}
```

I think it's because of this line https://github.com/pubkey/rxdb/blob/master/src/plugins/server.js#L58

where `/db/` string is hardcoded instead of the use of path value `const toFull = req.originalUrl.replace('/db/' + colName, '/db/' + to);`

Second thing is that in `tunnelCollectionPath` function `/` is added to path without checking path value so for example you can't use just `/` as a path.

I was able to fix it quickly with this changed code:
```
function tunnelCollectionPath(db, path, app, colName) {
  db[colName].watchForChanges();

  const pathWithSlash = path.endsWith('/') ? path : path + '/';

  app.use(pathWithSlash + colName, function (req, res, next) {
    if (req.baseUrl === pathWithSlash + colName) {
      var to = normalizeDbName(db) + '-rxdb-0-' + colName;
      var toFull = req.originalUrl.replace(pathWithSlash + colName, pathWithSlash + to);
      req.originalUrl = toFull;
    }

    next();
  });
}
```

Should I create a PR for this?

**Comment by pubkey** [comment]
@dstudzinski thx for reporting. I fixed this and added some tests.
