### ISSUE TITLE
Feature request: upsert with default primaryPath

### ISSUE THREAD

**Issue by choma** [pubkey/rxdb#145]
I'm trying to use upsert with a schema that has default primaryPath _id.

If I don't provide an _id I get [RxCollection.upsert() does not work without primary](https://github.com/pubkey/rxdb/blob/master/src/RxCollection.js#L277)

If I DO provide an _id I get: [do not provide ._id, it will be generated](https://github.com/pubkey/rxdb/blob/master/src/RxCollection.js#L238)

Or maybe I'm doing something wrong...

**Comment by pubkey** [comment]
I never had this case.
Looks like we need to add a generated id to the `upsert()`, equal to [this](https://github.com/pubkey/rxdb/blob/58fa5a1fa700975e7c5106d5556e8b81bbbd185e/src/RxCollection.js#L241)

**Comment by pubkey** [comment]
Closed. Use insert if you have a generated primary. Use upsert if you have the primary and want to make sure there is no update-conflict.
