### ISSUE TITLE
skip_setup is skipped when initializing a collection

### ISSUE THREAD

**Issue by CAYdenberg** [pubkey/rxdb#1497]
## Case

Bug

## Issue

RxDB does not respect the `skip_setup` option in `pouchSettings` when passed to a new collection.

## Info

RxDB 8.5.0
pouchdb-core 7.0.0
pouchdb-adapter-idb 7.1.1
Node 8.16.0
Chromium 76

## Code

Minimal repo: https://github.com/CAYdenberg/rxdb-pouch-settings-reproduction

Once running open the console and enter:

```
db.collection({name: 'mycollection', schema: window.schema, pouchSettings: {skip_setup: true}}).then(console.log)
```

The promise resolves successfully and a new IndexedDB instance is created.

**Comment by CAYdenberg** [comment]
I misread the Pouch documentation: `skip_setup` applies to remote collections only. Sorry for the misreport.

**Comment by pubkey** [comment]
No problem. I think they should that make more clear in the docs.
