### ISSUE TITLE
please upgrade react-native example to the newest version

### ISSUE THREAD

**Issue by iwater** [pubkey/rxdb#151]
please upgrade react-native example to the newest version both rxdb and react-native

**Comment by pubkey** [comment]
PR's are welcome. The RxDB version is always the newest since its linked relative to the dist folder.

**Comment by pubkey** [comment]
Closed.
The examples are very work-intensive to stay up-to-date with the current rxdb-version.
They do not have to be always the latest dependency versions. I upgraded the rxdb-version to always be the latest.
