### ISSUE TITLE
ANNOUNCEMENT: Version 4.0.0 

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#154]
A few minutes ago, I released Version 4.0.0. [CHANGELOG](https://github.com/pubkey/rxdb/blob/master/CHANGELOG.md#400-may-5-2017)
The focus was on even better performance especially a better Caching, faster Queries and ressource-Saving on observed Queries.

One main feature is the [QueryChangeDetection](https://github.com/pubkey/rxdb/blob/master/docs/QueryChangeDetection.md). This is something only event-based databases can do and can add a huge performance-gain now and an even bigger one with more optimisations in the future.

The QueryChangeDetection is very complex and so I decided to put in beta-mode.
This means it's disabled by default and you have to enable it. Read [this](https://github.com/pubkey/rxdb/blob/master/docs/QueryChangeDetection.md#notice) to learn how to do that.

Please comment here if you have some ideas or concerns about the changes.

**Comment by matsuo-ts** [comment]
@pubkey I encountered an error as below after update to `4.0.0`.

```
Failed to open collection:  Error: Cannot sort on field(s) "status" when using the default index
    at validateSort (bundle.js:165)
    at bundle.js:165
(anonymous) @ bundle.js:244
```

Not sure if this is due to update but as I search Internet this is probably come from [PouchDB](https://github.com/pouchdb/pouchdb/issues/6399).

**Comment by pubkey** [comment]
@matsuo-ts Maybe its comes from pouchdb, but its also possible that rxdb is the wrong. Can you create an issue where you include your schema and the query?

**Comment by natew** [comment]
So far so good. Been using for 2 days now without problem. Very significant speedups, this is awesome!
