### ISSUE TITLE
Can't get Rxdb working in Electron

### ISSUE THREAD

**Issue by Aaltuj** [pubkey/rxdb#1557]
Hi I love Rxdb, but i have hit a snag. Working on a new application, i've started development by creating a terminal app with NodeJS. (10.16.0) on windows 10

It works great with the `node-websql` adapter. But migrating it to the electron based app gave me the following error: 

`ERROR in ./node_modules/pouchdb-adapter-node-websql/lib/index.es.js
Module not found: Error: Can't resolve 'websql' in 'D:\Dev\native\node_modules\pouchdb-adapter-node-websql\lib'
`

I've looked at multiple issues and i can't figure out what's the problem.

Attached is a reproduction project.

1) `yarn install`
2) `yarn start:electron`

Let the application run and it will fail the previous error message.

Any help would be appriciated. Thanks!
[native.zip](https://github.com/pubkey/rxdb/files/3691791/native.zip)

**Comment by pubkey** [comment]
Can you reproduce the problem in the [electron example](https://github.com/pubkey/rxdb/tree/master/examples/electron)?

**Comment by Aaltuj** [comment]
the couple of days i've tried some approaches. fIrst i've tried to use the `node-websql-adapter` in the example. That was working in the end. next step was to convert the example to TypeScript with Angular. That is what i'm now working on. Angular in electron is working, I'm now adding the Rxdb code in the main.ts for electron. So that's a work in progress.

**Comment by pubkey** [comment]
@Aaltuj any update on this?

**Comment by pubkey** [comment]
I'm closing this. the electron example works so I do not think this is a problem with rxdb itself.

**Comment by Aaltuj** [comment]
sorry for the late reaction. It's working with the server / client solution. The browser window talks to a pouchdb-index-db adapter and syncs it to the server on the Electron thread. What i was looking for was a solution that uses the pouch-websql directly in angular because of the storage limitations i've could hit in chrome.  So this way we could have angular directly talk to the pouchdb instance that is creating SQLITE database on the file-system. I've managed to share that instance in the browser window. This way the sync between the two threads (read PouchDb instances) is not necessary.

**Comment by pubkey** [comment]
@Aaltuj that sound great. Can you share your code or even implement this in the electron example?

**Comment by Aaltuj** [comment]
@pubkey I'll try to do that when i have time left. Keep you posted.
