### ISSUE TITLE
Throwing error in async preInsert doesn't prevent insert

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#158]
Issue title mostly describes it, but basically this code:

```js
async preInsert(data) {
      if (await this.get(data.slug).exec()) {
        throw new Error(`Already exists a place with this slug! ${data.slug}`)
      }
}
```

Shows this:

![image](https://cloud.githubusercontent.com/assets/12100/25861763/7c7682fa-349a-11e7-927b-16927fa29b52.png)

But the value is still inserted!

Not using any promise library shim.

**Comment by pubkey** [comment]
I added a test but could not reproduce this on node(7.8.0), chrome or firefox.
Please describe your environment because I think it depends on the Promise-implementation.

**Comment by natew** [comment]
Ah, lack of awareness! Missed that it was being wrapped elsewhere. Thank you.
