### ISSUE TITLE
Support getters on methods/statics

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#160]
```js
db.collection({
  methods: { get thing(){ return 1 } }
})
```

Getting this when attempting this currently:

![image](https://cloud.githubusercontent.com/assets/12100/25877897/873f3498-34db-11e7-9e9c-45481ec194a8.png)

**Comment by pubkey** [comment]
Getters cannot be used here. Read the reason [here](https://github.com/pubkey/rxdb/issues/150#issuecomment-298829529)
