### ISSUE TITLE
Add webpackbin to issue template/readme

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#161]
Adding this here, after a bit of playing around got it to generally work.

It's complaining now just on schema having changed for me, but I can't clear the data (need to go into iframe and clear it). Maybe a way to programmatically clear?

**Comment by pubkey** [comment]
There is currently no way to programmatically clear the storage. A hacky option would be to change the database-name or add the current timestamp as string.

**Comment by pubkey** [comment]
Any update on this?

**Comment by pubkey** [comment]
[Done](Closed in favor of [0d662d9beecccb9aac63384a582f0544307ef2ca](https://github.com/pubkey/rxdb/commit/0d662d9beecccb9aac63384a582f0544307ef2ca))
