### ISSUE TITLE
rxdb  running on arm based os?

### ISSUE THREAD

**Issue by spade69** [pubkey/rxdb#1610]
hey guys, i want use rxdb on an arm-base device, like my raspberry pi.  I already install a node.js runtime,

**Comment by pubkey** [comment]
As far as I know, leveldb works on the rpi. So using the leveldb adapter should work for you.

**Comment by spade69** [comment]
thx bro, i will check it.

**Comment by pubkey** [comment]
I'm closing this since it is not really an issue.
It would be great if you could write here if you found out how rxdb runs on the rpi
