### ISSUE TITLE
Recursive error when inserting bad object

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#163]
## Issue
Getting an error on this: https://www.webpackbin.com/bins/-KjpgcHUKURB4JtitaYe

```js
import React from 'react'
import {render} from 'react-dom'
import 'base64-js'
import 'ieee754'
import 'isarray'
import 'rxjs'
import * as RxDB from 'rxdb'
import pIDB from 'pouchdb-adapter-idb'

console.log('got rxdb')

RxDB.plugin(pIDB)

render(<div>null</div>,document.querySelector('#app') )

RxDB.create({
      adapter: 'idb',
  name: 'user',
  password: 'password'
    }).then(db => {
  console.log('got db', db)
  
  return db.collection({
      name: 'test2',
      schema: { title: 'test2', version: 0, properties: { name: { type: 'string' } } }
    })
})
.then(collection => {
  console.log(collection)
  
  collection.insert({ title: new ClipboardEvent(1)  })
})
```

error:

```
Uncaught (in promise) TypeError: Cannot assign to read only property 'NONE' of object '#<ClipboardEvent>'
    at _clone (VM80 dll.js:1944)
    at _clone (VM80 dll.js:1944)
    at clone (VM80 dll.js:1984)
    at RxCollection.insert (VM80 dll.js:29385)
    at VM149 main.js:174
    at <anonymous>
```

**Comment by natew** [comment]
Minor issue, but the error could be a bit better.

**Comment by pubkey** [comment]
The things you throw into `RxCollection.insert` should be plain simple javascript-objects.
You have to convert your ClipboardEvent into a string.

**Comment by natew** [comment]
No worries, my thing here was obviously it was unintentional to put that object there (I had attached an insert directly to a DOM event on accident).

BUT: the error took me a long time to figure out as I had no idea what was even happening. Namely, the error stack here is horrible, and then the error itself is confusing. Fixing one of the two would save people time, but this is a pretty edge case scenario.

**Comment by natew** [comment]
A quick typeof check in RxDB would allow putting at least an error "must be an object"

**Comment by pubkey** [comment]
The thing is, that in some cases this can work as long as the object can be JSON.stringy-fied.
I will investigate

**Comment by pubkey** [comment]
Ok, I think this is an edge-case. We could check if the passed object is a plain-js-object before `insert()` starts, but in some cases this could be a restriction which should not be done in a functional-programming-language.
For example I could create any object of any prototype which will still be saveable by rxdb, but with the check, this does not work anymore.
