### ISSUE TITLE
Github repository emoji not correctly rendered.

### ISSUE THREAD

**Issue by vSanjo** [pubkey/rxdb#1631]
## Case
The emoji used in the summary of the Github is not rendered.

## Issue
It's such a small issue, but in the interest of ticking all the boxes, I thought I'd bring it up. The emoji is rendered as an unknown character on my platform. Images attached.

## Info
  - Environment: Firefox (71.0b3 (64-bit) - **developer version**), Chrome (Version 78.0.3904.70 (Official Build) (64-bit)).
  - Operating System: MacOS 10.14.6 (18G103)

![chrome](https://user-images.githubusercontent.com/5829775/67556961-b2243700-f746-11e9-9499-ce821a874564.png)
![firefox](https://user-images.githubusercontent.com/5829775/67556962-b2bccd80-f746-11e9-9dc2-e887cca1151c.png)

**Comment by AngelGzS** [comment]
Here are more supported emojis

https://www.webfx.com/tools/emoji-cheat-sheet/

**Comment by pubkey** [comment]
![repli](https://user-images.githubusercontent.com/8926560/67596929-320fc880-f76a-11e9-9330-c47805266630.png)
I now changed it so something that maybe indicates the replication feature.

**Comment by vSanjo** [comment]
Sorry, I have been out of the loop a few weeks.

This looks great!
