### ISSUE TITLE
Change the way indexes are specified at collection schema definition

### ISSUE THREAD

**Issue by marinrusu1997** [pubkey/rxdb#1655]
## Case
This is an improvement for the way indexed fields are specified at collection schema definition.

## Issue
The actual implementation of RxDB requires indexed fields be marked with a boolean property index. The way these fields are extracted when RxSchema is created implies creating a flatten object from json schema an then doing a lot of filtering and mapping over the keys of this object just to retrieve indexed fields (https://github.com/pubkey/rxdb/blob/master/src/rx-schema.ts#L240). The problem with actual implementation is that it induces huge performance penalties for big schemas with many leves of imbrication ( > 5). In my performance tests, I had a schema which had 9 leves of imbrication and 661 keys of flattened object, it took 52 ms to run _getIndexes_ function. Given the fact that collections are usually created at the application boot, this is a **huge penalty for  application boot time**.
A possible solution is to define indexed fields at the collection schema level, not at the fields level, like _compoundIndexes_. This way, _getIndexes_ could be run in a constant O(1) time. This will imply to add a new check in the _checkSchema_ function to make sure that specified fields actually exists in properties of the schema. 

## Info
  - Environment: Chrome 77.0.3865.120 64-bit on a Windows 10 Enterprise virtual machine running over an Intel Xeon E5-2620 v3 @2.40Ghz, 12GB of RAM. 
  - Adapter: PouchDB adapter using IndexedDB as its data store
  - Stack: Tests were made in a Web Worker

## Screenshots
Bellow is a screenshot from Chrome Profiler:
![image](https://user-images.githubusercontent.com/29524251/67851489-40b40200-fb13-11e9-821b-13138d0e5a55.png)
GC time took 9 ms.
![image](https://user-images.githubusercontent.com/29524251/67851686-9ee0e500-fb13-11e9-8f58-8985b464f2a2.png)

**Comment by pubkey** [comment]
This is a great proposal.
In the last major release we also moved the `require: true` statements to the top-level of the schema.
Doing this also with the indexes makes sense.

**Comment by marinrusu1997** [comment]
Should I implement the proposed improvements myself and do a PR, or you can implement them yourself? Also, when will the new major release come out?

**Comment by marinrusu1997** [comment]
Perfect. I will create a new branch where these improvements will be implemented, and then the community could use it in beta-version.

**Comment by marinrusu1997** [comment]
Could you please give me access rights so I can create remotely the branch which contains changes?

**Comment by pubkey** [comment]
I created the branch [9.X.X](https://github.com/pubkey/rxdb/tree/9.X.X). Please make a PR to that one. I will then ensure that changes to 8.x.x will be merge upwards.

**Comment by marinrusu1997** [comment]
`
git push --set-upstream origin change-the-way-indexes-are-specified-at-collection-schema-definition
ERROR: Permission to pubkey/rxdb.git denied to marinrusu1997.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
I need the rights to create my branch remotely and then make make a PR to [9.X.X](https://github.com/pubkey/rxdb/tree/9.X.X).

**Comment by pubkey** [comment]
I think you have to fork this and the merge the fork with a PR

**Comment by pubkey** [comment]
@marinrusu1997 
I merged the PR and [commited](https://github.com/pubkey/rxdb/commit/436d468b8b568750d06a906f93ab415aef43ce3c) a new build. I will not release a beta for this on npm because most people install always the latest version and will then end up which something that does not match the docs. Also the release of version 9 will take some time.

You can use the next major like this:
```json
"dependencies": {
      "rxdb": "git+https://git@github.com/pubkey/rxdb.git#436d468b8b568750d06a906f93ab415aef43ce3c"
  }
```

**Comment by marinrusu1997** [comment]
Thanks!

**Comment by rizwan92** [comment]
"rxdb": "^9.15.0",
   facing same issue
schema :-[Schema Gist Link]( https://gist.github.com/rizwan92/d2ce38e0956a90ba0d2da43c936ee6a7)

```
import { createRxDatabase, addRxPlugin } from "rxdb";
import { BillsSchema } from "./Schema";

addRxPlugin(require("pouchdb-adapter-idb"));

export const initRxDb = async () => {
  const db = await createRxDatabase({
    name: "mydatabase", // <- name
    adapter: "idb", // <- storage-adapter
    password: "mypassword", // <- password (optional)
    multiInstance: false, // <- multiInstance (optional, default: true)
    eventReduce: false, // <- eventReduce (optional, default: true)
    ignoreDuplicate: true,
  });

  const bills = await db.addCollections({
    bills: {
      schema: BillsSchema,
    },
  });

  return { db, bills };
};
```
trying to insert like this

```
  import { initRxDb } from "../../RxDb";

createRecord = async ()=>{
    const { bills } = await initRxDb();
    bills.insert(payload); // where payload is my record 
}
```
facing this issue 

```
index.js:22 Uncaught (in promise) RxError (SC26): RxError (SC26):
SchemaCheck: indexes needs to be specified at collection schema level
Given parameters: {
index:"createdAt"}
```

**Comment by pubkey** [comment]
Please make a PR woth a failing test case.

**Comment by marinrusu1997** [comment]
@rizwan92 check the [documentation](https://github.com/pubkey/rxdb/blob/master/docs-src/rx-schema.md#indexes).

**Comment by rizwan92** [comment]
@marinrusu1997 @pubkey  fixed i was configuring wrong. 

```
createdAt: {
      type: "string",
      format: "date-time",
      index: true, // removed this line and it worked
    },
```

but i dont like the idea of migration its very pain full, and tough to maintain in electron production application for different different version
