### ISSUE TITLE
Question: any topics about security ?

### ISSUE THREAD

**Issue by Soontao** [pubkey/rxdb#1663]
Hello friends, 

I think this project is a great idea to drive applications that share data in real time, but I want to know how to protect applications built by rxdb, specifically how the application implements authentication and authorization, and how to avoid user/hacker access unauthorized data.

Is there any discussions/community/issue/roadmap for this ?

Thanks a lot.

**Comment by pubkey** [comment]
There are many tutorials on how to do auth with GraphQL or CouchDB. Most of them can be used with RxDB.


From the issue template:
  If you have a common question which cannot be solved with a PR, ask it at one of these places:
  - https://stackoverflow.com/
  - https://gitter.im/pubkey/rxdb

**Comment by MentalGear** [comment]
Actually, I would second that. A tutorial especially on how to integrate with this package would be great.
