### ISSUE TITLE
discussion: use @Decorators instead of jsonschema to describe stored data

### ISSUE THREAD

**Issue by NoNameProvided** [pubkey/rxdb#168]
## Case

Feature requets

## Issue

Using JSONSchema is not developer friendly, describing the stored objects in its is painful. It would make sense to support a cleaner approach via decorators. Something like in [TypeORM](https://typeorm.github.io/index.html#example-create-columns)

So it can look something like this:

```js
@Entity()
export const User = {

    @Column({ type: number })
    id: undefined;

    @Column({ type: string })
    email: undefined;

    @Column({ type: string })
    name: undefined;

}        
```
Under the hood decorators can generate JSONSchemas, so it can stay backward compatible.

## Info
- Environment:  n/a
- Adapter: n/a

## Code

n/a

**Comment by natew** [comment]
Personally I've been using [Kontur](https://github.com/zweifisch/kontur). Seems like you could adapt this without needing to change RxDB.

**Comment by NoNameProvided** [comment]
Thanks, will check it out!

**Comment by pubkey** [comment]
I don't know if its possible to add decorators to a plain-javascript-module.
Or am I wrong?

**Comment by NoNameProvided** [comment]
I think it does, but you need to compile your source to use them for sure. (Until spec finalized and browsers add support.)

**Comment by pubkey** [comment]
Do you know any library which does that at the moment?
I checked the angular modules but couldnt figure out how they do it

**Comment by NoNameProvided** [comment]
Eg: [core-decorators.js](https://github.com/jayphelps/core-decorators.js)

**Comment by pubkey** [comment]
Hi @NoNameProvided 
I have thought about this a lot. And my conclusion is that decorators will not be added to RxDB in the near future.

I have worked with decorators a lot at some angular-projects, and I believe that decorators should not be used in functional-programming. I know that this position can be upsetting to hear, but notice that it's just my personal standpoint based on my current knowledge. It can change in the future.

Also to mention that next to no other non-typescript-project is using decorators at the moment. So I think that using them will scare off newcomers, especially if they are new to javascript itself.

**Comment by michaeljota** [comment]
Hi! I know that is not a long time, but, have you though about this? 

Currently ```decorators``` are in stage 2, meaning that, even when right now they need a polyfill, soon they won't. Both, TypeScript and Babel have support for decorators. And they are some projects, besides Angular, using ```decorators```
- [typeorm](http://typeorm.io)
- [nest](https://nestjs.com)
- [mobx](https://mobx.js.org)

**Comment by JonathanTurnock** [comment]
I know this is an old issue but this came up for me. Try mixing class-validator with a Json schema generator. 

I'm not personally using the generator because of my setup but it's probably the best way to start mixing RxDB with classes and decorators that define their structure and corresponding json schema.
