### ISSUE TITLE
Temporary document

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#171]
## Case
Want to create a RxDocument without persisting it.

## Issue
This is helpful for certain UI interactions with temporary objects, without needing to clean up or do other hacks. The need arises when you want to access your methods you've defined, but don't want to persist it.

**Comment by pubkey** [comment]
You are right. We need this.
Commit will follow in the next 14 days..

**Comment by pubkey** [comment]
I added this feature and added an example-usage [here](https://github.com/pubkey/rxdb/blob/master/examples/angular2/app/src/components/hero-insert/hero-insert.component.ts)
