### ISSUE TITLE
Duplicate collections on Safari

### ISSUE THREAD

**Issue by diegomolinavera** [pubkey/rxdb#1719]
## Case
Bug

## Issue
I have an app in React. This issue only happens on Safari. When I'm switching between screens on my app or I refresh the web browser, a new collection - with the same name of an existed one - is created. It may seems is a Safari issue but I don't know. I check if a query is executed from the instance of the database, but no.

## Info
  - Environment: Safari 13.0.3 (14608.3.10.10.1)
  - Adapter: idb - 'pouchdb-adapter-idb',
  - Stack: React 16.8.6

## Code
Here's the code I use as a configurations. It's called only ones in the whole app.

```js
import 'babel-polyfill';
import RxDB from 'rxdb';
import idb from 'pouchdb-adapter-idb';
// Project
import {
  DB_NAME,
  CHECKING_VERSION,
  USER_SESSION
} from './collections';

RxDB.plugin(idb);

let dbInstance = null;

const getCollectionStructure = collectionName => ({
  name: collectionName,
  keyCompression: true,
  schema: {
    title: collectionName,
    version: 0,
    type: 'object',
    properties: {
      data: {
        type: 'string'
      },
      id: {
        type: 'string',
        primary: true
      }
    }
  }
});

export const createDB = async (name = DB_NAME) => {
  const adapterOK = RxDB.checkAdapter('idb');

  try {
    if (adapterOK) {
      const db = await RxDB.create({
        name,
        adapter: 'idb',
        ignoreDuplicate: true,
        multiInstance: false,
      });

      if (process.env.NODE_ENV !== 'production') {
        window.db = db;
      }

      const collections = [
        CHECKING_VERSION,
        USER_SESSION
      ];

      await Promise.all(
        collections.map(schemaName => db.collection(getCollectionStructure(schemaName)))
      );

      return db;
    }
    console.error('El adaptador no es compatible con el navegador');
  } catch (error) {
    console.error(error);
  }
};

const getDB = (name = DB_NAME) => {
  if (!dbInstance) {
    dbInstance = createDB(name);
  }

  return dbInstance;
};
````
Using this basic configuration, the db is created with all the collections. If i refresh using `cmd+R` or `F5` a new collections are created over and over again. This behavior happens only on Safari. Even when the collections are already created.

I changed `ignoreDuplicate` ot `false` but the app get broken when i refresh the app because tries to create a duplicate db instance.

Is there a way to check if a collections or the db is already created when I refresh the app?

**Comment by pubkey** [comment]
I do not fully understand what the problem is or could be.
Can you minimize the code to only contain stuff that is usefull to replicate the issue?
Also it might be better if you could a PR with a test that fails on safari

**Comment by diegomolinavera** [comment]
I updated the description of the issue

**Comment by pubkey** [comment]
The collections-instance is a javascript object which gets created each time you call RxDatabase.collection

**Comment by pubkey** [comment]
@diegomolinavera can you help me to reproduce this?
The provided description and code make not clear for me what happens. Can you create a test-page or a unit test or something for that?
