### ISSUE TITLE
Angular 2/Vue event not emitted

### ISSUE THREAD

**Issue by greg9504** [pubkey/rxdb#174]
## Case
Bug

## Issue
When I run the Angular 2/Vue examples if I press Cancel while editing a Hero.hp field the instance I'm editing does not revert back.  Here is a screen shot that shows two browser windows open to the same data. The one on the right is not in sync with the one on the left (look at the user Rick's progress bar), this is after editing user Rick, changing the hp value, then hitting cancel on the edit.

![image](https://cloud.githubusercontent.com/assets/1952281/26203535/a4918652-3ba9-11e7-8465-b8c1facd07fb.png)

## Info
- Environment: (Node.js/browser/electron/etc.)

> D:\devtools\js\tutorials\rxdb\examples\angular2>npm list --depth=0
> rxdb-example-angular2@3.0.0 D:\devtools\js\tutorials\rxdb\examples\angular2
> +-- UNMET PEER DEPENDENCY @angular/animations@4.1.2
> +-- UNMET PEER DEPENDENCY @angular/common@4.1.2
> +-- @angular/compiler@4.1.2
> +-- @angular/compiler-cli@4.1.2
> +-- UNMET PEER DEPENDENCY @angular/core@4.1.2
> +-- @angular/forms@4.1.2
> +-- UNMET PEER DEPENDENCY @angular/http@4.1.2
> +-- @angular/material@2.0.0-beta.2
> +-- @angular/platform-browser@4.1.2
> +-- @angular/platform-browser-dynamic@4.1.2
> +-- @angular/platform-server@4.1.2
> +-- @angular/router@4.1.2
> +-- @types/chai@3.5.2
> +-- @types/core-js@0.9.41
> +-- @types/hammerjs@2.0.34
> +-- @types/requirejs@2.1.29
> +-- angular2-template-loader@0.6.2
> +-- appcache-webpack-plugin@1.3.0
> +-- awesome-typescript-loader@3.1.3
> +-- babel-core@6.24.1
> +-- babel-loader@7.0.0
> +-- babel-polyfill@6.23.0
> +-- babel-preset-env@1.4.0
> +-- concurrently@3.4.0
> +-- copy-webpack-plugin@4.0.1
> +-- core-js@2.4.1
> +-- css-loader@0.28.1
> +-- extract-text-webpack-plugin@2.1.0
> +-- file-loader@0.11.1
> +-- font-awesome@4.7.0
> +-- fsmonitor@0.2.4
> +-- hammerjs@2.0.8
> +-- html-webpack-plugin@2.28.0
> +-- json-loader@0.5.4
> +-- less@2.7.2
> +-- less-loader@4.0.3
> +-- node-gyp@3.6.1
> +-- normalize.css@7.0.0
> +-- npm-run-all@4.0.2
> +-- postcss-cli@3.2.0
> +-- pouchdb-adapter-http@6.2.0
> +-- pouchdb-adapter-idb@6.2.0
> +-- pouchdb-adapter-localstorage@6.2.0
> +-- pouchdb-replication@6.2.0
> +-- pouchdb-server@2.3.7
> +-- random-int@1.0.0
> +-- raw-loader@0.5.1
> +-- regenerator@0.9.7
> +-- rimraf@2.6.1
> +-- roboto-npm-webfont@0.0.2
> +-- rxjs@5.4.0
> +-- style-loader@0.17.0
> +-- tslint@5.2.0
> +-- typescript@2.3.2
> +-- url-loader@0.5.8
> +-- webpack@2.5.1
> +-- webpack-dev-server@2.4.5
> +-- webpack-merge@4.1.0
> `-- zone.js@0.8.10

> npm ERR! peer dep missing: @angular/common@^2.3.0, required by @angular/material@2.0.0-beta.2
> npm ERR! peer dep missing: @angular/core@^2.3.0, required by @angular/material@2.0.0-beta.2
> npm ERR! peer dep missing: @angular/http@^2.3.0, required by @angular/material@2.0.0-beta.2
> npm ERR! peer dep missing: @angular/animations@4.1.2, required by @angular/platform-server@4.1.2

 - Adapter: (IndexedDB/Localstorage/LevelDB/etc.)
see example

## Code
use Angular 2 or Vue examples in repo

**Comment by pubkey** [comment]
Fixed. @greg9504 please also test this and reopen if more problems.
