### ISSUE TITLE
ActiveRecord style classes?

### ISSUE THREAD

**Issue by iyobo** [pubkey/rxdb#1761]
New Feature request

I love RXDB and the cool features, but I find the process of defining models and collections to be quite convoluted.

Would it be possible to consider an ActiveRecord pattern? Whereby our models are classes that probably inherit some sort of Model/Collection class?

I say this because, especially in the Typescript example, it becomes quite clear that doc methods and static methods could be more easily defined as static and class methods within a class, as well as the various fields.

**Comment by pubkey** [comment]
Hi  @iyobo I am open for any changes to make using RxDB more simple.
Can you paste some code on how the API should look like and show what the benefits are with that?

**Comment by iyobo** [comment]
Something like this.

https://www.npmjs.com/package/pouchdb-activerecord

**Comment by pubkey** [comment]
I thought a lot about your proposal.
The reason why document- and collection-methods are defined in RxDB in the current way, is to be similar to mongoose.
I think the proposal would add even more efford to setup the database. You have to create classes and stuff for each document type.
In the future I want to move RxDB away from this 'orm' API and make the document- and collection-methods available as optional plugin.
