### ISSUE TITLE
Feature: one way sync

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#179]
## Case
This goes hand in hand with allowing query-based syncing feature. But if you are manually replicating a remote DB into RxDB using the new `selector` feature, then you'll still want to replicate UP separately (either with or without selector).

## Issue
Right now RxDB only supports whole-db sync. Need it to support one-way (up/down), much like PouchDB `replicate`.

**Comment by pubkey** [comment]
Added sync-directions with the linked commit. Please also test this and reopen if something does not work.
Query-Based sync will come soon.
