### ISSUE TITLE
Error: Adapter idb not added

### ISSUE THREAD

**Issue by drop-c** [pubkey/rxdb#180]
## Case
Bug

## Issue
I've been trying to setup unit testing on a collection's methods using Ava testrunner, but also the same happens in Safari:

[Error] Unhandled promise rejection – Error: Adapter idb not added.
                 Use RxDB.plugin(require('pouchdb-adapter-idb');

although RxDB.plugin(require('pouchdb-adapter-idb') is called.

## Info
- Environment: Node, Safari OSX
- Adapter: idb

## Code
Please check with default jsfiddle link (or this, forked: https://jsfiddle.net/gdLdepze/) on Safari
For AVA, this is what my test.js file looks like:

```js
import test from 'ava'
import * as Database from '../db/db'

test.beforeEach(t => {
  const db = await Database.get()
  t.context.db = db
})

test('add doc', async t => {
  const {db} = t.context
  const mock = {
    id: 'b6',
    name: 'B6'
  }
  await db.col.insert(mock)
  t.is(db.col.length, 1)
})
```

**Comment by pubkey** [comment]
I do currently have no apple-device to test this. The fiddle works on my chrome, but this does not help.
I will try to reproduce next week when I have a macbook in my hands.

**Comment by pubkey** [comment]
@drop-c Please run [this](http://bl.ocks.org/nolanlawson/raw/9af8f79637b6f0d553ee121ef6fdd428/) test-suite in your safari.

**Comment by pubkey** [comment]
This is an known issue. The idb-adapter does not work with safari 10.

It will possibly resolved soon [here](https://github.com/pouchdb/pouchdb/issues/5572).
For now you have to stick to another adapter.

**Comment by Ranmus** [comment]
The problem still occurs in safari 11 beta.

**Comment by Ranmus** [comment]
@pubkey You can simply reproduce this for eg. by using chrome browser on linux and enabling device toolbar. Then choose iphone 6 plus.

**Comment by Ranmus** [comment]
@pubkey  
Here is sreenshot from test-suite you provided: http://i.imgur.com/3ohBrLj.png
Macos Sierra + Safari 11 beta. Only six failures in test.compaction.js-local
