### ISSUE TITLE
Feature: Sync based on query

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#181]
## Case
I never want to sync an entire DB, and for initial load my ideal case would be something akin to:

```
const x = RxDB.collection('some-remote')
const query = x.collection.findAll().where('name').eq('my-name')

// ?
const syncer = query.syncToRemote()
syncer.cancel()
```

## Issue
Using RxDB for a general application is hard right now because once you have a few revisions of anything you end up fetching tons of data, and your app takes 10+ seconds to load in common cases I'm running into.

Ideally, you'd have this:

1. Sync up everything I write to local databases
2. Sync down queries I write, but ONLY get the last revision the first time
3. OPTIONALLY sync down up to a certain number of revisions in history after 2 completes

This would make it snappy for initial load, and still let you control if you'd like to fetch backwards.

I'm not sure if 2 is possible. It seems you can say `{ since: 'now' }` but then you end up with only new stuff, would be ideal if you could say `{ lastRevisions: 1 }`. I'd be willing to write an adapter for couch (maybe a proxy of sorts) that does this, and we could include it in RxDB as a plugin or something.

**Comment by pubkey** [comment]
One idea is to sync to a remote-pouch-server which has [auto_compaction](https://pouchdb.com/guides/compact-and-destroy.html#auto-compaction) set to true

**Comment by natew** [comment]
I was able to get downwards selective sync working. It actually is very recently possible in pouchdb 6.2, which is awesome, not sure how I found this but was added here:

https://github.com/pouchdb/pouchdb/pull/6339/files

**Comment by natew** [comment]
https://github.com/pouchdb/pouchdb/issues/5717
