### ISSUE TITLE
Use of oneOf fails

### ISSUE THREAD

**Issue by depeele** [pubkey/rxdb#182]
## Case
This is a bug

## Issue
This bug seems related to #86 but persists.

I am trying to use the `oneOf` features of Json Schema, but `RxSchema` throws and error because of an issue with "`fieldName`"s.

The  [paragraph](/pubkey/rxdb/blob/4a63e4b1e001e1a657b1a028617e9a995c2aa407/docs/RxSchema.md#notice-not-everything-of-the-jsonschema-spec-is-allowed)  added to the documentation does not explain (to me at least) that this feature is not supported.

Looking at [line 49 of `index.d.ts`](/pubkey/rxdb/blob/4a63e4b1e001e1a657b1a028617e9a995c2aa407/src/index.d.ts#L49) along with [line 20612 of `rxdb.browserify.js`](/pubkey/rxdb/blob/4a63e4b1e001e1a657b1a028617e9a995c2aa407/dist/rxdb.browserify.js#L20612) suggests that `oneOf` should be a supported feature.

## Info
- Environment: Node.js (v7.9.0)
- Adapter: LevelDB

## Code
Taken from the example provided in #86 and altered for use in Node.js:
```javascript
const RxDB    = require('rxdb');
const schema  = {
  "title": "Transaction Schema",
  "version": 0,
  "description": "Structure of Transaction Data",
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "format": "date-time"
    },
    "credit": {
      "type": "number",
      "multipleOf": 0.01
    },
    "debit": {
      "type": "number",
      "multipleOf": 0.01
    }
  },
  "oneOf": [
    { "required": [ "date", "credit" ] },
    { "required": [ "date", "debit" ] }
  ],
  "additionalProperties": false
};

RxDB.RxSchema.create( schema );
```

This fails with:
```
src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:322
        throw new Error('\n        fieldnames must match the regex:\n        - regex: ' + regexStr + '\n        - fieldName: ' + fieldName + '\n        ');
        ^

Error:
        fieldnames must match the regex:
        - regex: ^[a-zA-Z][[a-zA-Z0-9_]*]?[a-zA-Z0-9]$
        - fieldName: 0

    at checkFieldNameRegex (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:322:15)
    at checkField (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:334:174)
    at traverse (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:374:17)
    at traverse (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:378:13)
    at validateFieldsDeep (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:381:5)
    at checkSchema (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:399:5)
    at Object.create (src/rxdb/node_modules/rxdb/dist/lib/RxSchema.js:499:18)
    at Object.<anonymous> (src/rxdb/test-oneOf2.js: 28:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by pubkey** [comment]
It's not possible to use `anyOf, allOf, oneOf`. This is to reduce complexity and to prevent schemas which will break with RxDB in the future. The performance-optimisations are build in a way where they always now which fields a document can have.

**Comment by errorx666** [comment]
@pubkey 
I need `oneOf` to express nullability.
e.g.
```js
{
  oneOf: [ { type: 'null' }, { type: 'object', properties: {} } ]
}
```

**Comment by pubkey** [comment]
A workaround is to set type: "object" to a property, it is like the `any` type in typescript. There you can then store whatever you want.

**Comment by maxfriedmann** [comment]
Puh, found this after 2 months of migration. That is very bad. We use a lot of allOf and oneOf and can't just get rid of that now. 

> A workaround is to set type: "object" to a property, it is like the `any` type in typescript. There you can then store whatever you want.

@pubkey Don't I lose type safety / validation by just type: object?

**Comment by maxfriedmann** [comment]
@pubkey Your project looks quite complicated, I guess without spending a lot of time I won't be able to create a satisfying pull request. We'll go for a custom solution for now.

**Comment by gabrielgrant** [comment]
@pubkey can `oneOf`, `patternProperties`, `additionalProperties` etc be used within a sub-property of type object?

**Comment by gabrielgrant** [comment]
Expanding/better explaining that: [as you explained elsewhere](https://github.com/pubkey/rxdb/issues/86#issuecomment-287529182)

> The schema is used by rxdb in 2 ways:
> 
> 1. for schema validation
> 2. to map the plain data to the RxDocument and create the right getters for streams and population.

I certainly understand why implementing 2 for all of JSON schema would be hugely complicated. Your recommendation has been to opt out of both 1 & 2 by using  a plain `type: "object"` sub-property. But it seems like there are a lot of cases where having 1 without 2 would be totally sufficient, and (unless I'm misunderstanding) it seems like just applying the validation to a more complex object should be fairly straightforward

It may be this is possible today?

Or, if not, would you be open to a RxDB-specific flag in the JSON schema that enables this behavior? (something like `rxdb: "validateOnly"`)

**Comment by gabrielgrant** [comment]
A quick experiment shows that the original `oneOf` example that fails immediately at the top level does seem to work in a sub-object:

https://codesandbox.io/p/devbox/icy-silence-4386k2?file=%2Findex.js

```javascript

const RxDB = require("rxdb");
const schema = {
  title: "Transaction Schema",
  version: 0,
  description: "Structure of Transaction Data",
  type: "object",
  primaryKey: "id",
  properties: {
    id: {
      type: "string",
      maxLength: 100,
    },
    date: {
      type: "string",
      format: "date-time",
    },
    transaction: {
      type: "object",
      properties: {
        credit: {
          type: "number",
          multipleOf: 0.01,
        },
        debit: {
          type: "number",
          multipleOf: 0.01,
        },
      },
      oneOf: [
        { required: ["date", "credit"] },
        { required: ["date", "debit"] },
      ],
    },
  },
  additionalProperties: false,
};

new RxDB.RxSchema(schema);
```

**Comment by gabrielgrant** [comment]
unfortunately, it doesn't seem to be applying the validation either, though. @pubkey is this expected behavior?

Full example can be run here:
https://codesandbox.io/p/devbox/tender-mountain-r6tn85?file=%2Findex.mjs

```javascript
import { createRxDatabase } from "rxdb";
import { getRxStorageMemory } from "rxdb/plugins/storage-memory";

const schema = {
  title: "Transaction Schema",
  version: 0,
  description: "Structure of Transaction Data",
  type: "object",
  primaryKey: "id",
  properties: {
    id: {
      type: "string",
      maxLength: 100,
    },
    date: {
      type: "string",
      format: "date-time",
    },
    transaction: {
      type: "object",
      properties: {
        credit: {
          type: "number",
          multipleOf: 0.01,
        },
        debit: {
          type: "number",
          multipleOf: 0.01,
        },
      },
      oneOf: [{ required: ["credit"] }, { required: ["debit"] }],
    },
  },
  required: ["date"],
  additionalProperties: false,
};

const db = await createRxDatabase({
  name: "exampledb",
  storage: getRxStorageMemory(),
});

await db.addCollections({
  transactions: {
    schema: schema,
  },
});
console.dir(db.transactions.name);
db.transactions.insert({
  id: "1",
  date: "2024-01-04T17:56:46.537Z",
  transaction: {
    debit: 1,
  },
});

db.transactions
  .find()
  .exec()
  .then((documents) =>
    documents.forEach((d) => console.dir(d.get("transaction"))),
  );

db.transactions.insert({
  id: "2",
  date: "2024-01-04T17:56:46.537Z",
  transaction: {
    debit: 1,
    credit: 1,
  },
});

db.transactions
  .find()
  .exec()
  .then((documents) =>
    documents.forEach((d) => console.dir(d.get("transaction"))),
  );
```

```shell
$ nodejs index.mjs
'transactions'
{ debit: 1 }
{ debit: 1, credit: 1 }
{ debit: 1 }
{ debit: 1, credit: 1 }
```

**Comment by pubkey** [comment]
@gabrielgrant Starting the sandbox fails for me: 

![fails](https://github.com/pubkey/rxdb/assets/8926560/ad59d55d-77e0-49d2-a5bf-beee69f895b1)

Can you make a PR with a unit test?

**Comment by gabrielgrant** [comment]
hmmm, I'm getting an error from CodeSandbox right now that seems to be occurring before I even get to that point:

![image](https://github.com/pubkey/rxdb/assets/493968/59e5c54e-f18c-4d04-a75b-8c9711f730a5)

I'll try fixing it in a bit. Not sure about writing a unit test, though -- I'm not sure what your intended behavior is in this case
