### ISSUE TITLE
Support syncing revisions with GraphQL

### ISSUE THREAD

**Issue by gautambt** [pubkey/rxdb#1830]
## Case
Feature Request

## Issue
Currently GraphQL based replication does not support syncing revisions. The documentation mentions that the server needs to resolve conflicts. However often for the server to even detect conflicts it needs to have some kind of versioning information. Further for many use cases some kind of user intervention is required for resolving a conflict (i.e the server cannot completely auto resolve conflicts). It would therefore be useful if there was a mechanism to sync the version data as well. 

I can think of the following approach to implementing this: add two new fields to the syncGraphQL options: syncRevisions (boolean) and revisionField (string). If these options are set then:

1) the pushQueryBuilder would get the pouchdb revision along with the rest of the doc
2) for every document pulled using the pullQueryBuilder we can create the revision using the value of the revisionField + endpointHash + plugin ident before storing into pouchdb.

If the approach sounds correct, I can try to make a pull request.

**Comment by pubkey** [comment]
Passing the `_rev` to the pushQueryBuilder should be done, it is removed [here](https://github.com/pubkey/rxdb/blob/master/src/plugins/replication-graphql/index.ts#L259) for whatever reason.

At the moment the revisions is generated from `dataHash + endpointHash + PLUGIN_IDENT` for what reason do you need the revision field in there?
I think when the pushQueryBuilder can include the value of `_rev` there are no other things that must be changed in rxdb and the server can still handle conflicts. I do not understand the benefits to configuring `revisionField` but maybe an example would help.

**Comment by gautambt** [comment]
Yeah you are right, the current method of generating the revision hash should be sufficient. However I think we will need to copy the revision height that we receive remotely. Otherwise there would be no way to detect that there is a conflict. I am inferring from PouchDB documentation that the revision height is the only way to detect that there have been two conflicting modifications.

**Comment by pubkey** [comment]
Any update on this? Are you still working on the PR?

**Comment by gautambt** [comment]
Hey yes, I had fallen sick in between, hence the delay. Hoping to send the PR by EoW

**Comment by gautambt** [comment]
@pubkey Just FYI, I am still working on this. Feel free to mark this issue as closed though.
