### ISSUE TITLE
What is the best practice for using the rxdb for electron apps?

### ISSUE THREAD

**Issue by vergaenglichkei** [pubkey/rxdb#1833]
Hi There,
Thanks for this nice library :)
I want to start a new project which has a lot of integrations with storing data and persistence data on user's machine, like saving 10.000 array of objects. 
I just checked out you examples for electron, You used it in two different ways. remote in client and main.js, I want to know what is the best approach in this case?
What is if i use remote? will rxdb block the UI thread? because I having this issue with other databses like nedb or electron-store (even on main process).
The second question is, Is it better to use child_process to fork another thread? Is that possible? Is that effective?
It'd be nice if someone can help me with this. Thanks again...

**Comment by pubkey** [comment]
I recommend to use the remote API because it reduces much overhead which comes from the replication. RxDB will never block the UI thread. Things that take long will free the thread regulary.

Please do not use the issue-tracker for non-issues.
