### ISSUE TITLE
understanding queries method

### ISSUE THREAD

**Issue by nakos52710** [pubkey/rxdb#1858]
Hi,
Sorry for bothering you with this issue, but I already researched a lot and cannot get my answer. and also documents are little poor.
I'd like to do  something simple with rxdb. but the output is weird for me.
Here is my db config for node.js

```js
    const db = await RxDB.create({
        name: 'testdb',           // <- name
        adapter: leveldown,
        password: 'myPassword',     // <- password (optional)
        multiInstance: true,         // <- multiInstance (optional, default: true)
        queryChangeDetection: false // <- queryChangeDetection (optional, default: false)
    });
```
here is my collection config

```js
await db.collection({
        name: 'heroes',
        schema: {
            title: 'hero schema',
            description: 'describes a simple hero',
            version: 0,
            type: 'object',
            properties: {
                _id: {
                    type: 'string',
                    "primary": true
                },
                name: {
                    type: 'string',
                },
                lastname: {
                    type: 'string',
                },
                dummyField: {
                    type: 'string',
                },
            },
        }
    });
```
everything works fine on inserting.
but when i want to get list of docs in heroes collection it returns rx object. this is so simple, I want to know what should i do to get the json as a input from calling `.find().exec()`.

```js
   const list = await db.collections.heroes.find().exec();
   console.log(list);
```
and the output is this.

![image](https://user-images.githubusercontent.com/60001887/72611823-60491280-392b-11ea-9d5b-5dbb60fc7819.png)

**Comment by pubkey** [comment]
Please use the github issues for real issues, not for common questions.

You can transform the list of documents by calling `RxDocument.toJSON()`

**Comment by nakos52710** [comment]
Sure, Sorry.
So for example if i have 10000 records and want to get list of them I should do another loop after calling `find().exec()`?

**Comment by pubkey** [comment]
If you want 10000 RxDocuments, you have to do nothing.
If you want the plain json-value, you have to itterate and call toJSON
