### ISSUE TITLE
RxDocument to offer a proxy object?

### ISSUE THREAD

**Issue by jimthedev** [pubkey/rxdb#19]
Hi there. Great job on this project. 

One thing that might be helpful:

Right now you need to called `person.get('name')` to get the name property off of a person RxDocument. Is there a way to have RxDocument be a proxy object so that we could call `person.name` instead?

Currently I am doing this with: 

```
// Proxy simple properties get calls to an rxdocument's get method
const p = function(proxyObj) {
  return new Proxy({}, {
    get: (target, name) => {
      return proxyObj.get(name);
    },
  });
};

// Example:
const person = p(rxPerson);
console.log(person.name);
```

My use case is pretty much getting a lot of properties off of a single model so I don't know how well this scales.

**Comment by pubkey** [comment]
Hi @jimthedev I have thought about using the proxy-object for several times the last month.
I know that the usecase you describe is exactly what the proxy-object is here for.

I will try to figure out how to implement it the best way after the holidays.

In your example, how do you handle nested sub-objects like ```person.hair.color``` and how to use the observables like ```person.hair.color.$``` or ```person.hair.color$``` ?

**Comment by marshall007** [comment]
@pubkey you might want to consider wrapping `RxDocument` in an observable wrapper like [`lell`](https://github.com/arkverse/lell) to avoid any specialized getter/setter or "get as observable" functions all together. Then you can just treat `RxDocument` as a plain ol' assignable object.

**Comment by pubkey** [comment]
@marshall007 lell looks nice.

I will make the proxy-feature after I finished the one I'm currently making (middleware-hooks).

Or is there someone willing to create a PR for this?

**Comment by pubkey** [comment]
@jimthedev Finished.
RxDocument is now a proxy-object so you can directly set and get values and also observables of values.

[CHANGELOG](https://github.com/pubkey/rxdb/blob/master/CHANGELOG.md)
[DOCS](https://github.com/pubkey/rxdb/blob/master/docs/RxDocument.md)

get:
```js
var name = myDocument.name;
var nestedValue = myDocument.whatever.nestedfield;
```

set:
```js
myDocument.firstName = 'foobar';
myDocument.whatever.nestedfield = 'foobar2';
```

get observable:
```js
myDocument.firstName$
  .subscribe(newName => {
    console.log(newName)
  });

// nested
myDocument.whatever.nestedfield$
  .subscribe(newValue => {
    console.log(newValue)
  });
```

Check it out.

**Comment by marshall007** [comment]
@pubkey really slick. Nice work!

**Comment by ssured** [comment]
It's a cool feature, but can this be made an opt-in? Afaik Proxy is not available on Edge, IE and Safari. Maybe because I dont know the objectives of this lib, but not supporting all 4 evergreen browsers makes rxdb unusable for me... Very cool project though

**Comment by pubkey** [comment]
@ssured Before I implemented it, I checked [caniuse-proxy](http://caniuse.com/#search=proxy) which tells me that I can use it on all relevant browsers (including edge).

But since it's not supported by IE, you are right, I should provide an opt-out of the proxy-feature which is easy to implement. I will finish the key-compression and than do that (max 2 weeks). Or maybe you want to send a PR for that?

**Comment by ssured** [comment]
This table has some more detailed info on all browsers and ES6 features: http://kangax.github.io/compat-table/es6/#test-Proxy

**Comment by pubkey** [comment]
Hi @ssured .
I now refactored and found out that we don't need the proxy-object.
Because of the strict schema-enforcement, we can use [defineGetter/Setter](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__) which is supported by IE11.
See [this commit](https://github.com/pubkey/rxdb/commit/64148a8e3e9914c90eaa7a03ba6b2f6155e9834c).

**Comment by ssured** [comment]
Smart thinking! Cool stuff!
