### ISSUE TITLE
RxQuery field limiting is not working.

### ISSUE THREAD

**Issue by OverseePublic** [pubkey/rxdb#191]
## Case
Bug / Feature. 

## Issue
Current db.collection.find({}, {field: 1}) does not work since you do not allow the {projection} param
https://docs.mongodb.com/manual/reference/method/db.collection.find/

Maybe I am dumb and I can't find the doc?

**Comment by pubkey** [comment]
This is not supported atm. The performance-gain of projections is minimal because of how pouchdb and the underlaying storage-engines work. If you want to have a single field only, you have to map the results array.
