### ISSUE TITLE
Angular example not working

### ISSUE THREAD

**Issue by oddvarogreid** [pubkey/rxdb#1914]
## Case
Bug in example code

## Issue
Unable to run angular example code.
 An unhandled exception occurred: Job name "..getProjectMetadata" does not exist.

## Info
  - Environment: npm@6.13.4, node@v10.16.3

I don't know if it's my environment or if it's something wrong in the repo but I'm unable to run the Angular example code.

I'm able to create a simple DB using PouchDB in my project, but when i try to import pouchdb-adapter-memory I get "core.js:6014 ERROR TypeError: Cannot read property 'slice' of undefined" in the console.
When I try to use RxDB and the in memory module/adapter i get "ERROR RxError: RxError:
RxDB Error-Code DB9."
To me it looks like the spawnInMemory does not work as intended.

Hope someone can guide me in the right direction or fix the example code.

## Code

```ts
const db = await new PouchDB('foo', {
  adapter: 'memory',
});

db.put({
  _id: 'foobar',
  foo: 'bar',
});

db.get('foobar').then(doc => {
  console.log('found db: ', doc._id);
}).catch(error => {
  console.log('Not working:');
  console.dir(error);
});
```

**Comment by pubkey** [comment]
Breaks also in the CI https://travis-ci.com/pubkey/rxdb/jobs/288158337
We should upgrade to angular 9 anyways which will likely fix this problem.

**Comment by oddvarogreid** [comment]
I tested upgrading to angular 9 and it works.
I will continue testing in our project upgrading to angular 9.
Thanks

**Comment by pubkey** [comment]
If you have time it would be cool if you also upgrade the rxdb angular example
