### ISSUE TITLE
Angular localstorage adapter problem

### ISSUE THREAD

**Issue by Meshkati** [pubkey/rxdb#192]
## Issue
Hi, I was looking for use rxdb on my angular+electron app with localstorage adapter, but I got several errors. I Event tried to run the official (:D) angular example, everything is ok with websql adapter, but on localstorage I get errors:

## Info
- Environment: angular2
- Adapter: Localstorage
- Version: 4.0.2

## Errors
http://paste.ubuntu.com/24734508/

**Comment by pubkey** [comment]
I'm sorry but this stacktrace does not help.
Can you run the code before doing the bundling?

**Comment by Meshkati** [comment]
Before bundling what ?!
I'm just running your angular example by the guid written in readme, with localstorage adapter :-?

**Comment by pubkey** [comment]
Could reproduce. Fix will come

**Comment by pubkey** [comment]
Solved. In the past we had to used a monkey-patched localstorage-adapter to fix a bug which ensures cross-tab-events are working. This is not nessesary now.
