### ISSUE TITLE
transpile should have --watch option

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#196]
Before I could pipe --watch into babel, but now it seems it has a custom transpile script which is dense.

Can we get a `npm run transpile:watch` to help people contribute while linked locally?

**Comment by natew** [comment]
Specifically, babel can do granular watch, not a recompile everything watch.

**Comment by pubkey** [comment]
The reason for the custom transpile-script, was that on slow devices a transpile-on-file-change was destroying the performance. The transpile-script only transpiles files which really got changed during the last transpilation.

For local developement you can so run `npm run test:node` everytime you want to check the tests.
Or you can use `npm run dev` which re-runs transpilation and tests on every filechange.

**Comment by pubkey** [comment]
`TODO add a doc to describe how the developement-workflow works (explain important npm-scripts)`
