### ISSUE TITLE
Pre pull / push hook in replication-graphql

### ISSUE THREAD

**Issue by dome4** [pubkey/rxdb#1977]
## Case
Feature request

## Issue
I am dealing with the problem that bearer tokens of my app are constantly updated and I don't want to abort and restart `syncGraphQL()` every time. Therefore it would make sense to have something like an asynchronous prePush and prePull hook to request a new bearer token from a possibly implemented AuthService and send the request to the backend afterwards.

## Info
  - Stack: replication-graphql plugin

## Code

```js
replicationState.prePush(async () => {
   await this.authService.getBearerToken();
  /* ... */
}, false);
```

**Comment by pubkey** [comment]
@dome4 Yes this is a good proposal.
However I would set the hooks directly when `syncGraphQL()` is called. Like

```ts
const replicationState = myCollection.syncGraphQL({
    url: 'http://example.com/graphql',
    prePush: () => {}
    prePull: () => {}
}
```

I know that this works different atm with the hooks of a `RxCollection` where the function is set after the collection was created. But that was a bad API design and will also be changed in the next major version.

**Comment by pubkey** [comment]
I'm closing this issue since. I still think this is a good request and a PR is welcomed.
