### ISSUE TITLE
RXDB doc to json

### ISSUE THREAD

**Issue by bakaa99** [pubkey/rxdb#1978]
On find() query on a collection i'm getting array of rxdb docs as result
`
_atomicQueue: {}
_dataSync$: {_isScalar: false, _value: {…}, closed: false, hasError: false, isStopped: false, …}
_deleted$: {_isScalar: false, _value: false, closed: false, hasError: false, isStopped: false, …}
_isTemporary: false
collection: {__docChanges$: {…}, _atomicUpsertQueues: {…}, _changeEventBuffer: {…}, _crypter: {…}, _dataMigrator: {…}, …}
isInstanceOfRxDocument: true
`

Mongoose has lean() to handle this issue. Does rxdb has a similar option. If not how do i get only JSON objects on find? 

Thx in advance

**Comment by pubkey** [comment]
`RxDocument.toJSON()`  see https://rxdb.info/rx-document.html#functions
