### ISSUE TITLE
Collection Sync

### ISSUE THREAD

**Issue by MichalZak** [pubkey/rxdb#20]
Could you provide me with clarification on collection sync.
In your implementation you have one database with multiple collections, these collections can sync with couch...

Now can I sync multiple collections with one server side couchdb? Is this what you are already doing? What if I have one collection that I want to sync, and one that I don't , is this possible?

Btw great library, excited to learn and use it.

Mike

**Comment by pubkey** [comment]
Hello @MichalZak . Every collection has it's own sync-stream with a serverside-couchdb.
You can sync multiple collections with one serverside couchdb by starting the sync()-function on every collection.

**Comment by MichalZak** [comment]
Ok thanks, 
So every collection is an instance of Pouchdb right?
Also, did you guys attempt to make an Ionic 2 app?  

Mike

**Comment by MichalZak** [comment]
Im trying to make an Ionic 2 app work

Here is what I have so far:
In my provider (Angular 2 Service)
`
import { Injectable } from '@angular/core';
import * as RxDB from 'rxdb';
import * as WebSQLAdapter from 'pouchdb-adapter-websql';
import 'rxjs/add/operator/map';
import { Observable } from 'rxjs';

@Injectable()
export class PostProvider {

  public postCollection: RxDB.RxCollection;
  public postDB: RxDB.RxDatabase;

  postSchema = {
        "title": "Post schema",
        "description": "describes a single post",
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "primary": true
            },
            "body": {
                "type": "string",
            },
            
        },
   } 
  
 constructor() {
    console.log('Hello Posts Provider');
    
    //setup our rxdb
    RxDB.plugin( WebSQLAdapter);


    //create posts collection
    RxDB.create('postDB', 'websql')
      .then((db) => {
        console.log("PostProvider DB: "+JSON.stringify(db));
        this.postDB = db;
        return db.collection('postCollection', this.postSchema);
      },
      (err)=>{
        console.log("PostProvider -> err: "+JSON.stringify(err));
      }) 

      .then((collection) => {
        collection.insert({title:'Testing'});
        this.postCollection = collection;
      },
      err=>{
        console.log("PostProvider Error: "+JSON.stringify(err));  
      })

      console.log("testing.....");
    }
}
`

The last catch err gets caught, but the error has no content just a plain object {} gets printed
None of the other console.log statements get called.

When I try to use the collection, I get an error, its Null, so none of the .then statements get called.

Do you have any suggestions on how to improve this.

**Comment by RangerMauve** [comment]
@MichalZak If you use `JSON.stringify` on an Error object, you lose its information. Instead you should use `console.log(err.stack)` to log the stack trace.

**Comment by pubkey** [comment]
@MichalZak 
1. Yes, every collection has its own pouchdb-instance.
2. No, there is currently no ionic2-example app. It would be nice if you could start creating one, I will of course help you where I can.

Could you solve your current problem with the empty errors?

**Comment by MichalZak** [comment]
I have solved the issue, thx,  once I get a simple project running, I'll write a tutorial, help out a bit :)

I have a few questions on the design/philosophy of Rxdb 
1.  I have been using pouchdb for a while, I'm comfortable with it, and since you have pouch running in background, I still think in pouch terms.  Ex. Using _id, in rxdb I can make any field primary, can I still use _id

2. What about revisions, _rev, and attachments, will these become available later on?

3. By default pouch is schema-less, you can add anything, but right now rxdb is being really strict, once you start using a schema, you can't make changes to it.  But in development process, you will need to constantly adjust schema. Is it possible to remove this strictness, maybe when a change is detected,run through the objects, see if any don't comply with the new schema, and add warning, maybe allow developer to choose a migration strategy to run.

Suggestion: to make a new instance of rxdatabase, can you allow to add a pre-created pouch object.
When I make a new pouchdb I don't have to pass an adapter, by default pouch will determine which adapter is best and choose that one. This way it will not require to install Typescript require typings and manually specifying an adapter.  It's a little thing, but will make getting started just a little simpler.

I really like what you have done so far, thx for the hard work.

**Comment by pubkey** [comment]
@MichalZak I'm sorry for not answering early.

1. If you do not add a primary to your schema, the _id is the default primary. RxDB basically translates the schema-primary directly to the _id and backwards on every write/read.

2. Revisions a are still used, but not explicitly exposed by RxDB. If you want to get the revision of a RxDocument you can use ```myRxDocument.rawData._rev```.

3. When I wrote the strict schema-hanlding, I had in mind that I would reimport the collection when a change to the schema is made. As @jimthedev mentioned, that is not as easy as it could be. A schema-migration-strategy will be added to RxDB in the near future. [see](https://github.com/pubkey/rxdb/issues/21)

To your suggestion: A single pouchdb-instance would be mapped to a RxCollection, not a RxDatabase. Therefore it is not possible to do that. Every collection of a database has to use the same storage-adapter because it is needed when propagating events to other collections and other RxDatabase-instances on other open browser-tabs.

**Comment by motin** [comment]
> Now can I sync multiple collections with one server side couchdb? 

Check out https://www.npmjs.com/package/rxdb-utils#replication:

> **replication**
> Will allow for filtered replication of collections to a single remote instance. This would allow you to use a single remote pouchdb/couchdb database (per user, if applicable) to save all collections, instead of using one remote instance per user and collection.
> 
> In order to achieve so, all schemas will be modified by adding an rx_model property to all collections, which will be populated for all documents with the name of the collection. The key for this property will not change even if you activate key compression.

Originally posted [here](https://github.com/pubkey/rxdb/issues/29#issuecomment-423802707)
