### ISSUE TITLE
WebpackBin won't let us .then() after collection create / pouchSettings ignored?

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#204]
## Case
Attempt to test pouchSettings skip_setup

## Issue
Seems to not work on my local stack, can't test in webpackbin.

## Info
https://www.webpackbin.com/bins/-KmnW5PpBMmOuw-xcjRo

I tried doing .then() in a few places but get a maximum call stack error in webpack bin.

**Comment by natew** [comment]
Looks like pouchSettings is a legit bug, from RxDatabase.js file, I see the settings look hardcoded.

**Comment by pubkey** [comment]
It looks like the webpack-bin in the issues_template is broken.

**Comment by natew** [comment]
Just re-read and I see that was for internal collections, not RxCollection.create. Going to attempt bumping version and seeing if that fixes it.

**Comment by natew** [comment]
Could it be that you're passing these options as the third argument?

https://github.com/pubkey/rxdb/blob/eec3b033da47ad40bb0dccec3b74c77203a68fb4/src/RxDatabase.js#L401

In pouch docs it shows just two https://pouchdb.com/api.html#create_database

**Comment by natew** [comment]
Actually, had to reset my couchdb and for some reason that fixed it! Sigh...

**Comment by pubkey** [comment]
Is this solved?
