### ISSUE TITLE
destroy a database instance

### ISSUE THREAD

**Issue by maxime-helen-sb** [pubkey/rxdb#206]
## Case
Find a way to destroy a database.

## Issue
No information in documentation.

## Code
Appear in this [test](https://github.com/pubkey/rxdb/blob/master/test/unit/RxCollection.test.js#L39). Is this really synchronous? Does this flush the db?

**Comment by pubkey** [comment]
This destroys the object-instance, not the storage. Check the changelog for RxDatabase.remove(). It will come with v5.0.0 in the next days. I think thats what you are looking for.

**Comment by maxime-helen-sb** [comment]
Yep thanks!
