### ISSUE TITLE
Expose RxQuery / RxCollection for instanceof checks

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#207]
Looking to be able to do this, to auto-sync a query:

```
if (query instanceof RxQuery) {
  // do sync
}
```

Would be helpful for RxDB to export these to access.

**Comment by pubkey** [comment]
Can you paste an example-code where you need this?
I don't know if this would really be usefull because you always know if the given object is and rxquery or not.

**Comment by natew** [comment]
I have a small module that wraps various values in streams and handles those streams, including RxQueries. But it's it's a module of part of a bigger framework, so would like to keep the boundary and just have it check if it's a query using instanceof. Right now I'm doing query.mquery.

**Comment by pubkey** [comment]
This should be solved with the linked commit. Next release containing this will come at the weekend.
Reopen if there is a problem.
