### ISSUE TITLE
For type:number in RxSchema, which one is valid? min or minimum?

### ISSUE THREAD

**Issue by Albert-Gao** [pubkey/rxdb#2070]
https://rxdb.info/rx-schema.html

There is a schema here:

```json
      "healthpoints": {
          "type": "number",
          "min": 0,
          "max": 100
      },
```

But typescript will complain there is no such properties.
![image](https://user-images.githubusercontent.com/18282328/79042903-a7575300-7c4f-11ea-9cf1-e90ff6e3b10d.png)

The most likely type definition to use is:
https://github.com/types/lib-json-schema/blob/master/v4/index.d.ts

```typescript
    maximum?: number;
    minimum?: number;
```

So, which one is right? Or I miss something? Thanks :)

**Comment by pubkey** [comment]
Yes you are right, I fixed the docs.
