### ISSUE TITLE
ANNOUNCEMENT: Published 9.0.0 beta

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#2093]
Hi.
I released the beta of the next major release `9.0.0` to npm.

Please read about all changes [here](https://github.com/pubkey/rxdb/blob/master/orga/releases/9.0.0.md)

It would be great when you test out the new release and post here about problems and stuff.

Also every change is still discussable and also new breaking changes can still be added.

**Comment by lucasmez** [comment]
Hi. Thank you for the update.
I just started using this library. So far I've only created 1 schema and the database, but I'm getting the following error:

![ts_error](https://user-images.githubusercontent.com/20986580/80530734-740f0680-8967-11ea-9c71-89053070397a.jpg)

Relevant packages versions:
"rxdb": "^9.0.0-beta.9"
"typescript": "^3.7.5"

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "baseUrl": "src",
    "allowJs": true,
    "noImplicitAny": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "downlevelIteration": true
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by pubkey** [comment]
@lucasmez thanks for reporting, I will fix

**Comment by pubkey** [comment]
It is done, `9.0.0` is released.
