### ISSUE TITLE
Changes to Schemas

### ISSUE THREAD

**Issue by jimthedev** [pubkey/rxdb#21]
I had a first version of my database. It worked great. The problem is when I modified my schema (by adding a new field to my schema). I get an error on Rxdb.create. My collection is called (audio):

`Error: collection(audio): another instance created this collection with a different schema`.

I figured I might try to handle the error and just drop the existing databases, but I don't see a way to destroy the databases or do any kind of migration. Do you have any insight into how one could deal with this kind of thing in Rxdb?

**Comment by pubkey** [comment]
Hi @jimthedev There is currently no migration-standard when you change the schema. Of course you could just json-export and reimport to another collection audio2.

I'm not sure if the schema-hash-enforcement should be done how it currently is done in RxDB.

To hard-reset the schema-hash you have to find it in the collections-collection and delete it.

```js
const collectionDoc = await this.collectionsCollection.findOne({  name }).exec();
await collectionDoc.remove();
```

**Comment by jimthedev** [comment]
@pubkey Ok that actually helps quite a bit. I was using a sha1 hash of the collection schema then saving it to localstorage https://gist.github.com/jimthedev/a6be98703d22765eb6442b9aa52b57ea

I suppose it makes sense that rxdb is already doing this. Would be interested in some exit hatches to allow folks to know when to execute migrations but I will have to do some more digging into Rxdb next week to see if this will be a simple PR.

Thanks!

**Comment by pubkey** [comment]
@jimthedev A good solution I had in mind is to save schema-versions in the schema itself, like the indexeddb-versions.
Then an update-strategy from schema x to schema y can be defined which also works from schema x->y->z


```js
var mySchema = {
    version: 1                     // <- Version as Integer
    title: "hero schema",
    description: "describes a simple hero",
    type: "object",
    properties: {
        name: {
            type: "string",
            primary: true       // <- this means: unique, required, string and will be used as '_id'
        },
    required: ["color"]
};
```

**Comment by naivefun** [comment]
Is it possible to create collection without schema?

**Comment by pubkey** [comment]
I'm working on this at branch [schemaMigration](https://github.com/pubkey/rxdb/tree/schemaMigration)

**Comment by donni106** [comment]
I am playing around with your React Native example.
I want to import own docs with an given schema. It worked once. I changed something in the data and schema and want to destroy the db to import again.

But then I also get the error:

```
Error: collection(): another instance created this collection with a different schema.
Given parameters: {
  name: "xyz",
  previousSchemaHash: "d1eb...",
  schemaHash: "6c93..."
}
```

I want to reset everything. I have tried to destroy the created database, tried to remove all collections, restarted packager with `yarn clean cache` und `yarn start --reset-cache`.

```
const db = await RxDB.create({
  name: 'xyzdb',
  adapter: 'asyncstorage',
  multiInstance: false
});

db.destroy();
```

Also when i am not running the following, the error occurs.
```
//const xyzCollection = await db.collection({
//  name: 'xyz',
//  schema: xyzSchema
//});

// console.log('remove collection');
// await xyzCollection.remove();
```

How can i clean up my entire db and reset everything?

**Comment by pubkey** [comment]
@donni106 
In dev-mode you can either:
- Use the memory-adapter so your db resets on restart
- Call `RxDB.removeDatabase('mydatabasename', 'adapter');` before creating a new instance
- Add a timestamp as suffix to the database-name to create a new one each run

In prod-mode, you should always create the required migrationStrategies when changing the schema.

**Comment by adam-ashored** [comment]
@pubkey FYI - the memory adapter in development mode isn't working for RN because it's not a full node runtime and it's missing a bunch of modules.

For me, hot-reloading seemingly sometimes screws up the schema hashes, despite the fact that I haven't actually changed the schemas. This might require another issue.

**Comment by pubkey** [comment]
@adam-ashored yes, I am aware of the memory adapter not working in RN. In fact, the whole implementation of the memory adapter is way from optimal.
It should be rewritten without the leveldb-abstraction, this would also fix the big performance problem.
