### ISSUE TITLE
DX Improvement: express-pouchdb

### ISSUE THREAD

**Issue by shellscape** [pubkey/rxdb#2125]
##  Case

I have a suggestion for improved DX

## Issue

While setting up RxDB I attempted to use the `electron` example. It appears that the example is a bit out of date. After attempting to run it I was prompted with this error in the console:

```console
Since version 8.4.0 the module 'express-pouchdb' is not longer delivered with RxDB.
```

That's a frustrating thing to see attemtping to run an example, which kind of should be functional out of the box. My suggestions for improving the DX (developer experience) are:

1. Give the examples a refresh and include all required dependencies in each example's package.json
1. Add `express-pouchdb` to `peerDependencies` or the ceremonial `optionalDependencies` so that we're notified by our package managers of its need.

## Info
  - Environment: Node 12.16.3
  - Adapter: rxdb/plugins/server
  - Stack: Typescript

## Code

n/a

**Comment by pubkey** [comment]
Yes it should be in the package.json of the example if it is used there, PR is welcomed.
Having it in the `peerDependencies` will throw a warning for each RxDB user so I did not do that.
As far as I know `optionalDependencies` does not exists in npm and would have no effect.

**Comment by shellscape** [comment]
It does indeed exist :smile: https://docs.npmjs.com/files/package.json#optionaldependencies.

I had to get through some other bits of that example that are out of date with the rxdb package now as well, so it looks like there's a bit more work to get that example functional again.

For perspective into my thought process; I opened the issue because a `start...fail...fix` process is burdensome for developers and provides a non-optimal experience. A `start...warn...continue` process is much more conducive to a good experience and allows a developer to choose whether or not to terminate.

I'm happy to open a PR for the electron example if you'll consider it, but I humbly suggest that the other examples get a quick functional audit from our benevolent package author when the opportunity arises 🙇

**Comment by pubkey** [comment]
Ah this is new for me. But if I understand correctly, putting sth into the optional dependencies means that it will be installed on `npm install`?

I think the first step is to put the electron example into the CI so that the build fails when the example is broken. We have done this before with most of the other examples. Also we should install rxdb via file, not via relative path, like [we do here](https://github.com/pubkey/rxdb/blob/master/examples/angular/package.json#L42)

**Comment by shellscape** [comment]
Yes, `optionalDependencies` will install if the dependency is available on the registry. That's different than `peerDependencies`. The other option would be to publish the server plugin separately with its own dependencies. I understand why you're not depending directly on express-pouchdb anymore, and it's a good call. 

> I think the first step is to put the electron example into the CI so that the build fails when the example is broken. We have done this before with most of the other examples. Also we should install rxdb via file, not via relative path, like we do here

That sounds good!
