### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by rasdaniil** [pubkey/rxdb#213]
Hi
Couldn't find any information on working with attachments. Are they supported or one should use the underlying pouchdb interface?

Thanks

**Comment by pubkey** [comment]
Hi @rasdaniil 
Attachments are currently not supported. You have to use the underlying pouchdb.
I don't know if it will be added in the future.

**Comment by pubkey** [comment]
Closing this. If you need attachments-support directly in RxDB and are willing to submit a PR, reopen this.
