### ISSUE TITLE
Disable or Modify Logging to log.txt

### ISSUE THREAD

**Issue by shellscape** [pubkey/rxdb#2130]
## Case

I searched the documentation and here in the repo but couldn't find any information about `log.txt` nor how to disable logging to it. 

## Issue

I'd like to know if there's a way to manage logging to `log.txt`. One or any of the following would be useful:

- disable logging to `log.txt`
- choosing the log file location
- choosing the log file name

## Info
  - Environment: Node 12.16.3
  - Adapter: memory + idb
  - Stack: Typescript

## Code

n/a

**Comment by pubkey** [comment]
I think this must be configurated by pouchdb-server.

**Comment by shellscape** [comment]
OK thanks, I'll take a look there. What's the right method to pass config settings onto Pouch through RxDB?

**Comment by pubkey** [comment]
You can pass the variable `pouchSettings` to createRxDatabase or when you create a collection

**Comment by shellscape** [comment]
:+1: 

That setting combined with this https://github.com/pouchdb/pouchdb-server/blob/master/README.md#logfile should do the trick. Cheers!

**Comment by shellscape** [comment]
Looks like I was a bit quick to close this. Tried to pass the log settings through `PouchSettings` and ran into a type issue:

```typescript
export interface PouchSettings {
    auto_compaction?: boolean;
    revs_limit?: number;
    ajax?: any;
    fetch?: any;
    auth?: any;
    skip_setup?: boolean;
    storage?: any;
    size?: number;
    location?: string;
    iosDatabaseLocation?: string;
}
```

Doesn't look like `log` is allowed there.

**Comment by pubkey** [comment]
We have to use our own typings because there a no valid 'official' typings for pouchdb out there.
Also I think this param is pouchdb-server specific, so we might have forgotten that.
Please make a PR where you add the log field.

**Comment by shellscape** [comment]
> Please make a PR where you add the log field.

This seems like a fundamental miss in one of the core functions, so I'm not sure asking someone who's just trying to get the package working for a PR is the best way to go there :smile: Totally get it for new features and edge case bugs, but that pouchDB setting is a first class citizen.

**Comment by pubkey** [comment]
There are so many pouchdb plugins out there, each adding additional options to pouchSettings. The log option does not come from pouchdb directly. I'm closing this, PR will be welcomed.

**Comment by pubkey** [comment]
Fixed here: https://github.com/pubkey/rxdb/commit/8da3c8766a303616df95e500a4c10b216532dec8
