### ISSUE TITLE
Primary must have type: string

### ISSUE THREAD

**Issue by shellscape** [pubkey/rxdb#2132]
## Case

I received an unexpected error message while creating a new collection:

```
RxError (SC16): RxError:
SchemaCheck: primary must have type: string
Given parameters: {
value:{
  "type": "number",
  "primary": true
}}
```

## Issue

I was surprised when I attempted to create a new collection and used a number property as the primary. The documentation doesn't mention any constraints on types that can be used, and it doesn't point users anywhere to read about constraints.

So this leads me to ask two questions:

1. Why are we forced to use a string?
1. Can we add this (and other) constraints to the documentation?

## Info
  - Environment: Node 12.16.2
  - Adapter: idb
  - Stack: Typescript

## Code

```js
const propertiers = {
  id: { type: 'number', primary: true }
};

const schema = {
  title: 'Configuration Schema',
  description: 'Bionic Tit Configuration',
  version: 0,
  type: 'object',
  properties
};
```

**Comment by shellscape** [comment]
Man this is frustrating. I just ran into the `SC26` error now, and there isn't any documentation available about these error messages. I'm trying really hard to love this project, but I can't even get a simple collection setup to match my types because there's no direction for these errors available.

**Comment by pubkey** [comment]
@shellscape 
Sorry for the frustration, there might be some missing parts in the docs, let's fix them together.

Notice that the current documentation is not describing the new `9.0.0-beta.9` but the old `8.X.X` version. This is why `SC26` is not in there. You can read the docs for 9.0.0 directly [in the sources](https://github.com/pubkey/rxdb/tree/master/docs-src). They will be put to rxdb.info as soon as 9.0.0 is released.

Like in most NoSQL databases, the primary key must be a unique, final, required, string. The [docs here](https://rxdb.info/rx-schema.html#example) say `the name-property is the primary. This means its an unique, indexed, required string which can be used to definitely find a single document.`

**Comment by shellscape** [comment]
> Notice that the current documentation is not describing the new 9.0.0-beta.9 but the old 8.X.X version. 

Typically package authors won't make beta versions the `latest` version. I hadn't inspected package.json (that's on me) but I definitely didn't expect  the `latest` dist-tag to point to a beta version.

```console
→ npm info rxdb dist-tags
{ latest: '9.0.0-beta.9' }
```

A much better practice there is to use the `beta` or `next` tag, which is pretty common practice, for beta and test versions.

> The docs here say the name-property is the primary. This means its an unique, indexed, required string which can be used to definitely find a single document.

Man, I must have read over that doc four times and didn't see "string" there. The various properties that RxDB does support should be clearly laid out with relevant requirements. It's too difficult to pick up on requirements in sentences like that.

So taking a step back and looking at the 9.x docs, I still can't find where this rule "indexes needs to be specified at collection schema level" is laid out, nor how my schema differs from what the error message is trying to say. Every error message is important. If you're reporting a schema problem, please show the user where in the schema the error is. AJV, Yup, and Joi do a great job of this and I'd encourage you to think about using one of those three rather than json-schema in 9.x before you release it.

I really, really like the idea behind the library. You've done a great job on a hard task. The work I'm doing requires me to move forward and I really wish I had the time to help improve this. I want you to be encouraged and keep at this. Unfortunately I think I'll have to move down to a lower level and use pouch directly to keep my project moving forward.

**Comment by pubkey** [comment]
Thanks, didn't know that it is possible to set the dist-tag, I will fix the latest release.

I think you should use pouchdb directly.
Notice that RxDB is an open source project, not something I want to sell you.

**Comment by shellscape** [comment]
> Notice that RxDB is an open source project, not something I want to sell you. You have to fix stuff by yourself.

With respect, I'm a maintainer of quite a few open source projects. Several of those receive millions of downloads per week. I opened issues here to help your project and help you as a maintainer. _"You have to fix stuff by yourself"_ is really only acceptable if you inform users right out of the gate that the project is not maintained any longer. Adding a header to the README is a great way to go about that. Otherwise, users asking for fixing of fundamental parts of a project, which are not edge cases, is something that should be expected.

I wish you the best of luck with your project and I hope that it continues to mature.

**Comment by pubkey** [comment]
The definition maintaining does not mean you have to spend your free time fixing other peoples bugs. Your edge cases are not a fundamental part of this project, you are also the first one that thinks a runtime schema check which tells you exactly what to do, is a bug.

Also npm download is a bad metric for open source projects.
