### ISSUE TITLE
Collection.newDocument have no params

### ISSUE THREAD

**Issue by topperblues** [pubkey/rxdb#214]
Hi, 
I'm working with typescript 2, i have a db service and i can get collection in component.
When i try to create newDocument on that collection i get this error:

```
[ts] Supplied parameters do not match any signature of call target.
(method) RxCollection.newDocument(): RxDocument
```
So i go to see what i have in newDocument definition and i see:

```
declare class RxCollection {
    database: RxDatabase;
    name: string;
    schema: RxSchema;

    ...
    newDocument(): RxDocument;
    ...

}
```
Typescript block me to make call like this:
collection.newDocument({
<new blank data>
})
so, how i can create a new blank data object on a collection with typescrit?
Thanks, regards.

**Comment by pubkey** [comment]
The input-param was missing on the typings. Added with the linked commit.
