### ISSUE TITLE
rxdb to rxdb replication

### ISSUE THREAD

**Issue by peterpetre** [pubkey/rxdb#216]
Hello, is possible to sync between two rxdbs in general?

I tried having one rxdb on browser and one on nodejs with express-pouchdb, did some turnarounds like: 
```
collections.filter(col => col.sync).map(col => col.name).map(colName => db[colName].sync({
   remote: syncURL + 'heroesreactdb-rxdb-0-' + colName + '/'
}));
```

Kind of works, if i put the RxDB.PouchDB on express-pouchdb, but there is a clear solution for it?

Another example, is if rxdb.sync(rxdb) is possible.

**Comment by pubkey** [comment]
hi @peterpetre . You can not sync RxDB-RxDB. But you can sync RxCollection-RxCollection.
So if you want to sync complete rxdb-instances, you have to sync each collection. There is also a [test](https://github.com/pubkey/rxdb/blob/master/test/unit/Replication.test.js#L272) which is using this. But this has both RxDB-instances in the same process.

At the moment you cannot use RxDB as sync-server. So you have to sync your browser and your node-database to the same express-pouch or couchdb.
