### ISSUE TITLE
Sorts are broken

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#219]
This query works with a index defined through RxDB for createdAt:

```js
Document.collection.pouch.find({ selector: { createdAt: { $gt: null } }, sort: [{ createdAt: 'asc' }] }).then(console.log)
```

This query never actually returns anything:

```js
Document.collection.find().sort('createdAt').exec().then(console.log)
```

This one throws an error:

```js
Document.collection.find({ createdAt: { $gt: null } }).sort('createdAt').exec().then(console.log)
// throws  Error: Cannot sort on field(s) "createdAt" when using the default index
```

I can't seem to construct a query that actually lets me use createdAt using RxDB find without either never returning or throwing a sort error.

**Comment by pubkey** [comment]
Hi @natew 
Can you post your schema so I can create a reproduce of this bug?

**Comment by natew** [comment]
Tried a few more variants:

![image](https://user-images.githubusercontent.com/12100/28586426-a2170a6e-7128-11e7-9c10-ef1d1018554e.png)

**Comment by natew** [comment]
Ahhh, ok. I was creating index manually from a previous error, and then a new error caused index: true to be not set on timestamps. All my end 👍 apologies for bugging.

**Comment by natew** [comment]
On a totally separate note, I've been trying to use [Kontur](https://github.com/zweifisch/kontur) and now have a Proxy in front of it to try and extend it to support some RxDB stuff.

Maybe could donate to RxDB though I guess having layers of libraries gets scary.

**Comment by woss** [comment]
aaaand i found it in the examples. https://github.com/pubkey/rxdb/blob/master/examples/supabase/src/hero.schema.ts#L21
