### ISSUE TITLE
Adpater Idb not added 

### ISSUE THREAD

**Issue by michiel1995** [pubkey/rxdb#22]
i want to user RxDb idb adapter in an ionic project but when i use this
```
import * as RxDB from 'rxdb';

RxDB.plugin(require('pouchdb-adapter-idb'))
RxDB.plugin(require('pouchdb-replication'))  //enable syncing
RxDB.plugin(require('pouchdb-adapter-http'))
``` 

After that i want to create the database by doing this
`RxDB.create('nikoDb', 'idb', 'myLongAndStupidPassword', true)` but then i get this error ```Adapter idb not added.
                 Use RxDB.plugin(require('pouchdb-adapter-idb');```
But i added the plugin. Do you know what i do wrong?

**Comment by pubkey** [comment]
Have you tried to use websql? I dont know if ionic supports idb.

**Comment by labibramadhan** [comment]
I'm experiencing the same issue, i checked the rxdb source code that idb adapter wasn't registered after calling `RxDB.plugin()`, the PouchDB object inside rxdb (index.js) still has `adapters` empty property. but when i'm using websql adapter, `adapters` property filled, i still don't have any solution, even i'm using websql for now but i was using idb adapter without any problem then this problem suddenly occurs

**Comment by igorissen** [comment]
Any news about this issue? Because I'm also experiencing this issue.

**Comment by chinmaymahajan** [comment]
@michiel1995  you didn't install pouchdb-adapter-idb. Just do yarn add pouchdb-adapter-idb and you should be good.
