### ISSUE TITLE
Will work with nestjs? 

### ISSUE THREAD

**Issue by theArianit** [pubkey/rxdb#2227]
I don't know if it's ok to make just question of this kind. But does rxdb for couchdb also work with nestjs? It's a nodejs framework like angular (typescript).
if it's not supported for nestjs now, will it be in the future?

**Comment by pubkey** [comment]
I think you should try it out. I never used nestjs so I cannot say for sure.
RxDB supports many storage adapters so in theorie it should be possible to make it work with serverside rendering.
