### ISSUE TITLE
Feature Request: Access to previous revisions - document history

### ISSUE THREAD

**Issue by gotjoshua** [pubkey/rxdb#2232]
## Case
Feature Request: Easy access to document history

## Issue
I spent quite some hours looking at the internals of the IndexDB rxdb_pouch storage, and syncing back and forth between memory and idb collections. I noticed that the idb has many document revisions saved (and visible in the "by-sequence" section). I also struggled like hell to get access to them. The closest I managed was to get all changes since the last refresh via: `_changeEventBuffer` and to get all revision ids via `RxDBidb[collectionName].pouch.get` (see code example below)

## Info
  - Environment: (browser)
  - Adapter: (IndexedDB/memory..)
  - Stack: (Typescript, Vue, Quasar)

## Code
```js
changes = await RxDBidb.todos.pouch.get(this.todo.id, {
        revs: true,
        open_revs: 'all', // this allows me to also get the removed "docs"
        revs_info: true // Include a list of revisions of the document, and their availability.
      })
      if (changes.length && changes[0].ok && changes[0].ok._revisions) {
        const revID = changes[0].ok._revisions.ids[2]
        console.log('fetching rev:', revID)
        const res = await RxDBidb.todos.pouch.get(this.todo.id, {
          rev: revID,
          revs: true,
          open_revs: 'all', // this allows me to also get the removed "docs"
          revs_info: true // Include a list of revisions of the document, and their availability.
        })
        undoTarget = res[0].ok
      }
```

So, As annoying as that was, it seemed like it ought to be possible. However, undoTarget is always the most recent revision... even when i manage to fetch the list of previous revisions and try to explicitly fetch an older one from pouch.

Proposal:
Allow two new properties of a collection: 
 - disable compaction (keep all revisions and allow explicit/manual cleanup/archiving of older history)
 - enable document history (easily accessible via `RxDoc.history: RxDocType[]`)

**Comment by pubkey** [comment]
Compaction can be disabled by using `pouchSettings` when a database or collection is created.
I think this overall is an edge case and using the internal pouchdb to get all revisions is a good way to handle this.
At the moment I am working on an abstraction for the RxStorage like described in the 9.0.0 release. I do not want to maintain any more features before this is done.

**Comment by gotjoshua** [comment]
It seems like autoCompaction is anyway disabled by default...
 >  See [Create a DB... auto_compaction](https://pouchdb.com/api.html#create_database)

Eventually, I was able to get the actual previous revision document (thanks to [this answer](https://stackoverflow.com/a/42181600/2919380)) - One needs to use bulkGet and to be sure to formulate the revision ids correctly.

but I still find it very awkward. I fully respect that it is not top priority (and a bit of an "edge case"). Still if you agree that it _could_ be an interesting feature, I'd be happy to consider making a PR, if we come to an agreement about how the Rx api could look.

I would propose a simple array on each RxDocument.history that is disabled by default, and enabled via a new collection option RxCollection({documentHistory: true})

If you like the general idea, I can work it into a pre-proposal before starting on a PR

**Comment by gotjoshua** [comment]
I started a plugin and have a first viable prototype:
https://github.com/st-ax/rxdb-history

I think I will need to ask some pouch experts if there is a more eloquent way to get those revision docs (cuz my code is rather ugly so far)

**Comment by pubkey** [comment]
This looks good.
I think we should add a page to the rxdb-docs where we link to third party plugins. Along with [rxdb-utils](https://github.com/rafamel/rxdb-utils)

I am closing this issue because I think this is resolved.
