### ISSUE TITLE
no RxCollection type available to import

### ISSUE THREAD

**Issue by techo207** [pubkey/rxdb#2234]
I'm testing the new 9.0.0 update but when i use:
import { rxCollection } from 'rxdb';
it produce:
Module '"../../node_modules/rxdb/dist/types"' has no exported member 'rxCollection'. Did you mean 'isRxCollection'?

that works perfectly before update, i already checked 
https://rxdb.info/tutorials/typescript.html 

rxdb v9.0.0

**Comment by pubkey** [comment]
It is `RxCollection` with uppercase R.
