### ISSUE TITLE
Chained Query methods should be available in Documentation

### ISSUE THREAD

**Issue by rbarisic-lme** [pubkey/rxdb#2249]
https://github.com/pubkey/rxdb/blob/master/docs-src/rx-query.md

should contain a list of available methods.

While it links to a doc from MongoDB, that doc doesn't really help. For example, it doesn't contain the where() method mentioned in the examples. It's getting kinda frustrating.

On another note, the mango syntax isn't even the same as in the linked doc, as there are no mentions of "selector" in the linked docs.

**Comment by pubkey** [comment]
Edit, the methods can be found here https://github.com/aheckmann/mquery

**Comment by pubkey** [comment]
A PR with the missing docs content would be nice.
But since we use a third party module, it would be sufficient to link to their docs.
