### ISSUE TITLE
migrationStragies not working

### ISSUE THREAD

**Issue by phihochzwei** [pubkey/rxdb#2288]
## Case
Bug

## Issue
I basically try to get a feeling for RxDB. Therefore I created a schema with version 0, run it, than change it to version 1 and add migrationStrategies. When doing so, I receive the error: 

`oldCollection.dataMigrator.migrationStrategies[version] is not a function`

## Info
  - Environment: Browser 
  - Adapter: IndexedDB
  - Stack: Angular 9

## Code

```ts
 const test = {
    keyCompression     : true,
    version            : 1, // changing this from 0 to 1
    autoMigrate        : true,
    type               : 'object',
    properties         : {
      name: {
        type: 'string'
      },
      id  : {
        type: 'number'
      }
    },
    migrationStrategies: { // adding those after changing 0 to 1 above
      0: ( old ) => {
        return old;
      },
      1: ( old ) => {
        return {
          name: old.name
        };
      }
    },
    required           : []

  };
```

**Comment by pubkey** [comment]
You do not add this property to the schema.
Check this https://github.com/pubkey/rxdb/blob/bb3b4f1bd7cd1be46b947d9930829eb0e794b392/test/unit/data-migration.test.ts#L35 or the docs https://rxdb.info/data-migration.html
