### ISSUE TITLE
Hero percentage

### ISSUE THREAD

**Issue by PointOviu** [pubkey/rxdb#230]
## Case
So , just as a suggestion, I'd put the percentage bar green in relation to the written percentage, so that 100% means a full green bar. It's not, at the moment.
The code below solves this, adding the current percentage next to the name of the hero.

## Code
`
    <md-list-item *ngFor="let hero of heroes" class="listHero">
        <div class="color-box" [style.background-color]="hero.color"></div>
        <div class="name">
          {{hero.name + ": "}}{{hero.hp + "%"}}
          <div class="life">
            <div class="currentPercent" [style.width]="hero.hp + '%'"></div>
          </div>
        </div>
        <div class="actions">
            <i class="fa fa-pencil-square-o" aria-hidden="true" (click)="editHero(hero)"></i>
            <i class="fa fa-trash-o" aria-hidden="true" (click)="deleteHero(hero)"></i>
        </div>
    </md-list-item>
`

**Comment by pubkey** [comment]
Hi @PointOviu thank you for the suggestion. Can you do a Pull-Request with the changed code?

**Comment by PointOviu** [comment]
Hi,
I didn't even use git on this, I just did a rough change on my desktop. This is just a suggestion that doesn't invalidate anything on the example given.
