### ISSUE TITLE
GraphQL replication offline increasing requests 

### ISSUE THREAD

**Issue by zefman** [pubkey/rxdb#2336]
## Case
Bug

## Issue
When using the GraphQL replication plugin there appears to be an issue where when the user is offline the number of requests made to the graphql server increases infinitely until the browser crashes.

Here is a video demonstrating the problem: https://www.loom.com/share/6281119f4b7f41f19a48ff4f9e47c4b4

## Info
  - Environment: Browser - Chrome
  - Adapter: IndexDB
  - Stack: Typescript, Vue

## Code

I have created a repository that allows the reproduction of the issue here:

https://github.com/zefman/rxdb-replication-issue

**Comment by pubkey** [comment]
@zefman  the linked repo is gone

**Comment by zefman** [comment]
@pubkey Thanks for sorting this. The repo I made was still there, I think GitHub was having a bad day yesterday. Thanks again.
