### ISSUE TITLE
PreInsert hook not picking picking up insert operation

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#2343]
`   const accountCollection = await db.collection(account.schema)

    await accountCollection.preInsert(function (plainData) {
      console.log('-----> hello', plainData)
    }, true);
`

I'm getting no console on insert operation. Is there any issue with the syntax?

BTW..great work the DB, loving it.

**Comment by pubkey** [comment]
You do not need the `await` before the call to preInsert.
Your code should work. This is tested well I do not think this is a bug, maybe you do something wrong when you insert a document.

**Comment by ravi-poonia** [comment]
I was rxdb-utils for timestamps, that package is not updated for v9, spend a lot of time on try to upgrade that package but couldn't get the hooks working. Had to revert back to v8 in the end. I'll come back to it later on when i have some free time :-)

Thx for the quick reply.
