### ISSUE TITLE
Content-Security-Policy Error on validate schema

### ISSUE THREAD

**Issue by willyelm** [pubkey/rxdb#235]
**EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive**

Since module `is-my-json-valid` is using function generators to validate the schema when the [validator function](https://github.com/pubkey/rxdb/blob/5f9fabd1a27df8db58fa7104b765e8aa8aadee52/src/RxSchema.js#L120) runs on a secured server using a CSP. it does throw an error every time.

I think for server side usage it would be fine to keep using `is-my-json-valid` but use another when running it from the browser.

**Comment by pubkey** [comment]
Hi @willyelm .
Can you post some code to reproduce this problem? Maybe it also helps to describe your environment.
I never had issues with the validation, neither on browsers nor on node.

For future issues, please use the issues-template :)

**Comment by willyelm** [comment]
Hi @pubkey,

Thank for the response you can reproduce by adding the following the header to emulate the server in webpack.

If you add 
headers: {
  'Content-Security-Policy': 'default-src \'self\' \'unsafe-inline\''
}
inside your [devServer config](https://github.com/pubkey/rxdb/blob/b5de998d6ab57564356334390996cbaf1dc7d88f/examples/angular2/webpack.config.dev.js#L29)
 
Then run the server any unsafe code like eval, new Function, Function.* will be rejected.

I've tried other schema validators and seems like `[z-schema](https://github.com/zaggino/z-schema)` works with no issue.

**Comment by pubkey** [comment]
Hi @willyelm 
I realeased 5.3.0 a few minutes ago.
You can now create your own validation-plugin with `z-schema` instead of `is-my-json-valid`.
The easiest way would be to start with a copy of [this file](https://github.com/pubkey/rxdb/blob/master/src/modules/validate.js) and replace the validation-dependency.

**Comment by pubkey** [comment]
Closing this for now. A PR with an alternative validation-module is welcomed.

**Comment by phil-lgr** [comment]
@willyelm I fixed this FYI
