### ISSUE TITLE
JSON Schema types

### ISSUE THREAD

**Issue by c10b10** [pubkey/rxdb#2386]
Where in the documentation can I find the complete list of types allowed by RxSchema? I could only find them [in the code](https://github.com/pubkey/rxdb/blob/a6f335312520951c97d81ee2221804843ddf4f1c/src/types/rx-schema.d.ts#L4), but I'm still confused as to the difference between `integer` and `number`.

Which is more appropriate for a `float` type?

**Comment by pubkey** [comment]
this is defined by the json-schema standard. So you will not find this in the RxDB docs.

**Comment by c10b10** [comment]
Thanks!
