### ISSUE TITLE
unknown operator "0" 

### ISSUE THREAD

**Issue by msotnikov** [pubkey/rxdb#2401]
## Case
bug

## Issue
unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all

If I start with the name field and add any fields in any order, everything works.

If I remove one filter from the name, an error will occur. And in any other order, if i don't start with the name field, an error will appear in different places.

## Info
  - Environment: browser Chrome 84.0.4147.105
  - Adapter: pouchdb-adapter-indexeddb (same behavior with idb)
  - Stack: Babel 7.10.5, React 16.13.0, rxdb 9.3.0

### Working query example
```
const rxDocuments = await collection
  .find({
    selector: {
      $and: [
        {
          $or: [
            { name: {$eq: '23'} },
            { name: {$eq: '235'} },
          ]
        },
        { cost: { $eq: 532 } },
        {
          $and: [
            { price: { $eq: '623' } },
            { price: { $eq: '34' } },
          ]
        },
        {
          $or: [
            { quantity: { $lt: 363 } },
            { quantity: { $gt: 436 } },
          ]
        },
      ]
    }
  })
.exec()
```

### Schema
```
// schema
export const schema = {
  title: 'products',
  version: 0,
  description: '',
  type: 'object',
  properties: {
    id: {
      type: 'string',
      primary: true,
    },
    name: {
      type: 'string',
    },
    description: {
      type: 'string',
    },
    price: {
      type: 'number',
    },
    cost: {
      type: 'number',
    },
    quantity: {
      type: 'number',
    },
  },
  required: ['id', 'name'],
  indexes: [
    'id',
    'name',
    'cost',
    'price',
    'quantity',
  ]
}
```

**Comment by pubkey** [comment]
@msotnikov this likely is a pouchdb problem. Please try to reproduce it with plain pouchdb and maybe create an issue there.
