### ISSUE TITLE
Automatic Conflict Resolution Suggestion

### ISSUE THREAD

**Issue by MentalGear** [pubkey/rxdb#2430]
Just a quick tip, since automatic conflict resolution seems to be something that is worked on:
https://github.com/automerge/automerge

PS: thanks for this great lib with all it's amazing (offline-first) features !

**Comment by pubkey** [comment]
Hi @MentalGear thanks for the hint.
The current problem for automatic conflict resultion, is that this must be implemented as a hack by overwriting pouchdbs bulkDocs function. Only with that it can be guaranteed that rxdb always returns the correct results even when a conflict resolution is in progress.
For that we should first finish the abstraction to `RxStorage` so the 'hack' can be added easier.
