### ISSUE TITLE
Use the existing local DB

### ISSUE THREAD

**Issue by AndonMitev** [pubkey/rxdb#2453]
### **Case**
How to open an existing database?

### **Issue**
I already create one database with RxDB.create(), and created some collections, put some documents in it
So, in another script, i want to open that database to execute some queries, but I don't know how to do it.
I tried to use RxDB.create() with same database name, but it create new database and override the created database above.

### **Info**
Environment: Electron
Adapter: LevelDB
Stack: React

**Comment by pubkey** [comment]
Calling RxDB.create() again should reopen the previous db instead creating a new one. If this does not work for you, please try to reproduce the problem with the electron example https://github.com/pubkey/rxdb/tree/master/examples/electron

**Comment by AndonMitev** [comment]
So if the name of the db it's the same it's should reopen if exists instead of creating new one? I'll give a try but so far every time when i start application using the same db name recreate a new one and new .ldb file has been created

**Comment by pubkey** [comment]
yes this should work.

**Comment by AndonMitev** [comment]
I will test bit later today provided example and i will give feedback how the things are going. Thanks!

**Comment by sanjevirau** [comment]
@pubkey @AndonMitev I'm facing the same problem. The `createRxDatabase` for some reason creating new database instead of reusing the old one. I'm using `pouchdb-adapter-leveldb` and storing db as storage in my electron app.

**Comment by AndonMitev** [comment]
I notice some issue with writing on the file and it's not consistent tho:
![image](https://user-images.githubusercontent.com/32274987/91338579-d8d75200-e7dd-11ea-8165-123339c854eb.png)
I manage to add three heroes successfully, but on 4th which i tried to add, simply just do not add it to the file.
Otherwise if there are any entites in the database they are initially loaded i can confirm

**Comment by AndonMitev** [comment]
Ok i found the issue in my code. When collection was initialized i was not checking for existing docs and always was providing default state so thats why everything was overwritten 👍
