### ISSUE TITLE
Running 7 sync calls causes pouch emitter to log "potential memory leak" errors

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#246]
Apologies for quick issues here without much detail. If you create a quick look and run a few queries with .sync() calls for each, you quickly get large emitter logs in your console.

1. Any way we can add option to silence these sorts of things through RxDB? Because it abstracts pouch a bit seems natural.

2. Not sure if there's some better solution too that avoids using so many emitters or something.

**Comment by pubkey** [comment]
In nodejs you can increase the event-listener-limit. On browsers I don't think we can overwrite this behavior. Or do you see any solution?

**Comment by natew** [comment]
It's a good question, from what I understand this comes from Pouch? Basically there should be a hook on the emitter library. I'll try and check into this more soon.

**Comment by pubkey** [comment]
I think this is a known thing with pouchdb. See [here](https://github.com/pouchdb/pouchdb/issues/6225).
I very hacky workarround would be to overwrite console.log/error/warn and filter every memory-leak-log.
