### ISSUE TITLE
can not sync attachment from remote couchdb

### ISSUE THREAD

**Issue by eltonec** [pubkey/rxdb#2460]
i can not sync attachment(image) from remote couchdb but can sync attachment from client to server, other data is ok, i use angular!

**Comment by pubkey** [comment]
sorry but this does not help. Please use the issue template and provide enough information.

**Comment by eltonec** [comment]
thanks, i change to use pouchdb directly and replicate from server but get the error message "Cannot assign to read only property 'type' of object '[object Blob]'"

**Comment by pubkey** [comment]
Please use the issue template.
