### ISSUE TITLE
createRxDatabase not provided

### ISSUE THREAD

**Issue by pete-hotchkiss** [pubkey/rxdb#2463]
## Case
module does not provide createRxDatabase method

## Issue
Asked this on gitter a few days ago, but had no joy there - so apologies for repeating here.

I'm Working on a new RxDB project using 9.5.0 release (having previously used 8.n.0 releases perfectly) and my stack is having real problems simply creating a DB instance.

The command line is barfing - insisting that the module `rxdb` does not provide an export named `createRxDatabase`.

## Info
  - Environment: Node.js
  - Adapter: memory
  - Stack: Typescript

## Code

```typescript
import { createRxDatabase } from "rxdb";
...
this._db = await createRxDatabase<FooCollections>({
      name: "FooDb",
      adapter: "memory",
    });
```
the tsconfig.json set up is

```
{
    "compilerOptions": {
        "target": "es6",
        "noImplicitAny": false,
        "outDir": "dist",
        "rootDir": ".",
        "sourceMap": false,
        "moduleResolution": "node",
        "lib": [
          "es2017", "dom", "es2018.regexp", "esnext"
        ]
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [ "node_modules" ],
    "paths": {
        "rxdb": ["node_modules/rxdb/dist/es"]
    },
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@types/node"
    ]
}
```

**Comment by pubkey** [comment]
Please do `import * as rxdb from 'rxdb'` and then log the rxdb object.

**Comment by pete-hotchkiss** [comment]
Sorry - meant to come back and post a comment update for anyone else that hits a similar blocker.

The following adjustment to the import solves it

`import { createRxDatabase } from "rxdb/plugins/core"`
