### ISSUE TITLE
Using RxDB to only wrap remote (couch) endpoints

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#247]
Hey, final issue for the day (I think :)).

Curious, if I pass in a http:// endpoint to RxDB, it seems to take it and just treat it as a local db, if I'm not mistaken.

For example I see something like this on the internal pouch name: "username-rxdb-0-http://api.jot.dev/couch/documents/".

Wondering, any chance we can support non-local RxDB? My use case is server-side, would be vastly helpful to be able to use models on both sides, but there's really no need for my queries there to have a local cache at all.

Am I missing something that already exists?

**Comment by pubkey** [comment]
It's currently not possible to create remote-only collections (like with the pouchdb-http-adapter).
I don't think this will come in the near future, it's a lot of work that would have to be done.

**Comment by natew** [comment]
That seems fair, I can definitely deal with just running sync on everything for now!

**Comment by pubkey** [comment]
I added this feature to the [backlog](https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md#remote-only-collections). Maybe I or someone else can implement this in the future.

**Comment by pubkey** [comment]
@thcolin no sorry there is nothing new. Since I personally do not need this feature, we are still looking for someone who commits to implement this.
