### ISSUE TITLE
Property 'changed' does not exist on type 'EventReduceResult<any>' (and newResults)

### ISSUE THREAD

**Issue by baststar** [pubkey/rxdb#2477]
in /node_modules/rxdb/src/rx-query.ts
rxdb@9.5.0

![image](https://user-images.githubusercontent.com/3816601/91660423-0bcb5f80-ead6-11ea-8faf-8f5167d69f7e.png)

![image](https://user-images.githubusercontent.com/3816601/91660479-7d0b1280-ead6-11ea-8c7b-30ddf7e9eb73.png)

**Comment by pubkey** [comment]
which typescript version are you using?

**Comment by baststar** [comment]
typescript@3.9.5

**Comment by pubkey** [comment]
This is really strange. Do you have any idea how to reproduce this in the CI? Maybe your tsconfig compiler flags have sth to do with that.

**Comment by baststar** [comment]
Ahh easy to repoduce:

```
(npm install -g @angular/cli)

ng new rxdbtest

add "allowSyntheticDefaultImports": true to tsconfig.base.json

npm install --save rxdb

in app.component.ts 

import {RxGraphQLReplicationState} from 'rxdb/src/plugins/replication-graphql/index';

ng serve

```

**Comment by pubkey** [comment]
does it only show errors in PHPStorm or also when you run `npm run build` ?

**Comment by baststar** [comment]
also on build

**Comment by baststar** [comment]
can't you reproduce this?

**Comment by baststar** [comment]
so typescript doesnt know if calculatedNewResults returns an EventReduceResult or an EventReduceResultNeg (latest one doesnt have these both properties)

**Comment by pubkey** [comment]
I try to understand why this happens. [Here](https://github.com/pubkey/rxdb/blob/master/examples/angular/tsconfig.json#L11) in the angular demo, I set `allowSyntheticDefaultImports: false` because this makes it stricter when it does not allow imports from modules with no default export.

**Comment by baststar** [comment]
first error without allowSyntheticDefaultImports would be
![image](https://user-images.githubusercontent.com/3816601/91885249-c3ec3a00-ec87-11ea-94f4-7108a1b6ce2c.png)

```
from 
export = clone
to
export default clone
```

![image](https://user-images.githubusercontent.com/3816601/91885326-e41bf900-ec87-11ea-8264-139058e68e1a.png)

```
it could be
from
import Md5 from 'spark-md5';
to
import * as Md5 from 'spark-md5';
```

and so on

**Comment by baststar** [comment]
ah damn that doesnt work for deep-equal

**Comment by pubkey** [comment]
I think we should update the angular example to angular v10. Then likely we can reproduce the problem there and fix it while having it covered in the CI.

**Comment by pubkey** [comment]
I am closing this. Please reopen if it still occurs.
We need a proven bug by making the CI fail.
