### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by malikdoksoz** [pubkey/rxdb#2481]
Will there be support for Flutter?

**Comment by pubkey** [comment]
Unlikely. Please read the issue template.

**Comment by pubkey** [comment]
Sry you cached me in a bad mood :+1: 
So I was reading into flutter and tried to find out how to make RxDB usable.
There is a javascript runtime in flutter which could work for the RxDB internals. But anyway we would need a big dart wrapper over all functions. I decided that this is too much work for me, especially because I do not have any flutter project atm where I could use this for myself.

**Comment by malikdoksoz** [comment]
> Sry you cached me in a bad mood :)
> So a few months ago I was reading into flutter and tried to find out how to make RxDB usable.
> There is a javascript runtime in flutter which could work for the RxDB internals. But anyway we would need a big dart wrapper over all functions. I decided that this is too much work for me, especially because I do not have any flutter project atm where I could use this for myself.

It's okay np :)
Flutter is very popular right now, when I saw react native support, I thought it should have Flutter support. If you have the time, I think it will improve quickly if you start developing open source.

**Comment by pubkey** [comment]
No sorry, I do not have the time, there are too many things I want to do with RxDB.
But maybe you have?

**Comment by jtkeyva** [comment]
@pubkey Flutter has skyrocketed since this post. Any chance of supporting it now?

**Comment by jtkeyva** [comment]
@dshukertjr seems like there's a hint of interest from the developer. might be worth supabase backing a dart version of this for the flutter community?

**Comment by pubkey** [comment]
If have no time for this. You can make a PR if you need that.

**Comment by jtkeyva** [comment]
@pubkey awesome! they @dshukertjr i will collaborate on a write up or docs or graphics if you want for flutter

**Comment by jtkeyva** [comment]
@pubkey hopefully you will one day your tagline will broaden to add support for dart/flutter... from

A fast, offline-first, reactive Database for JavaScript Applications
to
A fast, offline-first, reactive Database for realtime Applications

**Comment by ArinFaraj** [comment]
@pubkey Do you intend to continue working on this, or should we make PRs?

**Comment by pubkey** [comment]
You should make PRs of course.

**Comment by fivestones** [comment]
Does anyone have a more step-by-step walkthrough/video of setting this up? I probably should work on learning rxdb first but I'm just diving in and reading the readme for this flutter example isn't quite enough for me to get there.
Thanks!

**Comment by jtkeyva** [comment]
This seems promising but it's pretty quiet here. Assuming this shouldn't be run in production?

**Comment by aehlke** [comment]
Anyone try running this in prod yet?
