### ISSUE TITLE
Update readme and docs to include a note that when using react + typescript (via create-react-app) and RxDB v9, the typescript dependency must be updated to 3.8+

### ISSUE THREAD

**Issue by campbellbartlett** [pubkey/rxdb#2487]
## Case
It took me a while to work out what was wrong with my setup. Eventually I came across the v9 change notes where it is noted that v9 requires typescript v3.8+. This can be confusing for new users of the library, because creating the default react app with CRA (with typescript) and installing the RxDB dependency breaks everything.

## Issue
It might make it easier for others in the future to discover that they need to update typescript to v3.8+ when adding RxDB.

## Info
  - Environment: `npx create-react-app . --typescript && yarn add rxdb rxjs && yarn start`

This is what the error looks like (which is why it's difficult to find the root cause of the issue being the wrong version of typescript):
<img width="947" alt="Screen Shot 2020-09-02 at 4 39 58 pm" src="https://user-images.githubusercontent.com/38512252/91940588-0c186480-ed3b-11ea-8742-08b7a606ecde.png">

**Comment by campbellbartlett** [comment]
Thanks, I have raised a PR with a change to the readme and Typescript page in the docs.

**Comment by pubkey** [comment]
Fixed at #2490
