### ISSUE TITLE
Sync setup of the store

### ISSUE THREAD

**Issue by pepibumur** [pubkey/rxdb#251]
## Case
I'm trying to add offline storage to my electron app using RxDB and the IndexedDB PouchDB adapter.

## Issue
The setup works, but I have a question regarding what's the best approach for setting up the database and sharing it with the app components.

I'm using ES6 modules and have a `store.js` file where I define an `async` function that initializes the database. However, I can't `await` that function at the top level and thus, I can't export any db instance that other files can import. 

I could initialize it asynchronously, but some files might import it and get a nil instance because the store hasn't been initialized yet.

What would you suggest that I do?

## Info
- Environment: Electron
- Adapter: IndexedDB

## Code

```typescript
import RxDB, { RxDatabase, DatabaseCreator } from "rxdb"
import plugin from "pouchdb-adapter-idb"

export const databaseConfig: DatabaseCreator = {
  name: "sourcerdb",
  adapter: "idb",
  password: "github",
  multiInstance: true
}

const createDatabase = async (): Promise<RxDatabase> => {
  RxDB.plugin(plugin)
  return RxDB.create(databaseConfig)
}

export default XXXXX
```

**Comment by pubkey** [comment]
Hi @pepibumur there is no way to create a non-async instance of rxdb, neither there will be one in the future.

I suggest to not re-export the rxdb-instance itself, but a service-method to get it. This is also done in the example, see [here](https://github.com/pubkey/rxdb/blob/master/examples/angular2/app/src/services/database.service.ts).

**Comment by pepibumur** [comment]
Thanks @pubkey, I'll do that. I wasn't sure about what pattern was the best in this case. I think it makes total sense to keep the creation asynchronous.
