### ISSUE TITLE
Feature Request: Split into multiple modules

### ISSUE THREAD

**Issue by wSedlacek** [pubkey/rxdb#2510]
## Case
Feature Request

## Issue
As it stands `rxdb` has quite a few dependencies, many of which are used only for particular plugins.
I am working on writing a library that will use `rxdb` as the primary data source however I would prefer to not to have to require many of these dependencies.

## Purposed Solution
I purpose moving dependencies that are only require for certain plugins into optional dependencies and dynamically importing these dependencies at run time.

Alternatively I purpose converting this repo into a mono repo (using something like `Nrwl Nx`) and moving plugins to their own packages so that consumers of this library only need to select the data they need.

## Breaking Changes
I am aware that these would be some major breaking changes as it is changing what the user needs to install in their `package.json` and that this would probably need to be a major release for these changes to take place.

I am happy to help make these changes possible.

**Comment by pubkey** [comment]
I do not think we need this. Why does your bundler include deps from plugins you do not need?

**Comment by pubkey** [comment]
Related: https://github.com/pubkey/rxdb/issues/2125

**Comment by wSedlacek** [comment]
I am not consuming the library directly in an application but building a library around it that others will consume in their applications.
So NPM/Yarn would resolve your package then install all of the other dependencies that you require.
This increases the install time (which is already bad enough when working in large Angular/NestJS repos)

This is not to mention that every package has the potential of having a malicious `postinstall` script.

**Comment by wSedlacek** [comment]
I believe the optimal user experience would be having a clear core package and clear plugin packages.
This is how many projects like Angular, NestJS, Nrwl, Storybooks, etc. work.

Packages would be like `@rxdb/core`, `@rxdb/pouch`, `@rxdb/graphql`.
This would would mean that a user who want's to use RxDB with pouch would only need the `@rxdb/core` and `@rxdb/pouch` packages and all dependencies would be included.
If a user does not wish to use pouch, then they simply use the core library.

This would also mean that users would not need to download new versions of the library if changes only affected a plugin.
And if you are using CI/CD and Nrwl you can also only test/build packages that were affected in a given PR.

**Comment by pubkey** [comment]
Ok, I understand.

So when I created the current plugin system (lets call it monomodule), there where different tradeoffs. First of all, we had less dependencies which is why installing everything did not really matter. When I checked the [deps now](https://github.com/pubkey/rxdb/blob/master/package.json#L88). There are some things which are really big and not needed by most users. Mostly `express`, `crypto-js` `graphql-client` and `modifyjs`.
I made this decision in the past, because there are some benefits with having everything in one npm module.
* the config is easier
* upgrading is easier for users because they only have to set the version in one place
* RxDB could be sure that every plugin has exactly the same version as the core

Moving to the multi-module scheme which is used by angular/pouchdb etc. is not a trivial task. I am open to that change but I do not think I have the time to do it by myself.

**Comment by wSedlacek** [comment]
> Ok, I understand.
> 
> So when I created the current plugin system (lets call it monomodule), there where different tradeoffs. First of all, we had less dependencies which is why installing everything did not really matter. When I checked the [deps now](https://github.com/pubkey/rxdb/blob/master/package.json#L88). There are some things which are really big and not needed by most users. Mostly `express`, `crypto-js` `graphql-client` and `modifyjs`.
> I made this decision in the past, because there are some benefits with having everything in one npm module.
> 
> * the config is easier
> * upgrading is easier for users because they only have to set the version in one place
> * RxDB could be sure that every plugin has exactly the same version as the core
> 
> Moving to the multi-module scheme which is used by angular/pouchdb etc. is not a trivial task. I am open to that change but I do not think I have the time to do it by myself.
> 
> I think you should rename this issue. I see many problems in moving stuff to optionalDependencies.

Renamed.
I am happy to help with this transition.
I have migrated many libraries into the Nrwl NX Monorepo system; Would you be opposed to using `Nrwl Nx`?
If you have not already I would recommend reserving the `rxdb` organization name on NPM.

**Comment by pubkey** [comment]
Great!
I reserved the org on npm.
I do not know nrwl. Pouchdb uses lerna. I will research a bit, atm I have no opinion.
Do you have a link to a library you have migrated?

**Comment by wSedlacek** [comment]
> Great!
> I reserved the org on npm.
> I do not know nrwl. Pouchdb uses lerna. I will research a bit, atm I have no opinion.
> Do you have a link to a library you have migrated?

Here is one I migrated.
https://github.com/wSedlacek/angular-web-worker/tree/cleanup
From
https://github.com/gleosmith/angular-web-worker

It hasn't been merged into the upstream library yet (the author kinda fell out of touch)
This does properly demonstrate how things were reorganized.
I also updated the library to follow Strict mode in TypeScript.

**Comment by wSedlacek** [comment]
Akita is a great example of how Nwrl Nx can be used for a library.
https://github.com/datorama/akita

**Comment by shadow81627** [comment]
PouchDB is has a similar issue and applying these kinds of improvements there could have upstream improvements here.

[PouchDB no longer uses Lerna](https://github.com/pouchdb/pouchdb/issues/5545)

The maintainers have created multiple issues highlighting the need for improving the build process and better tools for managing the monorepo.

- [[meta] Fix all the build things](https://github.com/pouchdb/pouchdb/issues/8097)
- [Simplify build process](https://github.com/pouchdb/pouchdb/issues/7651)

**Comment by pubkey** [comment]
I am closing this for now to remove it from my todo list.
The PR is still welcomed and we can reopen the issue when someone are working on it.

**Comment by pubkey** [comment]
I do not want optional dependencies because it will not guarantee the version. For example if rxdb uses a newer dexie version, the user might not update its own dexie version accidentially. This would not error at built time but create strange bugs at runtime. I do not want to maintain that.

Either we switch to submodules or we leave it as is.

**Comment by G-Rath** [comment]
@pubkey peer dependencies still have a version constraint, which package managers should respect and enforce - so `rxdb` would still be able to enforce min. required versions like what you do currently.

Even if you're still against using peer dependencies, would you be open to exploring unpinning some (if not all) dependencies to make it easier for users to do security patching downstream?

**Comment by pubkey** [comment]
That would still be a breaking change that would increase complexity for newbies and it would require a major version release.

Either we do the correct thing of splitting it into the modules, or we do not touch anything.

**Comment by pubkey** [comment]
Any PRs that just improve the codebase without having breaking changes is always welcomed.

**Comment by G-Rath** [comment]
To clarify, does that include PRs that unpin dependencies? (I'm happy to accompany those with my thoughts around their stability if that would help give you some further peace of mind, and I promise not to do PRs just blindly unpinning every dependency, but it really would be a huge security win for us).

**Comment by pubkey** [comment]
No. Dude I am tired. Either you do the full work or I assume it is not that important to you.
