### ISSUE TITLE
Question about performances issues for a new project

### ISSUE THREAD

**Issue by frederikhors** [pubkey/rxdb#2528]
## Case
Question about performances issues for a new project

## Issue
Dear @pubkey I'm looking for an offline-first solution for a project that I may have to build.

I read what you wrote here: https://github.com/pubkey/rxdb/issues/1636:

> the performance decrease by it's overhead which comes from how it handles it's revision tree.

and I was wondering if the performance problems you talk about are really unbearable or can be overcome somehow.

Also if you can give us some more data on what this performance problem means.

The characteristics of my project foresee that there are from 100 to 1000 new documents to manage per day. But there are few revisions of the previous documents and virtually zero deletions.

Do you think your CHARMING system can handle these rhythms?

What do you recommend to do?

Thanks for your amazing work.

**Comment by pubkey** [comment]
RxDB is a database for offline first UI applications. The plain read/write-performance is magnitutes worse then for server-side dbs like postgres. However for all use cases I have found, the performance is good enough. It is unlikely that your user clicks a button 100 times per second and triggers a write.

For you 1000 documents, I think you should just test it.

**Comment by frederikhors** [comment]
> I think you should just test it

But how? Can you suggest something?

**Comment by klarkc** [comment]
@frederikhors maybe this can help https://github.com/pubkey/rxdb/blob/master/test/performance.test.ts

Here I found some interesting options https://stackoverflow.com/questions/111368/how-do-you-performance-test-javascript-code
