### ISSUE TITLE
Can't save without additional properties error

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#253]
## Case
Bug

## Issue
Can't save in node

## Info
- Environment: Node 6 latest
- Adapter: Memory

## Code
Get a collection down, mutate any property that already exists on it, and hit `.save()`.

For some reason, it seems to think there are additional properties on the model:

```json
{"name":"object does not match schema","errors":[{"field":"data","message":"has additional properties"}],"schemaPath":"","obj":{"type":"github","percent":0,"tries":1,"status":1,"createdAt":"2017-08-18T20:49:17.495Z","updatedAt":"2017-08-21T19:43:08.922Z","_id":"aaxqvw3ry0:1503089357495","_rev":"1-99312e488ebb478eb5ff573516065f07","_ext":true},"schema":{"primaryPath":"_id","version":0,"disableKeyCompression":true,"database":"jobs","index":["createdAt","updatedAt"],"properties":{"type":{"type":"string"},"info":{"type":"object"},"percent":{"type":"number"},"tries":{"type":"number"},"status":{"type":"number"},"lastError":{"type":"object"},"createdAt":{"format":"date-time","type":"string","index":true},"updatedAt":{"format":"date-time","type":"string","index":true},"_rev":{"type":"string","minLength":1},"_id":{"type":"string","minLength":1}},"type":"object","required":["type","percent","tries","status","createdAt","updatedAt","_id"],"title":"jobs","additionalProperties":false,"compoundIndexes":[]}}
```

Though I can't seem to see anything here that should cause that besides:

- `_ext` isn't supposed to be there (only thing in the schema that is extra, but it's added by RxDB itself).

I can run the same thing in my browser and it works just fine.

**Comment by natew** [comment]
Tested using both npm shims `object.values` and just using `core-js`, and both give the same error unfortunately. Willing to provide any more info! Going to test other models and see if it has something to do with this specific schema.

**Comment by pubkey** [comment]
The `_ext` field was used in the past to determine if a change is coming from the internal event-stream or a replication-stream. This is not needed anymore so I removed it in the linked commit.

**Comment by natew** [comment]
Awesome, thank you! Excited for next release :)

**Comment by pubkey** [comment]
It would be nice if you could test this pre-relase. Just do this in your package.json:

```bash
"rxdb": "git@github.com:pubkey/rxdb.git#05dd10b2ed73c354afaee1c6b6ac241401345020"
```

**Comment by natew** [comment]
Works perfectly!

**Comment by pubkey** [comment]
Great :+1:
