### ISSUE TITLE
Allow await for first sync to finish

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#254]
In order to make using RxDB primarily as a remote-facing engine, it would be helpful to be able to basically enforce a sync() before any exec() finishes.

Not sure the best API for this internally, but I'm already wrapping much of RxDB and so have hooks to do this. Only problem is the current sync() implementation is purposefully opaque, so I can hook into .exec() and call sync (doing that now), but I can't await that sync to finish before returning.

Of course, I can do something like: see exec(), do a sync + subscribe, wait for subscribe to call back twice, or something like that. Or look at RxDB internal collection somehow. But both are super hacky.

I think a helpful interface would be for sync to return a Promise that resolves after it finishes doing the first sync.

**Comment by pubkey** [comment]
Is there a way in pouchdb to know if the initial sync is done?

One option would be to do a non-live-sync once and then you have the RxReplicationState which tells you when the sync is done. Afterwards you can do a live-sync for occuring changes.

Example:

```js
const replicationStateOne = myCollection.sync(
    remote: 'http://localhost:10102/db/'
    options: {
        live: false,  // falso to do a non-liveß-sync
        retry: true
    }
);

// now you can await the first sync
await replicationStateOne.complete$.filter(x => x==true).asPromise();

// and do the live sync for occuring changes
const replicationStateLive = myCollection.sync(
    remote: 'http://localhost:10102/db/'
);

// here you can use exec now
myQuery.exec()....

```

**Comment by natew** [comment]
Interesting. Thanks for the heads up on that. Will give it a shot.

**Comment by natew** [comment]
One question: Seems a valid use case would also be a live one too though right? Like waiting for first sync, but then have it continue syncing?

**Comment by natew** [comment]
Ok so with a few modifications this seems to work on node.

Hate to say though... but for some reason it doesn't work on browser.

In the `.filter` I get back either one or two replies, both with `false` as the value. And then nothing else. I know this is pretty outside your concern probably for this library. Apologies for all the poking here!
