### ISSUE TITLE
Congratulations, wonderful work.

### ISSUE THREAD

**Issue by frederikhors** [pubkey/rxdb#2541]
I am using your awesome RxDB in a [Svelte 3](https://svelte.dev) project.

**WORKS GREAT!** :smile: :smile: :smile: 

It is the first time that I have used such a solution (not only PouchDB, I mean the databases in the browser, in this case is a browser-only app) and I must say that I am delighted because YOU did a great job!

**So thank you once again!**

And besides thanking you I tell you that if you want I can publish a repo for Svelte users that maybe we can document in a section of "Recipes" or "Demo". Again, if you like.

### QUESTION

I have searched around the web, in the (EXCELLENT) documentation and in the issues but I have not found encouraging answers.
_That's why I'm stealing your time with this question. Forgive me._

This project has to synchronize several (really many) documents between multiple devices for a few days.

After a few days the documents are deleted and no longer needed on any device, forever.

**Is there a way to DEFINITELY delete a document from storage?**

In your documentation I only found the `remove()` method (https://rxdb.info/rx-document.html).

**Is there anything deep, definitive?**

And since it is the first time I use these systems I ask you:

since I would like to use the synchronization with GraphQL and not the one with CouchDB, if I want to delete the documents directly on the server, would it be possible in your opinion?

What if a device re-sync and no longer find those deleted on the server docs?

This is a use case that has driven the web crazy.

Can you enlighten us with your talent?

Any idea.

Thank you so much. For all.

❤️❤️❤️

**Comment by shadow81627** [comment]
I think you would have to look at the [PouchDB compaction options](https://pouchdb.com/guides/compact-and-destroy.html) to delete documents on the client.

**Comment by pubkey** [comment]
@frederikhors yes, as @shadow81627  this is not possible with pouchdb atm.
As workaround you can clean up and recreate a collection to purge the deleted documents.
Related https://github.com/pouchdb/pouchdb/issues/802

**Comment by Azza292** [comment]
@shadow81627 Svelte user here who is currently implementing RxDB. I would really appreciate an insight into how your implementation looks, if you're willing to share.

**Comment by tradaonline** [comment]
Any idea about quick start with Svelte? If you willing to share.

**Comment by pubkey** [comment]
> Is there a way to DEFINITELY delete a document from storage?

RxDB does now have  a cleanup plugin: https://rxdb.info/cleanup.html
