### ISSUE TITLE
FEATURE: RxQuery.count()

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#255]
There is currently no cound-method for queries.

Goal-API:

```js
// single-exec
const amount = await myCollection.count().where('foo').gt(10). /* .. */.exec();
console.log(amount);
// > 5

// subscription
myCollection.count().where('foo').gt(10). /* .. */.$.subscribe(nr => console.log(nr));
// > 5
await myCollection.insert({/* any docData */});
// > 6

```

There should be an optimisation to determine if the amount is needed once or many times (if we subscribe).
The first case should do a pouch-find-count-query, the second case should use the QueryChangeDetection for better performance.

**Comment by pubkey** [comment]
I added this feature to the [backlog](https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md#rxquerycount). Maybe this will come in the future.

**Comment by phal0r** [comment]
@pubkey 
Is it still in the Backlog? I am interested in firing count queries against rxdb for one of my current projects.

**Comment by pubkey** [comment]
Yes, see here https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md

**Comment by phal0r** [comment]
Ok, thanks. Do you have currently any plans to implement it?

**Comment by pubkey** [comment]
No. But you are also a developer ;)

**Comment by phal0r** [comment]
True. I don't hesitate to contribute to this project. Currently I am working on a project, where I actually use rxdb and I will see, if I can fit it into the project plan, but I can't promise to work on it yet and in general I thought, that you might have some plans, where you want to go with this project. This is why I asked in the first place :) 

I will let you know, once there is an opportunity for this feature.

**Comment by DouglasCalora** [comment]
@phal0r how do you resolve this, i'm new at rxdb.

**Comment by phal0r** [comment]
@DouglasCalora 
Currently I solve it by selecting all records from the collection and checking the length of the array. It is clear, that this is the worst approach to solve this, but I had no clue how RxDB worked back when I wrote this message. 

Now I think I would be able to implement this with reasonable amount of time, but no plans to do this within the next weeks.

**Comment by pubkey** [comment]
Related: https://github.com/pubkey/rxdb/pull/4096
