### ISSUE TITLE
Feature Request: Allow to skip docs in push/pull modifiers

### ISSUE THREAD

**Issue by DDoerner** [pubkey/rxdb#2552]
## Case
Feature Request

## Issue
Allow to skip docs in push/pull modifiers

## Code

```js
  (doc: any) => {
    if (doc?.type == 'debug') {
      return null;
    }
    return doc;
  }
```

## Reasoning
We currently have a bug where it occasionally happens that an existing database looses the crawling checkpoint that saves which objects are yet to be pushed/pulled, and therefore the complete local database is re-uploaded (we are yet unsure of whether the bug is due to our code or an issue with rxdb). One way to replicate this is by slightly changing the database url, e.g. with an additional query parameter.

We can determine which objects are synced and which aren't and would love to use this as a filter until we've found the root of the problem. We know that our case is not very important for most rxdb users, but client-side filters for push and pull could be quite useful for a larger range of use cases as well.

**Comment by pubkey** [comment]
Added with #2564
