### ISSUE TITLE
Performance improvement of using RxDB+GraphQL vs directly using GraphQL subscription?

### ISSUE THREAD

**Issue by tonyabracadabra** [pubkey/rxdb#2577]
Seems like using GraphQL subscription can achieve a similar effect with RxDB, just wondering how much performance gain will we get when using RxDB along with GraphQL instead of using GraphQL subscription alone? Is there any benchmarking on that? Thanks!

**Comment by pubkey** [comment]
No, using RxDB is not faster. But it has completely different tradeoffs. If you do not need offline support, you might be better just using a graphql stream.
