### ISSUE TITLE
Possible sync regression

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#258]
## Case
Bug

## Issue
After 5.3.0, running a sync and then watching the replicationstream.complete$ I only get two false values, and don't see any network activity.

If I manually grab the pouch and run .sync, I see the proper series of network requests. Weirdly, I don't see why that would be happening.

But I can definitely replicate it. Tried on 5.3.0 release.

## Info
- Environment: browser

**Comment by natew** [comment]
Aha, a clue. waitForLeadership is the source. If I disable it works.

**Comment by pubkey** [comment]
Couldn't reproduce this on the commited test. I also tried to so `waitForLeaderShip: true` on every replication-test. And they all still worked.

Which adapter do you use?
Do you think with another local instance or a remote server?
Which browser do you use?

**Comment by pubkey** [comment]
Ok I now think the problem is more that the leader-election does not work correctly. Can you check this by using waitForLeaderShip alone without sync?

**Comment by pubkey** [comment]
Any update on this?

**Comment by pubkey** [comment]
@natew any update on this?

**Comment by natew** [comment]
Will check this out today. I was seeing other sync issues only in electron
earlier even with waiting off too.

**Comment by natew** [comment]
@pubkey I'm actually not familiar with the leadership feature. Is there a demo online I can try?

**Comment by pubkey** [comment]
Leaderelection makes sense on node when you have more than one process accessing the same database.
The ng2-example uses the leader-election and shows a crown in the title when the tab is leader.

**Comment by pubkey** [comment]
@natew I still could not reproduce this.
Can you provide more information? I tested it with the idb-adapter and several sync-calls and browsers.

**Comment by natew** [comment]
I'm testing now using our latest and it seems to be syncing without it. We have been changing a ton, could be that we're compiling things a bit differently now, could have been the node version. I'll close this.
