### ISSUE TITLE
Full Text Search

### ISSUE THREAD

**Issue by FlorianKoerner** [pubkey/rxdb#259]
## Case
Feature Request

## Issue
Is there any way to implement an full text search, like pouchdb-quick-search?

- https://github.com/pouchdb-community/pouchdb-quick-search
- https://docs.mongodb.com/manual/core/index-text/

By the way: New version 5.3.0 is awesome!

## Info
- Environment: Node.js
- Adapter: LevelDB

**Comment by pubkey** [comment]
Hi @FlorianKoerner 
Thank you for this proposal. A full-text-search would be great and could be implemented with not-that-much effort as a rxdb-plugin.
However I have to apologize but I have currently no intention to do this by myself.
A PR would be welcome of course and I would also help wherever I can. Do you have plans to create a PR for this?

**Comment by FlorianKoerner** [comment]
I think I will implement this as a Plugin. Is there any plugin collection for rxdb? (wiki, awesome-rxdb, or something else?)

**Comment by pubkey** [comment]
There is not really a collection.
- One piece of information is the existing plugins in [this](https://github.com/pubkey/rxdb/tree/master/src/modules) folder
- Another piece is the docs about it [here](https://pubkey.github.io/rxdb/Plugins.html)

I hope this helps.

**Comment by pubkey** [comment]
Any update on this?

**Comment by pubkey** [comment]
@FlorianKoerner any update on this?

**Comment by FlorianKoerner** [comment]
No. I solve the problem in my project with https://github.com/fergiemcdowall/search-index.

I'm not working on a plugin for the time being.

**Comment by pubkey** [comment]
Ok thanks for the info. I added this to the backlog in case someone wants to implement this in the future.

**Comment by doriandrn** [comment]
Hello! I have started a plugin implementation for this. I'll keep this thread updated with the progress if I may.

**Comment by doriandrn** [comment]
I have just [published on npm](https://www.npmjs.com/package/rxdb-search) a working minimal implementation!

Feel free to test it out and please let me know your feedback!

**Comment by phal0r** [comment]
The question is, if it should be baked into rxdb or not. Apart from search-index, there are other really good fuzzy search libraries like fuse.js and lunr.js.

They work differently and different use cases. It would be cool, if we have a pluggable interface to write mango queries with the $text operator. This is how mongodb supports fulltext search.

**Comment by leandrogehlen** [comment]
I have built a plugin to solve this issue.

https://github.com/serenysoft/rxdb-flexsearch

**Comment by pubkey** [comment]
@leandrogehlen  Can you add it here? https://github.com/pubkey/rxdb/blob/master/docs-src/third-party-plugins.md

**Comment by leandrogehlen** [comment]
it's done #4861

**Comment by pubkey** [comment]
I will add that to the docs.
According to my tests the main-thread->wasm bridge is too slow for any database. This is why I would also not reccomend wasm-sqlite to anyone. Also wasm itself cannot store anything so you have another roundtrip to the js process to store data persistent.
