### ISSUE TITLE
Feature Request: replication-graphql, Allow specifying the data path

### ISSUE THREAD

**Issue by angelnar87** [pubkey/rxdb#2606]
The current code assumes that the data for graphql replication is always the first child of the response. It would be nice if this was actually configurable so that us as developers could specify a different root; in case that the actual data is 2 levels (or 3 or whatever) deep in the response.

Not an issue; just a would-be-nice-to-have 🙂

**Comment by christofu** [comment]
Agreed. We're using postgraphile which kind of wants to return the nodes under the 'nodes' property on the response). To get around it for now we updated src/plugins/replication-graphql/index.ts to match our specific use case in runPull, adding in

```        
// this assumes that there will be always only one property in the response
// is this correct? it is not. Some graphql servers (at least postgraphile) will return a list of
// nodes as an array under the 'nodes' property which therefore needs to be flattened.
// This probably should check if there is any property that is an array and use that, instead
// of just checking for 'nodes'
const initialData = result.data[Object.keys(result.data)[0]];
const data = initalData.nodes !== undefined && Array.isArray(initialData.nodes) ? initialData.nodes: initialData;
```
but I agree that this would be nice as a configuration option!

**Comment by pubkey** [comment]
Yes you are right.
We should make this an optional setting and use the first field if not set.

PR is welcomed.

**Comment by pubkey** [comment]
I am closing this since there is no progress.
PR is still welcomed.
