### ISSUE TITLE
Native async/await compiled version

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#261]
Our app only runs in electron/node, and this week finally got it to *not* use regenerator/async-to-generator, and just use native async/await, which is already a huge boost in productivity due to clear stack traces.

With that enabled, I notice RxDB still has weird traces (using regenerator). Any way we could have a more modern build to require that would exclude compiling?

**Comment by natew** [comment]
I'm not super familiar with best ways to do this, will look into it a bit.

**Comment by pubkey** [comment]
We currently have a es5 and a es6-version in the dist-folder. Both use the regenerator instead of native async/await.

If you build supports the es6-module-syntax, you can try to use the source directly.

`import RxDB from 'rxdb/src/index';`

**Comment by pubkey** [comment]
So no, I don't think we should create a node-only build just for esm-modules.
You can import rxdb from the src-folder to get an uncompiled version and then either do you own transpilation or use [@std/esm](https://github.com/standard-things/esm) to use import/export directly in node.

**Comment by natew** [comment]
I think adding the module field to package.json would allow it to resolve
properly. Mobile right now so not sure if that's already there.

**Comment by pubkey** [comment]
Yes the module-field already exists in the package.json. (refers to the es6-build)
But we cannot refer to the uncompiled sources there. This was done in the past and there where several problems with webpack-builds and vue-builds.
