### ISSUE TITLE
Flow types

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#263]
Did a quick search through the repo, would enjoy using RxQuery and RxCollection as types in flow, seems like `import type` for those doesn't resolve, and you can't import RxQuery for example directly.

**Comment by pubkey** [comment]
I always thought flow supports typescript-definitions. Is this not the case?

**Comment by pubkey** [comment]
I looked into this today. We do currently not export every internal class when you ` import rxdb`. I don't think this will change in the future.

To `import type` a class directly, you can still use the file from the src-folder like:

`import type {RxCollection} from 'rxdb/src/RxCollection';

Please reopen if this does not work.

**Comment by jakallergis** [comment]
Hi there @pubkey! I really appreciate your work here! 

This is an issue for me as well.
- RxDB `7.1.1`,
- RxJS `5.5.4`,
- Electron `1.6.10`,
- Flow `0.48.0`,
- React `15.6.1`,
- Flow-Runtime `0.13.0`

```javascript
import RxDB, { RxDatabase } from 'rxdb';
import type { RxCollection } from 'rxdb/src/rx-collection'; 
// your example says 'RxCollection' but there's no 'rxdb/src/RxCollection' module

class Database {
  _db: RxDB;

  //...

  objects = ({ type }: any): RxCollection => {
      this._validateDBAction(`Trying to access a collection of type [${type}]`);
      if (!type) throw new Error(`(type: ${type}) - Trying to access an invalid type of collection.`);

      return this.RxDB[type];
    };

  get RxDB() {
    return this._db;
  }
}
```

Then I call it like this:

```javascript
const TableCollection = Database.objects(Table);
```

And here's my really really weird error. 

¯\\_(ツ)_/¯

![developer_tools_-_file____users_giannis_git_20projects_bartendr2_bartendrtax_app_screens_root_html](https://user-images.githubusercontent.com/3890732/33765486-ae975c6c-dc21-11e7-9efc-446f1a25f0c8.png)

**Comment by pubkey** [comment]
Hi @jakallergis I'm sorry but my flow-skills are very low. Is there any change you can debug this?
