### ISSUE TITLE
Android Phone Sync Very Slow，Help ！！！

### ISSUE THREAD

**Issue by ES1993** [pubkey/rxdb#2633]
I want to synchronize several tables of servers. The total data is about 200,000. After my Android phone is synchronized for about 10 minutes, I exit the APP and re-synchronize the data will be stuck on the db.collections method for a long time, and then start to synchronize the data.

**Comment by pubkey** [comment]
Can you try to reproduce this with plain pouchdb?

**Comment by ES1993** [comment]
The first time I use a local database, I don't know about pouchdb. It's very process on ios, but it's bad on Android. I guess that the writing speed is very slow and cause a lot of data backlog. The following is my operation code according to the official document, thank you.


const SQLiteAdapter = SQLiteAdapterFactory(SQLite)
RxDB.addRxPlugin(SQLiteAdapter);
RxDB.addRxPlugin(RxDBReplicationGraphQLPlugin);
DBInstance = await RxDB.createRxDatabase({
  name: 'xxx',
  adapter: 'react-native-sqlite',
  multiInstance: false,
  ignoreDuplicate: true,
});

**Comment by ES1993** [comment]
graphqlSync

**Comment by ES1993** [comment]
"pouchdb-adapter-react-native-sqlite": "^2.0.0",
"rxdb": "^9.3.0",
 "react-native-sqlite-2": "^3.1.0",

**Comment by pubkey** [comment]
That is not how github issues work.

Please try using the replication with the same settings and plain pouchdb. If this is faster then RxDB, then we can fix it here. Otherwise create an issue at the pouchdb repo.

**Comment by luoboding** [comment]
i have the same problem.  it takes about twenty minutes to collection.
