### ISSUE TITLE
Bug: loading two tabs at the same time makes one tab not have database

### ISSUE THREAD

**Issue by jasperro** [pubkey/rxdb#2651]
## Case
Bug

## Issue
I'm using rxdb on a React project, when loading two tabs at the same time (like on browser restart), makes the database only available to one of the tabs.

## Info
  - Environment: (Node.js/browser/electron/etc..)
    Browser (Firefox and Chromium)
  - Adapter: (IndexedDB/Localstorage/LevelDB/etc..)
    IndexedDB
  - Stack: (Typescript, Babel, Angular, React, etc..)
    Typescript, Babel, React, Expo Webpack (React Native)

## Error message
Failed to establish transaction safely
DOMException: IDBDatabase.transaction: Can't start a transaction on a closed database

## Code to reproduce error

```js
import { createRxDatabase, addRxPlugin } from "rxdb";
import IndexedDBAdapter from "pouchdb-adapter-indexeddb";
addRxPlugin(IndexedDBAdapter);

async function getRxDB() {
    const rxdb = await createRxDatabase({
        name: "database",
        adapter: "indexeddb", // name of the adapter
        multiInstance: true,
    });
    return rxdb;
}
```
doesn't work with one of the two tabs.

## Reproduce
Open two tabs with the code, close browser, open browser and restore session. Error should appear on one of the two tabs.

**Comment by pubkey** [comment]
Can you reproduce this in one of the example projects?

**Comment by jasperro** [comment]
@pubkey loading two tabs of the react example repo doesn't produce this issue. The only difference in the code I could find was that it used pouchdb-adapter-idb, not the newer pouchdb-adapter-indexeddb. Using pouchdb-adapter-idb in my own app instead of pouchdb-adapter-indexeddb fixes the issue for me. Seems the issue needs to be fixed there.
