### ISSUE TITLE
React Native Example is crashing

### ISSUE THREAD

**Issue by edwinclement08** [pubkey/rxdb#2654]
## Case
This is a Bug

## Issue
React Native example is not running.
It gives this error when trying to open the web client on pc
```
 web  Failed to compile.
/home/edwin/coding/codersforhire/tmp/rxdb/examples/react-native/node_modules/pouchdb-adapter-asyncstorage/src/asyncstorage_core.js
Module not found: Can't resolve 'react-native' in '/home/edwin/coding/codersforhire/tmp/rxdb/examples/react-native/node_modules/pouchdb-adapter-asyncstorage/src'
```
and gives this error when trying to reopen on android emulator
```
Something went wrong.
This project uses SDK v33.0.0, but this expo client requires at least version v37.0.0
```

## Info
  - Environment: (Android, browser)
  - Adapter: (asyncstorage)
  - Stack: (React Native)

## Code
The base repo, with no additional changes

**Comment by pubkey** [comment]
This is likely because the renovate bot updated some dependencies and the CI didnt catch that the react-native example does not work anymore.
We should improve our CI to ensure the rendering is really working.

**Comment by pubkey** [comment]
I am closing this. To fix it, we need to add the react-native to the CI.
