### ISSUE TITLE
Indexes for array fields are created but not populated. 

### ISSUE THREAD

**Issue by marcoancona** [pubkey/rxdb#2656]
## Case
Bug

## Issue
The indexes for array fields are created but not populated (please see screenshots below).

## Info
  - Environment: Electron (Chromium 85)
  - Adapter: IndexedDB (`pouchdb-adapter-indexeddb` or `pouchdb-adapter-idb`) and Websql
  - Stack: Typescript

## Code
Here is a minimal example that uses a schema very similar to the example in the documentation.

```js
import { createRxDatabase, removeRxDatabase, addRxPlugin, RxDatabase, getIndexes } from 'rxdb';
addRxPlugin(require('pouchdb-adapter-indexeddb'));

const mySchema = {
  version: 0,
  type: 'object',
  properties: {
    passportId: {
      type: 'string',
      primary: true
    },
    firstName: {
      type: 'string'
    },
    lastName: {
      type: 'string'
    },
    creditCards: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          cvc: {
            type: 'number'
          }
        }
      }
    }
  },
  indexes: ['firstName', 'creditCards.[].cvc']
};

(async () => {
  // generate a random database-name
  const name = 'mytestdb';

  // create a database
  const db = await createRxDatabase({
    name,
    adapter: 'indexeddb',
    ignoreDuplicate: true
  });
  // create a collection
  const collection = await db.collection({
    name: 'mycollection',
    schema: mySchema
  });

  // insert a document
  await collection.insert({
    passportId: 'foobar',
    firstName: 'Bob',
    lastName: 'Kelso',
    creditCards: [{ cvc: 123 }, { cvc: 456 }]
  });
})();

```

Result: the index for `firstName` is created and contains 1 entry as expected. The index for `cvc` is created but is empty.

![image](https://user-images.githubusercontent.com/2278117/97816268-6af34f00-1c94-11eb-94d9-1489601dbd1a.png)

![image](https://user-images.githubusercontent.com/2278117/97816264-5b740600-1c94-11eb-956d-9d116f1b87fe.png)

**Comment by pubkey** [comment]
Do you have the same problem with the `idb` adapter?   https://www.npmjs.com/package/pouchdb-adapter-idb

**Comment by marcoancona** [comment]
Yes, in this case the comparison of the two `mrview` stores is as follows:

![image](https://user-images.githubusercontent.com/2278117/97869312-8cdee700-1d11-11eb-94d5-a707db638c75.png)

![image](https://user-images.githubusercontent.com/2278117/97869347-9f592080-1d11-11eb-98a0-326281c13182.png)

**Comment by pubkey** [comment]
I am sorry, I have no idea how to help here. I never used array-field indexes. Please investigate an make a PR if possible.

**Comment by pubkey** [comment]
Any update on this?

**Comment by marcoancona** [comment]
I could not find the issue yet.

**Comment by pubkey** [comment]
I am closing this.
I'm very sorry but I have no clue how to fix that and what is wrong here.
I will reopen when someone is planning on working on that.
