### ISSUE TITLE
Disable JSON-schema validation

### ISSUE THREAD

**Issue by c10b10** [pubkey/rxdb#2660]
I'm trying to use RxDB as a caching layer for a generic library, which means I have to construct the schemas dynamically from `protobuf` definitions. The problem with this approach is that I keep ending up in edge cases, and I'd like to know if there's any possibility to disable the necessity for the schema.

Since my RxDB instance mirrors subscribed data received from backend, the correctness responsibility lays with the backend implementation, so the JSON-schema validation is unnecessary for me.

**Comment by pubkey** [comment]
Use the no-validate plugin to disable schema validation
https://rxdb.info/custom-build.html#no-validate

**Comment by gianpaj** [comment]
how do I do this now in 2022? I don't see any docs or info about this :(

**Comment by pubkey** [comment]
If you do not add a validation plugin, there will be no schema validation.
