### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by FlorianKoerner** [pubkey/rxdb#267]
## Case
Bug

## Issue
When I do this

```
collection
          .find({ content: null })
          .exec()
```

I get this error:

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
418: /dist/lib/RxQuery.js
```

It seems to be a correct syntax in MongoDB:
https://docs.mongodb.com/manual/tutorial/query-for-null-fields/#faq-developers-query-for-nulls

**Comment by pubkey** [comment]
Looks like a bug where the pouchdb-query is created from the RxQuery. I will investigate..

**Comment by pubkey** [comment]
I fixed the error. But it looks like pouch-find does not respect querying for null-fields. So this must be opened there.

**Comment by FlorianKoerner** [comment]
Works now. Thank you.
