### ISSUE TITLE
RxDB for querying couchDB

### ISSUE THREAD

**Issue by promentol** [pubkey/rxdb#268]
Thank you for this awesome package
I am not sure if this is feature request or it is already implemented
I have a couchdb database around 10GB, and I want my browser application to query it. It will not be normal if a user will open the browser and download more than 10GB of it in order to be able to query it. Is there a way we can use RxDB without downloading all database records?

**Comment by pubkey** [comment]
We do currently not support remote-only collections. See the backlog [here](https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md#remote-only-collections)
