### ISSUE TITLE
[object object] not a valid query param?

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#2691]
I am trying to query a collection like:

`findOne({ abd: 'XYZ' }).exec()`

and I have the dev-mode plugin enabled.

Result :
`
error RxTypeError (QU11): RxError:
 RxQuery: no valid query params given
`
Am i missing something?

I checked the source code and it's being thrown from the `checkQuery ` function. It checks whether the query's class is [object object]. Is it not allowed to pass object queries in findOne?

**Comment by pubkey** [comment]
If you pass a query, pass a valid mango query.
Try 

```ts
findOne({ 
  selector: { abd: 'XYZ' }
 }).exec()

```

**Comment by pubkey** [comment]
I changed the docs a bit to have a better example for `findOne()`
