### ISSUE TITLE
Error: Cannot find namespace 'core'

### ISSUE THREAD

**Issue by nickyxu** [pubkey/rxdb#270]
Dear all,
     I am a newbie to RxDB.
I use RxDB with angular-cli on angular 4.3.2.

I get the error ' Cannot find namespace 'core'' when compling my app.

Does anyone meet this problem?

Thanks a lot!

**Comment by pubkey** [comment]
This is too less information to help here.
We need the code where you import rxdb.
Does the error tell a line-number?

Please note that the ng2-build with rxdb is used in the angular2-example where its also part of the ci.
