### ISSUE TITLE
Feature suggestion: DB sync instead of collection sync

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#2713]
I was trying the couchDB sync feature and it seems we have to add a separate sync for each collection?
Wouldn't it be more convenient to sync the whole DB at once?
What happens if I have like 15-20 collections, it'll exceed the listener limit of node which is 10.

**Comment by pubkey** [comment]
See https://rxdb.info/replication.html#limitations

**Comment by ravi-poonia** [comment]
What If i'm using it in electron?
