### ISSUE TITLE
rxdb-utils plugins stopped working after update to 9.10.1

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#2716]
rxdb: 9.10.1

Hi,
It seems almost all the plugins of rxdb-utils have stopped working after updating to the latest version. Were there any breaking changes regarding hooks?

BTW...Great Library. Respect!

**Comment by ravi-poonia** [comment]
I'm just fed up trying to fix rxdb-util issues on every version upgrade. I'll just create my own custom plugins. Thx

**Comment by Unforgiven-wanda** [comment]
@ravi-poonia Do you know what exactly broke it?

**Comment by ravi-poonia** [comment]
Not sure, the hooks were not being fired probably, I tried to test them but wasn't able to figure out the root cause. I just went ahead and added my own custom hooks and stuff. It was a little bothersome but removing the dependency of rxdb-utils was a better solution in the long run.

**Comment by Unforgiven-wanda** [comment]
@ravi-poonia Could I please trouble you to share a short example of a hook you created?
Thank you.
