### ISSUE TITLE
CouchDB sync issue

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#2717]
Steps to reproduce:
• Create schema (A,B) with primary `_id` key
• Sync all of them with couchDB
• create document for schema A
• try to get document for schema B, the document for schema A will be returned.

**Comment by pubkey** [comment]
Read the issue template.

**Comment by ravi-poonia** [comment]
I tried with the bug-report file but i'm not able to reproduce over there.

**Comment by pubkey** [comment]
then at least make a PR with your tries.
Your list above makes it impossible to reproduce anything

**Comment by ravi-poonia** [comment]
Ok, I found something. This issue only happens when there are a lot of replication listeners.
`[1] (node:76736) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 destroyed listeners added to [PouchDB]. Use emitter.setMaxListeners() to increase limit`
