### ISSUE TITLE
track migration progress

### ISSUE THREAD

**Issue by dome4** [pubkey/rxdb#2722]
## Case
Feature request

## Issue
I know that there's the possibility to disable the auto migration and track the progress (explained in [DataMigration](https://rxdb.info/data-migration.html)). Nevertheless for me it would be sufficient to know when the migration is started and stopped without knowing the collection progress in detail. Because I am not planning to implement any custom migration behavior the autoMigrate functionality seems to be sufficient for my purpose.

Therefore it would be cool to emit migration events besides the insert, update and delete events to the central observable $ of a collection. The problem I see is that the other RxChangeEvents are emitted in the scope of documents and the migration event would be collection scoped. Thus I am not sure if the collection observable is appropriate for emitting these events.

Does anybody have an idea how to implement the intended behavior or any feedback / thoughts? 

## Code
[rx-colelction.ts](https://github.com/pubkey/rxdb/blob/5938fe017c9a94e688585e0ff34549201d79a919/src/rx-collection.ts#L974):
```js
    return collection.prepare(wasCreatedBefore)
        .then(() => {

            // ORM add statics
            Object
                .entries(statics)
                .forEach(([funName, fun]) => {
                    Object.defineProperty(collection, funName, {
                        get: () => (fun as any).bind(collection)
                    });
                });

            let ret = Promise.resolve();
            if (autoMigrate && collection.schema.version !== 0) {

                // start migration
                //
                collection.$emit('MIGRATION STARTED', collectionName);
                //

                ret = collection.migratePromise();
            }
            return ret;
        })
        .then(() => {

            // migration done
            //
            collection.$emit('MIGRATION SUCCESSFUL', collectionName);
            //

            runPluginHooks('createRxCollection', collection);
            return collection as any;
        });
```

**Comment by ravi-poonia** [comment]
What are you using it with?
What environment?

**Comment by dome4** [comment]
I'm using RxDB in an angular project. The whole creation of the database is wrapped in a database factory service. The only solution that I see is to run `db.addCollections()` and afterwards start the migration for each collection to get the excepected behavior:

```js
    for (const collection of Object.values(db.collections)) {
      migration$.next('MIGRATION STARTED', collection.name);
      collection.migratePromise()
        .then(_ => migration$.next('MIGRATION SUCCESSFUL', collection.name))
        .catch(err => migration$.next('MIGRATION ERRONEOUS', collection.name, err));
    }
```

I am just thinking about if it would be useful for others as well to get migration events directly out of RxDB.

**Comment by pubkey** [comment]
There is `getDataMigrator()` which gives you the migration state.
https://github.com/pubkey/rxdb/blob/master/src/plugins/migration/index.ts#L14

It looks like it is missing in the docs.

**Comment by dome4** [comment]
`getDataMigrator` returns a instance of `DataMigrator` ([see code](https://github.com/pubkey/rxdb/blob/master/src/plugins/migration/data-migrator.ts)) with whom it is possible to execute `migrate()` "by hand" and get the migration state. But it's not possible to get the migration state if `autoMigrate` is used, is it? It might be possible to listen to `_migratePromise?: Promise<any>` in combination with `_migrated: boolean = false` to know when the replication finished. But that's not the best approach because both variables are private and should not be used.

Nevertheless I started the migration "by hand" and used the recommended approach described in the [docu](https://rxdb.info/data-migration.html). That's sufficient for my purpose :)

**Comment by pubkey** [comment]
Hi.
So the thing is, when auto-migration is used, the whole collection will be returned then the migration was done.
Therefore it makes no sense to get the migration state out of the collection, because anyway it will be on 100% at the time you have the collection.
So when you want to track the progress of the migration, always start it manually.

Triggering events looks strange to me, as you pointed out, all other events are in the scope of the documents of a collection.
We might be able to add you desired functionality with plugin hooks and then you can create a custom plugin that listens to the start and end of the migration.

**Comment by pubkey** [comment]
I am closing this. If the plugin hooks are needed, a PR is welcomed.
