### ISSUE TITLE
Have both current and old data inside hooks

### ISSUE THREAD

**Issue by mbret** [pubkey/rxdb#2740]
## Case
Feature request
- Pass both old and current data when possible inside hooks https://rxdb.info/middleware.html

## Issue
I am using the hooks to add/remove the dependencies between documents. For example when I want to add a book to a collection, I will either add the book to the `collection.books` or add the collection to `book.collections`. By doing so my hooks will then either update collection to add the book or the book to add the collection. This work well and give me an easy "orm" handling. Here is an example of one of my hook which will detach any book attached to a collection when I delete it

```
db.c_ollection.postRemove(async function (data) {
    // remove any book that were attached to this collection
    await db.book.safeUpdate({
      $pullAll: {
        collections: [data._id]
      }
    }, collection => collection.find({
      selector: {
        collections: {
          $in: [data._id]
        },
      }
    }))
  }, true)
```

One thing I would like to do is to have both `old` and `current` data. This way I could quickly make a check with prev and next dependencies. This would allow me to skip unnecessary query if the dependencies does not change for example. Maybe I am just worrying too much and theses query are fast but I guess it's always good to avoid i/o when possible.

## Info
  - Environment: browser
  - Adapter: IndexedDB
  - Stack: TS + React

Also as a side note, I rewrote an entire project from apollo to rxdb. I haven't had so much fun playing with a library for a long time. What you built is amazing, thank you so much

**Comment by pubkey** [comment]
Yes this makes sense to me. Can you prepare a PR?

**Comment by mbret** [comment]
I am glad you like the proposal. I will work on it and submit a PR.

**Comment by pubkey** [comment]
I am closing this. PR is still welcomed.
