### ISSUE TITLE
Crash "You are using a function which must be overwritten..."

### ISSUE THREAD

**Issue by mbret** [pubkey/rxdb#2748]
## Case
Bug

## Issue
When building the package with `create-react-app` for production. Some plugins that are part of the default rxdb does not get added and generate error

## Info
  - Environment: browser
  - Adapter: IndexedDB
  - Stack: Typescript, React

## Code

![image](https://user-images.githubusercontent.com/1911240/101886545-fc80a580-3bde-11eb-924c-50b96b196fbb.png)

This does not happens during development, they are not even required to be manually added to work.

That being said, it seems to work if I had them manually. Not sure if it's a bug on the lib or in the way I build the app yet.

Here is the code I use to create the database. The commented plugins are the one I need to manually add when building for production only.

```
import { addRxPlugin, createRxDatabase } from 'rxdb'
import { RxdbReplicationPlugin } from './rxdb-plugins/replication';
import { RxDBQueryBuilderPlugin } from 'rxdb/plugins/query-builder'
import { RxDBValidatePlugin } from 'rxdb/plugins/validate'
import { RxDBUpdatePlugin } from 'rxdb/plugins/update'
import { RxDBReplicationPlugin } from 'rxdb/plugins/replication'
import { RxDBLeaderElectionPlugin } from 'rxdb/plugins/leader-election';

// theses plugins does not get automatically added when building for production
// addRxPlugin(RxDBLeaderElectionPlugin)
// addRxPlugin(RxDBQueryBuilderPlugin)
// addRxPlugin(RxDBValidatePlugin)
// addRxPlugin(RxDBUpdatePlugin);
// addRxPlugin(RxDBReplicationPlugin)
// addRxPlugin(RxdbReplicationPlugin)

addRxPlugin(require('pouchdb-adapter-idb'));

export const createDatabase = async () => {
  const db = await createRxDatabase({
    name: '...',
    adapter: 'idb',
    multiInstance: true,
    ignoreDuplicate: false
  })

  return db
}
```

**Comment by pubkey** [comment]
Please paste your code where you import rxdb and create the database instance.

**Comment by mbret** [comment]
> Please paste your code where you import rxdb and create the database instance.

Updated the issue with the code to create database

**Comment by pubkey** [comment]
Do you use some query builder functions somewhere?

**Comment by pubkey** [comment]
Sorry for the late reply.
I double checked the code. We do not use the query builder inside of other plugins.
It looks to me that you are using it somewhere.
If you still think this is a bug, please create a test to reproduce.

**Comment by mbret** [comment]
@pubkey I only use the query builder that is in the doc. By that I mean I run my query following https://rxdb.info/rx-query.html#doesDocumentDataMatch.

For me it is still a bug because I have to have this code to not crash in production

````
// theses plugins does not get automatically added when building for production
addRxPlugin(RxDBLeaderElectionPlugin)
addRxPlugin(RxDBQueryBuilderPlugin)
addRxPlugin(RxDBValidatePlugin)
addRxPlugin(RxDBUpdatePlugin);
addRxPlugin(RxDBReplicationPlugin)
addRxPlugin(RxdbReplicationPlugin)
````

This is a sample of my database initialization file. I do not need theses line when on development but will crash on production if not present.

I would say it is not a big deal since it works so far but it does not seems to be expected behavior by looking at the doc.

**Comment by pubkey** [comment]
Ah I see. We have to update the docs so that the example queries do not use the query builder plugin.
