### ISSUE TITLE
Upsert with timestamps

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#277]
Have some code that is attempting to upsert, but also I've added a concept of timeStamps where updatedAt is always set automatically.

Currently doing that in preSave. But, that likely breaks down with upsert as we need to verify first.

So seems like either we need a preWillSave that only gets called if upsert is going to mutate, or I'd be forced to double-write in postSave, which is less desirable.

**Comment by natew** [comment]
One thing that may be helpful too for other cases is having middleware receive the action that triggered it.

So in this case I could at least temporarily patch it like:

```js
collection.preSave = function(doc, action){
  if (action !== 'upsert') { ... }
}
```

Because adding updatedAt property for upsert would cause it to actually query differently there.

**Comment by natew** [comment]
So I believe upsert should work by only checking primary keys no? In which case perhaps there's something else going on here... Going to do some tests my side.

**Comment by pubkey** [comment]
The upsert-function works on the primary-key only.
Basically its pretty simple:
- If doc with primary exists, update it
- If doc with primary does not exists, insert it

**Comment by pubkey** [comment]
I think it would be better to copy the few lines from RxCollection.upsert and create an own `upsertWithTimestamp`-ORM-function where you can update the timestamp if necessary.

**Comment by natew** [comment]
Ah funny, I didn't know upsert was just doing findOne => create. Should probably have checked that. Good to know, I already made a simple version of this previously.
