### ISSUE TITLE
how to really delete when use remove (free disk space) on leveldb

### ISSUE THREAD

**Issue by gcxfd** [pubkey/rxdb#2787]
how to really delete when use remove (free disk space) on leveldb

**Comment by pubkey** [comment]
Not possible atm because of pouchdb not supporting purge.
See https://github.com/pouchdb/pouchdb/issues/802

You have to recreate the database as a workaround.

**Comment by HarishRocks** [comment]
Hey @pubkey ,
Im destroying and recreating the database to achieve this. But Im just worried what if I lose any data inbetween as this destroy and sync up isnt an atomic operation.
![image](https://user-images.githubusercontent.com/102788106/171988089-5471e706-247b-4be6-b2ef-40b378522bee.png)
Im doing something like this, what if application crashes and the in-memory database ends up destroying. Can you help me mitigate such an issue?
