### ISSUE TITLE
es6-proimise module causes typescript build errors

### ISSUE THREAD

**Issue by mnmtanish** [pubkey/rxdb#28]
When using with Typescript, the "es6-promise" module causes build errors. For an example, when calling `doc.save()` we get this error.

```
[ts]
Type 'Promise<boolean>' is not assignable to type 'Promise<boolean>'. Two different types with this name exist, but they are unrelated.
  Types of property 'then' are incompatible.
    Type '{ <U>(onFulfilled?: (value: boolean) => U | Thenable<U>, onRejected?: (error: any) => U | Thenabl...' is not assignable to type '{ (onfulfilled?: (value: boolean) => boolean | PromiseLike<boolean>, onrejected?: (reason: any) =...'.
      Type 'Promise<any>' is not assignable to type 'Promise<boolean>'.
        Types of property 'then' are incompatible.
          Type '{ <U>(onFulfilled?: (value: any) => U | Thenable<U>, onRejected?: (error: any) => U | Thenable<U>...' is not assignable to type '{ (onfulfilled?: (value: boolean) => boolean | PromiseLike<boolean>, onrejected?: (reason: any) =...'.
            Type 'Promise<any>' is not assignable to type 'Promise<any>'. Two different types with this name exist, but they are unrelated.
              Property '[Symbol.toStringTag]' is missing in type 'Promise<any>'.
```

As a temporary solution, we can avoid the error with [type assertions](https://basarat.gitbooks.io/typescript/content/docs/types/type-assertion.html). I was wondering whether there's a better way to fix this.

**Comment by pubkey** [comment]
Hi @mnmtanish sry for answering so late.
Where did you get this error? I dont get it on the ng2-example of rxdb.
Which typescript-version do you use?

**Comment by mnmtanish** [comment]
I got this error on Angular v2.0 and Typescript v1.8
I'll try it again using a newer version of typescript.

**Comment by mnmtanish** [comment]
I'm sorry for the delay. I tried it again with TypeScript v2.0.9. This time I got this error:

```
Argument of type 'Promise<RxCollection>' is not assignable to parameter of type 'Promise<RxCollection>'.
  Property '[Symbol.toStringTag]' is missing in type 'Promise<RxCollection>'.
```

**Comment by labibramadhan** [comment]
i got the same issue here, any news?

**Comment by labibramadhan** [comment]
here is my fixes:

1. on typescript compiler options, set **moduleResolution** to **node** and use **es5 lib** instead of es2015 (i don't know the different). then, install these typings: dt~es6-promise and dt~es6-collections by using command:
```
typings install dt~es6-promise and dt~es6-collections --global --save
```

1. on typescript compiler options, don't use/set the lib and moduleResolution properties

**Comment by pubkey** [comment]
In [v3](https://github.com/pubkey/rxdb/tree/3.0.0), the polyfills etc. will not be included, which will fix this issue. Until then, you have to stick to the workarround. I'm sorry.

**Comment by Itrulia** [comment]
@labibramadhan es2015 is ES6. 

Also Angular 2 should not be used with Typescript < 2 and if you need Promise in Angular 2 you should use the `node` typings from `@types/node`

**Comment by pubkey** [comment]
Closing this since no response. It should work in RxDB v3 now, reopen if you think otherwise.
