### ISSUE TITLE
Nicer wrong type error messages

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#281]
[minor improvement, low priority]

## Case
When creating a thing with wrong type you get:

![image](https://user-images.githubusercontent.com/12100/30349464-f668c380-97c7-11e7-8dae-4f904b9f8fd8.png)

What would be helpful is showing the `typeof` and perhaps the value as well, so it's a bit easier to debug.

**Comment by natew** [comment]
Secondly, any downside to formatting the JSON there with `JSON.stringify(error, null, 2)`, would help readability a lot.

**Comment by pubkey** [comment]
Done. Thanks for the great idea.

- You can now acces the parameters of errors via `errorObj.parameters` so you can programmatically access the schema-errors. 
- Errors on node now look like this:

![error](https://user-images.githubusercontent.com/8926560/30402098-ee0f2efc-98dc-11e7-9fc5-16d4c5508fff.png)
