### ISSUE TITLE
how about support bulkRemove

### ISSUE THREAD

**Issue by qinyang912** [pubkey/rxdb#2831]
## Case
REQUEST FOR A NEW FEATURE

## Issue
I often need to delete some RxDocuments in batches. Now I use RxDocument.remove. It is a bit slow when the amount of data is large. So how about letting RxCollection support bulkRemove. I am very willing to develop this feature

## Info
  - Environment: browser
  - Adapter: memory
  - Stack: Typescript

**Comment by pubkey** [comment]
Yes makes sense. PR is welcomed.
Please try to have a similar api to `bulkInsert`
