### ISSUE TITLE
[FR] Retrieve conflicts from CouchDB for manual resolution

### ISSUE THREAD

**Issue by antonkravc** [pubkey/rxdb#2836]
## Case
Feature request.

## Issue
Add an option to include conflicts in documents retrieved from CouchDB to allow manual conflict resolution after sync.

It is my understanding that this is [already possible to do in PouchDB](https://pouchdb.com/guides/conflicts.html) so an option to do so in RxDB would be greatly appreciated.

Please let me know how I can help you implement this.

**Comment by pubkey** [comment]
Hi. So there is a problem with pouchdb, you cannot get conflicts out of normal queries.
Without that I see no easy way to implement that atm.
Please feel free to try by yourself and make a PR.
