### ISSUE TITLE
can we add primary key to exists schema?

### ISSUE THREAD

**Issue by Loliner** [pubkey/rxdb#2837]
we define a wrong Schema with no primary key before.
```js
const oldSchema = {
  keyCompression: true, // set this to true, to enable the keyCompression
  version: 0,
  title: 'folder',
  type: 'object',
  properties: {
      id: {
          type: ['string', 'null']
      },
      name: {
          type: 'string'
      },
      updateTime: {
          type: 'number'
      }
  },
  indexes: ['name', 'updateTime'],
};
```
This oldSchema will create two record with same id sometimes, and I haven't find out the reason.
Now I would like to add primary key to this schema, to prevent this situation(two record with same id property). like below:
```js
const newSchema = {
  keyCompression: true, // set this to true, to enable the keyCompression
  version: 1,  // update version to 1
  title: 'folder',
  type: 'object',
  properties: {
      id: {
          type: 'string',
          primary: true, // changed
      },
      name: {
          type: 'string'
      },
      updateTime: {
          type: 'number'
      }
  },
  indexes: ['name', 'updateTime'],
};

await db.collection({
    name: 'folders',
    schema: newSchema,
    autoMigrate: true,
    migrationStrategies: {
      1: function(oldFolder) {
           oldFolder.id = oldFolder.id + '';
           return oldFolder;
      },
    },
  });
```
I got a error after i change the schema, did i do something wrong?
```js
Error: RxError: migration of document failed final document does not match final schema
Given parameters: {
fromVersion:0
toVersion:1
finalDoc:{
  "updateTime": 1608641255857,
  "name": "c",
  "id": "1fLJsWa9QO-",
  "_id": "1yw2401vs8:1612174110971",
  "_rev": "1-8196f0cde9d9727005641e4d6ab73740"
}}
```
We can't change the data in production environment, so it's possible to resolve this problem by rxdb's DataMigration API?
by the way, our rxdb version is 9.3.0, and adapter is leveldown db.

**Comment by pubkey** [comment]
Yes. The migration plugin should work here for you.

**Comment by Loliner** [comment]
is 9.3.0 version not support primary key migration? 

> Yes. The migration plugin should work here for you.

**Comment by pubkey** [comment]
What is not working?

**Comment by jgchenu** [comment]
if I want to do primary key migration, do I need to do more extra operations ? Ensure data is not duplicated ？

**Comment by pubkey** [comment]
When you migrate while using replication, you must ensure that the new primary key value is deterministic and all replication nodes generate the same key for each document.

**Comment by Loliner** [comment]
> What is not working? It should work.

I found the reason from the information below:
![image](https://user-images.githubusercontent.com/12396141/106983559-0ec32e00-67a1-11eb-8728-b50d2d0cd1b7.png)
the default property '_id' does not match the schema, so i delete the _id property in the migrationStrategies function like: 
```javascript
migrationStrategies: {
    1: function(oldFolder) {
        delete oldFolder['_id']; // delete the property
        return oldFolder;
    },
},
```
and it works, the migrate success.
But each data is missing the _id field, and I'm not sure if it causes other problems.

**Comment by pubkey** [comment]
This looks correct.
RxDB will internally set your new primary value as _id before saving to pouchdb.

**Comment by Loliner** [comment]
I am sorry, you haven't resolve this problem and closed this issue. 
and I regret using RxDB.🙁

**Comment by pubkey** [comment]
Sorry, I do not remember why I closed this.
Please make a PR with a test case to reproduce the problem. Also see https://github.com/pubkey/rxdb/blob/master/orga/bug-checklist.md

Remember this is an open source project, nothing you have payed for. So no one really cares if you use or regret using it :)
