### ISSUE TITLE
Allow hooks into PouchDB creation

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#287]
Looked briefly over the hooks system and didn't see anything here.

Purpose is to attempt to integrate worker-pouch. Not sure if there are other potential pitfalls ahead of this, but for the first step seems necessary to add the `worker` field there.

**Comment by pubkey** [comment]
Hi @natew as you have seen there is currently no hook into the pouch-instance-creation.
You can use `pouchSettings` when a collection is created, but this is not what you need.

PRs for additional hooks are welcomed.

**Comment by natew** [comment]
❤️

**Comment by rweng** [comment]
@natew did you manage to get rxdb to work with worker-pouch?

**Comment by natew** [comment]
Didn't, but didn't spend much time
