### ISSUE TITLE
Resolve legacy dependency pouchdb-all-dbs

### ISSUE THREAD

**Issue by openscript** [pubkey/rxdb#2874]
## Case
It is an **improvement**. Nothing is broken.

## Issue
When I install the dependencies (one of them is `rxdb`) I get the following warning:

```
warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/home/node/.cache/yarn/v6/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411-integrity/node_modules/esprima-fb" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic behavior, skipping.
```

## Info
  - Environment: node.js 14.15.1 with yarn
  - Adapter: doesn't matter
  - Stack: doesn't matter

## Code

I've investigated this for a bit.

```
$ yarn why esprima-fb

yarn why v1.22.5
[1/4] Why do we have the module "esprima-fb"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "esprima-fb@3001.1.0-dev-harmony-fb"
info Has been hoisted to "esprima-fb"
info Reasons this module exists
   - Hoisted from "rxdb#pouchdb-all-dbs#es3ify#esprima-fb"
   - Hoisted from "rxdb#pouchdb-all-dbs#es3ify#jstransform#esprima-fb"
info Disk size without dependencies: "2.01MB"
info Disk size with unique dependencies: "2.01MB"
info Disk size with transitive dependencies: "2.01MB"
info Number of shared dependencies: 0
```

`pouchdb-all-dbs` wasn't updated for a few years. It is only used once in `rxdb`:
https://github.com/pubkey/rxdb/blob/8e02730e880bd7bb99a02338efbdd996201115e4/src/plugins/server.ts#L36-L39

Honestly I don't 100% understand why this is needed, but I would happy to help to replace this dependency.

**Comment by pubkey** [comment]
As far as I remember, I needed that to fix some problems when using the same db instance multiple times. https://github.com/pouchdb/pouchdb-server/issues/226
If you can, please remove the dependency. As long as the CI stays green of course.

Related https://github.com/pubkey/rxdb/pull/2152

**Comment by openscript** [comment]
I've upgraded the dependencies of `pouchdb-all-dbs` and sent a PR. If it doesn't get merged and released within one week I publish it by myself.

https://github.com/pouchdb-community/pouchdb-all-dbs/pull/34

**Comment by pubkey** [comment]
I merged your PR @openscript  thank you very much.
