### ISSUE TITLE
Purpose: add the sync config to the collection.

### ISSUE THREAD

**Issue by snowyu** [pubkey/rxdb#291]
the sync cojfiguration could be:

* readonly: collection is replicated to the CouchDB database. the client can not change the data.
* full: Bi-directional collection is replicated to the CouchDB database and  vice versa.
* manual: replication is triggered manually
* cached:  the collection is LRU cache, and pass through to the couchdb database.

```js
const collection =  db.collection({name: 'mydb', sync: 'readonly'});
```

**Comment by pubkey** [comment]
Hi @snowyu 
The replication only runs when started manually.
You can specify sync-directions with the `direction`-attribute, as described [here](https://pubkey.github.io/rxdb/Replication.html). This also allows a readonly, push-only or full sync.

Can you describe what you mean with LRU-Cache?

**Comment by snowyu** [comment]
Ok, first the local collection has a maximum size to keep items. The least recently used items will be dropped on the local collection if the saved keys number is greater than the size.

The `get operation` will get from local collection first, if not found then get from CouchDB and update the LRU age for the key.

**Comment by pubkey** [comment]
I don't think that the work needed to solve this, will create the corresponding performance-boost.
If you have half of the documents in cache, and then do a query over the whole collection, it would still need to  get the whole result from the remote collection.

**Comment by snowyu** [comment]
1. The LRU cache could keep the limited size items in it. You can fetch a lot of documents. but only the latest items could be in local. 
2. The client 's disk resource is always less than the server, so It could not get the whole result from the remote.
3. It should be speed up unless all documents are used once only or write-only to remote.

**Comment by pubkey** [comment]
I'm closing this.
The described feature will not be implemented because it takes too much work.
I also think this should be created as pouchdb-plugin first and then included into RxDB.
