### ISSUE TITLE
6.0.0 High CPU when tab is active

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#294]
Attempted to profile this a few ways and was having trouble explaining why. Chrome's "Task Manager" shows a blank page that has a few queries active (but nothing updating or even replicating), as sitting at 40%+ of CPU.

So I ran profiling and generally it looks fine, mostly idle:

![image](https://user-images.githubusercontent.com/12100/30611551-892590fe-9d36-11e7-8de3-485f434deef0.png)

But I noticed if I go off the tab the usage drops to 0.0 basically. When I focus it seems to go up to 40%+.

Not positive this is 6.0 specific, but I think I would have noticed before.

**Comment by natew** [comment]
Weirdly, I just noticed a more intense page with more queries seems not to have the problem, so hoping I'm not crying wolf here. Need to do some research on chrome profiling because both the Profiler and the Performance tab seem to say nothing is happening, but the CPU monitor says otherwise.

**Comment by pubkey** [comment]
Can you set ` multiInstance: false` and check if the problem disapears?

**Comment by natew** [comment]
Seems to have been likely something else, as I removed a few views from the page and it went down. Good tip to check for that though, thank you.
