### ISSUE TITLE
6.0.0 core is not defined

### ISSUE THREAD

**Issue by gvuyk** [pubkey/rxdb#296]
## Case
Bug

## Issue
 ```
ReferenceError: core is not defined
    at Object.<anonymous> (D:\projects\test\node_modules\rxdb\dist\lib\plugins\adapter-check.js:119:11
```

## Info
- Environment: Node.js

## Code
`$ npm install rxdb`
`var RxDB = require("rxdb");`

**Comment by pubkey** [comment]
Could reproduce. Something is wrong here :(

**Comment by natew** [comment]
I see this as well on master actually, weirdly. I just go delete that core line and it works.

**Comment by natew** [comment]
Just saw 6.0.1, checking

**Comment by tortilaman** [comment]
Was just about to report this. Great to see it resolved so quickly.
