### ISSUE TITLE
Impossible to bundle the documentation example with Webpack or Rollup

### ISSUE THREAD

**Issue by raratiru** [pubkey/rxdb#2998]
## Case
Documentation does not explain how to bundle RxDB

## Issue
I cannot make RxDB work because the bundlers (I have used Rollup and Webpack) output a file that emits various errors per occasion. 

For example: 

* `Uncaught (in promise) ReferenceError: process is not defined`
* `Module parse failed: The top-level-await experiment is not enabled`
* `Use "es" or "system" instead of "iife" format`

Trying a couple of hours to solve one error makes another appear.

### Question:

Where can I find a basic working example setup that renders the below code of  RxDB usable when included as 
```html
<script src="/static/js/rxdb.js"></script>
``` 

in an  `html` file?

## Info
  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: HTML, Javascript, Node-14.15.1

## Code

```js
import { createRxDatabase } from 'rxdb';
const db = await createRxDatabase({
  name: 'heroesdb',           // <- name
  adapter: 'idb',          // <- storage-adapter
  password: 'myPassword',     // <- password (optional)
  multiInstance: true,         // <- multiInstance (optional, default: true)
  eventReduce: false // <- eventReduce (optional, default: true)
});
console.dir(db);
``

**Comment by pubkey** [comment]
Check the examples folder, there are CI tested example to build rxdb with webpack and rollup

**Comment by raratiru** [comment]
Thank you!
