### ISSUE TITLE
GitHub issue template outdated

### ISSUE THREAD

**Issue by mstykow** [pubkey/rxdb#3028]
## Case
Outdated GitHub issue template

## Issue
When creating an issue on RxDB GitHub, the pre-filled template refers multiple times to a non-existing URL where one can supposedly test one's bug. The incorrect URL is `https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js`.

## Info
N/A

## Code
N/A

**Comment by pubkey** [comment]
Please make a PR
