### ISSUE TITLE
do not know why

### ISSUE THREAD

**Issue by z3214965** [pubkey/rxdb#305]
## Issue
the following questions occur when unfolded a RxDocument 
RxDocument {collection: RxCollection, _isTemporary: false, _dataSync$: BehaviorSubject, _data: Object, _atomicUpdates: Array(0), …}
Unhandled promise rejection
Error: cannot populate because path has no ref (name)
Unhandled promise rejection
Error: cannot populate because path has no ref (version)
Unhandled promise rejection
Error: cannot populate because path has no ref (modifdate)
Unhandled promise rejection
Error: cannot populate because path has no ref (author)
Unhandled promise rejection
Error: cannot populate because path has no ref (descrip)
Unhandled promise rejection
Error: cannot populate because path has no ref (comment)
## Info
angular 4.x   chrome
## Code
this.db = await RxDB.create({
name: 'pptdb',  
adapter: useAdapter
});
this.db.pptdb = await this.db.collection({
name: 'ppt',
schema: this.schemaJSON
});
let s = this.db.pptdb.insert({
version: "V0.1",
name: "zhang",
modifdate: "zhang",
author: "zhang",
descrip: "zhang",
comment: "zhang"
}).then((doc)=>{
console.dir(doc);
});

**Comment by pubkey** [comment]
Looks like we need a PR with a failing test here

**Comment by z3214965** [comment]
Now，what should I do now？，What is RP?

**Comment by pubkey** [comment]
Looks like the problem is that you manually assign the collection to the database.
Do not do `this.db.pptdb = await this.db.collection`..
Instead just `await this.db.collection..` and you can still use `this.db.pptdb`
You should never mutate a dependency-object manually.

**Comment by pubkey** [comment]
@z3214965 a PR is a pull-request.
Fork this repository, change things and then the button for a pull-request will be shown.
To add a test which reproduces the bug, you can start with [this file](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js)

**Comment by z3214965** [comment]
Thank you
