### ISSUE TITLE
Help with debugging

### ISSUE THREAD

**Issue by ravi-poonia** [pubkey/rxdb#3111]
RxError (VD2): RxError (VD2):
object does not match schema
Given parameters: {
errors:[
  {
    "field": "data",
    "message": "has additional properties"
  },
  {
    "field": "data",
    "message": "has additional properties"
  }
]

This is the error I receive when the schema doesn't match the sent data. Based on this error it's very hard to figure which additional property it actually is.

Is there a way we can add the field which it is actually talking about?

Let me know if I can help with it in any way.

**Comment by kuka** [comment]
AFAIK you have to add the schema for the nested data properties so that RxDB can be aware of them.

**Comment by pubkey** [comment]
The error should contains the error-object, the validated object and the schema.
See [here](https://github.com/pubkey/rxdb/blob/b770d637421b1e7712948f9eb059e1bc1826df14/src/plugins/validate.ts#L52)
At this point in the code, there is not really any more information that we can include to give the error more meaning.
