### ISSUE TITLE
Browser<->browser replication

### ISSUE THREAD

**Issue by deepmouse** [pubkey/rxdb#3130]
## Case
RxDB already replicates browser<->server and tab<->tab, so why not make it replicate browser<->browser?

## Issue
Sharing RxDB data across devices and users currently requires you to run some kind of central backend server of your own in order to replicate data. Since p2p is possible in browsers due to WebRTC, why not use it to enable replication from browser-to-browser without having to rely on a backend server?

## Info
  - Environment: browser/node
  - Adapter: any
  - Stack: javascript

## Solution

I am not sure what the ultimate best solution is, but I've recently discovered an existing p2p network that runs on any JS platform called GUN: https://github.com/amark/gun The repo provides tools to peer discover in order to establish a WebRTC connection between two browsers, and sync data across browsers without a central server in between. If the WebRTC connection fails, the data can be routed indirectly through the GUN network (which was used to establish the WebRTC connection). The data can be e2e encrypted to ensure data security when traversing through the network.

Maybe adding a plugin that replicates through GUN would be something that's desirable? Or something else to allow browser<->browser sync?

**Comment by deepmouse** [comment]
Architecturally this might be more relevant to implement as a PouchDB adapter perhaps, so I raised an issue there as well https://github.com/pouchdb/pouchdb/issues/8297

**Comment by deepmouse** [comment]
Other links relating to serverless data transfer over IP:

https://holochain.org/
https://hypercore-protocol.org/

**Comment by pubkey** [comment]
I think this should be done as a plugin on a seperate repo and later we can integrate it when it is proven to work.
Maybe it is even better to implement it as a pouchdb replication plugin. There are already some pouchdb webrtc plugins out there but the last time I checked they have been all out of date and unmaintained.

**Comment by pubkey** [comment]
Closing this as it is unlikely that work will be done here in the repo.
When you create a plugin please make a PR to link it from the rxdb docs so others can find it.

**Comment by pubkey** [comment]
@gotjoshua why don't you make a project to support this kind of replication?
