### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nbolt** [pubkey/rxdb#314]
```
const db = await RxDB.create({
        name: 'ro',
        adapter: 'leveldb',
        ingoreDuplicate: true
    });
```

is the code I'm using right now. should obviously be "ignoreDuplicates" and not "ingore".

![](https://image.ibb.co/jOKbJw/Screen_Shot_2017_10_01_at_3_31_36_PM.png)

**Comment by pubkey** [comment]
I'm a bit ashamed of myself that this mistake came througt.
I now added a spell-check to the linting to ensure this will not happen again.

Thank you @nbolt for noticing this :+1:
