### ISSUE TITLE
inconstancy with `deletedFlag` on push/pull for graphQL replication

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#3144]
We're setting up graphQL replication and I found it a bit interesting and confusing that you include the deleted field on the pull queries but omit it on the push queries. In both instances you specify it via `deletedFlag` so it seems to me it might be more consistent to either have to include or leave it out of both.

**Comment by pubkey** [comment]
Hi. This sounds like a bug.
We need the deleted flag in both direction.
Do you mean it is wrong in the docs or in the implementation?

**Comment by chrisdrackett** [comment]
This might only be an issue in the docs. If I'm reading the code right RxDB puts the deleted flag on both the Push and Pull automatically.

**Comment by chrisdrackett** [comment]
ok, so I have a bit more experience with this and I think the docs just need an update. I'll open a PR
