### ISSUE TITLE
Consider making `RxJsonSchema` type compatible with `FromSchema` from `json-schema-to-ts` (change readonlyness)

### ISSUE THREAD

**Issue by futpib** [pubkey/rxdb#3161]
## Case

This is a feature request.

## Issue

I'd like to use https://github.com/ThomasAribart/json-schema-to-ts with rxdb to derive doc types from schemas.

## Info
  - Environment: irrelevant
  - Adapter: irrelevant
  - Stack: Typescript

## Code

Full example here, note the only ts error towards the end of file: https://codesandbox.io/s/typescript-playground-export-forked-4tbfx?file=/index.ts

```ts
import { FromSchema } from 'json-schema-to-ts';

const heroSchema = {
	/* ... */
} as const;

type HeroDocType = FromSchema<typeof heroSchema>;

await myDatabase.addCollections({
	heroes: {
		schema: heroSchema as RxJsonSchema<HeroDocType>,
/*
Conversion of type '{ readonly title: "human schema"; readonly description: "describes a human being"; readonly version: 0; readonly keyCompression: true; readonly type: "object"; readonly properties: { readonly passportId: { ...; }; readonly firstName: { ...; }; readonly lastName: { ...; }; readonly age: { ...; }; }; readonly required...' to type 'RxJsonSchema<{ [x: string]: unknown; passportId?: string | undefined; age?: number | undefined; firstName: string; lastName: string; }>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'required' are incompatible.
    The type 'readonly ["firstName", "lastName"]' is 'readonly' and cannot be assigned to the mutable type '(string | number)[]'.ts(2352)
*/
	},
});

```

**Comment by pubkey** [comment]
Can you make a PR with the proposed change?

**Comment by pubkey** [comment]
I am closing this.
I can reopen when you have a PR with a proposal.
Please not that we have to internally handle schema properties as readonly because changing the schema of a running database can cause many problems. Also we do not want to deep clone the schema because that has bad performance on big schemas.
