### ISSUE TITLE
Typescript: Importing RxDocument from RxDB for typing yields warning/errors

### ISSUE THREAD

**Issue by jessiesanford** [pubkey/rxdb#3169]
I'm using typescript for my application and want to import the RxDocument type, I import it at the top of the file as:

`import {RxDocument} from "rxdb";`

however I am getting this error and am not sure how to fix it besides a typescript override...

`TS2724: Module '"../../../../../../../../Users/jessie/Documents/dev/node_modules/rxdb/dist/types"' has no exported member 'RxDocument'. Did you mean 'isRxDocument'?`

Any ideas are appreciated.

**Comment by pubkey** [comment]
Hm this is strange. Might have to do sth with your bundler.
Can you try `import {RxDocument} from "rxdb/plugins/core";`

**Comment by jessiesanford** [comment]
I'm getting the same error when importing using that line, the bundler I'm using is Parcel I'm not sure if that makes a difference.

**Comment by pubkey** [comment]
I'm pretty sure that has something to do with your configuration/bundler.
I am sorry I cannot help here without a reproduction in the CI.
