### ISSUE TITLE
Breaking change in minor version (from 9.18.0 to 9.20.0) not declared

### ISSUE THREAD

**Issue by lfongaroScp** [pubkey/rxdb#3175]
## Case
Release note not exhaustive

## Issue
For release 9.20.0 the release note does not speak about the change in the version required in rxjs.
It was upgraded from 6.6.7 to 7.0.1 and It is a huge change. 

## Info
  - Environment: Node.js 
  - Stack: Angular 11
  
 
 Can you update the release note?

**Comment by pubkey** [comment]
I added it to [9.20](https://github.com/pubkey/rxdb/releases/tag/9.20.0) now because creating a past release is painful in the github ui. Sorry for that.
Also it was written in the changelog.
https://github.com/pubkey/rxdb/blob/master/CHANGELOG.md
