### ISSUE TITLE
Database may need to  dump the whole db include the collections' schema

### ISSUE THREAD

**Issue by KeZhang** [pubkey/rxdb#319]
## Case

BUG

## Issue

When I try to use dump / importDump for the whole database, I must prepare all the collections in the destination database, or it can't import the data
## Info
- Environment: (Node.js/browser/electron/etc.)
- Adapter: (IndexedDB/Localstorage/LevelDB/etc.)

## Code
```
const assert = require('assert');
const RxDatabase = require('rxdb');
RxDatabase.plugin(require('pouchdb-adapter-memory'));

const docSchema = {
    name: 'demo',
    version: 0,
    properties: {
        firstName: {
            primary: true,
            type: 'string'
        },
        time: {
            type: 'string'
        }
    }
};
async function test() {
    const db = await RxDatabase.create({
        name: 'aaa',
        adapter: 'memory',
    });
    const db2 = await RxDatabase.create({
        name: 'aaa1',
        adapter: 'memory',
    });
  const col = await db.collection({
        name: 'demo',
        schema: docSchema
    });

    col.insert({ firstName: 'nnnn' });

    const json = await db.dump();

    await db2.importDump(json).then((r) => {
        console.log('=======db=========done=====');
        console.dir(r);
    });
    //!!! The collections must be created before importDump 
    const col2 = await db2.collection({
        name: 'demo',
        schema: docSchema
    });

    const docs = await col2.find().exec();

    assert.equal(docs.length, 1);
    db.destroy();
    db2.destroy();
}
test();
```

**Comment by pubkey** [comment]
This looks like a valid bug. I will inspect..

**Comment by pubkey** [comment]
Hmm.
When the collection does not exist, the import on the collection will not work.
We could now include the collection-schema into the export so we can create the collection on import if it does not exist.
But this will create strange behavior because we do not know about the other collection-settings like `migrationStrategies` or the orm-methods.

**Comment by pubkey** [comment]
I now added an error-message so people will know what they have to do.
