### ISSUE TITLE
Support for couch/pouch linked documents 

### ISSUE THREAD

**Issue by remon-georgy** [pubkey/rxdb#32]
Thanks for herding all those js packages into one coherent database solution!

Since rxdb is based on PouchDB, I'm wondering if it supports linked documents or any way to load referenced documents alongside their referrer. In other words, is there a support for any kind of [Joins](http://docs.couchdb.org/en/2.0.0/couchapp/views/joins.html)?

**Comment by pubkey** [comment]
Hi @remon-georgy there is currently no support for linked documents on RxDB.
I was thinking about implementing a ref-keyword like [mongoose](http://mongoosejs.com/docs/populate.html) so that you can `.populate()` on querys. But currently I have other features in focus.

**Comment by ssured** [comment]
Some days ago I stumbled upon https://github.com/mobxjs/serializr which tries to solve this problem of hydration of JS objects. It's API looks nice and the problem it solves is concise, so it might play well with RxDB. Haven't tried it myself yet

**Comment by pubkey** [comment]
Done with these commits:

- [c0e9b2c2ab16c7be75dba3784cd581b0c890c003](https://github.com/pubkey/rxdb/commit/c0e9b2c2ab16c7be75dba3784cd581b0c890c003)
- [c6a7352e465431ec74117b76f210869ba1f8f7a8](https://github.com/pubkey/rxdb/commit/c6a7352e465431ec74117b76f210869ba1f8f7a8)

Will be usable in version 3.0.0
