### ISSUE TITLE
Request for further documentation of imports

### ISSUE THREAD

**Issue by beruic** [pubkey/rxdb#3216]
## Case

I am in the unfortunate situation that I regularly need to wipe some collections and insert them again.

I have resolved to use imports for faster insert of documents in my database

E.g.
```javascript
const constructedDump = {
  docs: tableDocuments,
  encrypted: false,
  name: "myCollection",
  passwordHash: null,
  schemaHash: "1d...ac",
}
await database.myCollection.importDump(constructedDump)
```

## Issue

In this regard, I find the documentation lacking, and I have the following questions I would like to have answered:

- Does import yield events?
  - If it does: Can I disable it during import or bulk insert to gain performance? (maybe in the future?)
- Is there any speed to gain by constructing a dump for the whole database when I need to overwrite the whole thing anyway?
- If I import with `schemaHash` set to a previous version of the collection schema, will it then automatically migrate the imported data?

## Info
  - Environment: browser/Capacitor
  - Adapter: IndexedDB
  - Stack: Vue, Typescript

**Comment by pubkey** [comment]
From the issue template:

>   If you have a common question which cannot be solved with a PR, ask it at one of these places:
>   - https://stackoverflow.com/
>   - https://gitter.im/pubkey/rxdb

**Comment by pubkey** [comment]
1. Yes it will fire events. Atm there is no way to prevent this.
2. I do not know
3. No importing will not automatically migrate the documents.

**Comment by beruic** [comment]
Thanks @pubkey

I will try to see if I can get time for integrating this knowledge into the documentation.

Regarding 3: I guess that means that importing for an old schema is not possible then?

**Comment by beruic** [comment]
Also, just to verify that my findings are correct:

4. The main difference between importing and bulk-inserting is that importing overwrites documents with the same primary key (one might think of it as bulk upserting), and does not return an overview of the operation, right?

**Comment by pubkey** [comment]
@beruic I am not sure about this. The import makes 'normal' writes to the database so it cannot overwrite documents when they have the same or a higher revision.

**Comment by beruic** [comment]
@pubkey Ok. If you figure it out and clarify the behaviour to me, I'll drop an MR with documentation updates.
