### ISSUE TITLE
[Feature request] Accept functions as default values

### ISSUE THREAD

**Issue by ihadeed** [pubkey/rxdb#322]
## Case
New feature

## Issue
It would be useful to pass a function as the default value. Here are two use cases:
```ts
import { generate } from 'shortid';

const MySchema = {
  type: 'object',
  version: 0,
  properties: {
    id: {
      type: 'string',
      primary: true,
      // Results in a new unique ID generated every time a new document is created
      default: generate
    },
    creationDate: {
      type: 'number',
      // Results in a timestamp every time a doc is created
      default: Date.now
    }
  }
}
```

**Comment by pubkey** [comment]
I fixed the tests a few hours ago. I think they should work now with your PRs code.

When I created the `default`-attribute, I thinked a lot about using the same syntax as mongoose, which also allows functions for default. But I had chosen to not allow functions for the following reason:
Json-schemas that are used with rxdb should always be able to be stringified and parsed again.
This allows us to store the schema of a collection next to the documents and read out the schema afterwards.
This is done for example in the data-migrator. When you create a collection with a higher version-number, the schema of the 'older' documents is read out and used to parse the key-compression and handle other things.

A solution to have a function generating the default-value is to use the [postCreate](https://pubkey.github.io/rxdb/middleware.html#postcreate)-hook

**Comment by ihadeed** [comment]
Thanks for the feedback @pubkey 

I wasn't aware that RxDB users need to export their schemas as JSON.

Wouldn't it make sense to allow functions, and document that if you use a function you will not be able to stringify the schema?

**Comment by ihadeed** [comment]
Kinda off-topic:

Since it seems important to use valid Json-Schema format, I'm assuming it wouldn't be a good idea to make a PR that automatically converts collection names to lower case?

It would be easier to use camel case when naming collections. Mongoose allows this, and converts everything to lowercase automatically.

**Comment by pubkey** [comment]
Sry for the late answer.

I personally where confused when I found out that mongoose lowercased my collections. Also the pluralising of mongoose is a strange behavior.
MongoDB-Collections are case sensitive and the best practise is to lowercase all collections.
If we do this in RxDB, we have the same confusion not only when collections are created but also when the `ref`-keyword is used or you access a collection by `myDatabase.[collectionName]`

**Comment by ihadeed** [comment]
Looks like it doesn't work well with this module anyways. IndexedDB cannot store functions in the database. Only WebSQL can. Therefore, the schema cannot be stored properly in the DB.

**Comment by iyobo** [comment]
Resolution of this is not clear. IS it now possible to set a default function?
The purpose of a default function is simply to be run at that the time of creation of that instance in the database and the return value ascribed to that field...if the field is null/undefined.

**Comment by ihadeed** [comment]
@iyobo no, it's not possible. You can achieve that functionality with hooks.  https://rxdb.info/middleware.html
