### ISSUE TITLE
Query object typings

### ISSUE THREAD

**Issue by ihadeed** [pubkey/rxdb#326]
Hi again!

I just wrote some new typings for this library, but I wanted to ask you a few questions before submitting a PR. Here is the code so far:
```ts
export interface RxQueryOptions<T> {
  $eq?: T;
  $gt?: T;
  $gte?: T;
  $lt?: T;
  $lte?: T;
  $ne?: T;
  $in?: T[];
  $nin?: T[];
  $regex?: RegExp;
  $exists?: keyof T;
}

export type RxQueryObject<T> = keyof T & {
  [P in keyof T]?: T[P] | RxQueryOptions<T[P]>;
} & {
  $or: RxQueryObject<T>[];
  $nor: RxQueryObject<T>[];
  $and: RxQueryObject<T>[];
};
```

It's meant to be used in `.where()`:
```ts
declare class RxQuery<RxDocumentType>{
  ...
  where(queryObj: RxQueryObject<RxDocumentType>): RxQuery<RxDocumentType>;
  ...
}
```

So now the IDE's autocomplete will show us the available query options every time we use `.where()`. The method will accept a string that matches on of the schema properties, or an object containing operators (`$or, $nor, $and`) and/or properties of the schema. If the method is passed an object with a property of the schema, it will accept a value (same type defined in schema) or an operator.

My questions:
1. Is this something you are ok with?
2. does `$exists` accept an array or just a single string?
3. what does `elemMatch` do? is it a query operator?
4. what does `all` do?
5. am I missing any operators?

**Comment by pubkey** [comment]
1. Yes this is something I'm ok with
2. exists takes a `boolean` as value
3. According to the pouch-find-docs, `elemMatch` does `Matches all documents that contain an array field with at least one element that matches all the specified query criteria.`
4. `$all` 'Matches an array value if it contains all the elements of the argument array.'
5. I think you missed `$type`, `$mod` . You can use all options from the `pouch-find` plugin, see [here](https://github.com/nolanlawson/pouchdb-find)

**Comment by pubkey** [comment]
I think we need some kind of testing for the typings
