### ISSUE TITLE
Better type support for when using middleware

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#3280]
## Case
New Feature / Enhancement

## Issue

Right now we're finding it difficult to use typescript alongside middleware. Here is a simple example:

> we have a `createdAt` field that we want to set as part of the `preInsert`. Because this is set via the hook we don't need or want `createdAt` passed in when doing `RxCollection.insert`.

The issue right now is that if you omit `createdAt` from the object that is passed into insert you'll get an error in typescript.

This also come into play within the middleware itself as `plainData` has the type of a full document. This is most noticeable in a case where say you want to insert items with a Luxon dataTime and need to change it into a string before save.

My initial though about fixing this is being able to provide the collection optional types for what kind of input is required when adding or updating a document that might differ from that document's schema. This way, if provided, these types could be used on the methods for adding or updating documents as well as within the middleware. Ideally this would also help make sure that within the middleware you mutate the document correctly into the right format for it to successfully save/update.

**Comment by pubkey** [comment]
Can you make a PR with a proposal?

**Comment by chrisdrackett** [comment]
I can, but help me understand what the PR would contain. Should I attempt to start developing this feature? If its just an initial request, what files should I edit to be able to create a PR?

**Comment by chrisdrackett** [comment]
I suppose this is covered as part of #3231 which I kinda forgot I had opened...

**Comment by pubkey** [comment]
Closing this, [see](https://github.com/pubkey/rxdb/pull/3231#issuecomment-977908515)
