### ISSUE TITLE
Error when using `awaitInitialReplication` in graphQL replication on 9.21.x

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#3281]
## Case
GraphQL replication has an error that is present in 9.21.x and not in 9.18.x. When doing replication I get the following error:

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: (0, _rxjs.firstValueFrom) is not a function. (In '(0, _rxjs.firstValueFrom)(this.initialReplicationComplete$.pipe((0, _operators.filter)(function (v) {
        return v === true;
      })))', '(0, _rxjs.firstValueFrom)' is undefined)
```

this is when using `await replicationState.awaitInitialReplication()`

reverting to 9.18 makes this error go away and replication happens as expected.

## Issue

I haven't had time yet to put this into the template, but wanted to raise the issue now in case its cause is easy to figure out from the above. I'll try and repro with the template soon

## Info
  - Environment: React Native app
  - Adapter: Pouch Sqlite
  - Stack: Typescript + react

## Code

```js
      const initReplicationState = collection.syncGraphQL(
        url: envVars.GRAPHQL_URL,
        deletedFlag: DELETED_FLAG,
        pull: { queryBuilder: collectionPullQueryBuilders[collectionName] }
      )
      initReplicationState.run()
      await initReplicationState.awaitInitialReplication()
      await replicationState.cancel()
      // start normal replication here...
```

**Comment by pubkey** [comment]
You need to update rxjs

**Comment by chrisdrackett** [comment]
That did it, thanks :)
