### ISSUE TITLE
Proxied RxDocument fails to save

### ISSUE THREAD

**Issue by ofekd** [pubkey/rxdb#3284]
## Case
Bug

## Issue

I use Vue 3 which uses proxies to track changes. When I call `atomicPatch` on a proxied object, I get the following error:

`Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': #<Object> could not be cloned.`

![2021-07-20-175101](https://user-images.githubusercontent.com/6827960/126345548-df7fb7db-48d9-478d-a520-0db4ac7ce136.png)

Digging around, it seems to happen because `oldData` is a proxied object. Replacing with `JSON.parse(JSON.stringify(oldData))` during a debug session solves the issue.

## Info
  - Environment: browser (tried on latest Chromium and FF)
  - Adapter: IndexedDB
  - Stack: Typescript, Babel, Vue

**Comment by pubkey** [comment]
Which RxDB version do you use?

**Comment by ofekd** [comment]
I was using v9.21. Upgrading to v10 requires a bit of work I did not have time to do, so I edited the bug test file to see if it's a problem on v10. The test from #3285 displayed an error in the browser console for v9.21 but not for v10.

I then hacked my code around v10 changes to see if it errors out, and it did, but seems to happen only on the first call rather than permanently like v9.21. I am not sure what's the difference from my code yet. I tried to run the commented out code from the test in #3285 and it errored out only in my project,

I deep-cloned to verify the issue, not as a proposed solution. Not really sure how to solve this. `JSON.parse/stringify` worked for v10 as well. `Object.assign` did not.

**Comment by pubkey** [comment]
Hmm, in the CI the test works. There we run the test [10 times](https://github.com/pubkey/rxdb/pull/3285/checks?check_run_id=3123984602) to ensure randomly failing tests do really fail.
Maybe its worth trying to reproduce the problem directly with the [broadcast-channel module](https://github.com/pubkey/broadcast-channel)

**Comment by ofekd** [comment]
Added an `await` and errors are back. Tests didn't fail, though. Screenshot from my original fork but rebased on latest master + reinstalled dependencies to make sure that it still happens. v10 behaves somewhat different than v9.21 but they both have this issue, not sure why this is happening.

Pushed updated code

![2021-07-22-022342](https://user-images.githubusercontent.com/6827960/126572408-093ffb73-b196-4a19-af67-7604e7a54941.png)

**Comment by pubkey** [comment]
I am sorry but I cannot help here. 
I know that vue always hacks and wrapps around objects. Vue 2 did that with these pseudo-prototypes and now they do it again with the ref object.

I think the best way to fix this is to only pass plain json data to the RxDB methods.
I am open for any PR that fixes that in another way but I have no time working on it.

**Comment by ofekd** [comment]
I am currently running an `update` query on the `database.collection` rather than the document and it seems to work

**Comment by Alecyrus** [comment]
use `shallowRef`

**Comment by ezra-obiwale** [comment]
You may also use `toRaw(...)` on the ref before applying RxDocument methods.

For example:

```javascript
import { toRaw } from 'vue';

const data = $ref({});

// ....

document.insert(toRaw(data));
```
