### ISSUE TITLE
Add tags and releases for all versions

### ISSUE THREAD

**Issue by beruic** [pubkey/rxdb#3308]
## Case

I wanted to look at something on the current version, as I thought it was a bug (it wasn't). Finding the current version was however not straightforward.

## Issue

Latest tagged version is `10.0.0`, but according to https://www.npmjs.com/package/rxdb `10.0.2` is out. It is however untagged, and unmentioned at https://github.com/pubkey/rxdb/releases.

## Info
  - RxDB Version: N/A
  - Environment: GitHub
  - Adapter: N/A
  - Stack: N/A

**Comment by pubkey** [comment]
I added a release for the latest version. I hope that helps. Do you really need the tags for the other 2 also?
