### ISSUE TITLE
Should we type send$, error$, and canceled$?

### ISSUE THREAD

**Issue by special-character** [pubkey/rxdb#3310]
## Case
Request/question

## Issue
I see the response out of error$ was any and went to log the data that was in it and I see `innerErrors` as an array. Should we type the response for [these three](https://github.com/pubkey/rxdb/blob/master/src/plugins/replication-graphql/index.ts#L99)? I used `innerErrors` initially expecting it to be there but had an error where it was `undefined`.

If there isn't a reason not to, I can take a stab at typing it based on the code.

**Comment by pubkey** [comment]
Yes we can type them, please make a PR.

**Comment by pubkey** [comment]
Closing this, PR still welcomed as always.

**Comment by special-character** [comment]
Thanks, it is on my todo list! I will mark it as fixing this issue when I get it done.
