### ISSUE TITLE
Skip noop migrations (when a backwards-compatible change is made to the schema)

### ISSUE THREAD

**Issue by futpib** [pubkey/rxdb#3311]
## Case
Feature request.

## Issue
When updating the schema in a backwards-compatible (i.e. adding an optional field) way I'm forced to bump it's version. Bumping schema version forces me to write a noop migration. Executing noop migration on a large database slows down the app startup. 

## Info
  - RxDB Version: any
  - Environment: any
  - Adapter: IndexedDB (pouch, `'idb'`)
  - Stack: any

## Code

```ts
const noopMigration = (oldDoc: Transaction) => oldDoc;

const collectionCreator: RxCollectionCreator = {
  name: 'transactions',
  schema: transactionsSchema,
  statics: transactionsCollectionMethods,
  migrationStrategies: { // These still run and take a lot of time even though they could be safely skipped
    1: noopMigration,
    2: noopMigration,
    3: noopMigration,
    4: noopMigration,
  } as MigrationStrategies,
};

```

**Comment by pubkey** [comment]
Yes this sounds good. Also we could create a delete-all strategy with a function that returns null.
I am open for a PR. Please not that the rewrite of the migration plugin is still on the [backlog](https://github.com/pubkey/rxdb/blob/master/orga/BACKLOG.md) so it might make sense to do that first.

**Comment by pubkey** [comment]
Closing this, PR still welcomed as always.
