### ISSUE TITLE
Add a migration batch size option for auto migrate

### ISSUE THREAD

**Issue by futpib** [pubkey/rxdb#3314]
## Case
This is a feature request

## Issue
When using `autoMigrate: true` (the default) there is no way to set the batch size for migration.

## Info
  - RxDB Version: any
  - Environment: any
  - Adapter: any
  - Stack: any
 
## Code

```js
const collectionCreator: RxCollectionCreator = {
  schema: transactionsSchema,
  autoMigrate: true, // This line could be omitted
  migrationStrategies: {
    1: migrateToV1,
  },
  // Nothing I can write here to make migration batch size larger
};
```

**Comment by pubkey** [comment]
Please make a PR with a proposal.

**Comment by pubkey** [comment]
Closing this, PR still welcomed as always.
