### ISSUE TITLE
Content-Security-Policy Issue with rxdb sub dependency

### ISSUE THREAD

**Issue by Chinna-A** [pubkey/rxdb#3334]
### Discussed in https://github.com/pubkey/rxdb/discussions/3333

<div type='discussions-op-text'>

<sup>Originally posted by **Chinna-A** August 16, 2021</sup>
We have Content-Security-Policy for the project, facing issue with sub dependency (is-my-json-valid -> generate-function (index.js)) throwing unsafe eval exception. Can you please help on this

![image](https://user-images.githubusercontent.com/54196967/129579891-69939235-b911-405f-be54-b2e0194e6e56.png)
</div>

**Comment by pubkey** [comment]
Please make a PR.

**Comment by pubkey** [comment]
I think the reason when we made the other validation plugins, was that is-my-json-valid is not compatible with strict cors.
So either you should create an issue at the is-my-json-valid repo or use one of the other plugins.
