### ISSUE TITLE
TypeError: Cannot read property 'createStorageInstance' of undefined

### ISSUE THREAD

**Issue by eramudeep** [pubkey/rxdb#3347]
## Case
Bug reported

## Issue
followed the installation instruction from   [here](https://rxdb.info/rx-database.html#importdump)
and getting error `TypeError: Cannot read property 'createStorageInstance' of undefined`

## Info
 "rxdb": "^10.0.3",
    "rxjs": "^7.3.0",
 
## Code

``` 
  setDownloadStatus_Elastic({ status: "DL_START" });
    const db = await createRxDatabase({
      name: 'heroesdb',           // <- name
      adapter: 'idb',          // <- storage-adapter
      password: 'myPassword',     // <- password (optional)
      multiInstance: true,         // <- multiInstance (optional, default: true)
      eventReduce: false // <- eventReduce (optional, default: true)
    });
    console.dir(db);
```

**Comment by pubkey** [comment]
Sorry I missed changing that on the last release. Fixed with the attached PR.

**Comment by TangoPJ** [comment]
I have the same problem

**Comment by pubkey** [comment]
Yes this is fixed. It was wrong in the docs, not in the code.
Use `storage` instead of `adapter` and pass an `RxStorage`
