### ISSUE TITLE
Some local documents don't seem to get deleted on remove

### ISSUE THREAD

**Issue by special-character** [pubkey/rxdb#3396]
## Case
`removeRxDatabase` seems to not clear some local documents. The steps I took to get here:

1) Have an RxDB database with replication turned on (and some document replicated at least once)
2) Call `removeRxDatabase` and start from scratch
3) Call `syncGraphql` to start syncing with a fresh database

In this case, the `pullReplicationQueryBuilder` gets the document that was replicated in step one, skipping any documents before it (since it uses that document's `updatedAt`).

## Issue
The local doc from the first sync should not show up in the replication for the second one.

Example: 
<img width="807" alt="CleanShot 2021-09-16 at 15 03 21@2x" src="https://user-images.githubusercontent.com/5407471/133691729-248d2c4a-a8df-480c-9ffa-3e665c843ce3.png">

The doc returned above was replicated the first time this database replicated before calling `removeRxDatabase`.

## Info
- RxDB Version: 10.0.3
- Environment: React native
- Adapter: getRxStoragePouch('react-native-sqlite')
- Stack: React, TS

I am looking into why this happens.

**Comment by pubkey** [comment]
Likely equal to #3319

**Comment by pubkey** [comment]
@special-character I think this is solved with the latest release.
Please test and maybe close this issue.

**Comment by special-character** [comment]
Thanks, will do!

**Comment by special-character** [comment]
This appears to be fixed now, thanks.
