### ISSUE TITLE
regex MongoDB expressions supported?

### ISSUE THREAD

**Issue by cgatian** [pubkey/rxdb#34]
I'm a beginner to PouchDB and Mongo so I could be consuming this library incorrectly.

When I run the following query I return the correct number of results.
```javascript
        collection.find()
          .where({ name: { $eq: 'Bob' } })
          .$
          .filter(docs => docs !== null)
          .subscribe(docs => {
            docs.map(doc => console.log(doc.get('name')));
          });
```
If I modify the where clause to use a regex all results are returned.
```javascript
 .where({ name: { $regex: /Bob/ig } })
```
I'm referencing [this documentation](https://docs.mongodb.com/manual/reference/operator/query/regex/) for the query syntax. 

Thank you.

**Comment by pubkey** [comment]
Hi @cgatian . The query-engine depends on [pouch-find](https://github.com/nolanlawson/pouchdb-find) which supports the regex-syntax.
See [Regex with pouch-find](http://blog.davidvassallo.me/2016/01/12/nugget-post-pouchdb-find-regex-example/).

I will make a test for this tomorrow so that I tell you if its definitely working.
Could you post your schema please to make sure it has nothing to do with it?

**Comment by cgatian** [comment]
Thanks for the quick response. I'll test tomorrow morning. Thank you

**Comment by cgatian** [comment]
@pubkey Hmm still no luck. Im using the hero schema found in the example apps.

```javascript
    RxDB.plugin(require('pouchdb-adapter-idb'));
    RxDB.plugin(require('pouchdb-adapter-http'));
    RxDB.plugin(require('pouchdb-replication'));
    RxDB.plugin(require('pouchdb-find'));

    this.db$ = Observable.fromPromise(
      RxDB.create('heroesDB', 'idb', 'myLongAndStupidPassword', true)  // create database
        .then(db => db));

    this.col$ =
      this.db$
      .mergeMap(db => db.collection('hero', heroSchema))
        .filter(col => !!col)
      .map(col => {
        let c: RxCollection = <RxCollection>col;
        c.sync(`http://localhost:5984/hero/`);
        c.find({ name: { $regex: /c.*/ } })
          .$
          .filter(docs => docs !== null)
          .subscribe(docs => {
            docs.map(doc => console.log(doc.get('name')));
          });
```

**Comment by pubkey** [comment]
Hi @cgatian 
I added some tests for the .regex()-function. [See here](https://github.com/pubkey/rxdb/blob/master/test/node/Collection.test.js#L399)

The regex basically works, but you cannot use $regex on the primary-field by the mango-query-definition. [See here](https://docs.cloudant.com/cloudant_query.html#creating-selector-expressions)

I also added a [check](https://github.com/pubkey/rxdb/blob/master/src/RxQuery.js#L72) so it throws when you call `regex()` on the primary-field.
