### ISSUE TITLE
[Feature Request] Change Middleware to have an input and output to make working with typescript easier

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#3426]
## Case
Feature Request

## Issue
If using typescript working with middleware is hard to impossible. This is because the middleware is currently designed to modify data in place, sometimes transforming it from an input type to an output type. This isn't something that typescript can handle as far as I can tell which leads a developer to have to pick a single type or opt-out of typescript in middleware all together. 

A suggestion would be to switch middleware to have an input and then return its output. This way you could add distinct input and output types and both ends could be verified via typescript.

## Info
  - RxDB Version: 10

**Comment by pubkey** [comment]
I added this to the backlog. It would create a breaking change so I will not work on it before the next major release.
A PR is welcomed.

**Comment by pubkey** [comment]
Hi @chrisdrackett 
I will start working on the next major version soon.
This is a good timing to add other breaking changes like your proposal, so you might want to create a PR for that in the next weeks.

**Comment by chrisdrackett** [comment]
ok! I've gotten so good working around this I'll need to remember my thoughts about the best way to handle this :D I have a feeling this is still super valuable and will simplify our code a lot!
