### ISSUE TITLE
`syncGraphQL` should optionallly allow credentials/cookies to be sent with push and pull requests

### ISSUE THREAD

**Issue by tcandens** [pubkey/rxdb#3439]
## Case
I believe this may have just been an overlook option since I cannot find an open issue or PR related to it.

When implementing GraphQL syncing, the _pull_ and _push_ requests to the graphql endpoint should optionally allow the users cookies to be included with the request.
This is very helpful for authentication purposes, for example, when using an http-only cookie which stores a JWT.

## Issue
There is currently no option on a collection's `syncGraphQL` method to include user credentials with push and/or pull requests. 

## Code
I see in the source code for the GraphQL sync plugin, that `graphql-client` is being used to make requests to the graphql API. This library accepts an option for including 'credentials'.

[GraphQL sync plugin code](https://github.com/pubkey/rxdb/blob/master/src/plugins/replication-graphql/index.ts#L73)
[`graphql-client` option source code](https://github.com/nordsimon/graphql-client/blob/master/index.js#L51)

## Proposed Solution
It would be very easy to also accept an options field in a collections `syncGraphQL` method to include credentials which can then be funnelled to the underlying http graphql client. See link to GraphQL sync plugin code above.

I am more than willing to submit a pull request if that would be acceptable. Please let me know.

Thank you!

**Comment by pubkey** [comment]
Closing this, PR is still welcomed.

**Comment by marcoklein** [comment]
I am having the same issue and opened a PR for this at: https://github.com/pubkey/rxdb/pull/3976. Could you please have a look?
