### ISSUE TITLE
Feature: Allow queries before connection

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#346]
This one is a bit weird. I'm currently implementing this but it's a little hacky.

Basically, before connect you could write queries. If you run `.exec()` it would return presumably null, but if you subscribe to `.$`, it would return null, and then once connected, return again with the proper value.

**Comment by pubkey** [comment]
I don't exactly understand this. What is meant by 'connect' ?
Maybe some code would help

**Comment by natew** [comment]
Actually, I realize I'm completely in my own land here.

Right now I have a model layer above RxDB, but theres a point where you connect which essentially creates the collection.

Cool thing is, before it creates the collection (async), we run a render() with the app to render the placeholder version of the app. It actually still tries to call the queries, stuff like `.find().where()...`, but at that point the rxmodels don't exist. So, I have a worm() proxy thing that just remembers what was called, waits for async connect, and then re-runs them once they are finished.

So I think if I want this feature, I need to do myself :). Just wasn't thinking through the fact that they don't actually exist until they are "connected".
