### ISSUE TITLE
The expression of an export assignment must be an identifier or qualified name in an ambient context.

### ISSUE THREAD

**Issue by HexKrak** [pubkey/rxdb#347]
## Case
Since updating typescript to 2.6.0 I keep getting the following error:
`The expression of an export assignment must be an identifier or qualified name in an ambient context.`

## Issue
Critical failure

## Info
- Environment: Browser
- Adapter: WebSql

## Code
Just update to 2.6.0 and init a database.

**Comment by HexKrak** [comment]
In index.d.ts this fixes the problem. I should probably figure out how to do a pull request.

`declare let _default: {
    create,
    removeDatabase,
    plugin,
    isRxDatabase,
    isRxCollection,
    isRxDocument,
    isRxQuery,
    isRxSchema,
    RxSchema,
    PouchDB,
    QueryChangeDetector,
    RxDatabase,
    RxError
};

export default _default;
`

**Comment by pubkey** [comment]
I fixed this with the linked commits.
Thank you for reporting :+1:
