### ISSUE TITLE
Query returns outdated result in second subscription

### ISSUE THREAD

**Issue by swnf** [pubkey/rxdb#3498]
## Case
Bug report

## Issue
A second subscription to a query observable can return outdated results. The results don't change if EventReduce is disabled.

## Info
  - RxDB Version: 10.3.5
  - Environment: Node.js
  - Adapter: Memory
  - Stack: None

## Code

#3499

**Comment by pubkey** [comment]
Can you create a PR with a failing test case?

**Comment by swnf** [comment]
Created #3499
