### ISSUE TITLE
RxAttachment is lost on atomicUpsert call

### ISSUE THREAD

**Issue by BenLune** [pubkey/rxdb#3500]
Hi,
Thanks a lot for the great work here.

## Case
I trying to save Images in RxDb thanks to RxAttachement.
I'm loading a list of images, I'm saving the items of the list as RxDocument, then I attach an RxAttachment containing the Blob of the image file and it works very well.

## Issue
As my list can change, I need to refresh the items each times I load this list. I use the `atomicUpsert` function to update my image RxDocument. But when I do it, the RxAttachment is lost. Looking into IndexedDB in `by-sequence` table, I see revision where my document has attachments, then on next revision no more, then on next revision has attachments and so on.
Do you know if it is normal ?

Thanks a lot,
Benoît

**Comment by pubkey** [comment]
This looks like a bug please make a PR with a failing test.

**Comment by pubkey** [comment]
Closing this bc no answer.
If you still have this problem please make a PR with a test case so I will work on it.
