### ISSUE TITLE
[Feature Request] Better replicator abstraction

### ISSUE THREAD

**Issue by Hideman85** [pubkey/rxdb#3508]
First of all what a nice library, we are working with an AWS backend and by default you would use Amplify DataStore but there is a lot of limitation and somehow I came to your nice library with pretty simple thinking pull/push replication and backend agnostic, that's super!

I have a GraphQL endpoint with like the GQL purpose a pretty nested schema. I had a look to the doc, did some test and it was fine without nested "collection". Then I look at the code "maybe I could extend the built-in replicator" and there I found that lot of concerns are duplicated and not properly exposed/exported.

I'm wondering could we have more generic replicator?
Like `syncGraphQl` and `replicateRxCollection(...)` do the exact same stuff:
- Create an instance of a RxReplicationStateBase
- Wait for Leadership if asked
- Start a live sync if asked

Could it be a function `startReplication(replicator: RxReplicatorBase<RxDocType>, options)`?

You go down the line and you have the same issue with `_run(retryOnFail = true)` that do the same thing, `handleDocumentsFromRemote(...)` too.

Could we have something like:
```ts
export const handleDocumentsFromRemote = async <RxDocType>(
  collection: RxCollection<RxDocType>,
  docs: (WithDeleted<RxDocType> | DeepReadonlyObject<WithDeleted<RxDocType>>)[]
): Promise<boolean> => {
  // ...
}

class ReplicatorBase<RxDocType> {
  public constructor (
    protected readonly replicationIdentifier: string,
    protected readonly collection: RxCollection<RxDocType>
  ) {
    // ...
  }

  public startReplication({
    live = false,
    liveInterval = 1000 * 10,
    retryTime = 1000 * 5,
    waitForLeadership
  }: ReplicationOptions<RxDocType>)


  protected async runPull (): Promise<boolean> {
    throw new Error('Not implemented')
  }

  protected async runPush (): Promise<boolean> {
    throw new Error('Not implemented')
  }

  private async _run (retryOnFail = true): Promise<boolean> {
    // ...
  }
}

export default ReplicatorBase
```

And GQL would be:
```ts
class GraphQLReplicator<RxDocType> extends ReplicatorBase<RxDocType> {
  public constructor (
    protected readonly replicationIdentifier: string,
    protected readonly collection: RxCollection<RxDocType>,
    protected readonly pull: any,
    protected readonly push: any
  ) {
    super(replicationIdentifier, collection)
    // ...
  }

  protected async runPull (): Promise<boolean> {
    // ...
  }

  protected async runPush (): Promise<boolean> {
    // ...
  }
}

export default GraphQLReplicator
```

I'm adding that the role of splitting concerns like this is that it would be a lot more easier to support nested object in GQL for instance.
The `runPull()` could call multiple time `handleDocumentsFromRemote(...)` with each subcollections / subarrays of docs that would return the `pull` handler.

**Comment by pubkey** [comment]
> I'm wondering could we have more generic replicator?

Have you seen the replication primitives plugin?
https://rxdb.info/replication.html

**Comment by Hideman85** [comment]
I do but in my case I would need to override runPull and been able to call `handleDocumentsFromRemote` on different collections

**Comment by Hideman85** [comment]
Take that GQL schema:
```gql
type Comment {
...
}

type GetComments {
  items: [Comment!]!
  nextToken: String
}

type Document {
  id: ID!
  name: String!
  comments: GetComments!
}

type GetDocuments {
  items: [Document!]!
  nextToken: String
}

type Query {
  getDocuments: GetDocuments!
}
```

I need to save Documents in their collection/indexedDb table and same for the nested Comments

**Comment by Hideman85** [comment]
@pubkey What do you think about [this changes](https://github.com/Hideman85/rxdb/tree/master/src/plugins/replication)?
Note this is "just" a first try and could be improved but at least it works for my case of GQL nested collections.

**Comment by Hideman85** [comment]
I guess we don't absolutely need better abstraction you can handle everything your self by declaring multiple `RxReplicationStateBase` with all separate collection and you only need to call `await replication.handleDocumentsFromRemote(docs)` on each collection with the objects you just fetched.

The only drawback of the current implementation is that the whole logic of start replication, retry on error, live pulling and wait for leadership is duplicated in the different replicators and if you have to handle a custom nested schema you have to again copy/pasta the whole stuff.

I guess a better abstraction would be super nice there, but maybe there is other priority for now.

**Comment by pubkey** [comment]
@Hideman85 it is really hard to understand the proposed change on your repo. Can you make a PR?

**Comment by Hideman85** [comment]
At the end my proposal was a tryout but since I got troubles with the library I do not use my fork and made pure vanilla (multiple primitives and copy/pasta of live sync)

**Comment by pubkey** [comment]
Ok I am closing this.
I am open to any change  in the replication module. But we need a PR where it comes clear what exactly has been changed and why.
