### ISSUE TITLE
How can I optimize my query

### ISSUE THREAD

**Issue by Hin-D** [pubkey/rxdb#3518]
### Discussed in https://github.com/pubkey/rxdb/discussions/3517

<div type='discussions-op-text'>

<sup>Originally posted by **Hin-D** November 23, 2021</sup>
I am developing a chat application that will be migrated from nedb to rxdb.
The message collection has 190000 datas.
One of my queries takes 100 seconds.
How can I optimize my query?

Please help.

RxDB Version: 10.3.5
Environment: Node.js
Adapter: pouchdb-adapter-leveldb
Stack: None

query:
{"op":"find","other":{},"query":{"limit":21,"selector":{"sessionId":"d0b3889a1de0a4ee81bb0876334356d7","state":{"$ne":-5}},"sort":[{"timestamp":"desc"}]}}

message collection scheme:
{
  "title": "message schema",
  "version": 0,
  "keyCompression": false,
  "type": "object",
  "description": "describes message schema",
  "primaryKey": "id",
  "required": [
    "id"
  ],
  "indexes": [
    [
      "sessionId",
      "state"
    ],
    [
      "sessionId",
      "state",
      "timestamp"
    ],
    "companyId",
    "timestamp",
    "topTime"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "sessionId": {
      "type": [
        "string",
        "null"
      ]
    },
    "companyId": {
      "type": "number"
    },
    "state": {
      "type": [
        "number",
        "null"
      ]
    },
    "body": {
      "type": [
        "object",
        "null"
      ]
    },
    "timestamp": {
      "type": "number"
    }
  }
}

</div>

**Comment by pubkey** [comment]
Please read the issue template.
