### ISSUE TITLE
[custom-events-plugin] - Cannot read 'ids' of undefined

### ISSUE THREAD

**Issue by Hideman85** [pubkey/rxdb#3520]
Version:
- "rxdb": "~10.5.1",
- "rxjs": "~7.4.0",

Stack:
```ts
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ids')
    at custom-events-plugin.ts:170
    at Array.forEach (<anonymous>)
    at PouchDB._callee2$ (custom-events-plugin.ts:161)
    at tryCatch (runtime.js:63)
```

Code ref:
```ts
export function addCustomEventsPluginToPouch() {
...
            if (options.set_new_edit_as_latest_revision) {
                docs.forEach(doc => {
                    const id = doc._id;
                    const previous = previousDocs.get(id);
                    if (previous) {
                        const splittedRev = doc._rev.split('-');
                        const revHeight = parseInt(splittedRev[0], 10);
                        const revLabel = splittedRev[1];
                        doc._revisions = {
                            start: revHeight,
                            ids: previous._revisions.ids // =========== Error thrown
                        };
                        doc._revisions.ids.unshift(revLabel);

                        delete previous._revisions;
                    }
                });
            }
```

I cannot give neither the schema nor the sample data but I can say that I batch write by 100items and I have 3 * big GQL result of 1 000 items.

The items are written via this internal code (roughly the primitive replicator):
```ts
async handleDocumentsFromRemote<RxDocType> (
    collection: RxCollection<RxDocType>,
    docs: (WithDeleted<RxDocType> | DeepReadonlyObject<WithDeleted<RxDocType>>)[]
  ): Promise<boolean> {
    const toStorageDocs: RxDocumentData<RxDocType>[] = []
    const docIds: string[] = docs.map(doc => doc[collection.schema.primaryPath]) as any
    const docsFromLocal = await collection.storageInstance.findDocumentsById(docIds, true)

    for (const originalDoc of docs) {
      const doc: any = flatClone(originalDoc)
      const documentId: string = doc[collection.schema.primaryPath]

      const docStateInLocalStorageInstance = docsFromLocal.get(documentId)
      let newRevision = createRevisionForPulledDocument(
        this.replicationIdentifier,
        doc
      )
      if (docStateInLocalStorageInstance) {
        const hasHeight = getHeightOfRevision(docStateInLocalStorageInstance._rev)
        const newRevisionHeight = hasHeight + 1
        newRevision = newRevisionHeight + '-' + newRevision
      } else {
        newRevision = '1-' + newRevision
      }
      doc._rev = newRevision

      toStorageDocs.push(doc)
    }

    if (toStorageDocs.length > 0) {
      await collection.database.lockedRun(
        async () => {
          await collection.storageInstance.bulkAddRevisions(
            toStorageDocs.map(doc => _handleToStorageInstance(collection, doc))
          )
        }
      )
    }

    return true
  }
```

From that error part of the data is missing in the store.

Edit: Do I have a way to keep only one rev in the store and by definition not looking in DB before writing but just overrides? I mean local updated documents are saved in a separated IndexedDB instance, right? So in the end we "just" set the remote latest version?

**Comment by pubkey** [comment]
Can you make a reproduceable test case?
I do not think it is possible to reproduce this based on the given information.

**Comment by Hideman85** [comment]
I'm wondering could it be be because the remove do not have a _rev?
It looks like there is two times the same object but _revisions is undefined.

Do you have a reproduction sandbox that I clone and try to replicate the issue?

**Comment by Hideman85** [comment]
It is a real impediment for us to use your great library on production, I'm reaching the time allocated for that feature.
How could we better collaborate on that issue?

The error looks to happen pretty randomly but it is always the same behavior previous object does exist, _rev does exist on previous but no _revisions on that object.
Could I just fallback to an empty array?

**Comment by pubkey** [comment]
I think your [fix](https://github.com/Hideman85/rxdb/commit/73cb68905078f99e4cea18ce79b683980a50f10d) looks good. Can you make a PR with it?
Pouchdb has many fields that can be missing when the document comes out of pouchdb. So we have this fill ins at multiple places. So it do not see potential for any damage.

**Comment by Hideman85** [comment]
Just made the PR with just that small fix.
Yes after multiple investigations the error appear when you have two times the same object (same primaryKey) in the array of `handleDocumentsFromRemote` from the primitive replication.
So in the end you can do a simple test case with your heroes schema and add two times the same hero. I guess the latest one written will override the value (that make sense) but it wont crash :)
In meantime when I found out that was the issue I did just make my array with unique element before calling `handleDocumentsFromRemote`.

**Comment by pubkey** [comment]
I merged the PR. Would be cool to also have a unit test to reproduce the behavior.
