### ISSUE TITLE
Cannot to play with vue examples on my Mac machine

### ISSUE THREAD

**Issue by TangoPJ** [pubkey/rxdb#3521]
When I try to install packages I get errors:

![image](https://user-images.githubusercontent.com/64611024/143302371-dde6a952-313a-4610-9012-f5993ba4724d.png)

Can you help me please?

**Comment by pubkey** [comment]
I changed the [instruction](https://github.com/pubkey/rxdb/blob/master/examples/vue/README.md)
The vue example uses RxDB from the local build, not the one from npm. So it must be build first and the preinstall script must run.
