### ISSUE TITLE
unnecessary dependencies

### ISSUE THREAD

**Issue by 4321ip** [pubkey/rxdb#3545]
When use LokiJS Instead of using PouchDB as underlying storage engine, unnecessary PouchDB present in final bundle too!(~250К)

_minimal example:_
```
git clone https://github.com/4321ip/test-rxdb-loki.git
cd test-rxdb-loki
npm install
npm run build
#      see bundle analysis at http://localhost:8888
```
or the same in codesandbox: https://codesandbox.io/s/flamboyant-snyder-bytc3

`yarn why node_modules/pouchdb-core`
![image](https://user-images.githubusercontent.com/11890535/144735572-58b3018b-0402-4bfc-b541-fc24c227984b.png)

![image](https://user-images.githubusercontent.com/11890535/144735589-c439e95c-02a0-4676-94ac-67fbbb44ef8f.png)

**Comment by pubkey** [comment]
I do not have this problem with angular/webpack.
Which bundler do you use?

**Comment by 4321ip** [comment]
> I do not have this problem with angular/webpack. Which bundler do you use?

Vue3/webpack5

**Comment by 4321ip** [comment]
sorry. Its my mistake

`import { createRxDatabase } from 'rxdb'` 
instead of 
`import { createRxDatabase } from 'rxdb/plugins/core'`
