### ISSUE TITLE
query will never executed in some cases (freezes forever)

### ISSUE THREAD

**Issue by 4321ip** [pubkey/rxdb#3569]
occurs only if few tab is opened
here is simple example
![image](https://user-images.githubusercontent.com/11890535/145666865-831f907a-3dec-47cc-bb3f-be0c6d81b599.png)

if one page - its ok(see in log 'after exec')
on the second page 'after exec' will never printed (from onBtnClick)

_minimal example:_
```
git clone https://github.com/4321ip/test-rxdb-loki.git
cd test-rxdb-loki
npm install
npm run dev
```
1. open two pages http://localhost:8080/#/
2. on the second page - click clearDb button
3. see log

with multiInstance=false the problem is gone, but rxdb is useful due to Multi-Tab support(espesially with lokiJs)

**Comment by pubkey** [comment]
@4321ip I am aware of the problem, I also have that in production.
It is fixed in the newest master branch.
I will release the beta of version 11 in a few days so that you can try.

**Comment by pubkey** [comment]
I released the beta. Please try it out. https://github.com/pubkey/rxdb/blob/master/orga/releases/11.0.0.md

**Comment by 4321ip** [comment]
the issue is still there

**Comment by pubkey** [comment]
Can you create a PR with a failing test case?

**Comment by 4321ip** [comment]
ок

**Comment by 4321ip** [comment]
I don't know how to repeat the bug in unit tests.
The error is present only when multiple browser tabs are open

**Comment by 4321ip** [comment]
@pubkey 
I don't know how to repeat the bug in unit tests.
The error is present only when multiple browser tabs are open

**Comment by pubkey** [comment]
Hmm not sure. Maybe you can reproduce it in the e2e tests of the graphql example.
I can only fix things that I can reproduce.

**Comment by 4321ip** [comment]
@pubkey 
https://github.com/pubkey/rxdb/pull/3581
