### ISSUE TITLE
Data migration fails

### ISSUE THREAD

**Issue by Hideman85** [pubkey/rxdb#3573]
I do have a migration of schema (ultra basic) but it fails

![image](https://user-images.githubusercontent.com/16165119/146256137-a526a995-2c38-482d-99f0-80fa941b85c5.png)

```js
  migrationStrategies: {
    1: doc => doc //  All new attribute are optional so no need of modifying data
  }
```

By the way an optimization would be `1: false` for saying the data do not need to be modified :)

**Comment by pubkey** [comment]
I need a testcase to reproduce that.

There is still the task to rewrite the data migration plugin. There are many optimizations that could be made, like jumping multiple versions or having default strategies that tell RxDB to not modifiy data or delete everything. I just did not have to time to implement that. https://github.com/pubkey/rxdb/blob/master/orga/before-next-major.md#refactor-data-migrator

**Comment by Hideman85** [comment]
https://github.com/pubkey/rxdb/blob/c8ff69fa80156781c566e4d270ace30d7ea0ead1/src/plugins/migration/data-migrator.ts#L386-L402

I did forget to put any validation plugin, with no-validate plugin it looks to work.
Meaning err/asRxError is undefined somehow when no validation plugin is given.

**Comment by Hideman85** [comment]
Okey then yes the no-validate plugin solve the crash, if you want to be bulletproof you could fix the `cannot read parameters of undefined (alias asRxError)` otherwise the issue could be closed :)

**Comment by pubkey** [comment]
@Hideman85 For the next major release I removed the no-validate plugin.
Having the developer to add this nonsense plugin is just confusing. 

https://github.com/pubkey/rxdb/blob/master/orga/releases/11.0.0.md#removed-the-no-validate-plugin
