### ISSUE TITLE
Records not synced with GraphQL endpoint with PouchDB indexeddb

### ISSUE THREAD

**Issue by AntonOfTheWoods** [pubkey/rxdb#3626]
Under certain circumstances, upgrading a schema to a subsequent version can result in new records being created that are never synchronised to the GraphQL endpoint. This is illustrated by a small modification to the GrqphQL example https://github.com/AntonOfTheWoods/rxdb/commit/e318addf7df1497c541cca2574bc089bffa16ba7. A browser refresh appears to fix the issue for *further* records that are created, but those that are created during the "bug" period are never synchronised.

There are further circumstances under which a very similar bug appears but which are *not* fixed by a refresh, though I could not reproduce outside my main project.

A test case was required for acceptance of the bug but as this requires testing mechanisms I am completely unfamilar with, I am not currently capable of producing one. This report is created (and will be closed) for others who might find the issue before I can gain the required skills to produce a proper test case to get the issue fixed.

**Comment by pubkey** [comment]
With which storage/adapter have you tested this?

**Comment by AntonOfTheWoods** [comment]
The reproduction code above adds a couple of things to the existing `pouchdb` indexeddb graphql sync example in the main repo examples.

I was NOT able to reproduce with the default memory pouchdb setup in the unit tests. Unfortunately, I am not yet familiar enough with the tools you suggested for doing unit testing in a browser environment to know where to start with that (to reprod with indexeddb in a unit test ), and I am a PhD student working on open source software and my research is about 2 years late already (so I can't pressure my boss...).

It is also possibly not exactly the same problem as I have, so spending all the time to understand how to do this might not get me personally any closer to fixing the issue for me. I have it on my roadmap but that is pretty full unfortunately and I can workaround by deleting tables and resyncing from the graphql server rather than using migrations at all.
