### ISSUE TITLE
[bug] Lokijs adapter with collection.find()

### ISSUE THREAD

**Issue by Hideman85** [pubkey/rxdb#3670]
HI,
I'm reusing the same PR https://github.com/pubkey/rxdb/pull/3661 for demonstrating the bug.
Basically `collection.find()` always return an empty array. Others `findOne()` & `findByIds()` is getting the data.
I just wanted to try out lokijs to see if it can be a concrete alternative to pouchdb for us.

Please have a look and let me know if I did a mistake or if it is a bug.
At least locally it failing on browsers

**Comment by pubkey** [comment]
Isn't #3661 fixed already?

**Comment by Hideman85** [comment]
Sorry for the misunderstanding I could not spend that much time to do the thing properly.
It is a bug with lokijs and I built a quick unit test and pushed to the same PR.

Then if you check the logs https://github.com/pubkey/rxdb/runs/5050066812?check_suite_focus=true
You will see that I expect loki to give me 0 and then 10 docs but I only got 0.

Sorry again I should have made a different PR

**Comment by pubkey** [comment]
It is really confusing.
Please make a new PR.
Also please ensure that you find a minimal way to reproduce the problem.

**Comment by Hideman85** [comment]
Proper PR made https://github.com/pubkey/rxdb/pull/3671

**Comment by Hideman85** [comment]
```

        //  Simple helper to create data
        const createObject = (id: string) => ({
            passportId: id,
            firstName: id,
            lastName: id,
            age: 56,
            //  Thanks to @phal0r from gitter chat I get to know that loki has to have a _deleted boolean flag
            // _deleted: false
        })
```

The PR is updated according, please at least as a very quick fix update the loki documentation with a big warning lokijs need _deleted to be a boolean flag on any object.

**Comment by pubkey** [comment]
LokiJS RxStorage should not need to have set _deleted.

**Comment by pubkey** [comment]
Clsoing this. Having the _deleted field should work.
