### ISSUE TITLE
Docs: Code is hard to read in night mode

### ISSUE THREAD

**Issue by beruic** [pubkey/rxdb#3675]
Some of the code in night mode is black, which makes it hard to read on a dark background. Here is an example:

![image](https://user-images.githubusercontent.com/724716/152510086-0038ce5b-8316-4aa5-ad75-0cc3a16e6c0e.png)

Making all the black code white should fix it.

**Comment by pubkey** [comment]
Please make a PR.
In this CSS file we overwrite the styles from gitbook: https://github.com/pubkey/rxdb/blob/master/docs-src/styles/website.css

**Comment by beruic** [comment]
@pubkey I'd love to, but I cannot make it build and run the docs locally. I'm making another issue regarding that.

**Comment by beruic** [comment]
@pubkey I just read some code and got smarter. I also saw that there is a TODO for migrating to `honkit`.

In that light I have not created another issue.

However I would like to point out that this project is probably elegible for using the GitBook product for free (https://docs.gitbook.com/pricing/plans/non-profit-and-open-source-discounts), but `honkit` also seems a viable solution.

I till try to do an MR for this CSS, and see if I can get my changes confirmed through what is build in the workflow instead.

**Comment by pubkey** [comment]
You have to downgrade do node v13 to run the docs locally.
`sudo n 13`

**Comment by pubkey** [comment]
Any update on this?

> However I would like to point out that this project is probably elegible for using the GitBook product for free
Yes I know, but adding a documentation build tool that requires a login, is not an option for me. It just increases the developers complexity for a tool that just creates html from markdown files.

**Comment by pubkey** [comment]
If you craft working css-code, you can also just paste it here and I will copy it over.

**Comment by pubkey** [comment]
@beruic  which browser are you using?

**Comment by beruic** [comment]
@pubkey I got away from this because of a multitude of bad events, both at work and personal. This is why I havn't answered your last message in Gitter as well. I am keeping a tab open for this so I don't forget it though.

I use Google Chrome primarily, but I have verified the issue in Firefox as well.

**Comment by pubkey** [comment]
![darkmode](https://user-images.githubusercontent.com/8926560/156458157-b18fceaf-2378-4d14-a8b4-73895d808bec.png)
same on mac dark mode with safari

**Comment by pubkey** [comment]
Closing this because I cannot help here.
PR still welcomed if you find the problem.

**Comment by beruic** [comment]
@pubkey The problem is (I guess) not visible when the browser is in dark mode. Mine, for instance, is dark green, but not in dark mode. I still prefer seeing sites in dark mode though, and therefore I chose the theme when visiting sites where it is available. I guess the problem must be that the font color is inherited from the browser default instead of setting it explicitly in CSS.

Things are getting better BTW, thanks for the concern.

**Comment by beruic** [comment]
@pubkey I have figured out how to fix this in the compiled CSS in `docs/`, but I cannot find out where the themes are defined in `doc-src/`.

The fix is adding
```css
.book.color-theme-2 code {
  color: #8ba9b3 !important;
}
```
, or alternatively another color for code in the Night theme.
