### ISSUE TITLE
[Question] How to insertOrUpdate array of documents

### ISSUE THREAD

**Issue by HuuNguyen312** [pubkey/rxdb#3686]
Dear @pubkey 

When insertOrUpdate a document, I can find the 'upsert' method.
But I can't find any method to insertOrUpdate array of documents (many documents at once)
I tried 'bulkInsert' method, it return 409 error code.

Please help me resolve it.
Thanks

**Comment by pubkey** [comment]
There is no bulkUpsert at the moment. Make a PR if you need this feature.
