### ISSUE TITLE
Replication primitives: push handler goes into infinite loop if number of changed documents equals to batch size

### ISSUE THREAD

**Issue by 11bit** [pubkey/rxdb#3727]
Hello!

I am having an issue with replication primitives: sometimes it starts to push changes in an infinite cycle. After some debugging I found a possible reason for that. Could you check if my logic is correct?

1. In order to work correctly `runPush` command should update `lastPushSequence` here https://github.com/pubkey/rxdb/blob/master/src/plugins/replication/index.ts#L485  (it will update it only if `changesResult.hasChangesSinceLastSequence` is true)
2. `hasChangesSinceLastSequence` is calculated in getChangesSinceLastPushSequence function here https://github.com/pubkey/rxdb/blob/master/src/plugins/replication/replication-checkpoint.ts#L231 and can be false if `lastPushSequence !== lastSequence`
3. This can be the case if the number of changed documents is equal to batchSize. While loop will run twice: first time with full batch and the second time with empty changes array which leads to exiting loop without updating lastSequence and with incorrectly setting hasChangesSinceLastSequence to false

Simplified code from getChangesSinceLastPushSequence function from plugins/replication/replication-checkpoint.ts

```javascript

// If changesResults.changedDocuments.length === batchSize then loop will run twice
//  For instance if batchSize = 5 and lastSequence of last changed doc is 33
//  first iteration: changesResults = { cahngedDocuments: [5 elements], lastSequence: 33 }
//  second iteration: changesResults = { cahngedDocuments: [0 elements], lastSequence: still 33  }

while (retry) {
    const changesResults = await collection.storageInstance.getChangedDocuments({
        sinceSequence: lastPushSequence,
        limit: batchSize,
        direction: 'after'
    });

    lastSequence = changesResults.lastSequence;
    if (changesResults.changedDocuments.length === 0) {
        retry = false;
        continue; // we are exiting the loop at the second iteration with lastSequence of the first iteration
    }


    // .... Finding changedDocs based on changesResults

    if (changedDocs.size < batchSize && changesResults.changedDocuments.length === batchSize) {
        lastPushSequence = lastSequence;
        retry = true;
    } else {
        retry = false;
    }
}

return {
    changedDocs,
    lastSequence,
    hasChangesSinceLastSequence: lastPushSequence !== lastSequence,
};
```

Unfortunately, I wasn't able to run rxdb tests locally so I can't create a reproduction PR. Hope this explanation is enough. 

Rxdb version: 11.6.0
Storage: LokiJS
Replication primitives plugin

Thanks

**Comment by pubkey** [comment]
Seems plausible, but we still need a test with a reproduction.
Which error do you get when running the tests locally?

**Comment by pubkey** [comment]
I think your node.js version is too old

**Comment by 11bit** [comment]
> I think your node.js version is too old

Right, thanks! I'll try to build a replication test

**Comment by pubkey** [comment]
Related: https://github.com/pubkey/rxdb/pull/3627
