### ISSUE TITLE
Migrations do not work with LokiJS adapter

### ISSUE THREAD

**Issue by 11bit** [pubkey/rxdb#3749]
Hello! 

Looks like data migrations (`rxdb/plugins/migration`) don't work when I am using LokiJS adapter: migration function does run, but all the data just disappears (surprisingly it somewhat returns back after a few refreshes of the page). 

I found that unit tests for migrations work only for pouchdb and I don't know how to make them work with loki or other adapters. So I made a [repository](https://github.com/11bit/repro-rxdb-lokijs-migrations-bug) with the bug reproduction. It is nextjs project with two pages: 

1. Db is initialized here https://github.com/11bit/repro-rxdb-lokijs-migrations-bug/blob/main/db/db.ts
2. On the index page I am wiping all the data from indexeddb and then creating a simple document with schema version 0 https://github.com/11bit/repro-rxdb-lokijs-migrations-bug/blob/main/pages/index.tsx#L11-L17

3. On the '/migrate' page I am trying to migrate the created document to schema version 1 https://github.com/11bit/repro-rxdb-lokijs-migrations-bug/blob/main/pages/migrate.tsx#L11-L19

After running '/migrate' page I don't see any documents at all. But if I refresh the page a couple of times I can see an old document without any migrations applied. However, If I switch to pouchdb adapter, everything works well. 

Is it something I am doing wrong with migrations or it's a bug?

**Comment by pubkey** [comment]
To fix the tests for migration,
each of the test storages must have a method `getPersistendStorage()` similate to [getStorage](https://github.com/pubkey/rxdb/blob/master/test/unit/config.ts#L70).
Then we could simulate a correct migration in the unit tests and also fix the lokijs migration.

**Comment by alex-hladun** [comment]
Can confirm we are seeing the same behaviour, can only be solved by db reset.

**Comment by 11bit** [comment]
@pubkey Can we copy that setup from https://github.com/pubkey/rxdb/blob/master/test/performance.test.ts#L64-L68

**Comment by pubkey** [comment]
yes coping from there might work

**Comment by patrickcze** [comment]
@pubkey is this something that would be a relatively easy fix

**Comment by pubkey** [comment]
This might be fixed in the latest beta release. Please try.

**Comment by 11bit** [comment]
Works perfectly. Thank you very much!

@pubkey One more question. If I open two browser tabs simultaneously and then run migration in one of them then: 
1. With lokijs it crashes with `SNH` error
2. With pouch it seems to be working for tab with migration but the second tab looses connection

Is it a bug or do I have to do some special treatment for multi-instance situations (like maybe destroying other instances, running migrations and recreating them again)?

**Comment by alex-hladun** [comment]
@pubkey would you recommend upgrading to the beta to solve this issue, are things generally stable enough for prod?

**Comment by 11bit** [comment]
> Hmm this should work.
>  Maybe you can reproduce this when https://github.com/pubkey/rxdb/pull/3752 is done

Is there already a test with multiple instances from which I can borrow setup? Not sure how to emulate env as if databases run in separate browser tabs with leader election, broadcast channel and etc. 

By the way, there is a question not exactly related to this issue but.. when rxdb runs migrations is there a way to do it silently from replication mechanics (so they are not considered as changed and not pushed)? I am going to do migrations on a server anyway so I don't want all the migrated documents being pushed there again.

**Comment by pubkey** [comment]
@alex-hladun all planned changes have been implemented to version 12.0.0.
I am currently also migrating an app to use 12.0.0 in production.

@11bit yes, `ignoreDuplicate` must be used.
Migration keeps the revisions of the documents, so they should not be pushed again. But I am not sure if that is true when you migration from RxDB 11->12.

**Comment by 11bit** [comment]
> Migration keeps the revisions of the documents, so they should not be pushed again. But I am not sure if that is true when you migration from RxDB 11->12.

Hmm, yes. It works with pouch but doesn't work with LokiJS: migration changes also cause replication. I added a test for that into #3752 https://github.com/pubkey/rxdb/pull/3752/files#diff-497719bfb28eeec7952bdea061129f12d5cf71218ba8c7cd4bda765dc66690cbR1204

**Comment by patrickcze** [comment]
@pubkey We have not had this happen on past migrations but it looks like in our project when we updated our PWA we also saw some of our Loki collections attempt to push migrated documents as replications. Seems to be similar to what @11bit mentioned above, any clue why this might be happening?

We are using rxDB 12.0.8 with LokiJS and a service worker

**Comment by pubkey** [comment]
Closed, see https://github.com/pubkey/rxdb/pull/3752#issuecomment-1216798769
