### ISSUE TITLE
RxDB 7.1 tries to include levelup in build

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#376]
## Case
Bundler breaks because it's trying to load leveldown for browser. Likely need to update it to point to a browser field or something.

## Issue
How necessary is it to have the adaptor-memory included by default? I'm using a bundler that is choking on 7 because it's trying to grab leveldown now.

Reverting for now, I'll need to check the field it following to pick that up (guessing there must be a browser field it's missing).

**Comment by pubkey** [comment]
The adapter-memory is included by default because `RxCollection().inMemory()` needs it.
I never had a problem to create a browser-build with this. Our vue-example also includes everything and has no problems.

**Comment by natew** [comment]
This turns out to be issue with Pundle, closing here as it's acknowledged there.

**Comment by pubkey** [comment]
@natew I also found problems with the levelup-build (especially on windows). I now removed the [auto-import](https://github.com/pubkey/rxdb/commit/71a93b9077d7a8ace52b27a0fe21bb42a5a47de6).

**Comment by natew** [comment]
@pubkey thats cool, look forward to the next release!
