### ISSUE TITLE
findOne returns outdated results

### ISSUE THREAD

**Issue by nothingkid** [pubkey/rxdb#3780]
version 11.5.1
Hi. We have a situation where findOne returns outdated results. I couldn't reproduce this bug using clean database. Instead I checked source code and added logs.
![image](https://user-images.githubusercontent.com/22461210/165720666-8fbdeb4f-dbf4-4281-a19a-7a81dab07668.png)
![image](https://user-images.githubusercontent.com/22461210/165723300-58d7c3fd-aece-4dbe-9e51-047d2978635b.png)
![image](https://user-images.githubusercontent.com/22461210/165723802-69a185c0-4118-4214-894c-b1f3f25fb10f.png)
It looks like docData is mutated somehow. **if I replace  "doc._dataSync$.getValue()" with doc.toJSON()** everything works as expected.
Bug only occurs with "findOne" for some reason ("find" works as expected). "findOne" never calls "_setResultData", but still gets latest results in "_resultsData" object that were set by "find" rx-query. That's why I think data was mutated.

**Comment by pubkey** [comment]
I really need a test case that reproduces the problem, because it is very likely that you mutate the data elsewhere.

`toJSON()` does a flat clone. Using that as fix indicates that the outgoing object is mutated somehwere.
Do you use the dev-mode plugin? Because that will do a deep freeze in dev mode that ensures that you do not accidentally mutate data if it is not allowed.

**Comment by nothingkid** [comment]
Yes, we use this plugin. So, it's not allowed to mutate data. I will try to provide tests or at least more info.

**Comment by pubkey** [comment]
Can you check if this is also the case with `eventReduce: false` ?
Otherwhise I do not see any chance in fixing this without a proper test case.

**Comment by nothingkid** [comment]
yes, with `eventReduce: false` everything works as expected.

**Comment by pubkey** [comment]
Ok. This means it is dependend on the stored and queried data.
I really see no way in ever fixing this without a proper test case.
