### ISSUE TITLE
All data is gone after app is reloaded. 

### ISSUE THREAD

**Issue by Alecyrus** [pubkey/rxdb#3787]
Reproduction Repo: https://github.com/Alecyrus/testRxDB
```
pnpm install
```
```
pnpm run dev
```

Main Code: 
```javascript
import { addRxPlugin, createRxDatabase } from 'rxdb';
import { getRxStorageLoki } from 'rxdb/plugins/lokijs';
import { RxDBQueryBuilderPlugin } from 'rxdb/plugins/query-builder';
import { nanoid } from 'nanoid';

import { documentSchemaLiteral } from './document';
addRxPlugin(RxDBQueryBuilderPlugin);
onMounted(async () => {
  const clientDB = await createRxDatabase({
    name: `workspace.db`,
    storage: getRxStorageLoki({
      adapter: new IncrementalIndexedDBAdapter(),
    }),
    multiInstance: true,
    eventReduce: true,
    ignoreDuplicate: true,
  });

  const _collections = await clientDB.addCollections({
    documents: {
      schema: documentSchemaLiteral,
    },
  });

  console.log('The documents:', await _collections.documents.find().exec());

  await _collections.documents.atomicUpsert({
    id: nanoid(),
  });
  console.log(
    'New documnet is inserted',
    await _collections.documents.find().exec(),
  );
});

```

you will see this in Devtools Console:
<img width="577" alt="截屏2022-05-05 11 29 13" src="https://user-images.githubusercontent.com/13865581/166859830-f003f6be-e797-420a-9469-b05920414d47.png">

And then reload the app by 'Command/Ctrl + R', you will see this in Devtools Console:
<img width="582" alt="截屏2022-05-05 11 29 35" src="https://user-images.githubusercontent.com/13865581/166859860-b882b320-3725-4eda-8dd0-3ea4d0bb433f.png">

Once app is start, a new document will be inserted into the database, so we should see every document inserted before when app is reloaded. But as the images above shown, the documents list is always empty, which seems like all data is gone.

**Comment by mmouterde** [comment]
According to https://rxdb.info/rx-storage-lokijs.html :+1: 

> Data can be lost when the JavaScript process is killed ungracefully like when the browser crashes or the power of the PC is terminated.

Ctrl+R seems to be a part of "killed ungracefully" : https://github.com/techfort/LokiJS/issues/838

**Comment by Alecyrus** [comment]
I don't think that's the problem, because before I reloaded the application I was pretty sure that the data had been persisted to IndexedDB by printing the information in the saveDatabase function；

**Comment by Alecyrus** [comment]
Everything is fine by using DexieJS.

**Comment by mmouterde** [comment]
how did you import `IncrementalIndexedDBAdapter` ?

**Comment by Alecyrus** [comment]
```html
  <script src="incremental-indexeddb-adapter.js"></script>
```

Reproduction Repo is [here](https://github.com/Alecyrus/testRxDB) incase anybody wants to dig in.

I have gave up using lokiJS adapter.

**Comment by Alecyrus** [comment]
> According to https://rxdb.info/rx-storage-lokijs.html :
> 
> > Data can be lost when the JavaScript process is killed ungracefully like when the browser crashes or the power of the PC is terminated.
> 
> Ctrl+R seems to be a part of "killed ungracefully" : [techfort/LokiJS#838](https://github.com/techfort/LokiJS/issues/838)

The data loss you mention here should be the loss of some of the data that has not yet been persisted, but the phenomenon now is that all of the data is lost.

LokiJs is a very mature library and I don't think it is possible for a page refresh to result in a complete loss of data when configured correctly.

The persistence of LokiJS is done via a plugin, and I clearly know that the data has been persisted to IndexedDB When I insert a new record and refresh the page, LokiJS should recover from the data previously persisted to IndexedDB.

I'm still not sure if this is a problem with RxDB or LokiJS, and I'm no longer interested in going any further in this issue.

I'm still not sure if this is a problem with RxDB or LokiJS, and I'm no longer interested in going any further in this issue.

**Comment by mmouterde** [comment]
see PR on your repo that fix the issue by the right import.
Please close this issue.

**Comment by Alecyrus** [comment]
```html
  <script src="incremental-indexeddb-adapter.js"></script>
```

I
