### ISSUE TITLE
GraphQL Replication pull dataPath is not flexible enough

### ISSUE THREAD

**Issue by WonderPanda** [pubkey/rxdb#3792]
## You have a feature request?
I've implemented this in #3791 but the PR template indicated that new features should reference an existing Issue so I am also creating this.

It is not uncommon with a GraphQL query to deal with nested arrays

```
query getStuff {
  level1 {
    id
    level2 {
        name
    }
}
```

Where the result would look like:
```
{
  data: {
    level1: [
      {
        id: 1,
        level2: [
          {
            name: 'one',
          },
        ],
      },
      {
        id: 2,
        level2: [
          {
            name: 'two',
          },
          {
            name: 'three'
          }
        ],
      },
    ],
  },
}
```

With the current implementation of only allowing extraction through a data path there is no way currently to flatten all of the contents of level2 to build the documents to be inserted into RxDB.

I would like to be able to turn this result set into two documents to be inserted into RxDB (effectively its a `flatMap`). So it should end up with `[{ name: 'one'}, { name: 'two' }, { name: 'three' }]`

**Comment by WonderPanda** [comment]
> I am not sure if I fully understood the problem. Couldn't this be archieved by using the pull modifier?
> 
> ```ts
> const replicationState = myCollection.syncGraphQL({
>     url: 'http://example.com/graphql',
>     pull: {
>         queryBuilder: pullQueryBuilder,
>         modifier: dataRow => dataRow.level2,
>         dataPath: 'data.level1'
>         batchSize: 5
>     },
>     deletedFlag: 'deleted'
> });
> ```

@pubkey The `modifier` function is expected to return a single document. In the example level 2 is an array of documents which need to be flattened. If I try to return level2 inside the modifier function it throw an error because it is trying to insert an array of documents where only one is expected.

Either approach is could potentially work. I could attempt to alter the code so that modifier knows how to behave correctly if it returns an array instead of a single object. I personally think that it would be much better to give more flexibility to developers so that they can write their own data extraction function instead of relying soley on an string based object path.

**Comment by pubkey** [comment]
If level2 looks like  

```json
{
  level2: [
          {
            name: 'one',
          }
  ],
}
```

Then you can already map these in the modifier:

```ts
const replicationState = myCollection.syncGraphQL({
    url: 'http://example.com/graphql',
    pull: {
        queryBuilder: pullQueryBuilder,
        modifier: dataRow => dataRow.level2[0],
        dataPath: 'data.level1'
        batchSize: 5
    },
    deletedFlag: 'deleted'
});
```

> I personally think that it would be much better to give more flexibility to developers so that they can write their own data extraction function instead of relying soley on an string based object path.

Yes I understand this. But this is a feature that I would have to maintain for a loong time and I see many things that make this complex.

GraphQL was invented so that the caller can define the format of the api output.
In the graphql schema should already be able to map these things properly.

Having the modifier returning multiple documents, means we cannot just check the amount of returned rows to determine if the batch was `full`.

Also I am not sure what the behavior difference should be between

```ts
{
  dataPath: (result: Result) => {
                            return result.data.collectionFeedForRxDBReplication.collection;
  }
}
```
and 
```ts
dataPath: result.data.collectionFeedForRxDBReplication.collection
```

**Comment by WonderPanda** [comment]
@pubkey I agree, that's why I think it would be much better to give developers the option to provide their own extraction function which runs during `dataPath` and that way `modifier` remains the same and everything continues to work as expected.

Maybe I'm missing something but I don't entirely see where the complexity is coming from. If you refer to the open PR you'll see that it its a relatively small change that gives a lot of flexibility in how the candidate docs are extracted from the GraphQL response and it requires very little code to accomplish.

For the two code snippets at the end of your comment why would their be any different in behavior? (I assumes you meant to wrap the second one in quotes to make it a string `dataPath: 'result.data.collectionFeedForRxDBReplication.collection'`). In either case they fundamentally represent a way to extract documents from the GraphQL response. One uses extraction using a data path and the other uses a more flexible function but the ultimate end goal is the same.

I understand that GraphQL affords a certain level of flexibility in how the response shape is returned but there are sometimes where having a nested object result like I've demonstrated is very advantageous especially depending on how the GraphQL server processes the query. It can mean that completely different database indices are used to fullfil the query and allow for developers to execute queries which they know are more performant without being forced to always return it in a flat list.

**Comment by WonderPanda** [comment]
Hey @pubkey, sorry to be a bother but I was wondering if you'd had any time to futher evaluate the thoughts that I provided in the post above? I feel like this is a small change which is very valuable for developer flexibility and that RxDB shouldn't enforce certain query patterns on consumers.

If you feel strongly that this is not possble to be merged then we will most likely need to look at creating our own custom GraphQL replication using the Replication primitives or evaluate other technologies besides RxDB for our offline-first needs.

Thanks for all the hard work you've put into this project

**Comment by pubkey** [comment]
I'm on holidays for the next 10 days.

**Comment by WonderPanda** [comment]
> I'm on holidays for the next 10 days.

No worries! Enjoy your holidays

**Comment by pubkey** [comment]
Ok, so I really think this is an edge case.
I do not see a valid use case where the graphql api should not return an array of documents.
But I see many problems in not having the modifer return exactly one item.

If you really have no chance to use the pull query builder in a way that it returns an array of objects, you can still overwrite the whole graphql handler.

```ts
const oldQueryFn = myRxGraphQLReplicationState.clientState.client.query;

myRxGraphQLReplicationState.clientState.client = async(query, vars)=>{
  const result = await oldQueryFn(query, vars);
  // here you modify the result.
  return result;
}
```
