### ISSUE TITLE
[Premium Tasks]Update PouchDB to the newest version and make sure the CI is green.

### ISSUE THREAD

**Issue by cetsupport** [pubkey/rxdb#3806]
According to the premium tasks, here I need tell estimated time to finish task:

Estimated time: 3 days.

[PR Link:] https://github.com/pubkey/rxdb/pull/3763

**Comment by pubkey** [comment]
Done in https://github.com/pubkey/rxdb/pull/3763

@cetsupport Please write me at gitter so I can provide you access to the premium plugins.
