### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by inglesuniversal** [pubkey/rxdb#3811]
I got the following error while installing ...

core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

Is the error caused by the version required within the examples folder or am I missing something on my local machine => MacOS Monterrey?

Thanks

**Comment by pubkey** [comment]
Please read the issue template.
Which example gives that error?
Likely an example is outdated, so please make a PR with updated versions if that fixes the error.
