### ISSUE TITLE
[docs] Unique fields

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#384]
Notice there is `uniqueItems` documented, and that primary fields are assumed to be unique, but didn't see anything for just `unique` fields.

It does seem like it may work by searching code, but perhaps some tests + docs would help. I'm going to test to see if it works now as-is, and then could help with some docs.

**Comment by natew** [comment]
Ok did some verification, and it seems unique wasn't enforced for me. I changed the schema to have unique: true, it warned me it changed, cleared data, inserted a few things with the same property and it worked.

**Comment by pubkey** [comment]
We currently do not have unique fields.
`uniqueItems` is part of json-schema, but only works for elements of arrays.

**Comment by natew** [comment]
All good, doing a find on preInsert is good enough.
