### ISSUE TITLE
RXDB 12.x: rxdbMeta field synced in CouchDB, is it by design?

### ISSUE THREAD

**Issue by alecrt** [pubkey/rxdb#3908]
We did write Angular application with rxdb 10.x and now we upgraded to rxdb 12.
We use couchdb as master database, with RxDBReplicationCouchDBPlugin.

We found that new docs in couchdb, created by rxdb 12, now have "rxdbMeta" field, with lwt property valorized.

Old docs don't, so we can't update any of them:
main.0a3b5e4804ccbfe5.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'lwt')
TypeError: Cannot read properties of undefined (reading 'lwt')

Is it correct that _meta field is synced via pouchdb to couch? Even if it's only an "internal" field?

Thank you!

**Comment by pubkey** [comment]
Yes this is a known fact. For most user that was not relevant because they use RxDB also on the server side and then publish a CouchDB endpoint with the RxDB server plugin.

Using the RxDB migration will automatically add the _meta field. But using an old non-RxDB Couchdb instance will likely not work.

RxDB needs the _meta field only for locally stored stuff, it does not have to be replicated, so you can make a PR if you need that change.

**Comment by alecrt** [comment]
Thank you, all clear.

What in my opinion should be handled is this part of the code, since writeRow.previous._meta is always undefined for old documents. Even during RxDB migration

```
/**
 * Ensure that _meta fields have been merged
 * and not replaced.
 * This is important so that when one plugin A
 * sets a _meta field and another plugin B does a write
 * to the document, it must be ensured that the
 * field of plugin A was not removed.
 */
if (writeRow.previous) {
    Object.keys(writeRow.previous._meta).forEach(function (metaFieldName) {
      if (!writeRow.document._meta.hasOwnProperty(metaFieldName)) {
        throw newRxError('SNH', {
          dataBefore: writeRow.previous,
          dataAfter: writeRow.document
        });
      }
    });
 }

**Comment by alecrt** [comment]
> For most user that was not relevant because they use RxDB also on the server side and then publish a CouchDB endpoint with the RxDB server plugin.

Is it feasible even on production environment?

**Comment by pubkey** [comment]
> What in my opinion should be handled is this par...

I do not think so, RxDB should rely on having stored the correct json data. Patching on read is not a good solution.

> Is it feasible even on production environment?

I think most people use the non-couchdb-sync in production for performance reasons. But I myself use the RxDB couchdb server as backend in production, so for me the migration path from 10.x.x to 12.x.x worked.
