### ISSUE TITLE
Replication does not respect `batchSize` parameter

### ISSUE THREAD

**Issue by leandrogehlen** [pubkey/rxdb#3939]
Replication does not respect `batchSize` parameter

https://github.com/leandrogehlen/rxdb-batch-size,
I set the property `batchSize = 10`  
https://github.com/leandrogehlen/rxdb-batch-size/blob/main/src/index.ts#L54

![image](https://user-images.githubusercontent.com/1750751/185390600-82d0ab76-b389-4fb8-8aca-2b97b1ed57a1.png)

**Comment by pubkey** [comment]
Thank you for reporting, I added a fix.
