### ISSUE TITLE
Create replication instance does not reset `lastCheckpoint`

### ISSUE THREAD

**Issue by leandrogehlen** [pubkey/rxdb#3946]
If you recreate a replication instance the `lastCheckpoint` is not restarted.

https://github.com/leandrogehlen/rxdb-test/blob/instance/src/index.ts#L59

![image](https://user-images.githubusercontent.com/1750751/185791667-5694d179-1463-4256-8043-0d55d9d9d5b0.png)

**Comment by pubkey** [comment]
Yes this is intentional. If you reload the page, the replication must continue, not start from zero again.

**Comment by leandrogehlen** [comment]
Is there some way to force restart?

**Comment by pubkey** [comment]
Yes you can change the replication identifier.
But I see no reason why the replication should be restarted from zero on an already partially replicated database state.

**Comment by leandrogehlen** [comment]
You are right.
But using cordova or capacitor (hybrid apps) when happens some crash is necessary restart all replication process.
For this, currently the only way to do it, is remove and reinstall the app.

**Comment by pubkey** [comment]
But if the app crashes and is restarted, why shouldn't it be able to continue the existing replication?

**Comment by leandrogehlen** [comment]
Because there is no way to reset checkpoint.
I can change the logic in pull handler to do it, but i think, if is possible, to have a method to redefine `lastCheckpoint`
