### ISSUE TITLE
Loose typing of RxSchema property type

### ISSUE THREAD

**Issue by Zhincore** [pubkey/rxdb#3964]
Hey,
in addition to the types defined in the link above [rx-schema.d.ts#L7](https://github.com/pubkey/rxdb/blob/6766596dfaf3f90a8de0e4d34a4268c699e0a3d4/src/types/rx-schema.d.ts#L7) the line adds `| string`, which makes the typing very loose and VSCode doesn't suggest me the specific types. 
Does this looseness serve any purpose?

Current behavior:
![](https://static.zhincore.eu/tmp/rxdb-loosetype-current.png)

My desired behavior (without `| string`):
![](https://static.zhincore.eu/tmp/rxdb-loosetype-desired.png)

**Comment by pubkey** [comment]
There was a typescript bug and something broke without that. You can make a PR the bug was likely fixed in typescript already.

**Comment by pubkey** [comment]
Looks like it is still broken :(
