### ISSUE TITLE
Push batchSize in not respected 

### ISSUE THREAD

**Issue by meabed** [pubkey/rxdb#3994]
Thank you so much for the new release, it's working great with couple of minor issues:
- When adding batchSize 1 to the push handler and doing multiple rows updates fast ( in forloop for example ) the docs are passing sometimes in batchsize correctly and sometimes in more than batchsize ( incorrectly )
- Boolean fields that are used in an index, must be required, is not working as its not reading the variable from the schema path properly and throwing an error that field is not correct in the schema.

RxDB version: 13.3.0 used in ReactNative and PouchDB

Thank you so much

**Comment by pubkey** [comment]
Pls make a PR with a test case to reproduce. I cannot touch bugs that are not reproduced.

**Comment by meabed** [comment]
> Pls make a PR with a test case to reproduce. I cannot touch bugs that are not reproduced.

Thank you @pubkey appreciate your reply, I will share this shortly.

**Comment by meabed** [comment]
Thank you @pubkey I have put a simple nextjs app to demo it (https://github.com/meabed/rxdb-nextjs-demo-todo): 

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/45731/192481821-59de8556-4c46-4262-9c46-30573adc5afc.png">

On codesandbox ( https://codesandbox.io/s/github/meabed/rxdb-nextjs-demo-todofile=/src/components/todo.tsx ):
<img width="1890" alt="image" src="https://user-images.githubusercontent.com/45731/192483407-e4da00dd-2d9c-4af5-abab-d714b005579c.png">


I have added 10 db rows ( todos ) and as you see in the screenshot, the first item fires correctly at 1 batchSize, next push is 8 docs all together.

**Comment by pubkey** [comment]
I fixed the batchSize problem so that it is respected now.
Please also make a unit test for the boolean field problem so I will work on a fix for that.

**Comment by meabed** [comment]
Thank you so much @pubkey 🙏 

Yes I will re-produce the boolean field and open an issue, I tried on nextjs it was working, for react native it wasn't working, I will check if this issue still persists.

**Comment by meabed** [comment]
I have the error here ( i will post a code to reproduce it ): 

```

ERROR : error creating collections RxError (SC38):
Fields of type boolean that are used in an index, must be required in the schema
Given parameters: {
index:"isNew"
field:"isNew"
schema:{
  "keyCompression": false,
  "version": 1,
  "primaryKey": "_id",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string",
      "maxLength": 100
    },
    "data": {
      "type": "object"
    },
    "isNew": {
      "type": "boolean",
      "default": false
    },
    "createdAt": {
      "type": "string",
      "format": "date-time",
      "maxLength": 24
    },
    "updatedAt": {
      "type": "string",
      "format": "date-time",
      "maxLength": 24
    }
  },
  "required": [
    "_id",
    "data",
    "createdAt",
    "updatedAt",
    "isNew"
  ],
  "indexes": [
    "createdAt",
    "updatedAt",
    "isNew"
  ]
}}
```

**Comment by pubkey** [comment]
Ah I see. Thats good enough to reproduce, I will fix.

**Comment by pubkey** [comment]
Fixed here: https://github.com/pubkey/rxdb/commit/75ca7c15bed8d9a50158a81f9509d9275cf6c47d
Are you sure that your schema version should be `1` ?
If you create a collection for the first time, start with version `0`

**Comment by meabed** [comment]
Got it, I think when I used 0 I had another issue In the migration Plug-in I will verify and let you know. 

Appreciate your support ❤️

**Comment by meabed** [comment]
@pubkey Would you be planning to release this fixes soon?
Thank you
