### ISSUE TITLE
This.puch.sync is not a function

### ISSUE THREAD

**Issue by haikyuu** [pubkey/rxdb#4]
[Here is the line of code](https://github.com/pubkey/rxdb/pull/5/files/2cd263c4c2a0162a6cde51e6b689976bc8d7416d#diff-33a91eb26fd7aa1e32ecb4280f382401) causing the issue
Here is the stack trace 
`RxCollection.js:543 Uncaught (in promise) TypeError: this.pouch.sync is not a function(…)`
I tried with memory and idb adapter.

**Comment by pubkey** [comment]
Hello @haikyuu 
RxDB uses the pouchdb-core to minimize its build-size.
Pouchdb-core is not able to sync by itself.
You need [pouchdb-replication](https://www.npmjs.com/package/pouchdb-replication) to sync and [pouchdb-adapter-http](https://www.npmjs.com/package/pouchdb-adapter-http) to sync over http.

You can use the import from the angular2-example as reference. See [here](https://github.com/pubkey/rxdb/blob/master/examples/angular2/app/src/services/database.service.ts#L14)
