### ISSUE TITLE
Memory adapter - inMemory() throws error: `_id is required for puts`

### ISSUE THREAD

**Issue by adamJLev** [pubkey/rxdb#401]
## Issue
Getting `Uncaught (in promise) CustomPouchError {status: 412, name: "missing_id", message: "_id is required for puts", error: true}` right after calling `db.collectionName.inMemory()`.

## Info
- Environment: Chrome 62
- Adapter: indexed-db + memory

## Code
I can reproduce it using the local example project by modifying the `heroes-list.vue:mounted()` function to look like this:

```javascript
    mounted: async function() {
        const db = await Database.get();
        const col = await db.heroes.inMemory();
        
        this.subs.push(
            col
            .find().$
            .filter(x => x != null)
            .subscribe(results => {
                console.log('results:');
                //                console.dir(results);
                this.results = results;
            })
        );
    },
```

And added this to the top of `Database.js`
```javascript
RxDB.plugin(require('pouchdb-adapter-memory'));
```

Thanks!

**Comment by pubkey** [comment]
Hi @adamJLev can you post your schema?

**Comment by adamJLev** [comment]
@pubkey I'm just using the example vue project, the only change I made is the 2 things I posted in the issue.  https://github.com/pubkey/rxdb/tree/master/examples/vue

so this is the schema:
https://github.com/pubkey/rxdb/blob/master/examples/vue/src/database/HeroSchema.js

**Comment by pubkey** [comment]
Could reproduce, fix will follow soon
