### ISSUE TITLE
ANNOUNCEMENT: Win RxDB premium access by fixing my typos

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#4024]
# Win RxDB premium access by fixing my typos

Over the years, many spelling errors have slipped into the RxDB documentation and codebase.
To fix all of them, I want to start a special contest.

Every merged pull request that fixes a typo will get you one lottery ticket.
At the end, a random generator will cast a winner out of all tickets.

The winner gets a three-year access to the [RxDB premium plugins](https://rxdb.info/premium.html) for free.
Granted for personal projects that a fully owned by the winner himself. (Not for your company's project. Not for projects that are developed by more than one person. You have to sign a license agreement.)

## Do multiple Pull Requests count?

Yes, one lottery ticket per fixed typo. The limit is 30 PRs/Tickets per github account.
Please fix exactly one typo per Pull Request.
The counting will be done automatically with a script, so this will make it easier.
Only merged pull requests do count. Duplicate PRs will not be merged.

## Which kind of typos can be fixed?

Everything. Wrong spelling. Grammatical errors. Wrong wording. Wrong comma placements.
You can fix stuff in the documentation AND in the codebase AND in the tests (`docs-src`, `src` and `test` folders).
Event typos in code comments do count.
Only fixes in generated files (everything from the `dist` and `docs` folders) do NOT count.

## How long does  the event run?

It will run from now, 11.October 2022 to 19.October 2022 (GMT+2).
Only PRs that have been created during this time do count, even if they are merged after the end date.

## How to make a PR count?

To make the PR count, you have to set the start of the PR title to `TYPOFIX`. This will allow me to automatically scrape all PRs afterwards. You can leave the content field of the PR empty.
Only merged PRs count as lottery ticket. If your PR is causing a conflict and cannot be merged, you have to rebase it by yourself.
Duplicate PRs with fixes that already have been merged from another PR, do NOT count.

![typofix](https://user-images.githubusercontent.com/8926560/195096724-8c41deeb-9bec-423e-97b8-d40c219eac38.png)

**Comment by pete-hotchkiss** [comment]
RIP anyones inbox who's tracking every PR on this repos 🪦

**Comment by pubkey** [comment]
@pete-hotchkiss Tracking the PRs was also painful before because of the renovate bot that did so many PRs to update the npm dependencies.

UPDATE: I added a 30 PRs/Tickets limit per github account.

**Comment by pete-hotchkiss** [comment]
all good @pubkey - I was only joking really 

Easy enough for me to set up a rule in gmail to divert the tsunami away from the inbox 👍🏼

**Comment by pubkey** [comment]
Event is over.
Since we only had three participants, it is not worth creating a deterministic lottery :smile:  .
All three of you have won and get the premium access :tada:  : @Sohnio @nirvdrum @Albert-Gao 
Please send me your full name and address via discord pm so I can send you the license agreement and access tokens.
