### ISSUE TITLE
[minor feature] Show undefined props that break schema better

### ISSUE THREAD

**Issue by natew** [pubkey/rxdb#403]
## Case
```js
let things = await Rx.Collection({ schema: { title: { type: 'string' } } })
things.insert({
   title: 'passesvalue',
   body: undefined
})
```

## Issue
This will throw an error thats a bit confusing. In my case `body` doesn't exist on schema, notice it's undefined but in the error message you don't see that:

![image](https://user-images.githubusercontent.com/12100/33961938-aac8ad02-e004-11e7-9018-34ef98691655.png)

Because it doesn't show in the error the `undefined` it looks like the object should pass the schema.

Proposed solution would just be sure to log out the `undefined` value that causes it to fail.

**Comment by pubkey** [comment]
Hi @natew 
There is no `undefined`-value in json. I now transform fields with `undefined` to `null` to ensure the field is not denied in the error-message.
