### ISSUE TITLE
Resurrected legacy triple slash directives

### ISSUE THREAD

**Issue by jeromepochat** [pubkey/rxdb#4054]
PR #4023 was recently merged, changes are supposed to be part of 13.5.0, but removed lines are added back by commit d031b4b19e39cc90567d0d53f768a0936a836506.

https://github.com/pubkey/rxdb/blob/d031b4b19e39cc90567d0d53f768a0936a836506/dist/types/plugins/pouchdb/pouchdb-helper.d.ts#L1-L2

**Comment by pubkey** [comment]
Ah sorry. I haven't seen that when merging the PR. But anything in the `dist` folder is generated/transpiled code.
To have any effect, you have to fix that in the sources themself so that a `npm run build` will create the desired output.

**Comment by jeromepochat** [comment]
My fault, I missed that.

BTW, I fixed my initial issue by replacing `import ...from rxdb/plugins/pouchdb` by `const pouchdb = require('rxdb/plugins/pouchdb')`.

Sorry for unneeded PR #4023. My contribution mention should be removed from 13.5.0 release note :-)
