### ISSUE TITLE
rxdb addCollections err TypeError: Cannot read properties of null (reading 'hasOwnProperty')

### ISSUE THREAD

**Issue by Albert-Gao** [pubkey/rxdb#4055]
## for the following schema:

```typescript
import { RxJsonSchema } from "rxdb";
import { UserDocType } from "./types";

export const userSchema: RxJsonSchema<UserDocType> = {
  title: "user schema",
  description: "describes a user",
  type: "object",
  version: 0,

  // re-enable once not use dexie.js engine for the web since it does not support it
  keyCompression: false,

  primaryKey: "id",
  properties: {
    id: {
      type: "string",
      maxLength: 100,
    },
    birthday: {
      type: "string",
      default: null,
    },
    timezone: {
      type: "string",
      default: null,
    },
    createTime: {
      type: "string",
    },
    updateTime: {
      type: "string",
    },
  },
  required: ["id", "createTime", "updateTime"],
};
```

I get an error when creating the database, remove the usage of devplugin "solves" it...

wonder if I am missing something or a bug.

## a reproducible repo here:

https://github.com/Albert-Gao/my-rxdb-app

## Digging
With some debug, I found the issue here in this function,
![image](https://user-images.githubusercontent.com/18282328/195460532-85e27d96-3f5c-4518-aef3-642633f10775.png)

You can see the runtime value for `schemaObj` is `"string"` which is not an object, thus causes the problem, do not know the cause though.

**Comment by pubkey** [comment]
Your schema looks ok, this should work.

**Comment by Albert-Gao** [comment]
![image](https://user-images.githubusercontent.com/18282328/195467838-f191ba03-1795-472d-8ef1-1d411d5706a7.png)

added some guard, seems to solve the issue, can send a PR if you think it's a solution, I added the `isSchemaObj` guard and a nullable guard at line 162 in the `traverse()` function

**Comment by pubkey** [comment]
You should start with a unit test that reproduces the problem

**Comment by Albert-Gao** [comment]
I created a repo for reproducing it. 😄
and did some quick hack for unblocking. 😄

For a former PR, I cloned the repom, `npm i` and executed the tests via `npm run test`, the tests failed with the error `Blob is not defined` :D I am using Node v16.15.1, what am I missing here? Thanks 😄

![image](https://user-images.githubusercontent.com/18282328/195548036-92ee44ee-b2d8-4e07-b9b4-6e36f8ca86ea.png)

**Comment by pubkey** [comment]
You need at least node 18. https://rxdb.info/releases/13.0.0.html

**Comment by Albert-Gao** [comment]
Thanks for the help, progress made, stuck with this error

![image](https://user-images.githubusercontent.com/18282328/195590274-0b9a6f73-b1e9-4b09-b2c8-cbbbe485aceb.png)

The port 5000 is being used by control center, which is a Mac OS system app, I tried killing it, but not work, it always restarts itself right after killing.

![image](https://user-images.githubusercontent.com/18282328/195590345-ad0b236d-afd5-402a-9e0b-02c196a8a632.png)

I hard-coded the server-couchbase.ts to serve at another port, but having this same problem on another port 🤣

![image](https://user-images.githubusercontent.com/18282328/195591150-3830b77b-e4a0-4bf5-8186-ba84e760c814.png)

What am I missing here? thanks :)

**Comment by pubkey** [comment]
I fixed it to no longer use hard coded port numbers.
I have no idea about your second error :(

**Comment by Albert-Gao** [comment]
thanks, it sorts of working!

![image](https://user-images.githubusercontent.com/18282328/195667678-9996ac61-41c9-481a-a797-7290d4672cb2.png)

is this a test that tied to my local browser settings?

**Comment by Albert-Gao** [comment]
I removed all tests and added this test, now it can be reproduced


```typescript
/**
 * this is a template for a test.
 * If you found a bug, edit this test to reproduce it
 * and than make a pull-request with that failing test.
 * The maintainer will later move your test to the correct possition in the test-suite.
 *
 * To run this test do:
 * - 'npm run test:node' so it runs in nodejs
 * - 'npm run test:browser' so it runs in the browser
 */
import { createRxDatabase, addRxPlugin } from '../../';
import { RxDBDevModePlugin } from '../../plugins/dev-mode';
import config from './config';

describe('TypeError: Cannot read properties of null (reading hasOwnProperty)', () => {
    it('should fail because it reproduces the bug', async () => {
        // create a schema
        const userSchema = {
            title: 'user schema',
            description: 'describes a user',
            type: 'object',
            version: 0,

            // re-enable once not use dexie.js engine for the web since it does not support it
            keyCompression: false,

            primaryKey: 'id',
            properties: {
                id: {
                    type: 'string',
                    maxLength: 100,
                },
                birthday: {
                    type: ['string', 'null'],
                    default: null,
                },
                createTime: {
                    type: 'string',
                },
            },
            required: ['id', 'createTime', 'updateTime'],
        };

        // generate a random database-name
        const name = 'test-app';

        addRxPlugin(RxDBDevModePlugin);

        // create a database
        const db = await createRxDatabase({
            name,
            /**
             * By calling config.storage.getStorage(),
             * we can ensure that all variations of RxStorage are tested in the CI.
             */
            storage: config.storage.getStorage(),
        });

        // create a collection
        await db.addCollections({
            users: {
                schema: userSchema,
            },
        });
    });
});
```
