### ISSUE TITLE
dist folder not updated thus #4055 still there not fixed

### ISSUE THREAD

**Issue by Albert-Gao** [pubkey/rxdb#4060]
with the landing of v13.5.1, the bug #4055 is still not fixed,

I noticed the transpiled code is NOT changed at all.

https://github.com/pubkey/rxdb/blob/a56dc6fa0457e2c7dd342574d17bb52cbfc3e433/dist/lib/plugins/dev-mode/check-schema.js#L143

![image](https://user-images.githubusercontent.com/18282328/196006645-d4e8cd5d-8e34-40a1-811b-ff7a9fd84227.png)
![image](https://user-images.githubusercontent.com/18282328/196006658-ec001c12-a615-4afe-9c5b-4a76f92a51b7.png)

You can see in the image which the code is still in pre-PR stage

how do we update the transpiled version? in my PR, i was updating the transpiled files, but triggered linting error, said i should not do it.

**Comment by pubkey** [comment]
Gibe me time till monday, I will check.

**Comment by Albert-Gao** [comment]
Thanks mate :)

**Comment by pubkey** [comment]
The dist folder gets updated on the next release.
