### ISSUE TITLE
[Premium Task] BUG: Querying with $gt over a nested field returns the wrong results

### ISSUE THREAD

**Issue by bgervan** [pubkey/rxdb#4102]
From the https://github.com/pubkey/rxdb/blob/master/orga/premium-tasks.md

Estimated time: 1d

**Comment by bgervan** [comment]
PR: https://github.com/pouchdb/pouchdb/pull/8552

**Comment by pubkey** [comment]
Thank you, I updated the tasks list. https://github.com/pubkey/rxdb/blob/master/orga/premium-tasks.md
Please claim your free premium token when https://github.com/pouchdb/pouchdb/pull/8552 is merged.
I will close this issue, if you write anything here, `@` me so that I can see it.

**Comment by bgervan** [comment]
Hey @pubkey ,

I didn't use the product lately, can I still claim the token?

**Comment by pubkey** [comment]
@bgervan sure, just send me your address in discord, I can then send you the agreement you have to sign.
