### ISSUE TITLE
Wrong error type in replication state error subscription

### ISSUE THREAD

**Issue by nirvdrum** [pubkey/rxdb#4103]
I'm using RxDB 13.8.2 with TypeScript and subscribing to error events from the replication state. The [`error$` property](https://github.com/pubkey/rxdb/blob/0bc8e1edda9651a60f6c4657fa0b132214dd6ea6/src/plugins/replication/index.ts#L69) is typed as `Observable<RxError | RxTypeError>`. However, I've had error objects observed in my handler that don't match either the `RxError` or `RxTypeError` definitions.

Inspecting the object, it reports its name as "TypeError" and its type signature matches that of `Error` from lib.es5.d.ts. I.e., only has the following properties:
  * message
  * name
  * stack

I currently have errors coming from my error handler because the `parameters` property is `undefined` even though it's defined in both `RxError` and `RxTypeError`. I don't know if the type definition should be changed to add `| Error` or if RxDB's error handling needs to be improved.

Unfortunately, I don't have a readily available reproduction. I wanted to file this while the details are fresh. The stack for my error is:

```
TypeError: (0 , _util__WEBPACK_IMPORTED_MODULE_7__.ensureNotFalsy)(...).map is not a function
    at _temp10 (http://localhost:3000/static/js/bundle.js:141324:99)
    at o (http://localhost:3000/static/js/bundle.js:140950:44)
    at _settle (http://localhost:3000/static/js/bundle.js:140917:7)
    at _resumeAfterBody (http://localhost:3000/static/js/bundle.js:141034:9)
```

**Comment by pubkey** [comment]
The `ensureNotFalsy` in your stack trace, indicates that something in the RxDB internals is wrong. `ensureNotFalsy` is used when a variables is optional type but we can be sure that is set on runtime.
So we should investigate first where this comes from.

**Comment by nirvdrum** [comment]
It looks like the error is coming from:

 https://github.com/pubkey/rxdb/blob/60d17d0512876da0b0a932c488af1d5f87b0d908/src/plugins/replication/index.ts#L273

The result value is `null` in this case. The `ensureNotFalsy` code comes from _util.ts_:

https://github.com/pubkey/rxdb/blob/0bc8e1edda9651a60f6c4657fa0b132214dd6ea6/src/util.ts#L240-L245

You can see that neither `RxError` nor `RxTypeError` are being thrown.

**Comment by pubkey** [comment]
What does your server return on write requests?
Looks like it is not an array.

**Comment by nirvdrum** [comment]
I'm trying to upgrade from RxDB 11.7 and 13 just doesn't match what my server (Hasura) was doing previously. I've had to provide `responseModifier` for the pull configuration and I'm currently limiting push to a batch size of 1 to keep things simpler there. In particular, I have predefined mutations and pass variables, but that doesn't work when deletes and updates can appear in the same batch. Rather than map in a query for each item, I'm just doing single mutations. It's not a write-heavy system to begin with.

In this particular case, the replication is trying to delete a document that doesn't exist in remote data store, so the response looks like:

```json
{
  "data": {
    "delete_profiles_by_pk": null
  }
}
```

I'll work out the error as I continue to work my way through this upgrade. The reason I filed the issue is because the types aren't sound. The `error$` observer is defined to only receive `RxError | RxTypeError`, but it can receive other error types. I've identified a place where RxDB is violating the type.

I can open a PR to change the observer type to be `Observable<RxError | RxTypeError | Error>` or some variation of that. But, if the intention is that only RxDB errors should be handed to the subscriber, then the fix would require more comprehensive error wrapping.

**Comment by pubkey** [comment]
I added a test to ensure the push handler returns an array. This makes it easier to debug wrongly behaving backend in the future.
Yes the `error$` should only emit `RxError |  RxTypeError`. Any other error that gets emitted means that something is wrong in the code, either the RxDB code or the users backend behavior.

> but that doesn't work when deletes and updates can appear in the same batch

Your push handler does not have to do only one http request. You can start one for deletions and one for mutations in parallel.

**Comment by nirvdrum** [comment]
> I added a test to ensure the push handler returns an array. This makes it easier to debug wrongly behaving backend in the future. Yes the `error$` should only emit `RxError | RxTypeError`. Any other error that gets emitted means that something is wrong in the code, either the RxDB code or the users backend behavior.

That's the core of the issue though. If the type definitions are going to say the other types can't appear, then there needs to be a global error handler that rewrites them. Otherwise, it's going to lead to situations that the type definition says can't happen.

I've just run into another case where something other than `RxError | RxTypeError` is passed to the `error$` stream. I can't actually trust my error handler at the moment because I can't anticipate every runtime error that might occur.
