### ISSUE TITLE
GraphQL replication: WebSocket errors violate type definitions 

### ISSUE THREAD

**Issue by nirvdrum** [pubkey/rxdb#4112]
Related to #4103:

I've run into an issue where something other than `RxError | RxTypeError` is passed to the `error$` stream. This violates the type definition for the `error$` stream (as of RxDB 13.8.3). That in turn led to errors in my error subscriber related to reading properties that don't exist.

In this case, the `error` object ends up being an array of objects from the WebSocket module, I think:

https://github.com/pubkey/rxdb/blob/1e15b5f261746d6dab6b9aa9c48919e5faa5b2d9/src/plugins/replication-graphql/index.ts#L222-L224

The structure of the `error` value looks like:

```js
[
  {
    message: "unexpected variables in variableValues: headers",
    extensions: [
      path: "$",
      code: "validation-failed"
    ]
  }
]
```

The `error` value in WebSocket error callback is typed as `any`. I suspect this needs to be wrapped into an `RxError` before passing it on to the `pullStream$.error` call.

The underlying issue is I constructed my subscription to the Hasura server incorrectly. I used the RxDB docs as a guideline and didn't realize the `headers` value would be passed through as a GraphQL variable. The error ended up being masked because my `error$` subscriber was expecting the `parameters` property to exist and correspond to type `RxErrorParameters`:

`Uncaught TypeError: Cannot read properties of undefined (reading 'errors')`

**Comment by pubkey** [comment]
> I suspect this needs to be wrapped into an RxError before passing it on to the pullStream$.error call.

Yes this makes sense. Please make a PR.
