### ISSUE TITLE
window undefined ( react-native ) 

### ISSUE THREAD

**Issue by meabed** [pubkey/rxdb#4125]
Thank you so much for releasing the last update ❤️ 

Last version (13.10.0) breaks on react-native as `window` and `navigator` undefined:

```
TypeError undefined is not a function 
    node_modules/rxdb/dist/lib/plugins/replication/replication-helper.js:48:28 anonymous
```

**Comment by pubkey** [comment]
Release 13.10.0 is running, please test, create another issue or @ me here if it does not work.

**Comment by meabed** [comment]
Awesome thank you! just tested - its fixed.
FYI to re-produce the previous issue in react-native, it happen when switch device offline / or simulator ( because the navigator online check ) 

All good now. Thank you <3

**Comment by pubkey** [comment]
The problem is that it is very hard to reproduce these bugs in the CI with the rxdb electron example.
So I just fixed it without even testing. I have no idea how to ensure that these problems do not occur in the future.

Thank you for reporting the bug.

**Comment by pubkey** [comment]
I think we should change the react-native example to use the RxDB replication instead of the PouchDB replication. https://github.com/pubkey/rxdb/blob/master/examples/react-native/initializeDb.js#L72

**Comment by meabed** [comment]
Yes - I think moving the replication to the pouchdb is more common than couchdb
