### ISSUE TITLE
13.13.6 - in Electron.js  no response from await bulkUpsert / bulkInsert 

### ISSUE THREAD

**Issue by KVAnton-WEB** [pubkey/rxdb#4168]
No response from await bulkUpsert / bulkInsert  (the application hung at this point anyway) After update to 13.13.6  (13.13.5 work fine)
Electron version is not important (tried not all, but different ones)

**Comment by pubkey** [comment]
Please read the issue template.

**Comment by pubkey** [comment]
@KVAnton-WEB I will release a new version in a few hours. This might fix your problem.

**Comment by KVAnton-WEB** [comment]
yes thanks, 13.13.7 works great again
