### ISSUE TITLE
Opinion wanted: Naming of the RxDocument mutation functions

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#4180]
In the next major RxDB version, I want to rename the methods with which a RxDocument can be changed.

At the moment we have different methods and over the time the naming got inconsistend.

- `update()`: Updates a documents data by using NoSQL update operators like `update({ $set: {foo: 'bar'}})`. Reruns automatically on conflicts.
- `atomicPatch()`: Updates a documents data by a given partial object like `atomicPatch({foo: 'bar'})`. Reruns automatically on conflicts
- `atomicUpdate()`: Updates a documents data by a given function like `atomicPatch((doc) => { doc.foo = 'bar'; return doc; })`. Reruns automatically on conflicts.

In the future I want to have atomic and non-atomic versions of all 3 methods. Therefore `atomicUpdate()` can no longer take a function as input, but gets NoSQL update operators instead.
But migration would be confusing especially for non-typescript users because theyr old call to `atomicUpdate()` would give strang errors. So I want to replace the word `atomic` to prevent that.
Also the wording `atomic` makes no sense so a different word has to be chosen because atomic in the database context has a [totally different meaning](https://en.wikipedia.org/wiki/Atomicity_(database_systems)) than what the current RxDB methods do: they re-run on conflicts.

Current idea:

- Rename `atomicUpdate()` to `incrementalModify()`.
- Add `modify()` which errors on conflicts.

- Keep  `update()` but do not retry on conflicts.
- Add `incrementalUpdate()` which retries on conflicts and has the same input as `update()`.

- Rename `atomicPatch()` to `incrementalPatch()`
- Add `patch()` which errors on conflicts.

Questions:

- Is there a better word than `transform` which describes that a mutator function is the input.
- Which word should be used insteadd of `atomic` I thought about `incremental` or `additive` but both are long and hard to read.

**Comment by meabed** [comment]
Did you consider modify?

**Comment by pubkey** [comment]
Instead of `tranform` or instead of `atomic`?

**Comment by meabed** [comment]
Instead of transform

**Comment by meabed** [comment]
I think the retry could better clear expressed as non-atomic.

Could be option in modify or {retryOnConflict} and maybe max retry.

I think describing the retry behavior with atomicity is confusing.

**Comment by pubkey** [comment]
Yes your reight, `modify` is better, I updated my list above.
I am not sure with retry because it implies there was "a try" before the call to the method.

**Comment by meabed** [comment]
I see - could onConflictRetry - I just think it's not atomic if there is conflict already, so describing it with atomic is probably not accurate

**Comment by msotnikov** [comment]
modify, update, patch
modifyWithRetry, updateWithRetry, patchWithRetry

**Comment by phal0r** [comment]
I think retry is the wrong wording here. These are 2 modes to interact with data and I think they should not be mixed. If I understand the concept wrong, please feel free to correct me.

Mode 1: I want to use revisions and make sure, that the first write wins and changes are intentionally and based on the correct data

Mode 2: I just want to perform data modifications and don't care, what the current state in the database is (and therefor ignore any revision checks/errors) -> last write wins

One application should not mix these concepts and therefor the semantically best way to describe this, would be on when creating a collection (or even the database) and we only have the normal methods to work with data and it automatically enforces revisions or not.

I am not sure if this is feasible on an existing project or would confuse people even more, but I wanted to share my thoughts.

If we want to stick with the current concept, the wording should be something like "ignoreRevision" and should be provided as option to the method. Even though internally it just "retries" the operation, this is not the intention of functions. The intention is to just ignore revision checks, therefor the naming should be closer to the intention.

**Comment by pubkey** [comment]
In the next major release, the "atomic" operations do not only retry on conflict, but they are also merged into single writes when they happen directly after each other.
For example when you store the current mouse position in a document, and the mouse moves faster than how the storage can do the writes, all awaited "atomic" operations are merged into a single document write.

**Comment by pubkey** [comment]
Ok I think the current plan will be to rename `atomic` into `incremental` so that `atomicUpdate` becomes `incrementalModify` etc..

**Comment by alpha-computer** [comment]
Hello, if it's not too late, I would also like to bring in a suggestion. I would keep this as simple as possible. So also take terms that explain themselves.
update() stays as it is.
rename atomicPatch() to updateObject(). (or short updateObj())
and atomicUpdate() to updateFunction(). (orshort updateFunc())
thise all retry on conflict. For all functions which errors on conflict, put a "single" in front of it. So singleUpdate(), singleUpdateObject(), singleUpdateFunction(). It's a bit longer, but everyone knows when to use which function, even without documentation, or what the difference is to each other. 
 For people who are new to it, it might be a bit confusing what exactly is the difference between update modify and patch.
the easiest thing for the user would be an overload function "update()", which supports all 3 inputs.

**Comment by pubkey** [comment]
@alpha-computer 
I also thought about using overloads but I think that will be a problem when having to change something or extend some options because it will likely always cause a breaking change.

I try to not use any abbreviation in my code, I see no value in them other then saving a few milliseconds on writing.
