### ISSUE TITLE
Regrading installation of examples (Angular2)

### ISSUE THREAD

**Issue by roushanj** [pubkey/rxdb#42]
![screenshot from 2017-01-30 10-17-18](https://cloud.githubusercontent.com/assets/12628507/22412539/5b5b9d34-e6d5-11e6-85c8-0cf8d7e9bb88.png)

**Comment by SalamiMitPizza** [comment]
You need to run `npm install` in the directories rxdb and rxdb/examples/angular2.

**Comment by pubkey** [comment]
@roushanj Could you please describe your environment?
Node-Version / OS etc..
