### ISSUE TITLE
Set "type": "module" in the package.json

### ISSUE THREAD

**Issue by df2** [pubkey/rxdb#4213]
Hi Daniel,

Great project! Loving the potential of this. I am tackling the `type: module` premium task and estimate another 2 - 3 days to have it complete.

Will send a pull request once done.

Best,
Chris

**Comment by df2** [comment]
Still working on this Daniel. Mostly builds with errors in one plugin still to fix.

Something to mention is that `karma` is not compatible with modules. There is this library (https://www.npmjs.com/package/@open-wc/karma-esm), but it is no longer under development and they recommend `web test runner` (https://modern-web.dev/docs/test-runner/overview/).

Should I try getting `web test runner` to work, or would you prefer to use a different test runner?

**Comment by pubkey** [comment]
Yes we can switch out karma, but that should be done as separate PR to reduce the complexity of merging.
I only know the karma browser test runner. So I have no opinion about which one to use, `@web/test-runner` looks fine to me.

**Comment by df2** [comment]
Hi, I think `karma` is now compatible with ES modules by using something similar to:

```
files: [
    {
        pattern: '../test_tmp/unit.test.js',
        module: true
    }
]
```

in `karma.conf.js`.

I'm going to give that a shot and see if I can get the tests running and passing now. I changed the tests transpile option to es6.

Does there need to be two sets of tests, one for es5 and one for es6?

I think I will have to link imports in the es6 tests directly to the `dist` directory as that is the only way I could get the imports to work.

Chris

**Comment by df2** [comment]
Sure, what I meant was that instead of:

```
import { addRxPlugin } from '../../';
import { RxDBDevModePlugin } from '../../plugins/dev-mode';
```

I would need to do something like:

```
import { addRxPlugin } from '../../dist/es/index.js';
import { RxDBDevModePlugin } from '../../dist/es/plugins/dev-mode/index.js';
```

As you can see, I also had to add `.js` to every import. However, this eventually gets to:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/chris/Documents/Work/df2/rxdb/node_modules/crypto-js/aes' imported from /home/chris/Documents/Work/df2/rxdb/dist/es/plugins/encryption/index.js
Did you mean to import crypto-js/aes.js?
```

I'm stuck and I need your help. There is obviously a wrong setting somewhere. I tried many different combinations of the recommendations in these two pages (except downgrading mocha), but still couldn't get it to work:

https://stackoverflow.com/questions/65384754/error-err-module-not-found-cannot-find-module
https://stackoverflow.com/questions/64261239/mocha-tests-with-esm-support-for-native-es6-modules

**Comment by pubkey** [comment]
@df2  give me some time, I will check

**Comment by pubkey** [comment]
@df2 I am ok with having the `.js` filename in the imports of the tests. I have checked other repos, and they also handle it that way, like [here](https://github.com/sindresorhus/get-port/blob/main/test.js#L4).

**Comment by df2** [comment]
All good buds, I'm going to have to bow out of this and let someone else take a stab at it.
