### ISSUE TITLE
ANNOUNCEMENT: Test RxDB 14.0.0 BETA

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#4285]
RxDB version 14.0.0 is now it beta and you should try it out.
Bugs found related to the beta version, will be fixed by the maintainer.
The new version will be in beta for about **4 weeks**.
If you have problems after the 14.0.0 non-beta release, you will have to fix them by yourself.

Release notes: https://github.com/pubkey/rxdb/blob/master/docs-src/releases/14.0.0.md

You can find the latest beta version here: https://www.npmjs.com/package/rxdb?activeTab=versions

**Comment by swnf** [comment]
@pubkey I think it might be necessary for RxDB users to increment their schema version if a schema contains arrays (like `required`). Otherwise, an application might work in one browser and break in another browser because the new hash does not match. Maybe this should be mentioned in the release notes?

**Comment by pubkey** [comment]
@meabed No, PouchDB will no longer be maintained, [see](https://rxdb.info/questions-answers.html). It just makes no sense and nothing on PouchDB really worked.

@nickchomey I normally do not fix other peoples bugs. This is an open source project.

@swnf Yes you are right, I will put that into the release notes.

**Comment by Unforgiven-wanda** [comment]
As of beta.18 the replication to CouchDB is still broken. Upstream replication will occasionally and randomly get `ensurenotfalsy() is falsy` on [this line](https://github.com/pubkey/rxdb/blob/master/src/plugins/replication-couchdb/index.ts#L137)

**Comment by Unforgiven-wanda** [comment]
Hello again,
I'd like to report that as of beta.25 the **live replication** on CouchDB is broken. (Yes, live is set to true in `replicateCouchDB`)
Upstream replication (edits on the client) function perfectly.
But downstream syncs (edits on the CouchDB instance in the server) do not happen. No error is thrown.
Please see the following for an example: [Video](https://streamable.com/nbyjxf)
I'd like to create a test for this, but I honestly have no idea how, in this particular case.
Any insight of yours is most welcome.
As always, thank you for your time.

**Comment by pubkey** [comment]
@Unforgiven-wanda to reproduce the problem, you could just create 2 collections and replicate them with one server, like [here](https://github.com/pubkey/rxdb/blob/master/test/unit/replication-couchdb.test.ts#L128). Then do the document writes on either side of the collections.
If that does not reproduce the problem, you'd have to modifiy the document state by runnning POST requests against the PouchDB server that is used in the tests.

**Comment by ofekd** [comment]
2 questions:

1. `doc.populate` returns an array of mutable documents. Is that by design?
2. The read-only object returned when subscribing with `doc.$` does not have the methods I've defined on it on collection creation. Is that also by design?

**Comment by pubkey** [comment]
@ofekd 

1. Populate returns an array if you run it on an array-of-ids field. Otherwise it should return a single document.
2. doc.$ emits `Observable<DeepReadonly<RxDocumentData<RxDocType>>>`. So only the plain document data, not a RxDocument. Now that I think about it, this looks wrong. Maybe we should emit RxDocument objects instead.

**Comment by ofekd** [comment]
@pubkey Right -- returning just `RxDocumentData` really pulls the rug from under RxDB's collections extensibility.

In previous version it was only used with `toJson`, wasn't it?

**Comment by pubkey** [comment]
@ofekd changed here: https://github.com/pubkey/rxdb/pull/4318

**Comment by ofekd** [comment]
Thank you, works well.

**Comment by ofekd** [comment]
What is the best way to get all of the documents waiting on push from a graphql replication state? Currently doing something like this but I'm getting bad results:

```typescript
const internalState = replicationState.internalReplicationState;

if (!internalState) {
    return [collectionName, []];
}

const checkpoint = await getLastCheckpointDoc(internalState, 'up');

const changedDocuments = (
    await internalState.input.forkInstance.getChangedDocumentsSince(
        // arbitrarily large number
        1000000,
        checkpoint,
    )
).documents;

return [collectionName, changedDocuments ?? []];
```

I'm looking to indicate to the user which documents are syncing

**Comment by pubkey** [comment]
@ofekd Calling `getChangedDocumentsSince` without an `undefined` checkpoint, will return documents from the beginning of time.

**Comment by ofekd** [comment]
@pubkey I see. Does an `undefined` checkpoint queue guarantee there is nothing to push? Or it there a situation where it'll be `undefined`with items waiting? For example on initial load

**Comment by pubkey** [comment]
That I do not know, the queue only guarantees the correct order of stuff.

**Comment by pubkey** [comment]
This will be the last week for v14 to be in beta.
Please test the latest beta release!

**Comment by leonceaklin** [comment]
Is there more information somewhere about the worker plugin being removed in 14? Why is worker functionality removed and what are the best alternatives?

**Comment by pubkey** [comment]
@leonceaklin is is in the release post

> In the past, the [worker plugin](https://github.com/pubkey/rxdb/blob/master/docs-src/rx-storage-worker.html) was based on the [threads](https://www.npmjs.com/package/threads) library. It was completely rewritten and uses the plain JavaScript API together with the [remote storage plugin](https://github.com/pubkey/rxdb/blob/master/docs-src/rx-storage-remote.md). BUT notice that the worker plugin has moved into the [RxDB Premium](https://rxdb.info/premium.html) package.

**Comment by leonceaklin** [comment]
Oh ok, thank you for the info🙏

**Comment by Unforgiven-wanda** [comment]
Related to #4278 `$in` operator appears to be broken in LokiJS.
Previously working queries now return nothing.

**Comment by pubkey** [comment]
The loki storage was not touched I think https://github.com/pubkey/rxdb/commits/master/src/plugins/storage-lokijs
So please make a PR with a failing test if it does not work for you.
@Unforgiven-wanda

**Comment by pubkey** [comment]
Thank you everyone for testing and helping me fix stuff.
RxDB v14 is now released.
