### ISSUE TITLE
Id length limit reached with composite key

### ISSUE THREAD

**Issue by ofekd** [pubkey/rxdb#4315]
I am using a composite of two UUIDs, and end up getting something like this with replication:

`rx-storage-replication-pf7ru|ad5eccab-53a1-4e2e-bdbe-9e080536c3ce,eef351c3-1eca-4af2-bf9a-7a192028910b|0`

Which is above the limit:

https://github.com/pubkey/rxdb/blob/7607a8b9b2346f5de962eac9d2e04045a36d599c/src/replication-protocol/meta-instance.ts#L34

Thus errors out

RxDB v `13.17.1`

**Comment by pubkey** [comment]
Reat the issue template.

**Comment by pubkey** [comment]
Ok this is dangerous.
We should internally hash the id to ensure that the lenght is known, I will check.

**Comment by pubkey** [comment]
Fixed in #4317 together with some other refactorings.
Notice that this is a breaking change, so it will not be release on RxDB v13.
