### ISSUE TITLE
Update all open PRs from the renovate bot

### ISSUE THREAD

**Issue by dhrn** [pubkey/rxdb#4321]
Update all [open PRs from the renovate bot](https://github.com/pubkey/rxdb/pulls?q=is%3Apr+is%3Aopen+by%3A%40renovate) and ensure that the CI is green.

**Comment by dhrn** [comment]
@pubkey planning to take few pr from this

**Comment by pubkey** [comment]
Awesome. But notice that for the free premium access, the "all" keyword is required :)

**Comment by pubkey** [comment]
@dhrn  can you make a PR with a simple change, like adding a space in a file? Then I can merge that and github will automatically run the CI on your PRs without having me to click each time.

**Comment by pubkey** [comment]
Any update on this? @dhrn

**Comment by dhrn** [comment]
don't have react native setup. need some time to complete. @pubkey

**Comment by pubkey** [comment]
Closing this since there was no update.
