### ISSUE TITLE
Ignore additional properties

### ISSUE THREAD

**Issue by davidwadge** [pubkey/rxdb#439]
Is it possible to set a flag to ignore additional properties when creating or updating a record? Currently, if our API changes and we pull down data into our React Native app without adding a schema migration, it will throw an exception when the model is saved with additional, irrelevant properties.

**Comment by pubkey** [comment]
No I'm sorry but this is not possible. Rxdb must always have to know which fields a document can have.
Can you use the pre-insert-hook to strip all irrelevant fields before saving?

**Comment by davidwadge** [comment]
Thanks, that will do the job for the time being.
