### ISSUE TITLE
ANNOUNCEMENT: - The logo of RxDB

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#44]
Hello guys.
As you may have noticed, I created a logo for RxDB.
My plan is that we now further improve the logo to get a final version.
Everything, the colors, the shapes, the format is changeable by you.

# Thoughts on the current version:
- It displays the shapes of the ["official" database-logo](http://www.accentsoftware.co.uk/images/database-logo.jpg)
- The main color is the one from [rxjs](https://raw.githubusercontent.com/Reactive-Extensions/RxJS/master/doc/designguidelines/images/984368.png)
- The logo follows the [FFF](https://en.wikipedia.org/wiki/Form_follows_function) concept and should be recognized as made by open-source-developers, not by a big company.
- The logo should be recognizeable very big and even as favicon-size.

# Current version:
![logo](https://cdn.rawgit.com/pubkey/rxdb/ca17df8eb79147801c1b640934df6549040c6611/docs/files/logo/logo_union_path.svg)

I will later print some stickers and distribute them to RxDB-users. So give your best and **you** get one. :wink: 

# How to contribute:
I made the logo with plain javascript + d3.js. So feel free to create pull-requests to [this](https://github.com/pubkey/rxdb/blob/master/docs/files/logo/logo.html) file.

# Problems with the current version:
- We need a version which optional displays the name "RxDB"
- The colors are not perfect (just [my](https://github.com/pubkey) opinion)
- The proportions of the 3 big blocks, do not give the impression of the "offical"-database-logo.
- The pattern of the small blocks is not "random enough"

**Comment by iansinnott** [comment]
I don't have a submission, but to hopefully give some inspiration the custom Rx-related logos on Egghead look quite nice: https://egghead.io/technologies/rx 

FWIW I like the idea of combining Rx with the classic three-row DB logo in some way.

**Comment by pubkey** [comment]
Thx @iansinnott . I changed the colors a bit. What do you think?

![logo_v2_1](https://cloud.githubusercontent.com/assets/8926560/22571656/da24cf00-e9a0-11e6-8211-c92af3955fd8.png)
![logo_v2_2](https://cloud.githubusercontent.com/assets/8926560/22571658/db4bf174-e9a0-11e6-8c26-eb39c756d4f9.png)

**Comment by pubkey** [comment]
New version:
- Changed color so it doesn't look like the logo got washed too often
- removed some pixels so it does not look like created from a five-years-old
- fixed render-mode so there is not halo arround blocks

![v2](https://cloud.githubusercontent.com/assets/8926560/22600717/0324d576-ea3c-11e6-9e78-dc209959f24f.png)

**Comment by pubkey** [comment]
Final version:

![final](https://cloud.githubusercontent.com/assets/8926560/22607235/3d5f217c-ea57-11e6-8cc3-4a5eec394501.png)

**Comment by zoomclub** [comment]
Nice! IMHO the pixels sparking of the top and bottom from the earlier version looked okay as well.

**Comment by pubkey** [comment]
Maybe last version:
- changed font-family
- added font as vector so its equal on every os


![final2](https://cloud.githubusercontent.com/assets/8926560/22619903/e50f7604-eafe-11e6-9ec5-f5d2e66bbb9b.png)
