### ISSUE TITLE
ecccrypto in rxdb-premium

### ISSUE THREAD

**Issue by msotnikov** [pubkey/rxdb#4457]
The eccrypto package is stale https://www.npmjs.com/package/eccrypto
In some cases it doesn't build (e.g. https://github.com/nlindley/eccrypto/commit/5e659e99e8b025e97a48c12473812376096110bf)

I've tryed to resolve with @nlindley/eccrypto and it had works. Perhaps better to replace eccrypto with @nlindley/eccrypto.

https://www.npmjs.com/search?q=eccrypto

**Comment by pubkey** [comment]
Hi @msotnikov 
This is a good proposal. I tried to switch out eccrypto but `nlindley/eccrypto` is about 10x slower on node v19 which makes it unuseable. I am not sure how to proceed.

**Comment by msotnikov** [comment]
The maintainer propose to use the v3 at the top of readme (https://github.com/nlindley/eccrypto#eccrypto). But in my case it also have problems with build (no openssl header files #include <openssl/evp.h> #include <openssl/ec.h>). It requires some chore to fix it.

**Comment by pubkey** [comment]
But according to the readme, using v3 will use node native modules again, so wouldnt that cause the same problems for you?

> eccrypto - JavaScript Elliptic curve cryptography library for Node.js. This only uses pure JS dependencies to avoid having to compile native modules. **If you would prefer native modules, use v3.**

**Comment by pubkey** [comment]
I am closing this. I think we should fix problems in the "eth-crypto" library.
I cannot use a different encryption algorithm, because I gave out the premium tokens (=eth private key) to many people already.
