### ISSUE TITLE
Atomicity of `query.update()`

### ISSUE THREAD

**Issue by ofekd** [pubkey/rxdb#4458]
I was getting `CONFLICT` errors when executing `collection.find().update()`, which intuitively I found strange since updating a just-found record should be an update on the latest state.

After digging around the code a bit I see the underlying implementation is a two-step:

https://github.com/pubkey/rxdb/blob/master/src/plugins/update/index.ts

So there must be a race condition somewhere in my code.

I am refactoring my code to use the `incremental` implementation which should solve it for me, however this is unexpected behavior so I am reporting.

I am using `14.0.4` with Loki

**Comment by pubkey** [comment]
Yes, the are no cross-document transactions in RxDB. We need this to support offline first while still having fast replication.
This is also written in the docs somewhere.

**Comment by ofekd** [comment]
This may also affect the performance of a query observer -- it will fire many times if each of queried items is updated individually compared to in bulk

**Comment by pubkey** [comment]
Using rxQuery.update() does not run in a single "transaction". It first queries the documents and the updates them. Stuff can happen in between this steps. This is intentional.

**Comment by ofekd** [comment]
I have read the documentation and understand the considerations. What I don't understand is why isn't `update` atomic in the first place, the same way a `SQL UPDATE` is?

Or maybe a SQL UPDATE is converted to a two-step transaction as well (`SELECT` followed by some sort of `SAVE`)?

**Comment by pubkey** [comment]
Update is atomic, but only on the single document level, not accross documents.
This allows us to do several optimizations like done in the sharding plugin etc.
