### ISSUE TITLE
Manual Sync

### ISSUE THREAD

**Issue by ForumT** [pubkey/rxdb#449]
Hi,

I am using RXDB with react. My backend doesnot provide couchdb support.

So i am manually syncing the db. I am currently deleting each document and then recreating it like so:

const query = this.db.attendee21.find()
const removedDocs = await query.remove();

This takes time as each document is deleted individually.

Is there a way to clear the db?

I tried  this.db.attendee21.remove()
but this does not empty the db. Like when i call the same instance in another component, it shows the old values only. Am I not doing it correct?

If i can clear the entire db in a go, i just have to loop to add the attendees

**Comment by pubkey** [comment]
Calling `remove()` on the collection should clear up all data. If it does not this is a bug and I need some code to reproduce.

**Comment by ForumT** [comment]
Hi,

It does remove. I recreate it and check the count. It shows 0. But the thing is, when I try to access this.db.attendee21 in any other component, the  count is again same with the old data.

this is my code:

await this.db.attendee22.remove();
after this I reload the page and recreate the collection.
When i check the length it is zero.
....

code 1
let sub = this.db.attendee22.find().$.subscribe(async(attendee22) => {
     if (!attendee22.length) {
         //this is executed

    }
}

when i execute code1 in another component, i get the old data again. Is it because it still accesses the old instance?

**Comment by pubkey** [comment]
Hi @ForumT 
I'm sorry but it is very hard to reproduce this with the given information. Please submit a PR with a test that reproduces this.
The easiest way to do this is by editing the [bug-template](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js)

**Comment by ForumT** [comment]
Hi,

I am extremely sorry. Your bug template showed me where i was going wrong. It works fine now.
Thank you so much for your help :) this can be marked as not an issue

**Comment by pubkey** [comment]
:) no problem.
