### ISSUE TITLE
Question: How to programmatically reset checkpoint for replication to force re-sync from the a specific point 

### ISSUE THREAD

**Issue by meabed** [pubkey/rxdb#4528]
Hi @pubkey,

Question: How to programmatically reset checkpoint for replication to force re-sync from the a specific point?

This is a question, not an issue. I didn't find anywhere to ask it.

Thank you

**Comment by pubkey** [comment]
I do not think resetting is currently available.
You could create a new replication state with a different identifier and there you can specify a new start-checkpoint.

**Comment by meabed** [comment]
Got it, thank you

**Comment by msotnikov** [comment]
You can pass new checkpoint value in pull handler
```
const rxReplicationState = await replicateRxCollection<any, CheckpointType>({
  pull: {
    handler: (lastCheckpoint: CheckpointType) => {
          // some work here

         return {
            documents: payload,
            checkpoint: needReset ? 0 : newCheckpoint,
           }
     }
  }
})
```
