### ISSUE TITLE
Error: rxdb-premium version not found

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#4592]
When installing premium in CI we are getting the following error:

```
Error: rxdb-premium version not found 12.7.16
    at u (/Users/cwd/Developer/bank/node_modules/rxdb-premium/scripts/postinstall.js:1:967)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

this means we haven't been able to deploy for a couple days and anyone who does not have their node_modules already setup can't dev on the project.

**Comment by pubkey** [comment]
So there  was a flaw in how the premium installation works. I had to change it but all versions pre 13.7 do not have a way to update the installation script.
I have wrote you on discord on how to solve this.
