### ISSUE TITLE
The babel-polyfill causes typescript build errors

### ISSUE THREAD

**Issue by mnmtanish** [pubkey/rxdb#46]
The babel-polyfill causes build errors when used with Ionic2.

```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
	Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.) in /path/to/my/project/node_modules/zone.js/dist/zone.js (line 42)
```

**Comment by mnmtanish** [comment]
As a temporary fix, restore the Promise replaced by babel-polyfill.

```
const _Promise = Promise;
const RxDB = require('rxdb');
Promise = _Promise;
```

**Comment by pubkey** [comment]
You are right. Including the polyfill for everyone is not the final solution. I will figure out a better solution.
Maybe someone has a hint on how other npm-libs handle the problem of including polyfills.

**Comment by Lyoko-Jeremie** [comment]
i have the same problem in angular2 with angular-cli

i add those code in polyfill.ts
```ts
import 'core-js/es6/promise';
```
then, i can use es6 import style like that:
```ts
import * as RxDB from "rxdb";
import {RxDatabase, create as createRxDB, RxSchema, RxCollection} from 'rxdb';
import * as pouchDBAdapterIdb from 'pouchdb-adapter-idb';
import * as pouchDBAdapterWebsql from "pouchdb-adapter-websql";

RxDB.plugin(pouchDBAdapterIdb);
RxDB.plugin(pouchDBAdapterWebsql);
```
and than, i can use follow code in typescript:
```ts
    cacheRxDatabase: RxDatabase;
    cacheRxSchema: RxSchema;
    cache: RxCollection;
```

and, mnmtanish's way case typescript cannot use type info, i dont hate that way.

the, please fix this issue,thx.
@pubkey 
and, may be can not include pollyfill in rxdb, but include it with manual and say it in document?

**Comment by pubkey** [comment]
@Lyoko-Jeremie Yes I know of this problem. As mentioned [here](https://github.com/pubkey/rxdb/issues/28#issuecomment-281276584), polyfills will not be included when v3.0.0 is out.

**Comment by Lyoko-Jeremie** [comment]
@pubkey 
nnnn,  how long will v3 release ?

**Comment by pubkey** [comment]
[See](https://github.com/pubkey/rxdb/issues/48)

**Comment by pubkey** [comment]
@Lyoko-Jeremie . It's released now. Can you check if the polyfill-problem is solved?

**Comment by pubkey** [comment]
Closing this since no response. It should work in RxDB v3 now, reopen if you think otherwise.
