### ISSUE TITLE
database.remove() doesn't remove the database

### ISSUE THREAD

**Issue by adam-lynch** [pubkey/rxdb#4602]
The [docs](https://rxdb.info/rx-database.html) say it...

> Removes the database and wipes all data of it from the storage.

It clears the data but the tables and database still exist. RxDB v14.3.6, using the IndexedDB RxStorage storage adapter.

**Comment by pubkey** [comment]
Yes it is not possible on all storages to safely do a full cleanup. remove only ensures that the documents data is deleted.

**Comment by pubkey** [comment]
Fixed in #4603
