### ISSUE TITLE
Update rxdb-premium

### ISSUE THREAD

**Issue by meabed** [pubkey/rxdb#4613]
Hi @pubkey 

Could you please Update rxdb premium to match the latest version
<img width="388" alt="image" src="https://user-images.githubusercontent.com/45731/230914056-a027e698-375c-43d8-b30a-4aa4770c9cb0.png">

**Comment by pubkey** [comment]
I just released 14.7.2.

**Comment by meabed** [comment]
@pubkey Thanks for releasing the latest update - it would be great if the premium plugin kept up to date with new versions
`14.8.1`

**Comment by meabed** [comment]
@pubkey would you please publish the `[14.9.0]`

**Comment by pubkey** [comment]
Please stop asking each time.
If there are problems I have to fix them in the background. The premium is released as fast as possible.
