### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'entries'

### ISSUE THREAD

**Issue by ForumT** [pubkey/rxdb#465]
I am getting the above error in IE11(works fine is all other browsers). The error is linked to the plugin.js file line number 55.

I am using RXDB version ^7.1.1

The error comes on the landing page itself.
Is there a workaround for this?

**Comment by pubkey** [comment]
Object.entries is [not supported in IE](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)

Please use polyfills like described [in the docs](https://pubkey.github.io/rxdb/install.html#import)
