### ISSUE TITLE
why additionalProperties is always false?

### ISSUE THREAD

**Issue by naivefun** [pubkey/rxdb#47]
Actually there are a lot of payload that does not need schema, is it possible offer schemaless option?

**Comment by pubkey** [comment]
@naivefun I often thought about creating schemaless collections. But no it is not possible. The way that things like keyCompression, observables of subobjects, encryption etc. are implemented, is such less complicated when relying on a schema. This is also why `additionalProperties: true` must have been added.

If you dont know the structure of the object you want to save, you can have a schema with an object without defined properties:

```js
const schema = {
    title: 'human schema',
    description: 'this schema has no index',
    type: 'object',
    properties: {
        data: {
            type: 'object',
        }
    },
    required: ['data']
};
```

**Comment by naivefun** [comment]
@pubkey  with this the mongo query still works?

**Comment by pubkey** [comment]
I think so, but feel free to try it out.
What will probably not work is observables of nested unknown objects. `myDoc.data.foo.baar$.subscribe(..`
