### ISSUE TITLE
update `getSQLiteBasicsQuickSQLite` to take an open database vs. the `openDatabase` function

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#4700]
right now `getSQLiteBasicsQuickSQLite` from `rxdb-premium` takes the `openDatabase` function from `react-native-quick-sqlite` as its input. I assume it then opens the database internally.

The downside here is if other code needs to use the database for whatever reason (for me, currently, its debugging) you need to open a second connection. In my experience this works only until both connections try and access the DB at the same time, and then everything falls apart.

I'm wondering if this could be fixed by changing the input for `getSQLiteBasicsQuickSQLite`

so go from:

```
// create database
const myRxDatabase = await createRxDatabase({
    name: 'exampledb',
    multiInstance: false, // <- Set multiInstance to false when using RxDB in React Native
    storage: getRxStorageSQLite({
        sqliteBasics: getSQLiteBasicsQuickSQLite(open)
    })
});
```

to: 

```
// open database
const db = open('databaseName')

// create database
const myRxDatabase = await createRxDatabase({
    name: 'exampledb',
    multiInstance: false, // <- Set multiInstance to false when using RxDB in React Native
    storage: getRxStorageSQLite({
        sqliteBasics: getSQLiteBasicsQuickSQLite(db)
    })
});
```

**Comment by pubkey** [comment]
You can get the database connection with the `getDatabaseConnection` method that you can import from the sqlite storage plugin.
```ts
getDatabaseConnection(
    sqliteBasics: SQLiteBasics<any>,
    databaseName: string
): Promise<SQLiteDatabaseClass>;
```

**Comment by chrisdrackett** [comment]
excellent! I didn't see that in the docs :)
