### ISSUE TITLE
Replication with GraphQL STREAM does not update record in rxdb database locally

### ISSUE THREAD

**Issue by LeXaMeN** [pubkey/rxdb#4750]
I configured the client and server according to the [documentation](https://rxdb.info/replication-graphql.html).
I checked everything already 1000 times.

There is a record with fields:
key: string
name: string
updatedAt: string (ISO DateTime C#)

What's going on for me:

1. I set a new name for record in rxdb. updatedAt do not change.

2. Automatically sent mutation PushRecords with an array of 1 element:
assumedMasterState: old record
newDocumentState: new record

3. The updatedAt is set on the server and the record is updated in the database.
After that, the server creates a subsciption StreamRecords event with our updated record:
documents: Record[]
checkpoint: checkpoint

4. The client receives data from the StreamRecords event and MUST UPDATE the updatedAt field in rxdb. But this doesn't work.

I found out that the checkpoint updates successfully. But no matter what I do, the record is not updated in the rxdb database via STREAM (pullStreamQueryBuilder).

I tried to skip points 1 and 2, and manually generate events 3 and 4 on the server, but the client still does not update the record in the rxdb database.

I don't understand why this is happening, I'm tired.
I configured everything according to the current documentation.

I won't write a unit test for this.

**Comment by pubkey** [comment]
> I won't write a unit test for this.

It is unlikely that someone will debug and fix this for you.

**Comment by LeXaMeN** [comment]
@pubkey
How can I update the record in the rxdb database so that automatic point 2 is not called?
I will then manually update the record in the database after receiving data from stream. Because your code doesn't update the record.
Maybe there is a method for manually updating the checkpoint?

**Comment by LeXaMeN** [comment]
Didn't update because I removed the key before submitting.
In fact, I also had an id field - a numeric index (original key) and key I did not need to send to the server.

```
push: {
  batchSize: 100,
  queryBuilder: pushQueryBuilder,
  modifier: (doc => {
    // delete doc.key;
    delete doc.__typename;
    return doc;
  })
}
```
