### ISSUE TITLE
findOne.$.subscribe emits deleted documents

### ISSUE THREAD

**Issue by adam-lynch** [pubkey/rxdb#4794]
I've been working on custom React hooks for our app (`useCount`, `useFind`, etc) and have been working on (Cypress) tests for these. A lot of these hooks have similar tests, one of which goes like this: 

1. Insert a few documents.
2. Mount a React component which uses the hook.
3. The hook sets up the subscription (`rxQuery.$.subscribe`) and returns some result(s).
4. Delete all documents.
5. The hook should now return no results.

I can't figure out why, but the following issue only happens for `findOne`; step 5 always returns a document, even though they were all just deleted.

I've debugged it a good bit and I know it's not an issue in my tests or anything like that. (To be clear, the subscription is only set up once)

I have created #4793 to reproduce it but it doesn't fail (at least locally). 

Locally in my tests, I dug into it a bit more and saw that the emitted `RxDocument` contains `_data._deleted: true`. (If I filter those bad results out, everything else works as expected)

Again, to be clear, if instead of using `findOne.$.subscribe`, I use `find.$.subscribe` (and only return the first result), everything is fine.

## Schema used in my tests

```js
{
    primaryKey: 'id',
    properties: {
        id: { type: 'string', maxLength: 100 },
        value: { type: 'string' },
    },
    required: ['value'],
    type: 'object',
    version: 0,
}
```

## Versions

- rxdb: 14.11.1 or 14.14.1
- rxdb-premium: 14.11.1 or 14.14.1

**Comment by pubkey** [comment]
Hi @adam-lynch 
Which storage are you using while having this bug? Can you check if you have the same problem with the memory storage?

Running your test locally on browser and node does also not fail for me. Maybe this is a problem with the rxdb-hooks plugin?

**Comment by adam-lynch** [comment]
> Which storage are you using while having this bug?

IndexedDB

> Can you check if you have the same problem with the memory storage?

It's the same with the memory storage.

> Maybe this is a problem with the rxdb-hooks plugin?

No, I'm not using rxdb-hooks. I wrote these hooks from scratch.

I've debugged the code and it's essentially the test I provided in my PR. In my tests, if I console log the parameter given to `findOne.$.subscribe`'s callback, it has `_data._deleted: true`.

I'll try to creating a test in my codebase as simple as the PR I created here.

**Comment by adam-lynch** [comment]
*Argh...*

I set up a new repo with a minimal reproduction with Cypress and spent ages debugging because it actually worked fine. It looks like it comes down to the rxdb version. When I originally created this issue, I tested 14.11.1 and also tried updating to 14.14.1. I think there was some kind of caching or something, and that I was actually still running 14.11.1.

Sorry about this

**Comment by pubkey** [comment]
No problem.
