### ISSUE TITLE
ANNOUNCEMENT:  version 3.0.0

### ISSUE THREAD

**Issue by pubkey** [pubkey/rxdb#48]
Hello users.
There are plenty of things I want to add to RxDB which will be breaking features.
Therefore I have the big goal to finish version 3.0.0 which will contain all of them at once so that the dev will not have to migrate all the time.
The goal is to finish it until March2017.

You can see the milestone [here](https://github.com/pubkey/rxdb/blob/master/MILESTONES.md).
If you have an additional feature you want to see at v3.0.0, please write it down here.

Any help is appreciated! If you have the time to help with one of the features, please tell me so I can coordinate the work.

**Comment by jayem-io** [comment]
Can we have the ability to create indexes at levels other than the top level.

**Comment by pubkey** [comment]
@jayem-io Yes, you can. I'm sitting at it right now

**Comment by jayem-io** [comment]
Can you explain how please?

**Comment by pubkey** [comment]
@jayem-io  see [this commit](https://github.com/pubkey/rxdb/commit/36f91f18c6350e32508ad52a8e67caa058371254)

**Comment by jayem-io** [comment]
Fantastic I'll test it out

**Comment by Itrulia** [comment]
TTL on entries would be really nice :)

**Comment by pubkey** [comment]
@Itrulia TTL on documents is a nice feature. But on v3 I want to focus on things which would create breaking changes in the future.

**Comment by Itrulia** [comment]
Damn, I guess Ill write a PouchDB plugin for it then (if thats even possible)

**Comment by pubkey** [comment]
A few seconds ago, RxDB v3.0.0 got released.
