### ISSUE TITLE
AJV schema validation doesn't validate minimum / maximum for numbers

### ISSUE THREAD

**Issue by adam-lynch** [pubkey/rxdb#4821]
AJV schema validation doesn't validate minimum / maximum for numbers. It does error if you give a string for example, but it doesn't check if the number is greater than or equal to the minimum and less than or equal to the maximum defined in the schema.

**Comment by pubkey** [comment]
Hi adam.
This looks like a AJV bug, not a RxDB bug. Can you make an example?

**Comment by adam-lynch** [comment]
Test: https://github.com/pubkey/rxdb/pull/4842

**Comment by pubkey** [comment]
Your test is using bulkInsert. Calling this will not throw, it will return a error object "per document".
From [the docs](https://rxdb.info/rx-collection.html#bulkinsert):

> NOTICE: bulkInsert will not fail on update conflicts and you cannot expect that on failure the other documents are not inserted.

**Comment by adam-lynch** [comment]
Yep that's it, my bad. In my codebase I was wrapping the call and got mixed up.

**Comment by adam-lynch** [comment]
`bulkUpsert` returns `RxDocument[]`. Should it throw if there's a validation error?

**Comment by pubkey** [comment]
@adam-lynch You found something. The current api is wrong, `bulkUpsert` should behave equal to the other bulk methods.
But this would be a breaking change, I will add it to the todo list for the next major release.

**Comment by adam-lynch** [comment]
Thanks
