### ISSUE TITLE
doc issues

### ISSUE THREAD

**Issue by chrisdrackett** [pubkey/rxdb#4826]
I was going to fix this myself, but I got a bit confused so I decided to open an issue (I'm new to v14)

In the docs TOC the listed function under `RxDocument` include `incrementalModify` and `incrementalPatch`. However the docs themselves only include `modify` and `patch`. The code seems to include both things. I assume that having both is correct, but wanted to touch base before making a pull request.

**Comment by pubkey** [comment]
Yes, both exist. All modifying RxDocument function can be called either incremental or "normal".
