### ISSUE TITLE
question: Possibility to completly destroy documents

### ISSUE THREAD

**Issue by EinfachHans** [pubkey/rxdb#4830]
Is is possible to compltly destory single Documents somehow? 🤔

Imagine the following Situations: A User logs in for the first time, initial syncs the database and the backend returns only the data that a user is allowed to see. Let's say is allowed so see Products A, B and C. User goes offline, and the permission to see Product B is removed in the same time. When the User goes online again and syncs with the database the Product B and everything related to it should be removed from the device completly (for legal reasons).

The deletion itself i guess is not able to check in the sync itself, because on the product itself no change was done and if i understand correctly only the chanegs are synced (via the checkpoint). So my idea was after the sync, check the permissions, go through the database manually and remove products that the user has no permission to. BUt i didn't find a documented way to do excatly this.

**Comment by pubkey** [comment]
There is no exact way for permission handling in distributed systems.

Directly purgin a document is not possible with RxDB and I do not think I ever want to support that. As a workarround you could do a normal delete on the document and then call the `.cleanup()` manually with a very low `minimumDeletedTime`.
