### ISSUE TITLE
compiler errror: Strict mode

### ISSUE THREAD

**Issue by NicoRademacher** [pubkey/rxdb#4832]
Hello,
we are using Strict: false in our Angular application. However, this leads to many compiler errors in the rxDb modules. For example: Property 'changed' does not exist on type 'EventReduceResult<any>'.
We would like to keep strict: false. Is there a way to fix this issue on your side or find a workaround?

Best regards

**Comment by EinfachHans** [comment]
Same problem for me. Any solution for this?

**Comment by EinfachHans** [comment]
The problem in our case seems to be that we acidently imported a type declaration from the "src" folder. Does it make sense that the complete src ts files are included in the final build package?

**Comment by pubkey** [comment]
Please reproduce the problem in the rxdb angular example which is CI testsed.

**Comment by pubkey** [comment]
Closing this. Please reproduce in the angular example so I can fix it.
