### ISSUE TITLE
Replication does not trigger `postSave`, `posInsert` and `postRemove`

### ISSUE THREAD

**Issue by leandrogehlen** [pubkey/rxdb#4866]
I have built an extension to handle full text search, but when changes are made on the server side, these changes must be replicated in the index.

The hooks `postSave`, `postInsert`, and `postRemove` must be triggered to apply the changes into the indexes.
Another solution is to create a hook: `postBulkWrite`, where it is possible to identify the changes for each document.

**Comment by pubkey** [comment]
Hi @leandrogehlen 
This is intentional. The pre and post hooks only run on user-called RxDB functions. They are not called when an internal thing like replication changes the database state. They are also not called when another browser tab is changing data.

I do not know your exact use case but maybe you should listen to the event stream instead of using the orm hooks.

**Comment by leandrogehlen** [comment]
Hi @pubkey,

Thank you for your response.

I have built the plugin: https://github.com/serenysoft/rxdb-flexsearch.

Currently, this plugin only supports data management on the client side. Unfortunately, updating the full-text index with data managed on the server side is not possible at the moment.

To address this limitation, the only available approach is to create a dedicated replication to handle this situation. 
However, this is not an ideal solution since it requires writing a specific replication for each existing replication currently,
and the rxdb-flexsearch plugin will not be able to cover third party replications.

**Comment by pubkey** [comment]
Hmm. I do not fully understand your use case.
But maybe you should look at the storage-wrapper plugins (like key-compression, validation etc) and build something like that. This allows you wrap all writes to the storage and do additional operations on each write.

**Comment by leandrogehlen** [comment]
Thanks, i will try your suggestion.
