### ISSUE TITLE
Conflict Handler; set assumedMasterState

### ISSUE THREAD

**Issue by NicoRademacher** [pubkey/rxdb#4870]
Hello,

i use your custom conflict handler to handle conflict. That works so far, the problem is that the assumedMasterState isnt set.(next push)

If i used the realMasterState, the backend und client data are equals. How can i set the assumedMasterState manuel?

thanks for helping

best regards nico

**Comment by pubkey** [comment]
Hi @NicoRademacher 
Sorry for the late reply. I do not fully understand from your description.
Is the `assumedMasterState` missing somewhere?
Can you show in a test case what is not working?

**Comment by pubkey** [comment]
Please make a PR with some code to reproduce your problem.
