### ISSUE TITLE
Multiple calls to requestIdlePromise end up in a serial execution

### ISSUE THREAD

**Issue by costingeana** [pubkey/rxdb#4877]
RxDB Version: 14.15.1

Hello,
I just observed the changes applied on the `requestIdlePromise` function ( #4813 ) have some undesired effects. I'll explain below.

The previous version of `requestIdlePromise` returned a new `Promise` for each function's call; in this case, the consumer's code would wait only for the resolving of this sole `Promise`.

On the other hand, the current version returns indeed a new `Promise` for each `requestIdlePromise` function's call, BUT the consumer's code will have to wait for the resolving of the **entire Promise's chain** because the `requestIdlePromise` function returns the `idlePromiseQueue` itself. 
This ends up being similar to a serial execution, and the effect is the degradation of the performance in certain scenarios.

For example, I created 100 RxDB databases, and then I dispose them (dbInstance.remove()). Before the changes from #4813 (i.e. version = 14.14.1) the time spent to dispose all the databases was T. Now, after these changes (i.e. version >= 14.14.2) the time is about 10 x T.

IMHO, the previous implementation of the idle promises' queue was correct, so I altered it below to include the fix for the initial problem, namely the one related to the `requestIdleCallback`:

```
/**
 * If multiple operations wait for an requestIdlePromise
 * we do not want them to resolve all at the same time.
 * So we have to queue the calls.
 */
var idlePromiseQueue = PROMISE_RESOLVE_VOID;
export function requestIdlePromise(timeout = undefined) {
  return new Promise(res => {
    idlePromiseQueue = idlePromiseQueue.then(() => {
      /**
       * Do not use window.requestIdleCallback
       * because some javascript runtimes like react-native,
       * do not have a window object, but still have a global
       * requestIdleCallback function.
       * @link https://github.com/pubkey/rxdb/issues/4804
       */
      if (typeof requestIdleCallback === 'function') {
        requestIdleCallback(() => res(), {
          timeout
        });
      } else {
        promiseWait(timeout).then(res)
      }
    });
  });
}
```
Thank you.

_Originally posted by @costingeana in https://github.com/pubkey/rxdb/issues/4804#issuecomment-1673461967_

**Comment by pubkey** [comment]
I am not sure if I understood it correctly.
The returned `idlePromiseQueue` object each time is not the same on each function call because it will be reasinged with `idlePromiseQueue = idlePromiseQueue.then...`

From the code docs
```js
/**
 * If multiple operations wait for an requestIdlePromise
 * we do not want them to resolve all at the same time.
 * So we have to queue the calls.
 */
```

So I think what you describe is actually the intended behavior. Can you add a test to your PR which shows the difference in behavior and ensures that in the future noone will break the correct behavior.

**Comment by pubkey** [comment]
Yes, the behavior of your `requestIdlePromiseSlow` is correct, let me explain.
`requestIdlePromise` is used in RxDB for background task. Using `requestIdlePromiseSlow` ensures that background tasks are way less likely to affect actual  user usage of the main thread.

When multiple parts of RxDB await the next `requestIdlePromise` to run a background tasks, we do not want all background tasks to start directly on the next `requestIdlePromise`. Because that would increase the likelyness of affecting user interactions. Instead we want to start exactly one task and have the others await the next `requestIdleCallback`, so when the main thread is idle again.

The previous behavior was not correct which I detected on fixing the other bug. So it was changed in the last version.


Maybe it is questionalbe if `requestIdlePromise` should be awaited on `RxDatabase.remove()`

**Comment by costingeana** [comment]
Hello again and sorry for the delay,

I understand perfectly the purpose of `requestIdlePromise` (the one from plugins/utils). However, generally speaking, I'm not very sure that is quite ok to have queued `items` that wait for about 500 ms (when the queue has about 100 active items) or worse 4-5000 ms (when the queue has about 1000 active items) before being resolved. Indeed, this may not be happening in normal scenarios, but it can happen (as it happens in my scenario). 

About my scenario. First of all, I apologize for the confusion. When I saw the degradation of the performance, I quickly checked the published versions (14.14.1 and then 14.14.2) and I saw the changes that you applied for `requestIdlePromise`. Once that I identified those changes are the cause of my problem, my focus turned to the `requestIdlePromise` itself. Moreover, the fact these 2 functions have identical names contributed to my confusion. Once again, I'm sorry for misleading you.

On the other hand, what I observed empirically (that the `requestIdlePromise` changes affected the performance in my scenario) is still true. The `requestIdlePromise` comes into play at another level.
I am using the Loki's storage which uses a save queue, which turns to use the `requestIdlePromise` in its internals: https://github.com/pubkey/rxdb/blob/84035e65602ee20a3c8022127b75608bc64116a7/src/plugins/storage-lokijs/loki-save-queue.ts#L49-L73
So when a `RxDatabase.destory()` is issued, the loki's storage instance is closed, and that's that point where the save queue runs: 
https://github.com/pubkey/rxdb/blob/84035e65602ee20a3c8022127b75608bc64116a7/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L358C26-L358C26

Frankly, at this point, I have no idea what can be done to get rid of the performance degradation when destroying multiple databases. 
In the end I will highlight once again the scenario:
- RxDB Version: 14.15.1;
- RxDB storage: LokiJS with indexeddb adapter (in browser);
- destroy about 100 RxDatabases (this is a real scenario);
- when using RxDB 14.14.1 the time spent to dispose all the databases was T. Now, after these changes (i.e. version >= 14.14.2) the time is about 10 x T.

Thank you.

**Comment by pubkey** [comment]
Ok I understand your point.
This is a really edgy case because most users do not have to close 100s of lokijs RxDatabases.
You can make a PR to add a param to `requestIdlePromise` to "skip" the queue so that we can do an exception for the lokijs storage.

**Comment by costingeana** [comment]
Hello,

I don't think it would be a good idea to use a fork. Maybe we can do something for general availability in lokijs RxStorage. 
Regarding lokijs RxStorage I have a couple of questions. 
Once again, the context is the deletion of a RxDatabase. I observed that lokijs RxStorage instance has 2 methods that are used in this context:
- `close`: https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L344
- `remove`: https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L367
The `remove` function finally calls the `close` function:
https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L373-L374
Both functions issue a call to the LokiSaveQueue's `run` function:
- `close`: https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L358-L359
- `remove`: https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L373-L374

Moreover, the `close` method calls another function, namely `closeLokiCollections`: https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/lokijs-helper.ts#L190-L199
The `closeLokiCollections` also calls the LokiSaveQueue's `run` function.

Practically in a sequence like `remove` -> `close` -> `closeLokiCollections` there are 3 calls to the LokiSaveQueue's `run` function.

The first question: do you think we can do something so that we call the `saveQueue.run()` function only once?
The second question: theoretically speaking, when removing a database and all its data, is still needed to call the `saveQueue.run()` function?

In the end, I have a question regarding the LokiSaveQueue's `run` function. I don't fully understand the following code sequence: https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/loki-save-queue.ts#L51-L73
Is the second call to the `requestIdlePromise` function really needed?
https://github.com/pubkey/rxdb/blob/f816c2a2146c905fab3f5ab23d7e164d004da40a/src/plugins/storage-lokijs/loki-save-queue.ts#L69-L73

Thank you.

**Comment by pubkey** [comment]
> Is the second call to the requestIdlePromise function really useful?

No, likely not. But I did many tests back then to ensure it is not possible to lose memory-persisted data when having multiple browser tabs open. I do not want to touch that code without proper testing it again.
