### ISSUE TITLE
ability to use web-worker from Vite 

### ISSUE THREAD

**Issue by ahoyahoy** [pubkey/rxdb#4925]
I'm not sure why:
"The worker.js must be a self containing JavaScript file that contains all dependencies in a bundle."

It would be great if I could use the WebWorker in the getRxStorageSharedWorker which I get from the Vite bundler,.
instead of just a path to a ready-made web worker.
`import MyWorker from './worker?worker'`
https://vitejs.dev/guide/features.html#import-with-query-suffixes

I can't try it because (probably) it's not possible to use the whole WebWorker class instead of the url string?

I also found out that there are other workers in the package than in the documentation. There is no shared-idb worker, loki worker. JFYI

**Comment by pubkey** [comment]
This should just work out of the box. Whatever you give rxdb, it will call `new Worker(whatever)` on it.
I do not use Vite, so I can cannot help here any more.

**Comment by ahoyahoy** [comment]
yes, but whatever is url string (or base64), not also `options` object.
So I can't use worker like this `new Worker("/rx-worker.ts?type=module&worker_file",{type: "module"})`, because default type in options is `classic`.
Which is completely fine after production build, where I get compiled .js file, but not in development phase when I want to load the module.

**Comment by pubkey** [comment]
Ah I see. I will add the option to set `type: "module"`

**Comment by pubkey** [comment]
I added this to the next version. Release will come today or tomorrow.

**Comment by ahoyahoy** [comment]
nice, thanks :)
