### ISSUE TITLE
.get() doesn't work for field defined via definitions

### ISSUE THREAD

**Issue by adam-lynch** [pubkey/rxdb#4926]
I'm not sure this is a bug or not. I'm not sure if what I'm trying to do is supported.

I've defined a field in the schema like this:

```
tags: {
  type: 'object',
  additionalProperties: {
    $ref: '#/definitions/tag',
  },
},
```

And in the schema (on the same level as `properties`), I have:

```
definitions: {
  tag: {
    properties: {
      created: {
        type: 'integer',
      },
      name: {
        type: 'string',
      },
    },
    required: ['created', 'name'],
  },
},
```

If I fetch an `RxDocument` and do `rxDocument.toJSON().tags`, it's as expected. But if I do `rxDocument.get('tags')` or `rxDocument.tags`, I get the schema mixed in the result (e.g. `tags.additionalProperties` exists).

I have created a pull-request to show this behaviour: #4927

**Comment by pubkey** [comment]
Using $ref to reference other schemas is not possible. This is intentional. Parsing the $refs is big burden which would slow down initial page load and database creation time.


Also it is [not clear](https://json-schema.org/understanding-json-schema/structuring.html#base-uri) for a frontend code on how to find the other json schemas that are references. In node.js you would ask the filesystem but in the browser you would have to do more http-requests.

> A schema can reference another schema using the $ref keyword. The value of $ref is a URI-reference that is resolved against the schema’s [Base URI](https://json-schema.org/understanding-json-schema/structuring.html#base-uri).


I recommend to normalize the $ref schemas at build time, not at runtime. There are multiple npm packages that do that for you.

**Comment by adam-lynch** [comment]
The only reason I did this was because our existing data contains an object with unknown keys, each with an object as a value matching:

```
    {
      created: {
        type: 'integer',
      },
      name: {
        type: 'string',
      },
    }
```

Could you please confirm whether it's possible or not to achieve this in RxDB?

According to ChatGPT, I could do this with JSONSchema...

```
{
  "type": "object",
  "additionalProperties": {
    "type": "object",
    "properties": {
      created: {
        type: 'integer',
      },
      name: {
        type: 'string',
      }
    },
  }
}
```

...but I think RxDB doesn't support using `additionalProperties` like this

**Comment by pubkey** [comment]
I do not fully understand the use case.
RxDB only takes the fields from the properties object. `additionalProperties` has boolean values, not an object.
All fields are optional by default, so couldnt you just define the "created" and "name" field like normal and not having it required?

**Comment by adam-lynch** [comment]
@pubkey OK I'll clarify. Our data can contain this:

```javascript
{
  // ...
  tags: {
    example1: {
      created: 23432342,
      name: 'example1',
    },
    example2: {
      created: 23432342,
      name: 'example2',
    },
  },
  // ...
}
```

Or...

```javascript
{
  // ...
  tags: {
    crazyNameAUserGave: {
      created: 23432342,
      name: 'crazyNameAUserGave',
    },
  }
  // ...
}
```

`tags`' keys are unknown. They are user-generated. However, each value always matches this (JSONSchema):

```
{
  type: 'object',
  properties: {
    created: { type: 'number' },
    name: { type: 'string' },
  },
  required: ['created', 'name'],
}
```

I originally used `$ref` because I couldn't find another way to do it. Could you please confirm whether it's possible or not to define a schema which describes an object like this?

**Comment by pubkey** [comment]
Ok I understand your use case now.

It is possible to define this in jsonschema and make the RxDB schema validators correctly validate this document type.
BUT it is not possible to access the document properties like that because RxDB iterates over the **known** properties and only reflects them.
The only way to make this possible would be by switching from having a static constructor to using the Proxy API. But my tests have shown that the proxy API has a siginificant worse performance. It would slow down each property access of the RxDocuments.

**Comment by adam-lynch** [comment]
Okay thank you, got it

**Comment by adam-lynch** [comment]
Wait... I understand, I have to use `toJson().tags` and not `.get('tags')`, but...

> It is possible to define this in jsonschema and make the RxDB schema validators correctly validate this document type.

How would you define it then? (`tags`)

Is my original `$ref` approach ok or is there is a proper way to define an object like this?

**Comment by pubkey** [comment]
No, `$ref` schemas will not be resolved by RxDB, you cannot use them.

Maybe having the schema in `additonalProperties` [works](https://www.liquid-technologies.com/Reference/XmlStudio/JsonSchemaEditor_Property_AdditionalProperties.html), but I never did this myself. 
Also RxDB sets `additonalProperties: false` on the top level to prevent naming clashes. So this should be done in a nested property.

**Comment by adam-lynch** [comment]
Got it.

Just to be super clear in case someone reads this later. I should be able to use the `additonalProperties` approach on `tags` because `tags` is a root-level key. Tags is not the collection; I don't want `additionalProperties: ...` at the top-level of the collection's properties. E.g. an item in the collection would look like `{ tags: { example: { ... } } }` not `{ example: { ... } }`. I looked at the source code to confirm this.

**Comment by adam-lynch** [comment]
I've tried a few approaches and nothing works.  

## Using `additionalProperties: { ... }`

See https://github.com/pubkey/rxdb/pull/4950

## Using `patternProperties`

This fails schema validation; see https://github.com/pubkey/rxdb/pull/4951.

## Using `additionalProperties: true`

I thought... okay, it's not great but I'll accept having a schemaless `tags` object if I need to, but no that doesn't work either. See https://github.com/pubkey/rxdb/issues/4948 and https://github.com/pubkey/rxdb/pull/4949. This one seems like a real bug rather than just lack of support.

---

@pubkey can you please tell me categorically whether or not I can have an child object in RxDB like my `tags` object?

I don't even know how to truly test if something works. My `$ref` approach worked better than those above to me 🤷

**Comment by adam-lynch** [comment]
We're still stuck not being able to define our schema. Is there anything that can be done?
