### ISSUE TITLE
[Suggest] Better way to handle malformatted reversion other than throw without additional info

### ISSUE THREAD

**Issue by snowwolfjay** [pubkey/rxdb#4931]
src/plugins/utils/utils-revision.ts
```
export function parseRevision(revision: string): { height: number; hash: string; } {
    const split = revision.split('-');
    if (split.length !== 2) {
        throw new Error('malformated revision: ' + revision);
    }
```

This file checked the rev format, but just throw it, I think this is **disobey the offline first design** , the rev malformat should be a conflict like case, and user or developer should beable to gracefully handle it, not like curently - **always see the error and can do nothing**

**Comment by snowwolfjay** [comment]
so i hope there is a way to handle this error, like a configuration's revResolve handler or policy like 'ignoreAndDropDocument' 'ignoreLengthNotMatch'

**Comment by pubkey** [comment]
> This file checked the rev format, but just throw it, I think this is disobey the offline first design , the rev malformat should be a conflict like case, and user or developer should beable to gracefully handle it, not like curently - always see the error and can do nothing

No I do not think so. Also the revision parsing is done in a hot path very very often, so performance is critical here. I will not add a conflict handling here. RxDB requires all stored documents to have correct revisions and I see no way why this should not be the case.
