### ISSUE TITLE
Upsert Document with Attacment

### ISSUE THREAD

**Issue by yahyavi** [pubkey/rxdb#494]
## Case
Feature Request (didn't find any info on it in the documents)

## Issue
I am looking for a way to upsert or atomicUpsert a document with an attachment in one go. 
From my understanding right now I have to save a document and then do a put attachment (which is not atomic) and can potentially cause issues.

## Info
  - Environment: browser
  - Adapter: IndexedDB/Localstorage
  - Stack: Typescript,  React

## Code
I am looking for something like this:

```js
const fileAttachment = {
    id,     // string, name of the attachment like 'cat.jpg'
    data,   // (string|Blob|Buffer) data of the attachment
    type    // (string) type of the attachment-data like 'image/jpeg'
}
const docData = {
    name: 'Bob', // primary
    lastName: 'Kelso',
    attachment: fileAttachment,
};

myCollection.upsert(docData);
or 
myCollection.atomicUpsert(docData);
```

**Comment by pubkey** [comment]
Hi @yahyavi 
There is currently no way to do this with rxdb. You could of course use the underlaying pouchdb as workarround. Of course it would be nice if this was possible directly with rxdb.
I will not have time in the near future to implement this.
Do you have the time to create a PR?

**Comment by yahyavi** [comment]
Hi @pubkey,
I will try to have a look but right now I am running into a bug and I cannot create DBs anymore. Will open a separate issue here with a minimal repo to replicate.

**Comment by pubkey** [comment]
I'm closing this because I do not think someone will implement it.
I added the feature-request to the backlog.
