### ISSUE TITLE
winningRev is not a function Error

### ISSUE THREAD

**Issue by yahyavi** [pubkey/rxdb#499]
## Case
Bug (not sure RxDB or PouchDB issue). Using RxDB 7.3.2.
Also reported here: [pouchdb#7054](https://github.com/pouchdb/pouchdb/issues/7054)

## Issue
Getting Errors:
`Uncaught TypeError: winningRev is not a function`
and 
`Database has a global failure DOMException: Uncaught exception in event handler.`

![screen shot 2018-01-29 at 7 51 02 pm](https://user-images.githubusercontent.com/1531957/35547866-9fec8c72-0530-11e8-94e6-fbead5622e2a.png)

## Info
  - Environment: browser
  - Adapter: Tried with both IndexedDB and WebSQL
  - Stack: TypeScript

## Code
There is a minimal repository available here:
https://github.com/yahyavi/simple_rxdb

Just do:
```
npm install
npm run build
```
open the localhost in the browser.

**Comment by pubkey** [comment]
Hi @yahyavi 
I investigated into this yesterday.
As far as I can tell this is a webpack+pouchdb-problem. Maybe webpack tree-shakes the `winningRev` function await.
For the moment you can downgrade to `pouchdb-adapter-idb: "6.4.1"`.
If you do not use webpack, please tell me because then we can maybe fix this.

**Comment by yahyavi** [comment]
Hi @pubkey 
I am indeed using webpack and forcing to use `pouchdb-adapter-idb: "6.4.1"` did do the trick. I guess this is a pouchdb issue. 
Thanks!

**Comment by pubkey** [comment]
This is fixed now with the latest pouchdb-release.

**Comment by yahyavi** [comment]
So I upgraded the `pouchdb-adapter-idb` to 6.4.3 and everything seems to be working in my setup. 
`RxDB 7.3.2` is still installing `pouchdb 6.4.2` but I guess that should be fine unless it causes problems in other setups.
