### ISSUE TITLE
weird behaviour i cannot summarize better

### ISSUE THREAD

**Issue by jappyjan** [pubkey/rxdb#4999]
I am trying to use the firestore replication plugin.

This allways fails on the start of the replication with the following error / stack trace:

```
:5173/#!/battery_manufacturers:1 Uncaught (in promise) FirebaseError: Expected type 'vh', but it was: a custom Firestore object
Promise.then (async)
startReplicationOnLeaderShip @ index.ts:495
replicateFirestore @ index.ts:371
initReplicationOfOneCollection @ index.ts:26
initReplication @ index.ts:78
(anonymous) @ index.ts:84
(anonymous) @ index.ts:97
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
commitRootImpl @ react-dom.development.js:26935
commitRoot @ react-dom.development.js:26682
performSyncWorkOnRoot @ react-dom.development.js:26117
flushSyncCallbacks @ react-dom.development.js:12042
(anonymous) @ react-dom.development.js:25651
```

when i tried to debug this,
i wanted to add some logs to the library to better understand the issue, 
so i cloned the repo locally,
checked out tag 14.17.1,
installed npm modules
build using "npm run build"
linked using npm link
and then linked the module to my project.

fun fact. now it just works...

and this is reproducible for me...
whenever i use my locally compiled version it works,
whenever i use the downloaded node_module it throws the above error...

i am completely out of clues by now...

**Comment by pubkey** [comment]
I do not think I can help with the given informaiton. Without a reproduction, I have no clue. Maybe you have different versions installed? Check the package.json in the node_modules folder.
