### ISSUE TITLE
RxCollection's usage takes ~1min to resolve type

### ISSUE THREAD

**Issue by Banou26** [pubkey/rxdb#5023]
Following https://rxdb.info/tutorials/typescript.html and defining a simple schema, e.g
```ts
const testSchemaLiteral = {
  title: 'Test schema',
  description: 'Describes a test',
  version: 0,
  primaryKey: 'foo',
  type: 'object',
  properties: {
    foo: {
      type: 'string',
      maxLength: 255
    },
    bar: { type: 'string' },
  },
  required: ['foo']
} as const

const schemaTyped = toTypedRxJsonSchema(testSchemaLiteral)

export type TestDocument = ExtractDocumentTypeFromTypedRxJsonSchema<typeof schemaTyped>

export type TestMethods = {
  _: undefined
}

export type TestCollectionMethods = {
  __: undefined
}

export const testSchema: RxJsonSchema<TestDocType> = testSchemaLiteral

export type Collection = RxCollection<TestDocument>

// const foo: Collection = {}
// foo.                // THIS TAKES ~1 minute to resolve
```
pretty much renders typescript unuseable as any type trying to resolve takes more than a minute to do so

Removing `RxCollection<TestDocument>` fixes the issue

Using `"typescript": "^5.2.2"` & `"rxdb": "^14.17.1"`

Here's a repro, the related line showcase the issue, on vscode init/file change, the types take a minute or so to resolve: https://github.com/Banou26/rxdb-issue-5023/blob/main/src/collection.ts#L43C1-L43C37

Edit: For some reason, sometimes it bugs out typescript and sometimes not, trying to figure out what's the cause and how to get a consistent bug

**Comment by Banou26** [comment]
The issue only seems to happen when used in my vscode workspace with other projects. In a standalone project window it seems to work fine.

**Comment by pubkey** [comment]
When you clone the RxDB repo and open it in your editor, do you have the same problem?

**Comment by Banou26** [comment]
Yes, here's an example of the issue happening, it takes vscode from 0:40 to 2:04 to resolve the typings.
I've tried using multiple typescript versions, always result in the same issue of really long resolve times.

https://github.com/pubkey/rxdb/assets/5209149/7c8d0276-093f-4f3e-8e29-e51c810810bc

**Comment by pubkey** [comment]
Can you disable all other vscode plugins and check again?

**Comment by Banou26** [comment]
Tried running my vscode with all extensions disabled using `code --disable-extensions`, didn't seem to fix anything

I tried looking into TSC profiling(https://github.com/microsoft/TypeScript/wiki/Performance-Tracing)

I somehow did not manage to get anything weird looking on the repro, but on the real project, for the equivalent file of `main.tsx`, I've gotten the profiler to get stuck for 8s on it

![image](https://github.com/pubkey/rxdb/assets/5209149/59940b9e-3a89-49ea-a64a-2e0fe7b20a0c)

Trying to get more info on what's the actual cause, this doesn't really help much, but proves that the problem isn't coming from vscode itself but more TSC / the `as-typed` package.

**Comment by Banou26** [comment]
I ended up not using not using `toTypedRxJsonSchema` and simply defining my own typings, which doesn't cause the typescript resolving issue.

Not sure if you'd like to keep this issue open until potentially moving out of `as-typed` or not.

**Comment by Banou26** [comment]
Tried removing the `toTypedRxJsonSchema` & `ExtractDocumentTypeFromTypedRxJsonSchema` calls by making my own typings manually, but the same issue happen from the moment i wrap it around a `RxDocument`

**Comment by Banou26** [comment]
I'm starting to think that the issue might actually be caused by `rxdb-hooks`, when used with already made out `RxDocument`, it wraps those out in another `RxDocument` which might be causing the issue.

**Comment by pianomansam** [comment]
I also started experiencing this. It started when I upgraded to RxDB 14 and when using rxdb-hooks. With the help of this issue, I traced it to when passing a `RxDocument` type again to `RxDocument`.
