### ISSUE TITLE
Error on insert/update document with array properties

### ISSUE THREAD

**Issue by leandrogehlen** [pubkey/rxdb#5040]
An error is raised when insert or update a document that schema has array properties:
Example: 

```ts
export const contactSchema = {
  version: 0,
  description: "Contact schema",
  primaryKey: "id",
  type: "object",
  properties: {
    id: {
      type: "string",
      maxLength: 100
    },
    name: {
      type: "string"
    },
    company_name: {
      type: "string"
    },
    emails: {
      type: 'array',
      items: {
        type: 'string',
      },
    },
  }
}
```
Error: 
`
native.js:24 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': [object Array] could not be cloned.
    at Object.postMessage (webpack-internal:///./node_modules/broadcast-channel/dist/esbrowser/methods/native.js:37:21)
    at eval (webpack-internal:///./node_modules/broadcast-channel/dist/esbrowser/broadcast-channel.js:197:47)
`

Example repo:
https://github.com/leandrogehlen/ionic-vue-rxdb

**Comment by pubkey** [comment]
The problem seems to be that vue is changing your array into a way so that it cannot be JSON.stringif-fied anymore.

**Comment by leandrogehlen** [comment]
I disagree seems something related to https://pubkey.github.io/broadcast-channel/

**Comment by leandrogehlen** [comment]
@pubkey, you are rigth.
i have created a repo using angular and the error do not occur

**Comment by pubkey** [comment]
Some people have reported that before, I think the rxdb dev-mode should check for that before inserts and then throw a more helpful error.

**Comment by leandrogehlen** [comment]
In the Angular project, I changed the storage from Dexie to memory, and as a result, it was working. However, when I changed the storage in the Vue project, the error stopped occurring.

**Comment by leandrogehlen** [comment]
In production, the error not ocur.

**Comment by leandrogehlen** [comment]
https://github.com/pubkey/rxdb/issues/5046#issuecomment-1742164866
