### ISSUE TITLE
IndexedDB premium storage does not allow storing array properties

### ISSUE THREAD

**Issue by leandrogehlen** [pubkey/rxdb#5046]
Using `getRxStorageIndexedDB` when the schema has array properties on insert/update a document  the error bellow is raised:

`
indexeddb-storage-instance.js:1 Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': [object Array] could not be cloned.
    at l.bulkWrite (webpack-internal:///./node_modules/rxdb-premium/dist/es/plugins/storage-indexeddb/indexeddb-storage-instance.js:19:1349)
    at async RxCollectionBase.bulkInsert (webpack-internal:///./node_modules/rxdb/dist/es/rx-collection.js:180:19)
    at async RxCollectionBase.insert (webpack-internal:///./node_modules/rxdb/dist/es/rx-collection.js:145:23)
    at async onSaveClick (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-41.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/PageForm.vue?vue&type=script&setup=true&lang=ts:46:11)
`

Using `getRxStorageDexie()` works fine

Example repo:
https://github.com/leandrogehlen/ionic-vue-rxdb/tree/storage-indexeddb

**Comment by pubkey** [comment]
Related: https://github.com/localForage/localForage/issues/610

You can only store plain JSON data in RxDB. RxDB does not json-parse because the performance would decrease.
I will add a dev-mode check to give a better error message.

**Comment by leandrogehlen** [comment]
I don't understand
The the object bellow is not consider a plain object?: 
```ts 
database.collectitons.contact.insert({
  id:  'abacdef'
  name: 'Leandro',
  emails: [
    'leandrogehlen@gmail.com'
  ]
})
```

Following the reference [Plain Objects](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules__types_jquery_misc_d_.jquery.plainobject.html#:~:text=The%20plain%20object%20is%2C%20in,typeof%20value%20of%20%22object.%22) the object above is a plain object.

**Comment by pubkey** [comment]
Can you make a PR with a test case?

**Comment by leandrogehlen** [comment]
I found this test in the [RxDB repository](https://github.com/pubkey/rxdb/blob/master/test/unit/rx-document.test.ts#L930), and I believe that this test is not being executed using IndexedDB storage.

**Comment by pubkey** [comment]
![Screenshot from 2023-10-01 19-47-42](https://github.com/pubkey/rxdb/assets/8926560/6ecdfe36-a559-4926-874e-ca840d3e8e1d)

**Comment by leandrogehlen** [comment]
I found the problem.
I was using [ref](https://vuejs.org/api/reactivity-core.html#ref) that makes a [proxy object](https://vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue).
To solve it is necessary use  [toRaw](https://vuejs.org/api/reactivity-advanced.html#toraw) before store the object in rxdb

**Comment by pubkey** [comment]
@lavaxun Thank you for reporting. I am working on a fix: https://github.com/pubkey/rxdb/pull/5321
