### ISSUE TITLE
Better DX around RxDatabase and collection creation

### ISSUE THREAD

**Issue by ianengelbrecht** [pubkey/rxdb#5135]
I'm busy working on documentation updates for RxDatabase, and trying things out with rxdb inside a small sveltekit app to do so. Refering back to issue [#4578](https://github.com/pubkey/rxdb/issues/4578) and PR [#4549](https://github.com/pubkey/rxdb/pull/4549), I get the error that the database with the same name and storage cannot be created twice, and the problem of the differing schemas with RxDatabase.addCollections. I think it would be good to either improve these APIs to provide a smoother developer experience, or provide guidelines in the documentation for evolving a schema during development without getting these problems. 

I have the RxDatabase defined in its own module as follows:
```
//db.js

import { createRxDatabase } from 'rxdb';
import { addRxPlugin } from 'rxdb';
import { RxDBDevModePlugin } from 'rxdb/plugins/dev-mode';
import { getRxStorageDexie } from 'rxdb/plugins/storage-dexie';
import { RxDBMigrationPlugin } from 'rxdb/plugins/migration';

addRxPlugin(RxDBDevModePlugin);
addRxPlugin(RxDBMigrationPlugin);

const db = await createRxDatabase({
  name: 'rxdb-tryout',
  storage: getRxStorageDexie()
});

const locationSchema = { /*schema stuff here */ }

await db.addCollections({
  locations: {
    schema: locationSchema, 
    migrationStrategies: { /* migration functions here */ }
  }
});

export default db
```

I then import `db` into svelte components to test things out there (adding/deleting records, etc)

The first DX problem is that any time I make a change in this file Vite reloads just this file with HMR and I get the error about duplicating the RxDatabase. If I reload/refresh the page I don't get this error.  It would be better to be able to edit this file and have HMR working without throwing the error. I'm not sure how to solve it though, given the fact that dexie doesn't provide the necessary cache as you indicated. 

The other DX problem is the conflicting schemas error that is thrown if you change a schema and don't change the schema version and provide a migration function. My understanding is that one of the main benefits of NoSQL databases is to be able to evolve the schema quickly and easily while developing, or even have no schema at all and just save what you get. It would be nice to be able to do this while developing with rxdb without having to change the schema version for each schema change, and have the migration functions piling up at the same time. 

Please let me know your thoughts on this, and the direction you would like to see rxdb go in this regard. I can tackle the code and documentation accordingly.

**Comment by pubkey** [comment]
> I'm not sure how to solve it though, given the fact that dexie doesn't provide the necessary cache as you indicated.

I also have no idea how to fix that. I heard about the same problem for people with react.

> My understanding is that one of the main benefits of NoSQL databases is to be able to evolve the schema quickly and easily while developing

RxDB does explicitly not support non-schema collections, like other NoSQL databases do. Mostly because client-side database state is way more complex because many devices can run different versions of the application and fixing broken state is up to impossible. RxDB requires every piece of data to have a schema.

During development, when you change the schema you should not need to set a migration strategy. Instead you should just drop the local state in the browser devtools.
In chrome it is: DevTools -> Application -> Storage -> "Clear site data"

Maybe this should be better pointed out in the docs.

**Comment by ianengelbrecht** [comment]
Okay I'm going to close this and work on some ideas to get around these issues. Will send PR soon.
