### ISSUE TITLE
how to keep db connected

### ISSUE THREAD

**Issue by ahoyahoy** [pubkey/rxdb#5138]
I'm getting this error after longer (or shorter) inactivity my app. After trying save or read from db.
`Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

I'm running db in service worker.

I don't know if it is my bug, rxdb bug or expected behavior.
I couldn't find any info about it.

```
rx-storage-remote.ts:220  Uncaught (in promise) Error: could not requestRemote: {
    "methodName": "findDocumentsById",
    "params": [
        [
            "f8c487c0-40e2-11ee-8b6f-55ac604eee9c"
        ],
        false
    ],
    "error": {
        "name": "InvalidStateError",
        "message": "Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.",
        "code": 11,
        "stack": "Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. \n     at https://scotty4.local:8080/indexeddb.worker.js:1:78488 \n     at async Object.next (https://scotty4.local:8080/indexeddb.worker.js:1:87306)"
    }
}
```

**Comment by pubkey** [comment]
@ahoyahoy 
Is this with the dexie storage or the indexeddb storage?

I do not see any reason why the indexeddb could be closing. Does this also happen when you only have one single browser tab open?

**Comment by pubkey** [comment]
Closing this. I do not think I can reproduce or fix this with the given information. Please ping me when you find a way to reproduce the problem.
