### ISSUE TITLE
Issue with importing dev-module in react for rxdb

### ISSUE THREAD

**Issue by Vani03Dev** [pubkey/rxdb#5182]
#Steps followed:
  -installed rxdb & pouchdb-adapter-idb library using npm.
  -Created database repo and add index.js file
 -Setup database connection below code.
    
`import { addRxPlugin, createRxDatabase } from 'rxdb';
import { RxDBDevModePlugin } from 'rxdb/plugins/dev-mode';

addRxPlugin(RxDBDevModePlugin)

// eslint-disable-next-line import/no-extraneous-dependencies
addRxPlugin(require('pouchdb-adapter-idb'));

// Initialize RxDB and create a database
export default async function initDatabase() {
  if (process.env.NODE_ENV !== 'production') {
    const db = await createRxDatabase({
      name: 'mahalaxmi-dev',
      adapter: 'idb',
    });

    console.log('DatabaseService: created database');
    window.db = db;

    await db.collections({ name: 'todos' })
    return db;
  }

  return ''
}
`

Issue:
  -getting import issue while using dev-mode

**Comment by pubkey** [comment]
Which version are you using?
PouchDB rxstorage was removed a while ago. Please update to latest RxDB and use the Dexiejs RxStorage.

**Comment by Vani03Dev** [comment]
@pubkey Can u share the reference to integrate this with rxdb

**Comment by pubkey** [comment]
Please read the docs https://rxdb.info/quickstart.html
