### ISSUE TITLE
Primary key is required, but I haven't it

### ISSUE THREAD

**Issue by van9petryk** [pubkey/rxdb#5254]
I don't have a primary key. Read in docs, that before 10.0.0 it was optional.
Can update the docs what to do for who don't have primary key for their data?
Should I use this approach
https://www.mongodb.com/docs/v2.2/tutorial/create-an-auto-incrementing-field/
?

Or create uuid field?

**Comment by pubkey** [comment]
RxDB cannot do an auto-increment for performance reasons. RxDB does not have cross-document transactions or guarantees. Also the primary key must be a string, it cannot be a number.
If you do not have a primary key, I recommend filling it with an uuid.
