### ISSUE TITLE
PushModifier applied to pre-change legacy document, resulting in old document sent to endpoint

### ISSUE THREAD

**Issue by alex-hladun** [pubkey/rxdb#5256]
In our project up to Rxdb 13, we have used the pushModifier as a means to control whether a document is sent to the server or not, as [returning null is supposed to skip the document.](https://rxdb.info/replication-graphql.html). However, as of rxdb 13, the pushModifier is run twice, once on the new document, as well as the original document.

Example commit which highlights this issue [is here](https://github.com/pubkey/rxdb/commit/5db08ed990095bef9920adf5d04b3ddf13b3020d). After adding a hero and marking the 'doNotSync' field as true, the [pushModifier is applied to the new document, and then the original document](https://github.com/pubkey/rxdb/blob/316f06508e1998cf9cef9396232608ea9fb1c639/src/plugins/replication/index.ts#L258). 

This results in un-wanted behaviour, as the original document is sent to the server, despite doNotSync being marked as true. 

I see this as a bug, as we have no way to make changes to a local document and **prevent it from being sent to the server.** Any possible solutions would be welcome, as the only fix I can think of right now is to copy the replication plugin and modify that line of code.

**Comment by pubkey** [comment]
Yes I think this a bug, let me fix it.

**Comment by alex-hladun** [comment]
Ok, i think the bug I am refrerring to is still present. Working on a test to reproduce!

**Comment by alex-hladun** [comment]
Fixed in https://github.com/pubkey/rxdb/issues/5256
