### ISSUE TITLE
Docs on storage limits out of date 

### ISSUE THREAD

**Issue by nickchomey** [pubkey/rxdb#5271]
The details here about storage limits and persistence are out of date. https://rxdb.info/downsides-of-offline-first.html#

Here's the current guidelines https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria

And a good article that sparked the overhaul of the guidelines. https://patrickbrosset.com/articles/2023-01-17-web-storage/

**Comment by pubkey** [comment]
Thank you for the hint. fixed here https://github.com/pubkey/rxdb/commit/f23f940a0f4780ed8177e46257733ff843a48eb0
