### ISSUE TITLE
Queries that utilize compound indices without satisfying all keys in the selector can produce false bounds (query returns too many docs)

### ISSUE THREAD

**Issue by eliias** [pubkey/rxdb#5273]
There seems to be a bug in some RxDB storages (IndexedDB, Memory) when a compound index covers more than all fields of a selector (one or more additional fields are present in comparison to the fields used in the query selector). This can lead to situations where the query planner sets the `queryPlan.selectorSatisfiedByIndex` to true, but the bounds (upper/lower) might be wrong (in our case a boolean integer was set to a range between 0-9). When the additional index field is more significant than the actual fields used in the selector, the upper bound is too high, and the number of documents returned is greater than the expected number.

The storage implementations assume that `queryPlan.selectorSatisfiedByIndex=true` implies that the range defined by the bounds includes all valid documents, and skips the `queryMatcher` logic.

I debugged by logging the `endKeys` provided to the `getStartIndexStringFromUpperBound` function, and by checking the resulting string. For the example in this PR, the `endKeys` might look like this:

```
_deleted | exists | hasHighlights | lastOpenedAt
0                1           0                       1600000000000
0                1           9                       1650000000000
```

As you can see, the specificity of the `hasHighlights` key is overruling the otherwise correct upper bound of the timestamp. Therefore, the query returns 2 docs after execution instead of one. The actual problem is that `hasHighlights` is not provided to the selector, therefore the key is set to `min/max`. IMO there is no way this index is going to work without the `hasHighlights` value being provided to the query (selector), and therefore it shouldn't be determined as the best index.

I don't have a fix yet, the most simple one would be to just run the `queryMatcher` every time, but that obviously has some severe cost. I think the right solution would be to not use the index in such cases. That would require a change in the query-planner itself.

I have provided a minimal test case in this PR https://github.com/pubkey/rxdb/pull/5272

**Comment by pubkey** [comment]
Thank you for reporting. I added a fix and some more tests here: https://github.com/pubkey/rxdb/commit/f17feb5a6188c2da009c0a1a7f7ff2212b395ec9

**Comment by pubkey** [comment]
New beta release 31 is running atm, please test.

**Comment by pubkey** [comment]
@eliias For me this is fixed, please ping me if you find any more problems. Also notice there have been some newer v15 beta releases, please test.
