### ISSUE TITLE
$in does not work with array properties in lokijs & sqlite

### ISSUE THREAD

**Issue by lavaxun** [pubkey/rxdb#5320]
# Summary
The `$in` ops is working as expected for memory storage, however it's not for loki storage.
_Edited: The `$in` wasn't work for SQLite as well, but it works in memory storage._ 

After some reading, the lokijs uses `$contains` instead of `$in` for filtering with `array` properties.
`$in` only works for non-array properties in lokijs.
https://github.com/techfort/LokiJS/blob/25b9a33d57509717d43b4da06d92064f2b7a6c95/docs/tutorial-Query%20Examples.html#L138C197-L138C289

# Expected behaviour
The `$in` ops should works for memory storage and loki storage with a unified interface.

# How to reproduce?
1. Clone from a reproducible repo here https://github.com/pubkey/rxdb/compare/master...lavaxun:rxdb:master.
2. run `npm run test:browser:memory` and you will see everything is working.
3. run `npm run test:browser:lokijs` and you will see the unit tests failed.

# Env
1. `nodejs` - v18.18.2
2. `rxdb` - 15.0.0-beta.33

**Comment by pubkey** [comment]
Hi @lavaxun 
I didn't know that. I think we should rewrite the query in the lokijs storage [prepareRxQuery function](https://github.com/pubkey/rxdb/blob/master/src/plugins/storage-lokijs/rx-storage-lokijs.ts#L27)

I do not have the time to fix these lokijs query bugs anymore, which is why I had put the warning in the docs of the loki RxStorage. But a PR is always welcomed.

**Comment by pubkey** [comment]
This should be fixed already. The whole rxdb test suite also runs on the premium plugins as storage.
Can  you make a unit test with the query that does not work?

**Comment by pubkey** [comment]
Can you try without the query-builder plugin?
So instead of the `where()` call, use a "normal" find with a selector.

**Comment by pubkey** [comment]
Also if you add your $in test to the query-correctness tests, I could run it internally with the sqlite storage.
https://github.com/pubkey/rxdb/blob/master/test/unit/rx-storage-query-correctness.test.ts

**Comment by pubkey** [comment]
@lavaxun Your `skills` property is an array by itself. The `$in` operator is not supposed to work like that. https://www.mongodb.com/docs/manual/reference/operator/query/in/

**Comment by pubkey** [comment]
@lavaxun I fixed this in lokijs and SQLite, please test the latest version.
