### ISSUE TITLE
WebRTC Peer Gone issues

### ISSUE THREAD

**Issue by bastiankistner** [pubkey/rxdb#5342]
Hi Daniel,

I've been using v15 since beta 2x or so, primarily due to the promising WebRTC support, for an order processing system. I had some issue until today that I was unable to reproduce or even analyse yet. I figured you've also been working on the `simple-peer` connection handler recently, which I am using (but slightly modified it to get it to work with AWS API Websocket Gateway).

Long story short: I often but randomly experienced errors being thrown while trying to send a message to a peer and the whole sync got stuck (the error originates here: https://github.com/pubkey/rxdb/blob/a45f6bf9fc6d7cbb8790e5bd1befa603cd4c3c6a/src/plugins/replication-webrtc/connection-handler-simple-peer.ts#L238

At first I thought it was my implementation of the signaling server so I reimplemented it. I still had those issues. Then I tried using your new signaling server example. The latter worked fine in the beginning until I refreshed the browser, which led to a new peerId being assigned, while the old one still remained in the room. This seems to cause the issue when sending the messages because all participants still believe there are more peers that have already gone. We also cannot handle this reliably on the server side as it's never absolutely certain that the server's room state reflects the actual situation due to connectivity issues or lost connections.

This case, when a peer isn't available anymore doesn't yet seem to be handled. And when RxDB tries to send a message it get's kinda stuck. Until I refresh the browser that was changing the data. Shortly before it refreshes the page, the updates bubble through to the available peers.

So I tried the following and it seems to work fine:

```ts
if (peer.writable) {
  await (peer as any).send(JSON.stringify(message));
} else {
  error$.next(
    newRxError('RC_WEBRTC_PEER', {
      error: new Error('Peer gone'),
    }),
  );
}
```

I can also open a PR, but I first wanted to let you know and maybe see if this is the right way to handle it.

Thanks a lot! Really looking forward to being able to enjoy a reliable sync and hopefully upgrade to premium when my customers are happy with it.

**Comment by pubkey** [comment]
Released `15.0.0-beta.42` with a fix that reconnects broken peers. Please test.

**Comment by pubkey** [comment]
Sorry I accidentially closed this.

**Comment by pubkey** [comment]
> I could also get an error being thrown here

I need the whole stack trace for that.

It seems to me that this is a problem with the simple peer library.
Maybe you can reproduce the exact behavior with the [quickstart repo](https://github.com/pubkey/rxdb-quickstart).

Are you on the newest chrome version?

**Comment by DanielKucal** [comment]
I'm also experiencing similar issue with very basic setup (one collection, wss://signaling.rxdb.info/ server, Chrome on desktop + Chrome on Android)

```sh
RxError (RC_WEBRTC_PEER): RxError (RC_WEBRTC_PEER):
    RxReplication WebRTC Peer has error
    Given parameters: {
      error:{
        "code": "ERR_CONNECTION_FAILURE"
      }}
    at newRxError (rx-error.js:98:10)
    at _Peer.<anonymous> (connection-handler-simple-peer.js:116:31)
    at zone-patch-rxjs.js:98:41
    at proto.<computed> (zone.js:962:24)
    at EventEmitter.emit (events.js:81:17)
    at index.js:496:21
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at _Zone.runTask (zone.js:173:47)
    at drainMicroTaskQueue (zone.js:581:35)
  ERROR Error: missing value from map [object Object]
    at getFromMapOrThrow (utils-map.js:4:11)
    at RxWebRTCReplicationPool2.removePeer (index.js:174:21)
    at Object.next (index.js:37:147)
    at ConsumerObserver2.next (Subscriber.js:96:33)
    at Subscriber2._next (Subscriber.js:63:26)
    at Subscriber2.next (Subscriber.js:34:18)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:14695:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at _Zone.run (zone.js:129:43)
```

**Comment by AmnaZahoor11** [comment]
@DanielKucal  Is there any update on this issue? I'm trying to replicate my database between a React Native app and a website, and I'm encountering the same issue on my site.

**Comment by DanielKucal** [comment]
Hi @AmnaZahoor11, as far as I can remember it was the fault of signaling server itself - it was probably flooded by thousands of peers. I ended up setting up my own local signaling server written using Bun.js' `ServerWebSocket`
