### ISSUE TITLE
Electron : Object has been destroyed

### ISSUE THREAD

**Issue by pwi-informatique** [pubkey/rxdb#5370]
Hi,

I'm facing a small problem when using RxDB with Electron.
For ease of use, I've recreated a small project that can be accessed [here](https://github.com/pwi-informatique/electron-rxdb-test), this project is based on [RxDB Electron example](https://github.com/pubkey/rxdb/tree/ea2632dd69950747c9db089eef66022ee0dfc101/examples/electron).

#### Problem description

After launching the application, if you close one of the two windows and try to add a hero, the following error appears in the log / in an error popup :

```
(node:35380) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at WebContents.send (node:electron/js2c/browser_init:2:79151)
    at XXXXXXXXXXXXXXXXXXXX\electron-rxdb-test\node_modules\rxdb\dist\lib\plugins\electron\rx-storage-ipc-main.js:32:14
    at Set.forEach (<anonymous>)
    at Object.send (XXXXXXXXXXXXXXXXXXXX\electron-rxdb-test\node_modules\rxdb\dist\lib\plugins\electron\rx-storage-ipc-main.js:31:19)
    at Object.next (XXXXXXXXXXXXXXXXXXXX\electron-rxdb-test\node_modules\rxdb\dist\lib\plugins\storage-remote\remote.js:185:18)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:35380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

#### Workaround

I've slightly modified the code of the `exposeIpcMainRxStorage` function to remove windows that have been destroyed, from the `openRenderers` list.
The modified Typescript code of the `exposeIpcMainRxStorage` function can be consulted [here](https://github.com/pwi-informatique/electron-rxdb-test/blob/7a9d26a0805e051565cd6555339f26036c92d19d/rx-storage-ipc-main.custom.ts).

You can follow the steps listed in the README file to reproduce the bug and test the workaround.

**Comment by pubkey** [comment]
Hi @pwi-informatique 
thank you for investigating. The proposed change look good to me, can you do a PR?
Also do you think it is possible to reproduce the wrong behavior in the electron [e2e tests](https://github.com/pubkey/rxdb/blob/master/examples/electron/test/spec.js)?

**Comment by pwi-informatique** [comment]
Hi @pubkey,

No problem, I'll do a PR.

I can reproduce the wrong behavior in the electron e2e tests, but as the error occurs in the main process, a blocking message is displayed :

![image](https://github.com/pubkey/rxdb/assets/121101725/ba32fd01-1698-400f-90c4-0ab9953a8926)

I didn't find a way to hide this error, so the test will fail due to timeout.

**Comment by pubkey** [comment]
ok, so a PR with the fix would be ok for me. If it is not testable in CI, there is nothing we can do.

**Comment by pubkey** [comment]
Fixed here https://github.com/pubkey/rxdb/pull/5395

**Comment by esseguin** [comment]
Hi @pubkey , I believe this issue has re-appeared as of RxDB 16.0.0.

The [fix](https://github.com/pubkey/rxdb/pull/5395) you added involved listening to the ["destroyed"](https://www.electronjs.org/docs/latest/api/web-contents#event-destroyed) event of WebContents and deleting the renderer. However, with the release of 16.0.0, it was changed to [listen to a "closed" event](https://github.com/pubkey/rxdb/blob/502882df820e066064c3daca7cc9a792c725e9e8/src/plugins/electron/rx-storage-ipc-main.ts#L42) which does not exist.

Looking at the [16.0.0 commit](https://github.com/pubkey/rxdb/commit/633c0ab8c794007e7939a07a84c7bb14e6548ea0), I see "RENAME .destroy() to .close()". Is it possible that this was just an incorrect find/replace?

Thanks! Let me know if it would be easier for me to create a new issue.

**Comment by pubkey** [comment]
@esseguin Oh, I think you are totally right. This was on accident.
