### ISSUE TITLE
[!important]: v15 official realease undefined is now treated as null, this broken whole app used rxdb previous version.

### ISSUE THREAD

**Issue by 1yasa** [pubkey/rxdb#5414]
`storage-dexie`.

In RxDB v15 official release, undefined is now treated as null, which is inconsistent with the behavior of previous versions. Is there a solution to ensure compatibility with the previous data processing?

**Comment by 1yasa** [comment]
`remind_time?:number`

### prev v15.0.0-beta42
set remind_time: undefined => schema check pass

### v15.0.0
set remind_time: undefined => schema check failed

### Temporary solution

define `remind_time?:number|string`, filter update value(undefined => ''), but this may lead to other side effects.

**Comment by pubkey** [comment]
Hi @1yasa 
Can you make a PR with a test case?

**Comment by 1yasa** [comment]
> Hi @1yasa This should work exactly like it did in v14. Can you make a PR with a test case?

<img width="988" alt="截屏2023-12-22 16 56 41" src="https://github.com/pubkey/rxdb/assets/127166080/95b738a1-acbe-4ec3-8649-ffb91a4d6e9a">

I'm trying to figure out how to run the test cases for RxDB, but it seems that there are some issues preventing progress, possibly due to something in the `postinstall` process.

<img width="934" alt="截屏2023-12-22 17 00 49" src="https://github.com/pubkey/rxdb/assets/127166080/2aed9dda-f98a-42c6-afcf-1f65a985bdb0">

**Comment by 1yasa** [comment]
Here is the test case:

```ts
export type Item = {
        /** @maxLength 30 */
        module: string
        type: 'dir' | 'file'
        /** @maxLength 30 */
        id: string
        name: string
        create_at: number
        pid?: string
        prev_id?: string
        next_id?: string
        icon?: string
        icon_hue?: number
        update_at?: number
        backup_at?: number
}
```
```json
{
          "type": "object",
          "properties": {
                "module": {
                      "type": "string",
                      "maxLength": 30
                },
                "type": {
                      "type": "string",
                      "enum": [
                            "dir",
                            "file"
                      ]
                },
                "id": {
                      "type": "string",
                      "maxLength": 30
                },
                "name": {
                      "type": "string"
                },
                "create_at": {
                      "type": "number"
                },
                "pid": {
                      "type": "string"
                },
                "prev_id": {
                      "type": "string"
                },
                "next_id": {
                      "type": "string"
                },
                "icon": {
                      "type": "string"
                },
                "icon_hue": {
                      "type": "number"
                },
                "update_at": {
                      "type": "number"
                },
                "backup_at": {
                      "type": "number"
                }
          },
          "required": [
                "module",
                "type",
                "id",
                "name",
                "create_at"
          ]
    }
```

<img width="1005" alt="截屏2023-12-22 17 28 42" src="https://github.com/pubkey/rxdb/assets/127166080/755403d6-74b6-44ec-a237-a6ebdc8c282c">

### Context

`plugins`:

```ts
import { addRxPlugin } from 'rxdb'
import { RxDBFlexSearchPlugin } from 'rxdb-flexsearch'
import { RxDBCleanupPlugin } from 'rxdb/plugins/cleanup'
import { RxDBcrdtPlugin } from 'rxdb/plugins/crdt'
import { RxDBLeaderElectionPlugin } from 'rxdb/plugins/leader-election'
import { RxDBMigrationPlugin } from 'rxdb/plugins/migration-schema'
import { RxDBQueryBuilderPlugin } from 'rxdb/plugins/query-builder'
import { RxDBUpdatePlugin } from 'rxdb/plugins/update'

addRxPlugin(RxDBcrdtPlugin)
addRxPlugin(RxDBCleanupPlugin)
addRxPlugin(RxDBLeaderElectionPlugin)
addRxPlugin(RxDBUpdatePlugin)
addRxPlugin(RxDBQueryBuilderPlugin)
addRxPlugin(RxDBFlexSearchPlugin)
addRxPlugin(RxDBMigrationPlugin)
```

`action`:

```ts
$db.dirtree_items.insert({ ...item, create_at: new Date().valueOf() })
```

**Comment by 1yasa** [comment]
### More context

`version`: 

rxdb@15.0.0

`storage`:

```ts
const db = await createRxDatabase<RxDB.DBContent>({
      name: 'if_v1',
      eventReduce: true,
      allowSlowCount: true,
      multiInstance: false,
      password: 'I16DKS#hY+Two0O',
      cleanupPolicy: { waitForLeadership: false },
      ignoreDuplicate: window.$is_dev,
      storage: wrappedKeyEncryptionCryptoJsStorage({
            storage: wrappedKeyCompressionStorage({
                  storage: getRxStorageDexie()
            })
      })
})

await db.addCollections({
      activity_items: {
            autoMigrate: false,
            schema: schema_activity_items,
            migrationStrategies: migration_activity_items
      },
      dirtree_items: {
            autoMigrate: false,
            schema: schema_dirtree_items,
            migrationStrategies: migration_dirtree_items
      },
      todo: {
            autoMigrate: false,
            schema: schema_todo,
            migrationStrategies: migration_todo
      },
      todo_items: {
            autoMigrate: false,
            schema: schema_todo_items,
            migrationStrategies: migration_todo_items
      }
})

window.$db = db
```

**Comment by 1yasa** [comment]
This `feature` was from rafactored `storage-dexie`, so if you want to reproduce, save optional field as `undefined` use rxdb@15.0.0-beta.42 & rxdb@15.0.0, you will know `null` value will make rxdb@15.0.0 schema check failed.

**Comment by pubkey** [comment]
Please make a PR with a test so that the CI can run on it and it will also check the same behavior with the other storages.

**Comment by 1yasa** [comment]
Encountered an issue during the installation of rxdb, later identified it was caused by the `node-datachannel` library. Spent half a day troubleshooting and ultimately determined it was due to an incompatible `node` version and the absence of `cmake` installation.

For others with macos, if you want to dev rxdb, make sure install these:

- `install node@19.9`
- `brew install openssl@3`
- `brew install cmake`
- into rxdb root dir
- `npm install --ignore-scripts`
- into `rxdb/node_modules/node-datachannel`
- `npm install`
- `npm run _prebuild`

Then you can dev rxdb now.
