### ISSUE TITLE
Misleading documentation about `.info()` method

### ISSUE THREAD

**Issue by voznik** [pubkey/rxdb#5420]
Documentation mentioned that `.info` method was added
```
- Added RxStorage.info() which returns the total amount of stored documents
````
But it is missing. I was able to use it in some 15.beta version, 27 probably
After release v15 it is gone

**Comment by pubkey** [comment]
Hi @voznik 
You are right, this was left over from the latest refactorings.
RxDB v15 is able to query deleted and non-deleted documents and so the .info() call was no longer required because RxDB could just count all documents with a "normal" count query.
