### ISSUE TITLE
Docs: Sending RESYNC event from Graphql backend

### ISSUE THREAD

**Issue by emil14** [pubkey/rxdb#5424]
[Documentation](https://rxdb.info/replication.html) says:

> When the client goes offline and online again, it might happen that the pullStream$ has missed out some events. Therefore the pullStream$ should also emit a RESYNC event each time the client reconnects, so that the client can become in sync with the backend via the [checkpoint iteration](https://rxdb.info/replication.html#checkpoint-iteration) mode.

But there's no (working) example or documentation on how to accomplish this with graphql backend. 

There was a guy on discord with the same issue and couldn't figure out did he ever find out how to accomplish this:

> Actually yes, brainfart, I was looking at the graphql example but not understanding it. I guess I see how I would implement sending the diff. By "emit a 'RESYNC' event" (so as not to have to immediately implement the diff version), do we mean return the string 'RESYNC' instead of an array of objects from the subscription?

1. Am I right that if I would use bare websockets then I simply send "RESYNC" string to the connection from server to client?
2. Could you please provide an example of doing so with graphql?

Thank you!

**Comment by pubkey** [comment]
If your websocket fails and reconnects, you can call RxReplicationState.reSync() which is the same as having a "RESYNC" send over the masterStream$

**Comment by emil14** [comment]
@pubkey hello there :) I'm not sure if I've expressed my question clear enough. Let me try one more time with different words.

I have a (written in Go) graphql-backend. I would like to know how do I send `RESYNC` **from server to the client**.

E.g. I don't wanna send actual updates, all I want is to send "RESYNC" signals from time to time so the client does the _pull_ query.

So I have two questions:

1. Am I right that in case of bare web-sockets I would simply send "RESYNC" string via web-socket connection?
2. If yes, then how do I do this with graphql backend which is more high-level than web-socket or HTTP. Do you have a working example? Can we improve docs on that? Is there something I'm missing?

**Comment by pubkey** [comment]
Your server is not supposed to send RESYNC events. That is something which the `pullStream$` sends to the replication plugin.
If your server is not capable of sending actual valid `pullStream$` data, you can use whatever trigger you want to tell the client that there are new updates and then you run `RxReplicationState.reSync()` on the client.
