### ISSUE TITLE
Push doesn't work after migration

### ISSUE THREAD

**Issue by andronixmd** [pubkey/rxdb#5427]
### Push doesn't work after migration
After migration, records created locally are not transferred to the server, but the client receives new changes.

### Environment
```
NodeJS - v16.13.1
npm - 8.3.0
rxdb - 12.7.16
react-native - 0.66.4
```

### Step to reproduce

1. Build app
2. Press on button "Create Records" few times
3. Increase "Messages" schema version number
4. Rebuild app
5. Press "Create Records" button - the records are created, but not sent to the server.

**Comment by andronixmd** [comment]
Link to repository to reproduce bug - https://github.com/andronixmd/rxdb-sync-bug

**Comment by pubkey** [comment]
Hi  @andronixmd 
This needs a test case in the RxDB test suite.
The best start is by editing this file: https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.ts

**Comment by pubkey** [comment]
Is this really with RxDB v12? Because there will be no more bugfixes for that version.
