### ISSUE TITLE
I tested rxdb crdt on multiple device with crazy operations, i find when crdts.operations.length>400, rxdb subscribe become very slow.

### ISSUE THREAD

**Issue by 1yasa** [pubkey/rxdb#5443]
Is there a way to clean up the operations array of CRDT? When this array stores too many operations, it affects the response speed of RxDB. 

My current solution is to use a CRDT operation to delete the CRDT operation array(but this may lead to some side effects):

```ts
$db.dirtree_items.postSave(async data => {
      const doc = await $db.dirtree_items.findOne(data.id).exec()

      if (!doc) return

      if (data.crdts.operations.length >= 120) {
            const operations = data.crdts.operations

            operations.splice(0, data.crdts.operations.length - 120)

            return doc.updateCRDT({
                  crdts: {
                        hash: data.crdts.hash,
                        operations
                  }
            })
      }

      return
}, false)
```

Can a (db | collection).cleanCRDT(counts?:number) function be provided to clean up the CRDT operations array.

Or alternatively, provide a special atomic operation - `updateForce` (only effective in CRDT scenarios), that can modify document data without being recorded in CRDT operations?

**Comment by 1yasa** [comment]
After running test cases, it appears that the performance slowdown caused by an abundance of operations isn't originating from RxDB itself. My hypothesis is that certain operations, due to an overwhelming number of CRDT operations, are causing a blockage in the main thread, ultimately leading to a lag in user interaction.

Unfortunately, RxDB doesn't provide a built-in method to trim down the CRDT operations array. One workaround I'm considering is introducing a 'clean' operation for users. When users experience lag due to an excess of data and CRDT operations, they can utilize the clean button.

Through pagination queries (60 per page) and utilizing delete operations, we can strip away the CRDT objects from the retrieved JSON. Following this, we create a new mirrored document and clone the queried data without CRDTs into this mirrored document.

Once we've completed the cloning for all paginated data queries, we execute a doc.remove operation to eliminate the original document. This way, we obtain a fresh document devoid of any CRDT records.

**Comment by pubkey** [comment]
@1yasa  why did you close this?

Cleanup of CRDDT history is a missing feature of RxDB. PR is welcomed. I think the best way is to implement the definiton of crdt cleanup policy in the schema. And then the CRDT plugin can run that on each write to the storage and ensure that the history is cleaned up properly.

Notice that the CRDT plugin is way slower with [dev-mode](https://rxdb.info/dev-mode.html) than it will be in production. Because the dev-mode will check the correctness of each CRDT operation on each write.

**Comment by 1yasa** [comment]
> @1yasa
> 
> Cleanup of CRDT history is a missing feature of RxDB. PR is welcomed. I think the best way is to implement the definiton of crdt cleanup policy in the schema. And then the CRDT plugin can run that on each write to the storage and ensure that the history is cleaned up properly.RxDB 缺少 CRDT 历史记录的清理功能。欢迎公关。我认为最好的方法是在模式中实现 crdt 清理策略的定义。然后 CRDT 插件可以在每次写入存储时运行它，并确保正确清理历史记录。
> 
> Notice that the CRDT plugin is way slower with [dev-mode](https://rxdb.info/dev-mode.html) than it will be in production. Because the dev-mode will check the correctness of each CRDT operation on each write.请注意，CRDT 插件在开发模式下比在生产环境中慢得多。因为dev-mode会在每次写入时检查每个CRDT操作的正确性。

After grasping all the functionalities of the CRDT plugin, I'll be contemplating how to implement an automatic 'clean' operation based on the CRDT plugin.

Ignoring edge cases, essentially, it aligns with the 'operation reduce' operation in the OT algorithm — retaining a certain number of top operations (perhaps around 120 would be suitable, though customization should also be supported), while discarding surplus operations at the bottom of the stack.
