### ISSUE TITLE
Question: resync behavior

### ISSUE THREAD

**Issue by marbemac** [pubkey/rxdb#5446]
Hi there, I am attempting to manually manage syncing with rxdb and am a little confused about how resync is expected to work.

Effectively I am creating a replicator instance with the following configured (live and autoStart are false, with console.logs in the push and pull handlers):

```ts
const instance = replicateRxCollection<RxDocType, CheckpointType>({
  collection,
  
  live: false,
  autoStart: false,
  retryTime: 5 * 1000,
  waitForLeadership: true,

  push: {
    async handler(docs) {
      console.debug(`${collection.name}.replicate.PUSH.start`, docs);

      // ... rest of handler code
    },
  },

  pull: {
    async handler(lastCheckpoint, batchSize) {
      console.debug(`${collection.name}.replicate.PULL.start`, lastCheckpoint);

      // ... rest of handler code
    },
  },
});
```

Everything works OK with autoStart: true (or if call instance.start), however when I try to call `instance.reSync()` nothing happens - no network requests, and neither of the push/pull handler logs are printed. Does something else need to happen before reSync will fire (I am assuming that reSync simply calls the push/pull handlers?)?

Thanks!

**Comment by marbemac** [comment]
Ah.. fiddling with the options a bit - the pull handler is triggered on reSync, but only if `live: true` - is that expected?

**Comment by pubkey** [comment]
@marbemac yes this is expected. If multiple re-sync are called even when was not finished, it will also drop all but the latest. Maybe we should throw an error if resync is called but the replication has not started yet.

**Comment by marbemac** [comment]
> Maybe we should throw an error if resync is called but the replication has not started yet.

This would make it more clear (or a small docs adjustment).

So if my use case is that I'd like to manually control when pull/push occurs, instead of reSync should i be calling `start` on an interval with autoStart and live set to false?

**Comment by MrChadMWood** [comment]
@marbemac 

What did you end up doing? I'm debugging from my console, and `replicationState.start()` returns a promise. It resolves, I call `reSync`, and still nothing happens.

I also have `live: false`.

**Comment by marbemac** [comment]
@MrChadMWood I paused on the project, good luck!

**Comment by yashspr** [comment]
If anyone wants to implement syncing between custom interval, this is how it should be done. @pubkey I think this should be mentioned in the documentation as it not very straightforward to figure out without trial and error, and I think this is a common use-case that devs might want to implement.

You need to set `live` to `true` and then manually `start()` and `pause()` the replication using a setInterval or on any other custom logic. Here is how I did it:

I tried setting `live` to `false` and then calling `reSync()` but that didn't work.

```js
let is_replication_in_progress = false;

replication
  .start()
  .then(() => {
  	replication.pause();
  
    	setInterval(async () => {
    		if (is_replication_in_progress) return;
    
    		is_replication_in_progress = true;
    
    		try {
    			await replication.start();
    			await replication.awaitInSync();
    			replication.pause();
    		} catch (error) {
                         replication.pause();
    			console.error("Error during replication:", error);
    		}
    
    		is_replication_in_progress = false;
    	}, 15 * 1000);
    })
    .catch((err) => {
    	console.error("Error starting replication:", err);
    });
```
