### ISSUE TITLE
In rxdb 15 remove method throws error

### ISSUE THREAD

**Issue by pavel-shermayster-sage** [pubkey/rxdb#5452]
Test environment, Node 20
When running `remove` on `collection` or `db` rxdb 15 throws `Error: unknown operator $eq`, same code works fine in 14
```
 ❯ Query.processOperator ../../.yarn/cache/mingo-npm-6.4.10-00e9c8ae47-bee9c672da.zip/node_modules/mingo/dist/cjs/query.js:46:19
 ❯ Query.compile ../../.yarn/cache/mingo-npm-6.4.10-00e9c8ae47-bee9c672da.zip/node_modules/mingo/dist/cjs/query.js:35:26
 ❯ new Query ../../.yarn/cache/mingo-npm-6.4.10-00e9c8ae47-bee9c672da.zip/node_modules/mingo/dist/cjs/query.js:19:14
 ❯ Module.getMingoQuery ../../.yarn/unplugged/rxdb-virtual-c1c7d21a0a/node_modules/rxdb/dist/esm/rx-query-mingo.js:54:10
 ❯ Module.index ../../.yarn/unplugged/rxdb-virtual-c1c7d21a0a/node_modules/rxdb/dist/esm/rx-query-helper.js:194:42
 ❯ RxStorageInstanceMemory.query ../../.yarn/unplugged/rxdb-virtual-c1c7d21a0a/node_modules/rxdb/src/plugins/storage-memory/rx-storage-instance-memory.ts:307:46
 ❯ ../../.yarn/unplugged/rxdb-virtual-c1c7d21a0a/node_modules/rxdb/src/rx-storage-helper.ts:781:10
 ❯ IdleQueue.wrapCall ../../.yarn/cache/custom-idle-queue-npm-3.0.1-d5fa417127-053393fdf5.zip/node_modules/custom-idle-queue/dist/lib/index.js:84:22
 ❯ RxDatabaseBase.lockedRun ../../.yarn/unplugged/rxdb-virtual-c1c7d21a0a/node_modules/rxdb/src/rx-database.ts:412:1
 ❯ Object.query ../../.yarn/unplugged/rxdb-virtual-c1c7d21a0a/node_modules/rxdb/src/rx-storage-helper.ts:781:10
```

**Comment by pubkey** [comment]
This is tested multiple times in the unit tests, so I am wondering where this comes from.
Can you reproduce this case in a unit test? Maybe it is because some metadata constelation.

**Comment by pavel-shermayster-sage** [comment]
I've created a simple repo: https://github.com/pavel-shermayster-sage/react-vite-rxdb
I've tested on a local machine and in GitHub code spaces. In both environments, the error appears.

**Comment by pubkey** [comment]
Hi @pavel-shermayster-sage 
Can you try adding the problem to a unit test so that the CI can run and show the error?
You could start with this file: https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.ts

**Comment by pavel-shermayster-sage** [comment]
@pubkey I wasn't able to reproduce the error in the repo. Probably the issue with `vitest` test runner.

**Comment by pubkey** [comment]
Ok, thank for trying. So you should open an issue at the vitest repo.

**Comment by K3TH3R** [comment]
@pavel-shermayster-sage After doing some digging in, it appears that this has to do with how Vitest does module resolution. I'm still figuring out a workaround, but simply by changing the `node_modules/mingo/package.json` to have all the `exports` keys to be the ESM export, it fixed the problem. For example:
```json
"exports": {
    "./package.json": "./package.json",
    "./util": {
      "types": "./dist/types/util.d.ts",
      "node": "./dist/cjs/util.js",
      "require": "./dist/cjs/util.js",
      "default": "./dist/esm/util.js"
    },
}
```
to:
```json
"exports": {
    "./package.json": "./package.json",
    "./util": {
      "types": "./dist/types/util.d.ts",
      "node": "./dist/esm/util.js",
      "require": "./dist/esm/util.js",
      "default": "./dist/esm/util.js"
    },
}
```
fixed my unit tests that were breaking because of this problem. This is also, as far as I can tell, operating as expected from a Vitest perspective: https://github.com/vitest-dev/vitest/discussions/4233
> Vitest uses the same mechanism to resolve module with two exceptions. Vitest doesn't look at top-level "module" field in package.json, and it prioritizes "node" exports condition. This is needed so you won't have two separate modules imported in cases one of the modules is imported using Native Node resolver (which we can't modify to support "module" field without a big performance hit)
