### ISSUE TITLE
Planning to tackle the "Fix the flaky tests for the "example-supabase" CI" task

### ISSUE THREAD

**Issue by marbemac** [pubkey/rxdb#5466]
Per premium task instructions - creating an issue to indicate I'm going to take a look. Honestly, difficult to say how long it will take, but I spent the last hour doing a quick debug and I'm pretty sure I know what's going on so I'm hoping not more than a day. Will let ya know!

**Comment by pubkey** [comment]
Fixed at https://github.com/pubkey/rxdb/pull/5469
