### ISSUE TITLE
Replication + encryption question

### ISSUE THREAD

**Issue by marbemac** [pubkey/rxdb#5470]
I may have misunderstood the intent of the encryption functionality. 

Is there a way to use the encrypted data in the replication provider (atm it seems the unencrypted data is pushed up)? The use case here is privacy focused applications that want to store the encrypted data on the backend - the 3rd party is not able to decrypt it. The data is only readable by the end user, on their device, via the password they provide (also kept on the device).

**Comment by pubkey** [comment]
Encryption runs inside of the storage. RxDB itself always works with the non-encrypted plain data.
You can create a custom replication and run the encryption/decryption inside of the push/pull handlers.

**Comment by marbemac** [comment]
> You can create a custom replication and run the encryption/decryption inside of the push/pull handlers.

Got it, yeah this is what I ended up doing. Thanks for confirming, wasn't sure if I was missing something.
