### ISSUE TITLE
OPFS implementation - ensureNotFalsy() is falsy

### ISSUE THREAD

**Issue by alex-hladun** [pubkey/rxdb#5530]
During implementation fo [OPFS in Rxdb](https://rxdb.info/rx-storage-opfs.html#using-opfs-as-rxstorage-in-rxdb), running into error  `Error: ensureNotFalsy() is falsy` during runtime within the opfs.worker.js file. 

Made an example repo here: https://github.com/alex-hladun/rxdb-opfs (removed rxdb-premium token from package.json). 

Seeing this behaviour within chrome and safari.

**Comment by pubkey** [comment]
Thank you for reporting. I will check.

**Comment by pubkey** [comment]
Your schema does not contain `maxLength` for the primaryKey. This is required to set `maxLength` for all fields that are used in any index.
By adding the maxLength I could get your example to work.

**Comment by pubkey** [comment]
Also @alex-hladun  your repo contains the opfs.worker.js file and is public vissible. Please remove the repository or make it private.

**Comment by alex-hladun** [comment]
Thank you for verifying that. Also sorry, I have made it private.
