### ISSUE TITLE
Provide an option to suppress the dev-mode warning message

### ISSUE THREAD

**Issue by jonnyreeves** [pubkey/rxdb#5556]
The [dev-mode warning](https://github.com/pubkey/rxdb/blob/07b00dcae67938c975f7f4eabb1fc9214175db45/src/plugins/dev-mode/index.ts#L62) written to `console.warn()` triggers a toast in react native development builds which needs to be dismissed each time the app is started.

I understand this is a helpful message for some, but once acknowledged it would be a better developer experience if it could be supressed.

I propose this could be achieved through a `process.ENV` check, something like:

```
init: () => {
        if (!process.env.SUPRESS_DEV_MODE_WARNING) { 
                console.warn(
```

Happy to raise a PR if others are aligned?

**Comment by pubkey** [comment]
Is this really the case? Does react-native require user interaction on console.warn? I could not find anything about that online.

**Comment by adam-lynch** [comment]
👍 I'd use this option even in our web app

**Comment by pubkey** [comment]
Fixed and released in the latest release. Thanks @jonnyreeves

**Comment by jonnyreeves** [comment]
Awesome thanks for shepherding my first change to this awesome library.

Just getting my head around firestore replication for my own project but
happy to support further changes in future!

**Comment by adam-lynch** [comment]
Needs a docs update

**Comment by pubkey** [comment]
@adam-lynch Yes, added here https://github.com/pubkey/rxdb/commit/2bf846797915f113aa049d058ff9b360f933fd64
