### ISSUE TITLE
Error "Update expression must contain only one operator"

### ISSUE THREAD

**Issue by DanielKucal** [pubkey/rxdb#5563]
After update to v15, the following code started to throw an error:

```ts
DB_INSTANCE.my_collection.findOne({
      selector: { /*...*/ },
    }).update({
      ...data,
      title: 'newTitle',
    });
```

Error thrown:
<img width="602" alt="image" src="https://github.com/pubkey/rxdb/assets/8938562/e2490e68-925a-4fbd-9120-6880cbe5de2c">
Release note doesn't mention any change to the `update` method.

**Comment by pubkey** [comment]
Closing this. I think the correct call would be like:

```ts
DB_INSTANCE.my_collection.findOne({
      selector: { /*...*/ },
    }).update({
      $set: {
        ...data,
        title: 'newTitle',
      }
    });
```
