### ISSUE TITLE
Add electric-sql to the client-side-databases project to measure the performance metrics. 

### ISSUE THREAD

**Issue by mattriese** [pubkey/rxdb#5589]
Add electric-sql to the client-side-databases project to measure the performance metrics. 

For that, create an angular subproject like the already existing ones and then implement the logic interface.

I plan to be done with this on Feb 11th.

**Comment by pubkey** [comment]
Thank you @mattriese 
Let me write down a few notes that might help you:

- In the client-side-db project, each implementation uses the same angular components and setup. Only the logic-interface is different for each implementation. For example the pouchdb logic is here: https://github.com/pubkey/client-side-databases/blob/master/projects/pouchdb/src/app/app.logic.ts This is the crucial part to make it work, so for electric-sql, you have to implement that logic via electric instead of pouchdb.

- All subprojects use the same e2e test suite, so when you have implemented the logic, you can add a test:electric-sql script and run that (see package.json for the other scripts)

- Adding backend replication would be great but is NOT required. Having only implemented the client side part is also ok.
- Do not forget to add the electric test scripts to the CI

**Comment by mattriese** [comment]
udpate: I would like another couple weeks to finish this.

**Comment by pubkey** [comment]
@mattriese No problems, thanks for the update.

**Comment by MentalGear** [comment]
Keep it up, sounds really interesting !

**Comment by mattriese** [comment]
Update:
I have a first pass at translating the logic to use electric-sql and setting up the scripts so the project will run.
But the auto-generated typescript electric-sql client is being generated with many typescript errors, so it won't build. I asked about this in the electric-sql discord today but haven't got a response yet. If I don't hear back about that I will try manually fixing the type issues when I have some time this week. 

How will I make a PR when it is working? will you grant me write access to this repo?

Also, when I try to run the projects in this repo and use them in the browser, only the Firebase projects works. And it only fully works in production mode. In dev mode it does not load the chat history, but I can add new messages. All the other projects get stuck on the loading spinner after I enter my name. (I haven't tried the AWS project because of the extra steps). 
I'm not sure what the problem is, but PouchDB, WatermelonDB, Dexie, and Loki all have an error on the server related to ng-cli-ws, like '"GET /ng-cli-ws" Error (404): "Not found"'
PouchDB and WatermelonDB get the "user document not found" log in the client. 

The e2e tests do seem to run fine, though.

**Comment by mattriese** [comment]
The electric-sql folks have a [couple](https://github.com/electric-sql/electric/pull/1014) [PRs](https://github.com/electric-sql/electric/pull/1016) to fix the type issues, I will give it another try when those are merged and published.

**Comment by pubkey** [comment]
Hi @mattriese 
thanks for the update, lets wait for them to fix that.

**Comment by pubkey** [comment]
@mattriese the PRs at the electric repo seem to be fixed/closed.

**Comment by mattriese** [comment]
Ah yeah, I just noticed they released it with [electric-sql@0.9.5](https://github.com/electric-sql/electric/releases/tag/electric-sql%400.9.5). I'll try to wrap this up this week

**Comment by mattriese** [comment]
I've created a draft [PR](https://github.com/pubkey/client-side-databases/pull/484) to show my progress so far. There's a sqlite error when I try to load the app and the tests seem to have another problem. Any advice would be appreciated :)
I'm hoping to hear back from the electric-sql discord channel about the sqlite error soon.

**Comment by mattriese** [comment]
I solved one of the problems and narrowed down the cause of the other. see the new comments in the [PR](https://github.com/pubkey/client-side-databases/pull/484)

**Comment by mattriese** [comment]
@pubkey Ok thanks for the suggestions I will give it a shot

**Comment by mattriese** [comment]
Update: I didn't get any responses to my question in the Electric-SQL discord about this issue. I tried the suggestion of spawning a separate express server just to serve the wasm files, and that did work in dev mode but when running the tests I got the same error (TypeError: cannot read properties of `undefined`. reading "durability"). I didn't try the suggestion of bundling the wasm into base64. 
Unfortunately, I have run out of bandwidth to keep trying to fix this bug. Maybe someone else can take over from here. I hope once the bundling/testcafe issue is fixed, it will be pretty close to being done. I'd be happy to jump back in if that problem is fixed and there are questions or issues with my implementation of electric-sql.

**Comment by mattriese** [comment]
@pubkey hey I just wanted to make sure you saw my last update on here.

**Comment by pubkey** [comment]
@mattriese yes I have seen it. There is not hurry, just ping me when you want to continue.

**Comment by mattriese** [comment]
Ok gotcha. I don't have any immediate plans to continue working on this by myself, but if I do I will let you know.
