### ISSUE TITLE
Collection change events corrupt keys containing square brackets when key compression is enabled

### ISSUE THREAD

**Issue by adam-lynch** [pubkey/rxdb#5605]
We have a `tags` object on documents. When adding a key like `"[example]"`, the key is `""` in the collection change event, but only when key compression is enabled.

Test here: #5603

This is particularly bad for us because bad values are being sent to our server and when our client catches up with the server, it overwrites the good values with bad. So for users, they add a tag, it's fine, then it disappears.

**Comment by pubkey** [comment]
This was an error in the key-compression package, fixed in this commit: https://github.com/pubkey/jsonschema-key-compression/commit/7ab31e01c0e2b278cd1915c64f60d53429972fe0

**Comment by pubkey** [comment]
Should be fixed in the latest releases. Ping me if it still does not work.

**Comment by adam-lynch** [comment]
Thanks
