### ISSUE TITLE
shared worker does not fulfill its promise

### ISSUE THREAD

**Issue by ahoyahoy** [pubkey/rxdb#5615]
a shared worker does not fulfill its promise

minimal example
https://github.com/ahoyahoy/rxdb-shared-worker-error/blob/main/src/main.ts

getRxStorageWorker works ok
getRxStorageSharedWorker is still in pending

"rxdb": "15.7.0",
"rxdb-premium": "15.7.0",

**Comment by pubkey** [comment]
Could reproduce your error.
You can debug the shared worker process by opening this url in chrome: `chrome://inspect/#workers`

I get the in-shared-worker error:
```
Uncaught ReferenceError: Worker is not defined
    at node_modules/web-worker/cjs/browser.js (rxdb-premium_plugins_storage-worker.js?v=7b25e094:24:22)
    at __require (chunk-LNEMQRCO.js?v=7b25e094:9:50)
    at rxdb-premium_plugins_storage-worker.js?v=7b25e094:461:33
```

Seems that the problem comes from the [web-worker package](https://www.npmjs.com/package/web-worker)
This is used inside of the `getRxStorageWorker` function, I will check.

**Comment by pubkey** [comment]
Seems to be a bundling problem because it somehow bundles the `getRxStorageWorker` methode **inside** of the worker where it should normally be tree shaked.

**Comment by pubkey** [comment]
I tried to fix this from the RxDB side but this was not really possible. I made a PR at the web-workers package so we might be able to fix it there: https://github.com/developit/web-worker/pull/45

In the meantime you could build your worker file with webpack so it does not import the code it doesnt need. I added the webpack config that is used on the premium packages to the docs: https://github.com/pubkey/rxdb/commit/7a7fd5d2dc0e75e100de0e3db19bb348f8745777#diff-b2b38c09cb3bf9d03ed981e79cdb62f75cf3c9e345e6bd7ab3356574b7fa9e12

**Comment by ahoyahoy** [comment]
I was working on another SharedWorker and I tried using Worker but shared worker probably doesn't have access to Worker api at all? Because console.log(Worker) returned Worker is not defined even if I don't use the web-worker lib.

**Comment by ahoyahoy** [comment]
minimal example without any bundler
https://stackblitz.com/edit/js-c6nawk?file=index.js

**Comment by ahoyahoy** [comment]
yeah
This is a bug. You can find the [reported bug here](https://code.google.com/p/chromium/issues/detail?id=31666) and a polyfill is [available here](https://github.com/dmihal/Subworkers).

Working example
https://stackblitz.com/edit/vitejs-vite-twqsly?file=src%2Fshared-worker.ts&terminal=dev

**Comment by ahoyahoy** [comment]
ok
rxdb shared worker already works for me with this

```
import 'subworkers'

import {wrappedKeyEncryptionWebCryptoStorage} from 'rxdb-premium/plugins/encryption-web-crypto'
import {getRxStorageIndexedDB} from 'rxdb-premium/plugins/storage-indexeddb'
import {exposeWorkerRxStorage} from 'rxdb-premium/plugins/storage-worker'

exposeWorkerRxStorage({
    storage: wrappedKeyEncryptionWebCryptoStorage({
        storage: getRxStorageIndexedDB(),
    }),
})
```

**Comment by ahoyahoy** [comment]
for now it only works in dev mode
after the build it says the same error
I will continue tomorrow

**Comment by ahoyahoy** [comment]
https://chromestatus.com/feature/6080438103703552

Dedicated workers can create nested workers, but shared workers and service workers cannot.

Creating a nested dedicated worker from a shared worker is not yet supported.

Nested shared workers are also in the spec, but there is no plan to support them at this time.

**Comment by pubkey** [comment]
I checked out https://github.com/dmihal/Subworkers and this looks dangerous when used in multiple browser tabs that open and close randomly.
Notice that cross-worker communication is a performance bottleneck so using worker inside of your shared worker likely is slower then just using the shared worker and the subworkers package adds an additional layer of communication.
