### ISSUE TITLE
RxReactivityFactory & Svelte 5

### ISSUE THREAD

**Issue by MentalGear** [pubkey/rxdb#5631]
First off: Long time fan, amazing work & I'm looking forward finally using RxDB in a bigger project.

I was wondering if anyone has experience setting up `RxReactivityFactory` with Svelte 5 (full release Q1) 's new reactivity (hidden signals) system?

**Comment by pubkey** [comment]
Should be pretty easy to implement. The question is when to unsubscribe. Is there any cleanup functionality in svelte signals?
