### ISSUE TITLE
Dexie SchemaDiff: Schema was extended without increasing the number passed to db.version(). Some queries may fail.

### ISSUE THREAD

**Issue by DanielKucal** [pubkey/rxdb#5676]
<img width="1512" alt="image" src="https://github.com/pubkey/rxdb/assets/8938562/a54e03ef-49e1-4119-a28c-d08d690d6223">

> IDBDatabase.transaction: 'attachments' is not a known object store name
> NotFoundError: IDBDatabase.transaction: 'attachments' is not a known object store name

I've got this error on Firefox and I have no idea why. I don't use attachments or local documents features. 
Circumstances: Data in collections was created some time ago in localhost:4200 and I've not used Firefox for some time and that page for even longer (in favor of 127.0.0.1) . Now this single app instance doesn't start because of those errors. There was 1 change in the schema since then - added 1 optional field with simple migration strategy (and version increase):
```js
      1: (oldDoc) => {
        return oldDoc;
      },
```
No changes were made in the collections since then. More often used instances of the app migrated the collection and work properly, while here no migration was done (I can see `v0--0` in IndexedDB collection name). It's also not a regular error I've seen when schema is changed, probably needs to be caught by RxDB?

Versions:
Firefox v122.0 -> updated to 123.0 now (error started on 122.0 and hasn't changed after update)
RxDB v15.4.2

**Comment by pubkey** [comment]
I tried several things but I do not see a way to reproduce this. Normally this error comes when accessing a indexeddb store which was already replaced by a newer version, so accessing the old one throws exactly that error.
