### ISSUE TITLE
RN example project - problem with CouchDB fields 

### ISSUE THREAD

**Issue by ozmaat** [pubkey/rxdb#571]
Hi,

I have created a RN project manually, and copy/pasted the App.js and Schema.js from the react native example - only expo is excluded. 

I created a database on CouchDB with the name "heroesreactdatabase1"

The example works on front end and displays the items. 

But when I check the couchdb side, name and color fields are not added to couchdb doc. 

This is what it looks like on couchdb.

```
{
  "_id": "this is from text field",
  "_rev": "1-53c9ed6e001c4107a4d0ce6185fb4178",
  "|a": "#F35B5E"
}
```

Name field value is added to "_id" and color field don't exist. 

If I reload the app, I see all the added docs with name and color. So both fields exist on client side. 

Only change on app.js was changing the syncURL. 

Environment : React Native 
Adapter: pouchdb-adapter-asyncstorage

```
"dependencies": {
    "babel-polyfill": "^6.26.0",
    "pouchdb-adapter-asyncstorage": "^6.4.0",
    "pouchdb-adapter-http": "^6.4.3",
    "random-token": "0.0.8",
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.2",
    "rxdb": "^7.4.1",
    "rxjs": "^5.5.7",
    "util": "^0.10.3"
  },
```

I have gone through the docs to see if I missed some step but couldn't find anything. Is this a bug?

Thank you

**Comment by pubkey** [comment]
KeyCompression is currently enabled by default. This means your `color` field gets compressed into `|a`. The primary-field is always used as `_id` to make use of the free index.
You can disabled keycompression like [described in the docs](https://pubkey.github.io/rxdb/rx-schema.html#disablekeycompression).
