### ISSUE TITLE
CompressedKeys option doesn't work with suggested bulk insert strategy

### ISSUE THREAD

**Issue by ardoramor** [pubkey/rxdb#573]
## Case
I believe this to be a bug or possibly a feature request per suggested approach to handling bulk inserts, as mentioned in issue #552.

## Issue
An Electron process takes data at a very high rate. In order to handle it, I am aggregating it and bulk-inserting it into the collection. Per suggestion in #522, I am using the native pouchdb method. However, upon attempting to search the documents later on for specific field names, I get zero results. Yet, if I disable key compression, I do get back results.

Question is, can RxDB support bulk inserts natively through a method or expose a way to encode the keys prior to insertion?

## Info
  - Environment: Electron
  - Adapter: IndexedDB
  - Stack: Webpack, Babel, VueJS

## Code

```js
import * as Database from 'db'
  
export default {
   async importBeers (beers) {
         const db = await Database.get()

         await db.beers.pouch.bulkDocs(bufferedEntries))

         const hefes = await db.beers
            .find()
            .where('type')
            .eq('Hefeweizen')
            .exec()

         console.info('hefes:', hefes)
         ...
   }
}
```

**Comment by pubkey** [comment]
You can use the `_keyCompressor` of an RxCollection like it's done [here](https://github.com/pubkey/rxdb/blob/master/src/rx-collection.js#L161).
There will be no bulkInsert for rxdb in the near future. Maybe you want to create [a plugin](https://pubkey.github.io/rxdb/plugins.html) for that, that we can later merge into this repo.
