### ISSUE TITLE
Yes this feature is missing, you can do a pull request.

### ISSUE THREAD

**Issue by Ahmed30mara2018** [pubkey/rxdb#5735]
Yes this feature is missing, you can do a pull request.
I think the best way to implement would be to add `RxCollection.remove$` and then observe the internal store of the RxDatabase for the event where the metadata of the collection gets removed. Then you know you have to trigger the .remove$ observable.

_Originally posted by @pubkey in https://github.com/pubkey/rxdb/issues/5721#issuecomment-1978541342_

**Comment by pubkey** [comment]
What did you smoke?
