### ISSUE TITLE
BUG: Destroyed collections after sync

### ISSUE THREAD

**Issue by skycult** [pubkey/rxdb#574]
## Case
RxDB seems loose collections after sync.

## Issue
- create a new RxDB database
- create two collections
- start sync for every collection
- add some document to every collection
- query collections
- all query contains all documents of all collections.

## Info
  - Environment: browser
  - Adapter: IndexedDB
  - Stack: Vue project from standard web pack template

## Code

```js
import RxDB from 'rxdb'
import PouchDBAdapterIdb from 'pouchdb-adapter-idb'
import PouchDBAdapterHttp from 'pouchdb-adapter-http'

RxDB.plugin(PouchDBAdapterIdb)
RxDB.plugin(PouchDBAdapterHttp)

await RxDB.removeDatabase('mydb')
const myDb = await RxDB.create({
  name: 'mydb',
  adapter: 'idb',
  multiInstance: false
})
console.log(myDb)
const humansColl = await myDb.collection({
  name: 'humans',
  schema: {
    title: 'humans schema',
    version: 0,
    type: 'object',
    properties: {
      name: {
        type: 'string',
        primary: true
      }
    }
  }
})
console.log(humansColl)
const herosColl = await myDb.collection({
  name: 'heros',
  schema: {
    title: 'heros schema',
    version: 0,
    type: 'object',
    properties: {
      name: {
        type: 'string',
        primary: true
      }
    }
  }
})
console.log(herosColl)
humansColl.sync({
  remote: 'http://localhost:5984/mydb/',
  waitForLeadership: true,
  options: {
    live: true,
    retry: true
  }
})
herosColl.sync({
  remote: 'http://localhost:5984/mydb/',
  waitForLeadership: true,
  options: {
    live: true,
    retry: true
  }
})
const pippo = await humansColl.insert({
  name: 'pippo'
})
console.log(pippo)
const pluto = await humansColl.insert({
  name: 'pluto'
})
console.log(pluto)
const superman = await herosColl.insert({
  name: 'superman'
})
console.log(superman)
const spiderman = await herosColl.insert({
  name: 'spiderman'
})
console.log(spiderman)
setTimeout(async () => {
  const humans = await humansColl.find().exec()
  const heros = await herosColl.find().exec()
  console.log(humans) // <-- 4 docs!
  console.log(heros) // <-- 4 docs!
}, 5000)
```

**Comment by skycult** [comment]
Opening the CouchDB database I see all documents with only `_id` and `_rev` fields.

**Comment by skycult** [comment]
If I sync every collection with a different remote database it sync only if I update a document inside the local database but not the viceversa. How RxDB synchronize?
Thanks

**Comment by ozmaat** [comment]
"Opening the CouchDB database I see all documents with only _id and _rev fields"

Looks like the same issue with what I had [here](https://github.com/pubkey/rxdb/issues/571) in example RN project, only id and rev fields on couchdb.

**Comment by pubkey** [comment]
You replicate both collections with the same couchdb-endpoint which will make all documents replicated between the collections. You have to replicate each collection with it's own endpoint [see here](https://github.com/pubkey/rxdb/issues/543#issuecomment-370531150)
