### ISSUE TITLE
Explain the benefits of DB and add a benchmark

### ISSUE THREAD

**Issue by vitonsky** [pubkey/rxdb#5751]
Hi, i looking for an embedded in-memory database implemented on javascript for my project, because i want to make my app work as with Electron, as in browser too.

Currently i use [Better-SQLite3](https://github.com/WiseLibs/better-sqlite3) that implemented as nodejs native module, so i can't migrate my app in browser.

I see a couple solutions, but some of them is not under maintenance anymore, some of them not in-memory, but uses indexedDb that is not meet for me, some of them is actually not implemented on JS, but implemented as WASM, so they have issues about memory crash.

It looks your solution implemented on typescript, that is good, but i actually no need an RXJS framework and any reactive design for DB at all. Also i not see any benchmarks to make decision should i use this solution or not. It is important, because my app may intensively write, read and update relations between tables in database.

Could you at least add benchmark like it do a [Better-SQLite3](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/benchmark.md).

Also, if it possible, i would be appreciate if you elaborate what key feature of rxdb except reactive design.

When i ask about it, i mean actually "why i should not implement database myself, and prefer to use rxdb, except the problem that i will have to maintain my solution myself". Maybe your database implements powerful and fast queries engine and indexes for fast search or something else.

Please, don't take my question as assault kinda "sell it to me", take it as my feedback on readme, because as people who did not meet with RXJS, i don't see a benefits in readme, but i'm open to ask, this is why i create issue. Let's try to help each other.

**Comment by pubkey** [comment]
I have some benchmarks that compare rxdb with alternatives here: https://github.com/pubkey/client-side-databases
PRs with any other framework/lib are welcomed, so you can just add sqlite3 wasm there.

**Comment by vitonsky** [comment]
> Your better sqlite benchmarks are not really that relevant

Actually, DB performance is the only thing important for my app. I don't care if user will load page 3 seconds for first visit, instead of 1 second, because i built the app, but not an blog site.

But you're right about WASM limitations, this is why i looking for a DB implemented on javascript.

I see 2 significant problems with such databases
- javascript databases is not relational, every developer implements their own design and hacks, instead of standard design and hacks that been optimized by hundreds people in the world for the time SQL and SQLite exists. So even with costs for messaging with WASM, DB may perform better than pure JS implementation of non relational DB
- no tooling exists. I mean tools like DB viewer, to debug data in DB, DB analyzers and so on. So only one way to work with DB is use debug prints or waste own time to create tools self.

This is why i explore solutions and ask you questions about features of RXDB. I want to compare features and choose the solution i will use and where i will invest my time to contribute.

Thank you for benchmark, it looks enough useful for comparison with alternative DB solutions, but it would be great to simplify benchmark, to make as trivial, to be able reproduce tests with another DBs, like BetterSQLite3.

Could you explain in short the key features of RXDB for developers who no need a reactive design?

Currently, i see one definite benefit is that current DB have some downloads on NPM and you guys write code in repository and react on issues, so it looks as live project. It is not technical feature, but it is important too.

**Comment by pubkey** [comment]
I am sorry but I cannot give you detailed explanations for all of these questions. You have to read the docs and try out stuff.

**Comment by vitonsky** [comment]
> I am sorry but I cannot give you detailed explanations for all of these questions. You have to read the docs and try out stuff.

This is why I created this issue. I can't found answers on my questions in documentation.
Let's improve the docs.

**Comment by pubkey** [comment]
Sure, please make a PR with any missing information when you found out.

**Comment by vitonsky** [comment]
> Sure, please make a PR with any missing information when you found out.

To do it, i need help of some people who may ask on my questions. Can you share this issue with some contributor who can?

We could both win then, i would get known about RXDB, and project would improve docs, so eventually people who found this repository could find answers in readme.

**Comment by pubkey** [comment]
Thats not how open source works. The docs are there and the code is public. You have to do the work by yourself.

**Comment by vitonsky** [comment]
> Thats not how open source works. The docs are there and the code is public. You have to do the work by yourself.

I got your point that you don't care about users support, but the fact that your project no have documentation and ignore issues is not mean all opensource projects have such low quality, don't generalize 😉

**Comment by pubkey** [comment]
Lol

**Comment by pubkey** [comment]
Why dont you give free tech support to people that are too lazy to read the docs and the code? Where are these PRs and stuff, I couldnt find it on your gh account.

**Comment by vitonsky** [comment]
You're getting personal, instead of improve documentation in your project. That's all I need to know about this project to make decision about use it or not. Now i see why this project have only 11k installs in NPM 🙂
