### ISSUE TITLE
Typing issue with custom build

### ISSUE THREAD

**Issue by hubgit** [pubkey/rxdb#576]
## Issue

I'm following [the custom build instructions](https://pubkey.github.io/rxdb/custom-build.html) and everything's working well apart from an issue with types that I haven't been able to resolve:

When using `import RxDB from 'rxdb/plugins/core'` (where `rxdb/plugins/core/index.d.ts` contains `import * as RxDB from '../../src/index';`) tsc produces the error `node_modules/rxdb/plugins/core/index.d.ts(1,23): error TS7016: Could not find a declaration file for module '../../src/index'. '[…]/node_modules/rxdb/src/index.js' implicitly has an 'any' type.` 

The suggested resolution, adding `declare module 'rxdb'`, doesn't help in this situation.

[edit] I can work around this by enabling TypeScript's `skipLibCheck`, so it's not too much of a problem.

## Info
  - Environment: browser
  - Stack: TypeScript 2.7.2

**Comment by pubkey** [comment]
Hi @hubgit 
Thanks for finding this out. I could not reproduce this, but think I found the problem. Can you try this out by modifying the typings of the core-plugin in your node_modules-folder.

**Comment by hubgit** [comment]
Thanks - that seems to fix the warning.

When using a custom build, where should an application import things like `RxDocument` and `RxCollection` from, that would normally be imported from 'rxdb'?
