### ISSUE TITLE
Unable to query non-index field on couch db synced database

### ISSUE THREAD

**Issue by ForumT** [pubkey/rxdb#578]
Case
Bug Request

Issue
I have been using RXDB in my project for quite some time. Earlier I didn’t have access to couch db so i was manually importing data to my RXDB with pouchdb-server as my server-side database and things were fine. Now that I have couch db and auto sync is happening, I am unable to query the db except when sending blank query or search by id (index field)…

Info
  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: React

Code

Schema:

      export const schema = {
        title: 'Attendee List',
        description: 'Database schema for attendees',
        version: 0,
        properties: {
        id: {
          type: 'number',
          index: true,
        },
        name: {
          type: 'string',
        },
        email: {
          type: ['string', 'null'],
        },
        company_address: {
          type: ['string', 'null'],
        },
        evc_id: {
          type: ['number', 'null'],
        },
      },
     },
    };

DB Code:

    export const create = async () => {
        db = await RxDB.create({
        name: 'attendee',
        adapter: 'idb',
        password: 'xyz',
    });

    window.db = db;
    const attendeeCollection = await db.collection({
        name: 'attendees',
        schema,
    });

    const replicationState = attendeeCollection.sync({
      remote: `${syncURL}/`,
      direction: { pull: true, push: false },
    });
    this.subs.push(replicationState.change$.subscribe((change) => {
      console.dir(change);
    }));
    this.subs.push(replicationState.docs$.subscribe((docData) => console.dir(docData)));
    this.subs.push(replicationState.active$.subscribe((active) =>
      console.log(`Replication active: ${active}`)));
    this.subs.push(replicationState.complete$.subscribe((completed) =>
      console.log(`Replication completed: ${completed}`)));
    this.subs.push(replicationState.error$.subscribe((error) => {
      console.log('Replication Error');
      console.dir(error);
    }));
    } catch (error) {
      console.log(error);
    }
    return db;
    }

The component using db:
     
    window.db = await Database.create();
    const sub = window.db.attendees
      .find()
      .sort({ id: 'desc' })
      .$.subscribe((documents) => {
        if (!documents) {
          return;
        `}`
        this.setState({
          results: documents,
          totalCount: documents.length,
        });
      });
    this.subs.push(sub);
  }

Search query:

    window.db.attendees.find({id: 71}).exec().then((a) => console.log(a)) //works fine

returns a doc with id: 71, evc_id:2150, name:'abc' etc.

If i query the db with say name or evc_id like so:

    window.db.attendees.find({evc_id: 2150}).exec().then((a) => console.log(a))

I get an empty array.

Any idea why this could be happening? quering the couchdb works fine. When i was quering with pouchdb server earlier, it was fine. Only now, after i implemented couchdb and data is auto synced have i started facing this problem.

Attaching snapshots of my pouchdb as visible in my browser application tab:
1) With manual import:
![image](https://user-images.githubusercontent.com/12760636/37752738-77f5f1e2-2dbf-11e8-9677-3e933da5def8.png)

2) With couchdb:
![image](https://user-images.githubusercontent.com/12760636/37752729-74c98470-2dbf-11e8-9a7e-d26f09ac8a4e.png)

The schema has changed a little. But this is how it looks. In the first one, first id is 1005 and evc_id is 3948.

**Comment by pubkey** [comment]
Can you [disable the keyCompression](https://pubkey.github.io/rxdb/rx-schema.html#disablekeycompression) and check if it works then?

**Comment by ForumT** [comment]
It worked!! 
Thank you so much!! I was going crazy trying to figure out what could have gone wrong!!

Thank you so so much :)

**Comment by pubkey** [comment]
I know it's a bit confusing an the keyCompression will be disabled by default  with the next major release.
