### ISSUE TITLE
attachments missing field data replication failed

### ISSUE THREAD

**Issue by zkzk4635** [pubkey/rxdb#5806]
_attachments:{
    "Selected5.png": {
        "length": 48702,
        "digest": "a870713bf00b9fe0a49e3a36045c6cae4787f3f81555f4426c3a97a4771e8e17",
        "type": "image/png"
    }
}
The data returned in pullhander without field data will not be synchronized to the database.

**Comment by zkzk4635** [comment]
@pubkey I returned the data field in the backend and solved the problem, I don't know if this is the right thing to do。Now I find that I can't delete the attachment,even though I used attachments.remove()。it only removed the doc。 How do I delete attachments 。

**Comment by pubkey** [comment]
MAke a PR with a test case, otherwise it is unlikely that someone will help you. I also close this because do not @ me please.
