### ISSUE TITLE
WebRTC Replication plugin should pass an RTCPeerConnection configuration to simple-peer

### ISSUE THREAD

**Issue by cleech** [pubkey/rxdb#5835]
I'm making use of WebRTC replication for shared documents between pairs of mobile users.  I'm getting reports that seem to indicate some users that can pair through the signaling server (my own based on the example code) but don't seem to be making peer connections.  I suspect both peers are on mobile networks blocking incoming connections and need a TURN server.

I'd like to be able to pass my own configuration object for the ICE agent, through simple-peer and the webrtc replication API.

**Comment by pubkey** [comment]
I think there is an option already that is not documented. Check the code. Also a PR is welcomed, just make sure to not cause a breaking change.

**Comment by cleech** [comment]
PR #5838 already opened :smile:
