### ISSUE TITLE
More control over indexedDB names

### ISSUE THREAD

**Issue by bkniffler** [pubkey/rxdb#584]
Hey, 
I'd like to be able to control the indexDB collection names without affecting the collection name (db.data.find() should for example use an indexDB named `user-123-data`). Also, it would be good to not throw errors if different databases (`commondata`, `userdata`) have collections with conflicting names.

##  Use case
I got an electron app with multiple users that is being used on shared computers. There is common collections with lots of data that everyone shares, and there is individual collections that are scoped to the users permissions. I want the users to be able to switch accounts without loosing the collections data, so that offline usage works even when the users switch often.

All of this works currently by having one database for the common data `common` and for each new user a `user-[userID]` database. But I'm running into collection name conflicts if the common database has a collection with the same name as the user database, even though the corresponding indexedDB databases have different names due to the databases having different names.

The best solution for me would be what I mentioned above: Allow to change the indexedDB database names of collections and change the name conflict check only check upon current db collections.

ps.  Also, the collection.destroy() method is not currently documented.

// Edit:  Oops, it is documented, but it doesn't have a menu item in the docs :)

pps. Great library, its really worth to use this compared to bare pouchDB, since performance with lots of items is so much better, since there is schemas, etc, keep it up!

**Comment by pubkey** [comment]
Hi @bkniffler 
When two collections with the same name are spawned in a different database, there should be no error. This sounds like a bug, maybe we should reproduce this.

**Comment by bkniffler** [comment]
What do you think about allowing to control db names in a more fine grained way?

**Comment by pubkey** [comment]
Yes this is a good idea. The idb-name of a collection should not be immutable defined by the collection/db-name. Maybe something like the `location`-flag of pouchdb would be a good solution. This would also allow to better specify the foldername when a filesystem-adapter is used.

**Comment by pubkey** [comment]
Any plans for a PR?

**Comment by pubkey** [comment]
I'm closing this. I do not need this and it could currently be solved with the hooks.
