### ISSUE TITLE
Icorrect working attachments in electron-render.

### ISSUE THREAD

**Issue by Feverqwe** [pubkey/rxdb#587]
## Case
Add attachment.

## Issue
Icorrect working attachments in electron-render. Webpack 4.

## Info
  - Environment: electron
  - Adapter: IndexedDB
  - Stack: React

## Code
```js
await file.putAttachment({
    id: 'thumbnail.jpg',
    data: buffer,
    type: 'image/jpeg'
});
```
Throw error
```js
TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:97)
    at binaryMd5 (index.es.js:15)
    at preprocessBlob (index.es.js:211)
    at preprocessAttachment (index.es.js:240)
    at eval (index.es.js:271)
    at Array.forEach (<anonymous>)
    at preprocessAttachments (index.es.js:253)
    at idbBulkDocs (index.es.js:300)
    at PouchDB.idb_bulkDocs [as _bulkDocs] (index.es.js:1471)
    at PouchDB.eval (index.es.js:1024)
```

Here create blob, not buffer.
https://github.com/pubkey/rxdb/blob/80ce6b2b3ba4b40c8737bb3d356cf06fc845c087/src/plugins/attachments.js#L41-L55

pouchdb-md5 expect buffer.
https://github.com/pouchdb/pouchdb/blob/7c0988c0ae6b773e2a81554b1b49ffe74471ce97/packages/node_modules/pouchdb-md5/src/binaryMd5.js#L3-L6
But in package.json for browser used other file. Webpack with target "electron-renderer" don't use "browser" files.
https://github.com/pouchdb/pouchdb/blob/7c0988c0ae6b773e2a81554b1b49ffe74471ce97/packages/node_modules/pouchdb-md5/package.json#L11-L15

I can fix it if in webpack add alias
```js
resolve: {
  alias: {
    'pouchdb-md5': path.resolve(__dirname, './node_modules/pouchdb-md5/lib/index-browser')
  },
},
```
But will better if createBlobBuffer function in rxdb will depend from target via package.json.

**Comment by pubkey** [comment]
I could reproduce this. Fix will come.
