### ISSUE TITLE
rxdb-server incorrectly replies with the `updatedAt` instead of `lwt` property - rendering the client unable to sync properly

### ISSUE THREAD

**Issue by David-van-der-Sluijs** [pubkey/rxdb#5882]
I've created a pull request on this matter over at https://github.com/pubkey/rxdb-server/pull/61

The client looks for the `lwt` property but instead the server replies in some cases (documents > 0) with the property `updatedAt`. This way the client always requests the `lwt` `0` from the server and syncing never finishes when the whole collection doesn't fit inside just one `batchSize`.

I personally encountered this error for my use case and tinkered together this patch until the proper fix arrives:
```typescript
const expressRxServer = express();
    
expressRxServer.use( ( request, response, next ) => {
    
    const originalSend = response.send;
    
    response.send = function( body ) {
        
        const obj = JSON.parse( body );
        
        if ( obj.checkpoint?.updatedAt ) {
            obj.checkpoint.lwt = obj.checkpoint.updatedAt;
            delete obj.checkpoint.updatedAt;
        }
        
        return originalSend.call( this, JSON.stringify( obj ) );
    };
    
    next();
} );
```
    
After this synchronization started working.

**Comment by pubkey** [comment]
Thank you for reporting.
Fixed here: https://github.com/pubkey/rxdb-server/pull/61#issuecomment-2060863836
