### ISSUE TITLE
rxdb-server parses `lwt` property to an integer - creating an infinite synchronization-loop

### ISSUE THREAD

**Issue by David-van-der-Sluijs** [pubkey/rxdb#5883]
In [this line](https://github.com/pubkey/rxdb-server/blob/master/src/plugins/server/endpoint-replication.ts#L89) of the rxdb-server `lwt` gets parsed down to a integer which has the **catastrophic** side effect of creating an **infinite synchronization-loop** in the event when many documents have such a close `lwt` that they only differs in their decimal point so that they all get parsed to the exact same integer. This happens if we use `bulkInsert` or `bulkUpsert`:

```typescript
await rxdb.yourCollection.bulkInsert( somethingBig );
```

A ugly workaround until a proper fix arrives is to just don't use bulk at all and rather something like this:
```typescript
for ( const data of somethingBig ) {
    await new Promise( ( resolve ) => setTimeout( resolve, 1 ) ); // Ensuring `lwt` cannot be on the same ms
    await rxdb.yourCollection.insert( somethingBig );
}
```

**Comment by pubkey** [comment]
@David-van-der-Sluijs Thank you for the investigation. Indeed this is a bug. Can you make a PR with a fix and a test case?
