### ISSUE TITLE
RxDb 15.17 and TypeScript Error

### ISSUE THREAD

**Issue by mr-menno** [pubkey/rxdb#5884]
Using RxDb 15.17.0, getting the following typescript errors:
```
error TS2305: Module '"rxdb"' has no exported member 'RxDocument'.

6 import { RxCollection, RxDatabase, RxDocument } from 'rxdb';
```

When downgrading to 14.17.1, the error stops occurring.

**Comment by mr-menno** [comment]
Sample repo: https://github.com/mr-menno/rxdb-test.  File sample is `database.ts`

**Comment by pubkey** [comment]
Interesting, this seems to be vite related.
The RxDB default export looks to be correct: https://github.com/pubkey/rxdb/blob/master/package.json#L90

**Comment by tsuharesu** [comment]
Could it be that after v15 Typescript 5 is required? https://rxdb.info/releases/15.0.0.html#requires-at-least-typescript-version-500. I see that you project uses TS 4.

I'm having the same issue, using CRA, can't update typescript to 5 https://github.com/facebook/create-react-app/issues/13080.

**Comment by pubkey** [comment]
Closing this. Typescript v5 is required for RxDB.

**Comment by esbelf** [comment]
I am having the same issue but I am using typescript 5.8 with rxdb 16
