### ISSUE TITLE
getRxStorageLoki deprecated, what could replace it?

### ISSUE THREAD

**Issue by wuxiao-ling197** [pubkey/rxdb#5948]
tips:
![1](https://github.com/pubkey/rxdb/assets/77096395/0c1e41f7-bdb6-472c-922d-9cd4d9a1a573)

**Comment by pubkey** [comment]
From the core you likely use the dexie.js RxStorage.
From premium you could use the memory-synced or in the next release use the memory-mapped storage, which has similar behavior to how lokijs loads all data into memory.
