### ISSUE TITLE
Do not publish *.ts file on NPM

### ISSUE THREAD

**Issue by Xample** [pubkey/rxdb#5984]
Hi, as .ts source files might be imported by mistake (often because of webstorm or VS but [not only](https://github.com/microsoft/TypeScript/issues/22228)) it is generally considered a good practice not to include them into the NPM package.

I spent a few minutes searching for the faulty import into my code, I ended up deleting the "rxdb/src" folder to refine the search which directly lead me to the faulty import.

**Comment by pubkey** [comment]
When you delete the src folder, which import suggestions does your IDE give you? Are they correct or are they from the dist-folder?

**Comment by jwallet** [comment]
you can in the meantime prevent it with eslint

```
"no-restricted-imports": [
  "error",
  {
    "patterns": [
      {
        "group": [
          "rxdb/src/**"
        ],
        "message": "RxDB src imports are not allowed"
      },
    ],
  }
]
```

**Comment by Xample** [comment]
Before deleting:

![image](https://github.com/pubkey/rxdb/assets/944605/fc0a4e45-e407-457b-8bfe-30c1956eccf6)

none is correct.

After deleting I've a mix of 'rxdb' and 'rxdb/dist/types/types' for instance this is what is automatically imported

```typescript
import {
  MangoQuerySelector,
  MangoQuerySortDirection,
  MangoQuerySortPart,
} from 'rxdb/dist/types/types';
import { MangoQuery } from 'rxdb';
```

I manually had to change to

```typescript
import {
    MangoQuery,
    MangoQuerySelector,
    MangoQuerySortDirection,
    MangoQuerySortPart,
} from 'rxdb';
```
To get the imports from the main 'rxdb' bucket properly.

**Comment by pubkey** [comment]
Hmm, so the default import would not be correct anyway, no matter if the src folder is in the package or not. I do not want it to remove it in that case.

There are the correct exports [listed](https://github.com/pubkey/rxdb/blob/master/package.json#L89) in the package.json and I am hoping that the IDEs use that in the future.

**Comment by jwallet** [comment]
It looks like you are using WebStorm, this IDE can be tricky to setup properly, try your repo in vscode cause it works as expected. If it does that means you have webstorm messing up your repo settings.

![image](https://github.com/pubkey/rxdb/assets/23088305/25c0cb02-8bd4-408e-8456-f9740b871eb8)

**Comment by pubkey** [comment]
I do not have Webstorm, only vscode and there the import suggestions are wrong, both with and without having the `src` folder. I tried several things like removing legacy main/module fields but that did not help.

**Comment by Xample** [comment]
and I'm not using vscode on my side
