### ISSUE TITLE
RxDatabase.create(): Adapter not added. Use RxDB.plugin(require('pouchdb-adapter-[adaptername]');

### ISSUE THREAD

**Issue by igorissen** [pubkey/rxdb#600]
## Case

🐞 BUG, but I don't know where 😭

## Issue

`RxDatabase.create(): Adapter not added. Use RxDB.plugin(require('pouchdb-adapter-[adaptername]');`

I'm trying to create a service which will handle all database stuff.
When I'm using the database service I keep getting an error message telling me that IndexedDB adapter is not imported as PouchDB plugin. I have tried with WebSQL adapter and it works with a warning message telling me to use IndexedDB adapter because it will be deprecated soon.

## Info
  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: Typescript, Angular

## Code

```js
import { Injectable } from '@angular/core';
import { Logger } from '@nsalaun/ng-logger';

import * as RxDB from 'rxdb';
import * as PouchDBAdapterWebSQL from 'pouchdb-adapter-websql';
import * as PouchDBAdapterIdb from 'pouchdb-adapter-idb';

RxDB.plugin(PouchDBAdapterWebSQL);
RxDB.plugin(PouchDBAdapterIdb);

@Injectable()
export class DatabaseService {
  private _database: RxDB.RxDatabase;

  constructor(private logger: Logger) {
    this.initDatabase();
  }

  private async initDatabase(): Promise<any> {
    this._database = await RxDB.create({
      name: 'seristdb',
      multiInstance: true,
      adapter: 'idb'
    });

    this._database.$.subscribe(event => this.logger.debug(event));
  }
}
```

## Screenshots

![error](https://image.ibb.co/m898XH/Screen_Shot_2018_04_05_at_13_56_42.png)

**Comment by ngohuunam** [comment]
`RxDB.plugin(require('pouchdb-adapter-idb'))`
this work for me, hope this can help

**Comment by igorissen** [comment]
@ngohuunam not working for me I'm still getting the same error

**Comment by pubkey** [comment]
Is this on safari?

**Comment by igorissen** [comment]
@pubkey No, I'm testing only on Chrome

**Comment by pubkey** [comment]
Maybe that has something to do with webpack. Have you tried using a plain pouchdb with your chrome?

**Comment by igorissen** [comment]
> Maybe that has something to do with webpack. Have you tried using a plain pouchdb with your chrome?

No. You mean that I need to try with `pouchdb-browser`?

**Comment by pubkey** [comment]
No I mean an non-bundled version of pouchdb. Here open [this fiddle](https://jsfiddle.net/81xj277a/6/) and check if it works with your browser.

**Comment by thsowers** [comment]
Happening for me as well using the sample Vue project in Chrome on Linux, also in Safari (iOS 11.3) Looks like everything works fine on Firefox

**Comment by igorissen** [comment]
> No I mean an non-bundled version of pouchdb. Here open this fiddle and check if it works with your browser.

It's working with Chrome

![screenshot](https://image.ibb.co/ivq2zx/Screen_Shot_2018_04_09_at_17_07_09.png)

**Comment by pubkey** [comment]
Ok so the idb-adapter works with a plain pouchdb-instance but not with a webpack-bundled rxdb-instance. 

@thsowers & @igorissen  can you check if the rxdb-pouchdb-instance works by adding the following to your project:

```js
import { PouchDB } from 'rxdb';
const db = new PouchDB('foo', {adapter: 'idb'});
console.dir(db);

db.put({
  _id: 'foobar',
  foo: 'bar'
});

db.get('foobar').then(doc => {
  console.log('found doc: '+doc._id);
}).catch(err => {
  console.log('not working:');
  console.dir(err);
});
```

**Comment by thsowers** [comment]
I get `Uncaught Error: Invalid Adapter: idb` when running this, even when I install the adapter separately

**Comment by igorissen** [comment]
It works for me

![screenshot-01](https://image.ibb.co/iKOYNH/Screen_Shot_2018_04_09_at_18_52_11.png)
![screenshot-02](https://image.ibb.co/gVkr9x/Screen_Shot_2018_04_09_at_18_52_34.png)

**Comment by pubkey** [comment]
Can you try the same once with `core` and once with the normal pouchdb:
`import PouchDB from 'pouchdb-core';`
`import PouchDB from 'pouchdb';`

Which node-version do you use?
Have you updated any dependencies on the example-projects?
Have you changed the webpack-config?

I tried to reproduce this with the same chrome-version but could not. There must be something different :(

**Comment by igorissen** [comment]
Got this using `import PouchDB from 'pouchdb-core';`

> Uncaught Error: Invalid Adapter: idb
    at new PouchDB (index.es.js:1262)
    at eval (database.service.ts:27)
    at Object../src/app/services/services/database/database.service.ts (main.bundle.js:187)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (index.ts:2)
    at Object../src/app/services/services/index.ts (main.bundle.js:195)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (authenticated.guard.ts:11)
    at Object../src/app/guards/guards/authenticated.guard.ts (main.bundle.js:99)
    at __webpack_require__ (inline.bundle.js:55)

Got this using `import PouchDB from 'pouchdb';`

> Uncaught Error: Invalid Adapter: idb
    at new PouchDB (index-browser.es.js:2687)
    at eval (database.service.ts:26)
    at Object../src/app/services/services/database/database.service.ts (main.bundle.js:187)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (index.ts:2)
    at Object../src/app/services/services/index.ts (main.bundle.js:195)
    at __webpack_require__ (inline.bundle.js:55)
    at eval (authenticated.guard.ts:11)
    at Object../src/app/guards/guards/authenticated.guard.ts (main.bundle.js:99)
    at __webpack_require__ (inline.bundle.js:55)

**Comment by f4bio** [comment]
@pubkey it doesn't happen in chrome, only safari (for me at least)
I am using a modified webpack config. If that matters, I'll try later without it?!

**Comment by igorissen** [comment]
* npm install -g @angular/cli
* ng new pouchdb-test
* npm install --save pouchdb rxdb
* update app.component.ts

```typescript
import { Component, OnInit } from '@angular/core';
import { PouchDB } from 'rxdb';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';

  private _db: any;

  constructor() {
    this._db = new PouchDB('foo', { adapter: 'idb' });
  }

  ngOnInit() {
    console.dir(this._db);
    this._db.put({ _id: 'foobar', foo: 'bar' });

    this._db
      .get('foobar')
      .then(doc => {
        console.log('found doc: ' + doc._id);
      })
      .catch(err => {
        console.log('not working:');
        console.dir(err);
      });
  }
}
```

Got this error

> Error: Invalid Adapter: idb
    at new PouchDB (index.es.js:1262)
    at new AppComponent (app.component.ts:15)
    at createClass (core.js:12437)
    at createDirectiveInstance (core.js:12284)
    at createViewNodes (core.js:13742)
    at createRootView (core.js:13631)
    at callWithDebugContext (core.js:15056)
    at Object.debugCreateRootView [as createRootView] (core.js:14339)
    at ComponentFactory_.create (core.js:11236)
    at ComponentFactoryBoundToModule.create (core.js:4023)

* use `import { PouchDB } from 'pouchdb-core';` or `import { PouchDB } from 'pouchdb';`

Got this error

> TypeError: pouchdb_core_1.PouchDB is not a constructor
    at new AppComponent (app.component.ts:15)
    at createClass (core.js:12437)
    at createDirectiveInstance (core.js:12284)
    at createViewNodes (core.js:13742)
    at createRootView (core.js:13631)
    at callWithDebugContext (core.js:15056)
    at Object.debugCreateRootView [as createRootView] (core.js:14339)
    at ComponentFactory_.create (core.js:11236)
    at ComponentFactoryBoundToModule.create (core.js:4023)
    at ApplicationRef.bootstrap (core.js:5854)

**Comment by pubkey** [comment]
To import PouchDB or PouchDB-core, do not use the braces. not `import { PouchDB }..` but `import PouchDB..`

**Comment by pubkey** [comment]
Please do not forget to add the idb-adapter:

```js
import { PouchDB } from 'rxdb';
import idb from 'pouchdb-adapter-idb';

PouchDB.plugin(idb);
```

I tried to reproduce this with the ng-cli like you described, but everything works there.

**Comment by f4bio** [comment]
fresh ionic3 app (`ionic start rxdb-test`), with demo code:
```
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
import {PouchDB as PouchDBOrig} from "pouchdb";
import idb from "pouchdb-adapter-idb";
import RxDB, {PouchDB} from "rxdb";

import { HomePage } from "../pages/home/home";
@Component({
  templateUrl: "app.html"
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();

      RxDB.plugin(idb);
      PouchDB.plugin(idb);
      PouchDBOrig.plugin(idb);

      const _pouchdb = new PouchDB("pouchdbtest", {adapter: "idb"});
      console.log("_pouchdb:", _pouchdb);

      const _pouchdbOrig = new PouchDBOrig("pouchdborigtest");
      console.log("_pouchdbOrig:", _pouchdbOrig);

      const _rxdb = RxDB.create({
        name: "rxdbtest",
        multiInstance: false,
        adapter: "idb"
      });
      console.log("rxdb:", _rxdb);
    });
  }
}
```

gives me:

```
$ ionic cordova run ios
Running app-scripts build: --platform ios --target cordova
[13:39:29]  build dev started ...
[13:39:29]  clean started ...
[13:39:29]  clean finished in 2 ms
[13:39:29]  copy started ...
[13:39:30]  copy finished in 430 ms
[13:39:30]  deeplinks started ...
[13:39:30]  deeplinks finished in 22 ms
[13:39:30]  transpile started ...
[13:40:06]  typescript: src/app/app.component.ts, line: 24
            Property 'plugin' does not exist on type 'typeof PouchDB'.

      L23:  RxDB.plugin(idb);
      L24:  PouchDB.plugin(idb);
      L25:  PouchDBOrig.plugin(idb);
```

**Comment by f4bio** [comment]
when commenting out `L24:  PouchDB.plugin(idb);` it builds fine.
interestingly enough, my `PouchDBOrig` automatically switches to websql.
so, I guess as kind of a workaround, you could not require an adapter at rxdb initialisation?!

**Comment by pubkey** [comment]
`plugin()` is missing in the typings :(
Can you use `PouchDB['plugin'](idb)` ?

**Comment by igorissen** [comment]
@pubkey I have added these lines

```typescript
import idb from 'pouchdb-adapter-idb';

PouchDB['plugin'](idb);
```

It works on the first try (`ng serve`) but when you reload the page (`cmd + R`) you get the same error `Error: Invalid Adapter: idb`

**Comment by pubkey** [comment]
I now tried to reproduce this on the 5th pc, but could not :(
Can someone share a project where this is reproducible?
@igorissen can you open your project on a different computer and check if it also happens there?
Please debug into this, `console.dir` on the idb import etc.

I don't think I can help.

**Comment by pubkey** [comment]
@f4bio the ionic-code works for me:
```typescript
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';

import { TabsPage } from '../pages/tabs/tabs';

import idb from "pouchdb-adapter-idb";
import RxDB from "rxdb";

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = TabsPage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      statusBar.styleDefault();
      splashScreen.hide();


      RxDB.plugin(idb);

    RxDB.create({
      name: "rxdbtest",
      multiInstance: false,
      adapter: "idb"
    }).then(db=> {
    console.log('db created:');
    console.dir(db);
    });
    });
  }
}
```

**Comment by pubkey** [comment]
@ all can you try importing via `RxDB.plugin(require('pouchdb-adapter-idb'))`

**Comment by pubkey** [comment]
@igorissen 
Does your windows-pc have the same node-version?
Also the same chrome-version?

Can you delete `node_modules` at the ios-pc and rerun `npm install`

**Comment by igorissen** [comment]
- On Windows (works)

> Chrome version 65.0.3325.181 (32 bits)
> Node version 8.11.1

- On macOS (not working after deleting `node_modules` and rerun `npm install`

> Chrome version 65.0.3325.181 (64 bits)
> Node version 8.11.1

**Comment by igorissen** [comment]
When debugging on macOS

![screenshot-01](https://image.ibb.co/fbWORc/Screen_Shot_2018_04_10_at_22_42_31.png)

When debugging on Windows

![screenshot-02](https://image.ibb.co/iNeGex/2018_04_10.png)

You can see that the variable `isSafari` equal `true` on Chrome macOS.

**Comment by igorissen** [comment]
Thanks 🍏 🤬

![screenshot-01](https://image.ibb.co/gkwhmc/Screen_Shot_2018_04_10_at_23_04_33.png)

**Comment by igorissen** [comment]
@pubkey Silly me 😔 as I'm developing a system tray application I use the screen size of the iPhone 6. So in the Chrome dev tools, I set the responsive mode to `iPhone 6s` and because of that the UserAgent is `... Safari ... iPhone ...`.

So `RxDatabase.create()` is working now that I remove the `iPhone 6s` responsive mode.

Sorry about the mess I've created 🙏 and thank you for your help.
