### ISSUE TITLE
Slow event loop? when attempting to sync with an offline server

### ISSUE THREAD

**Issue by gvuyk** [pubkey/rxdb#601]
## Case
Bug

## Issue
I have 12 collections that need a 1 time (non-live) sync, so I pass a PouchDb instance as a 'remote' to each collection's `sync()` method. Everything works as expected except when the remote server is offline, then its like if the event loop is processed reaally slowly for a few minutes until maybe a timeout kicks in and things go back to normal. No error is reported by the `RxReplicationState`s

Will try to provide a test case after the weekend

## Info
  - Environment: Node.js
  - Adapter: LevelDB

## Code

```js
const RxDB = require("rxdb");
const PouchDB = require("pouchdb");
const fs = require("fs");

RxDB.plugin(require("pouchdb-adapter-memory"));

async function startReplication()
{
	var db = await RxDB.create({
		name: "testdb",
		adapter: "memory",
		multiInstance: false
	});
	var mySchema = {
		version: 0,
		type: "object",
		properties: {
		    passportId: {type: "string"}
		}
	};
	for(let i=0; i<12; i++)
	{
		let collection = await db.collection({name: "collection"+i, schema: mySchema});
		collection.sync({remote: new PouchDB("http://offlineserver/collection"+i)});
	}
}

startReplication().then(() => {
	console.time("fileRead");
	fs.readFile("file", (error, data) => {    // file doesn't need to exist
		console.timeEnd("fileRead");
	});
});
```

**Comment by pubkey** [comment]
It's not clear to me what you mean with `event loop is processed reaally slowly`. Have you done a chrome-profiling?

**Comment by pubkey** [comment]
I'm closing this because it's a pouchdb/leveldb-problem which should be resolved at their repo.

**Comment by gvuyk** [comment]
It turned out to be a dns module problem, [issue and workarounds](https://github.com/pouchdb/pouchdb/issues/7221)
