### ISSUE TITLE
Can't resolve types

### ISSUE THREAD

**Issue by dongnaebi** [pubkey/rxdb#6022]
I am using RxDB in TypeScript, but I'm not getting any type hints. I looked in `dist/types/index.d.ts` and found this code:
```
export * from './plugin.ts';
export * from './rx-database.ts';
export * from './rx-error.ts';
export * from './rx-database-internal-store.ts';
// ...
```
It seems that the file names are incorrect. They should be `xxx.d.ts`?

**Comment by pubkey** [comment]
I have no idea what you mean. But there are several unit tests that ensure these things work. For example in the angular RxDB example.

**Comment by dongnaebi** [comment]
My point is: the types specified in `package.json` are `./dist/types/index.d.ts`, but the file names exporting these types in `./dist/types/index.d.ts` are incorrect, causing the editor(e.g. webstorm) to be unable to find these files, as shown in the picture:

![image](https://github.com/pubkey/rxdb/assets/6902417/6b375251-8f21-433e-8e89-da490d8fdad4)

**Comment by pubkey** [comment]
Can you make a PR with a proposed fix?

**Comment by dongnaebi** [comment]
OK, I think for now, the most cost-effective solution is to directly replace the content of `index.d.ts`

```js
// scripts/fix-type.mjs
import { promises as fs } from 'node:fs'

async function main () {
    const file = './dist/types/index.d.ts'
    try {
        let content = await fs.readFile(file, { encoding: 'utf-8' })
        content = content.replaceAll('export *', 'export type *').replaceAll('.ts', '.d.ts')
        await fs.writeFile(file, content)
    } catch (err) {
        console.log(`Fix type error：${err.message}`)
    }
}
main()
```

package.json
```diff
{
  "scripts": {
-     "build:types": "npm run build:version && rimraf -rf --max-retries=3 ./dist/types && tsc --project ./config/tsconfig.types.json && cp -r ./src/types ./dist/types/types",
+     "build:types": "npm run build:version && rimraf -rf --max-retries=3 ./dist/types && tsc --project ./config/tsconfig.types.json && cp -r ./src/types ./dist/types/types && node ./scripts/fix-type.mjs",
  }
}
```

**Comment by dongnaebi** [comment]
Yes, it's work for me

![image](https://github.com/pubkey/rxdb/assets/6902417/828b9fea-869f-41a8-81e1-3dcd7638ca66)

**Comment by pubkey** [comment]
@dongnaebi Thank you for the screenshot.
Can you make a PR with your [proposed changes](https://github.com/pubkey/rxdb/issues/6022#issuecomment-2129973908)?

**Comment by dongnaebi** [comment]
I'd be pleased to do this.
