### ISSUE TITLE
replicate firestore not replicating correctly

### ISSUE THREAD

**Issue by marnec** [pubkey/rxdb#6064]
I can't create a working pull request because this bug requires a firestore database;

I have a minimal Angular test PWA that instantiates a single collection called `inbox` with Dexiejs 

after awaiting creation and migration, I start the firestore replication:

```javascript

this.rxDatabase = await createRxDatabase<...>(...);
const collections = await this.rxDatabase.addCollections({...});
if (collections.inbox.migrationNeeded()) await collections.inbox.startMigration(10);

const replicationState = replicateFirestore({
    collection: collections.inbox,
    replicationIdentifier: 'inbox',
    autoStart: true,
    live: true,
    pull: {},
    push: {},
    firestore: {
        database: this.firestore,
        collection: collection(this.firestore, 'inbox'),
        projectId: environment.firebase.appId
    },
})
```

documents in firebase have the `serverTimestamp` correctly filled, and the `serverTimestamp` property is not added to RxJsonSchema of the document as per documentation

the replication shows the following behaviours: 
- firestore:
    - First-time replication works, existing documents in firestore are pulled, existing documents in local-db are pushed
    - Subsequently, only push operations work (from browser to firestore and from the pwa installed on a phone to firestore), while pull operations don't work
    - If I restart the development environment not even first-time replication works
    - Only by changing the `replicationIdentifier` property, first-time replication works again once
    - By inspecting the network the replication system is continuosly opening and closing subscription to firestore

![firestore_subs_loop](https://github.com/pubkey/rxdb/assets/25674657/96ee0158-8f76-4f4c-931e-0f8533551549)

- firestore emulator:
    - First-time replication does not work completely, existing documents in local-db are not pushed but existing documents in firestore are pulled correctly
    - Subsequently pull and push operations work correctly
    - The replication system correctly opens a subscription to firestore and keeps it open

I looked online, read the discord and tried many different configuration but I can't get it working

**Comment by pubkey** [comment]
Shouldnt it be possible to make a PR with a test that shows the failing emulator behavior?

**Comment by marnec** [comment]
> Shouldnt it be possible to make a PR with a test that shows the failing emulator behavior?

Yes I'll try as soon as possible, thanks for the quick reply
