### ISSUE TITLE
RxDB not replacing local state with real master state

### ISSUE THREAD

**Issue by malhous** [pubkey/rxdb#6085]
I am using **RxDB** along with a replication to **Supabase**.
I have the following scenario:
1. User logs in.
2. User enters OTP (One Time Password).
3. Sync "Settings" collection to local DB:
   a. If no "Settings" doc found, insert a new document to local which will then sync.
   b. Else insert remote "Settings" doc.

Here's the code, i'm using React + Typescript:
```typescript
import {
  selectSession,
  setSession,
  setSettings,
} from "@my-app/store";
import { uuid } from "@supabase/supabase-js/dist/main/lib/helpers";
import { useEffect } from "react";

import { supabase } from "../api";
import { getDB } from "../rxdb";
import { useAppDispatch } from "./useAppDispatch";
import { useAppSelector } from "./useAppSelector";


export const useInitApp = () => {
  const dispatch = useAppDispatch();
  const session = useAppSelector(selectSession);

  useEffect(() => {
    if (!session) {
      return;
    }

    getDB()
      .then((db) => {
        // LOAD RXDB MODELS TO STORE

        db.settings
          .find({ sort: [{ created_at: "asc" }] })
          .$.subscribe((documents) => {
            console.log(documents); // returns [] on first Observable event, then [RemoteSettingsDoc] on second one
            if (!documents.length) {
              void db.settings.insert({
                user_id: session.user.id,
                created_at: new Date().toISOString(),
                modified_at: new Date().toISOString(),
                analytics_id: uuid(),
                replication_revision: "",
                _deleted: false,
              });
            } else {
              const mappedClean = documents.map((d) => d.toMutableJSON());
              void dispatch(setSettings(mappedClean[0]));
            }
          });
      })
      .catch((err) => {
        console.error("DB INIT FAILED");
        console.error(err);
      });
  }, [session]);

  useEffect(() => {
    supabase.auth.onAuthStateChange((_, latestSession) => {
      dispatch(setSession(latestSession));
    });
  }, []);

// ...
};
```

For some reason `documents` are returned as `[]` on the first observable emission, which is weird.
But that's not my problem, what's then happening is that it's inserting the document into db, triggers `conflictHandler`, which uses the `realMasterState` but does not sync it with the local state.

![image](https://github.com/pubkey/rxdb/assets/141725980/9af9898e-4694-4d3d-a58a-df0e12d2e968)

I'm not sure what are the next steps or how to solve it, any help would be great!

I'm using Dexie Storage and i noticed this empty function in `rxbd/src/plugins/storage-dexie/rx-storage-dexie-instance.ts`, not sure if it's relevant.

![image](https://github.com/pubkey/rxdb/assets/141725980/3185bfb6-fb43-4ce3-8c1d-8b5121593025)

**Comment by pubkey** [comment]
The conflict handler is not only used to handle conflicts but also to detect them. So it is called many times at various places.
Next step would be that you create a PR with a test case to reproduce the problem. Maybe it is even reproducable without supabase which would make debugging easier.

**Comment by jean-paul-supy-io** [comment]
For sure! It would be easier for me to create a PR with supabase, but i'll try to figure out something without it.

**Comment by jannessm** [comment]
+1

**Comment by jannessm** [comment]
While nailing down the executed code, I stumbled across the default conflict handler. There the new document state is compared to the assumed master state. Is this correct? If so, why? I thought a conflict exists if the assumedmaster is != the realmaster. Could someone explain this to me?
