### ISSUE TITLE
Feedback: What would be the most optimum way to have a React component re-render whenever a value changes in a document?

### ISSUE THREAD

**Issue by MrChadMWood** [pubkey/rxdb#6161]
Currently, my approach is to move a state setter function into the subscription with useEffect, and unsubscribe via the effects return function. Like this:

```
useEffect(() => {
  let subscription;

  const fetchStatus = async () => {
    if (!myCollection || !value.primaryKey) return;

    const document = await myCollection.findById(value.primaryKey).exec();

    // Create a subscription to the document
    subscription = document.$.subscribe( newDoc => {
      // Calculate some derived value
      const newStatus = calculateStatus(
        newDoc.actual_start_date,
        newDoc.actual_finish_date,
        newDoc.expected_start_date,
        newDoc.expected_finish_date
      );
      // Set the new value
      setStatus(newStatus);
    });
  };

  fetchStatus();

  return () => {
    // Unsubscribe once component unmounts
    if (subscription) {
      subscription.unsubscribe();
    }
  };
}, [value.primaryKey, myCollection]);
```

However, I am noticing some scalability issues with this approach. My use case is to re-render cells within an MUI Data Grid whenever a new "status" is determined for the cell. Statuses change based on user input elsewhere in the application.

I'm utilizing this approach with a very large table, about 500,000 cells with virtualization on both the column and row levels. In my actual use case, a cell corresponds to a "workcenter",  which watches 3-6 different documents rather than just one as shown in my example. I must calculate an "overall status" on top of calculating each documents status. 

The task is becoming quite expensive and I'm looking to optimize whatever I can. I did not see much documentation specific to React though, so I'd like some feedback. What would be considered the fastest way to make a component re-render based on changing values within a document? Does it make sense to Memoize the document retrieval process, for example?

Thank you.

**Comment by pubkey** [comment]
rxjs emits can be CPU expensive. So for better performance you can try subscribing to the query instead of each single document. Also use a WeakMap to cache/reuse the result of calculateStatus on a per document basis. Use the _rev of the RxDocument to invalidate that cache.

**Comment by MrChadMWood** [comment]
I'll give this a try. I see that `_rev` is a hash of the document. How can I implement its use to invalidate the cache? I looked through the documentation, but wasn't able to find much on the behavior. Thanks!

**Comment by pubkey** [comment]
_rev is not a hash. It is a string that contains the revision-height and the token of the instance that did the last write.
So each time the document gets changed, the revision height is increased by 1.

**Comment by MrChadMWood** [comment]
Thanks, I understand now. I was confusing, thinking I would use `_rev` to invalidate some caching RxDB does.

I ended up finding good performance with the approach shown below. I subscribed to a single query returning all docs. In the subscription, I still utilize the state setter function. I didn't end up caching results because, for my implementation, I'm not sure it'll have the highest yield on performance. The subscription should only emit when changes occur to the query result, and in that case the cache should be invalidated anyway. Also, the `useEffect` only reruns if something in its dependency array changes, in which case the cache should also be invalidated.

One area I can see the cache being helpful in my case would be to only recalculate the status of the document that actually changed, rather than recalculating all statuses for any change in the documents returned by my query. I may run tests to see how this improves things, but for now I believe performance is good enough.

```
// Main hook for handling status calculation and updates
const useCellData = (myCollection, primaryKeysArray) => {
  const [cellData, setCellData] = useState([]);

  useEffect(() => {
    if (!myCollection || !primaryKeysArray.length) return;

    const subscription = myCollection.findByIds(primaryKeysArray).$.subscribe(docMap => {
      if (!docMap.size) return;
      
      const newCellData = []
      docMap.forEach((doc, id) => {
        newCellData.push({
          primaryKey: id,
          space_pretty_name: doc.space_pretty_name,
          status: calculateStatus(
            doc.actual_start_date,
            doc.actual_finish_date,
            doc.expected_start_date,
            doc.expected_finish_date
          )
        });
      })

      setCellData(newCellData);
    });

    // Cleanup subscriptions on unmount
    return () => subscription.unsubscribe();
  }, [primaryKeysArray, myCollection]);

  return cellData;
};

export default useCellData;
```


Thanks for the help!
