### ISSUE TITLE
Feedback: How to handle offline use appropriately with network errors?

### ISSUE THREAD

**Issue by MrChadMWood** [pubkey/rxdb#6172]
I am testing an application's stability while offline and everything works great, though the console gets filled with errors like shown at the bottom of this issue.

Is there a way to catch the network errors and, maybe just display a banner to the user when they are offline?
I did attempt to catch any errors within the push handler, like so:
```
const createPushHandler = (endpoint) => async (changeRows) => {
    try {
        const rawResponse = await fetch(`${endpoint}/push`, {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(changeRows)
        });

        if (!rawResponse.ok) {
            throw new Error('Failed to push changes to the server');
        }

        return await rawResponse.json();
    } catch (error) {
        console.error('Error pushing changes to server:', error);
    }
};
```

My attempt does not work though, as I am still receiving the `RxError (RC_PUSH_NO_AR)`. Error below:

```
15:52:02.064 Replication Error: RxError (RC_PUSH_NO_AR): RxError (RC_PUSH_NO_AR):
RxReplication push handler did not return an array with the conflicts
 You can find out more about this error here: https://rxdb.info/errors.html?console=errors#RC_PUSH_NO_AR 
Given parameters: {
pushRows:[
  {
    "assumedMasterState": {
      "updated_at": "2024-06-19T17:52:48.099070Z",
      "_deleted": false
    },
    "newDocumentState": {
      "updated_at": "2024-06-19T17:52:48.099070Z",
      "_deleted": false
    }
  }
]
direction:"push"
args:{
  "result": null
}}
    Babel 2
    RxError rx-error.ts:63
    newRxError rx-error.ts:125
    masterWrite index.ts:312
```

**Comment by pubkey** [comment]
The push- and pull handlers will be retried until they no longer error. If you want to pause that, return a promise that does not resolve until the user does something.

**Comment by sagark1235** [comment]
Hi guys I ma facing the same issue with the push replication although my data is getting pushed but getting this error and I think because of this only one (first record is getting pused to the server). What to do ant suggestion please.
