### ISSUE TITLE
Wrong generics passed by RxCollection extending RxCollectionBase

### ISSUE THREAD

**Issue by artaommahe** [pubkey/rxdb#6188]
`RxCollectionBase` has 5 generics with `Reactivity` as a last one. When `RxCollection` extends `RxCollectionBase` it passes only 4 of them and instead of passing `StaticMethods` as 4th the `Reactivity` is used.

https://github.com/pubkey/rxdb/blob/5e603d0a7025a72fba7cd6629cfc3f7e5fb00418/src/types/rx-collection.d.ts#L83
```ts
export type RxCollection<
    RxDocumentType = any,
    OrmMethods = {},
    StaticMethods = {},
    InstanceCreationOptions = {},
    Reactivity = unknown
> = StaticMethods &
    RxCollectionBase<InstanceCreationOptions, RxDocumentType, OrmMethods, Reactivity> &
    RxCollectionGenerated<RxDocumentType, OrmMethods, Reactivity>;
```
https://github.com/pubkey/rxdb/blob/5e603d0a7025a72fba7cd6629cfc3f7e5fb00418/src/rx-collection.ts#L112
```ts
export class RxCollectionBase<
    InstanceCreationOptions,
    RxDocumentType = { [prop: string]: any; },
    OrmMethods = {},
    StaticMethods = { [key: string]: any; },
    Reactivity = any
> {
```

This leads to wrong types for `Reactivity` and most likely `StaticMethods`

```ts
export interface DbCollections<Reactivity> {
  smth: RxCollection<Smth, unknown, unknown, unknown, Reactivity>;
}

export type Db = RxDatabase<DbCollections<Signal<unknown>>, unknown, unknown, Signal<unknown>>;

let db: Db;

const data = db.smth.find().$$;
//         ^ any
```

Btw also looks like even after fixing this issue types for reactivity `.$$` will be wrong and always equal passed `Reactivity` generic value (`Signal<unknown>` in the example above)

**Comment by pubkey** [comment]
Thanks for investigation. PR is welcomed. I tried to fix the Signal<unknown> problem some time ago but did not find a solution.

**Comment by pubkey** [comment]
Fixed in the linked commit. Please test the next release.

**Comment by artaommahe** [comment]
@pubkey the type is better now, thx!

as for proper reactivity types looks like it's not possible with the current typescript and requires smth like this to be implemented https://github.com/Microsoft/TypeScript/issues/1213

**Comment by pubkey** [comment]
@artaommahe Thank you for that link. This helps me a lot because I can now stop looking for how to make it work and just wait for that issue to be resolved.
