### ISSUE TITLE
Questions about `date-time` data type

### ISSUE THREAD

**Issue by leandrogehlen** [pubkey/rxdb#6203]
I have some questions regarding the `date-time` data type:

- Is it possbile to apply [Condition Operators](https://github.com/cloudant/mango?tab=readme-ov-file#condition-operators)?
- Is not possible create index with this data type. By default this type is indexed?
- How is the best approach to handle datetimes attributes? Should be to define as 'number'

**Comment by pubkey** [comment]
When you have a field with `format: "date-time"`, then the `type` is still `string`. So you can only store plain strings in RxDB. You can do whatever operators or indexing on that. If your date format is sortable, you can apply $gt and index it.

**Comment by leandrogehlen** [comment]
@pubkey, thanks for the answer.

It could be helpful to have a doc section for this topic

**Comment by pubkey** [comment]
Yes good idea. I added it to the docs.

**Comment by leandrogehlen** [comment]
Hello, i'm trying create index on `date-time` attribute and i'm receiving the follow message.
I'm using `getRxStorageIndexedDB` storage

![image](https://github.com/pubkey/rxdb/assets/1750751/4c0d7efc-c35d-4f1f-b735-0c82dd3c01b5)

**Comment by pubkey** [comment]
Please make a PR with a test case. But from your error it looks like you set `type: "date-time"` which will not work.

**Comment by leandrogehlen** [comment]
I'm confusing... I understood that `date-time` type supports index

> If your date format is sortable, you can apply $gt and index it.

**Comment by pubkey** [comment]
But still you need a valid json schema and cannot put date-time as type, only as "format".
