### ISSUE TITLE
Migration from pouchdb

### ISSUE THREAD

**Issue by jabdinghoff** [pubkey/rxdb#6213]
Is there a way to migrate from pouchdb?

I tried following the docs: 
```js
import { getRxStoragePouch, addPouchPlugin } from "rxdb-old/plugin/pouchdb"

async migrateOldStorage() {
        addPouchPlugin(require('pouchdb-adapter-idb'));
        await migrateStorage({
            afterMigrateBatch: () => {
                console.log("Storage migration: batch processed")
            },
            batchSize: 500,
            database: this.db,
            oldDatabaseName: "mydatabase",
            oldStorage: getRxStoragePouch("mydatabase", {
                adapter: "indexeddb",
            }),
            parallel: false,
        })

        console.log("Storage migration complete.")
}
```

But I am unsure how to properly initialize the `oldStorage` here.
I went a bit through old issues an found https://github.com/pubkey/rxdb/issues/3417

Maybe I should do something similar and first init my old db dump it and then init my new one and load it?

**Comment by pubkey** [comment]
The migration plugin cannot be used with version ranges greater then 1. You cannot migrate from like version 10 to 15 with it.
Maybe use the json export-import plugin instead to migrate the data.

**Comment by jabdinghoff** [comment]
Ah I see!
I went with keeping the old init code around and then using the export json plugin, but I manually import it while reading the olds db's collection's versions out, since those sadly aren't in the export.
This way I can apply the migrations myself ^^
This now runs whenever a pouchdb is found and is afterwards just deleted from indexedDB.
