### ISSUE TITLE
Unexpected Behavior: `collection.remove()` resets `localDocuments` setting to default of `false`.

### ISSUE THREAD

**Issue by MrChadMWood** [pubkey/rxdb#6237]
Hello, please let me know if this is actually expected behavior. It seems that calling `collection.remove()` on a database collection with local documents enabled results in local documents being disabled. Here is a test case that can be ran from the browser console, assuming `database` references an RxDB database instance:

```
const response = await database.addCollections({ test_collection: { 
    localDocuments: true,
    schema: {
        version: 0,
        primaryKey: 'primaryKey',
        type: 'object',
        properties: { primaryKey: { type: 'string', maxLength: 100 }}
    }
}});

const test_collection = response['test_collection'];
await test_collection.remove();
await test_collection.insertLocal('test-local-doc-post-remove', { time: 0 });
```

Output:
```
 Uncaught (in promise) RxError (LD8): RxError (LD8):
localDocuments not activated. Set localDocuments=true on creation, when you want to store local documents on the RxDatabase or RxCollection.
 You can find out more about this error here: https://rxdb.info/errors.html?console=errors#LD8 
Given parameters: {
database:"test_database"
collection:"test_collection"}
    Babel 2
    RxError rx-error.ts:63
    newRxError rx-error.ts:125
    getLocalDocStateByParent local-documents-helper.ts:112
    insertLocal local-documents.ts:38
    <anonymous> debugger eval code:22
    async* debugger eval code:25
````

This behavior is just slightly confusing to me because I interpret the documentation to say that `collection.remove()` simply removes data and schemas. I figure `collection.destroy()` would go deeper than that: removing settings, replications, observables, etc.

**Comment by pubkey** [comment]
`collection.remove()` should remove everything from the collection. Also the replication states and local documents and metadata stored by other plugins.
I think the error message is confusing maybe we should change that.
