### ISSUE TITLE
Issue: Notification of updatedAt Values to Frontend on Push

### ISSUE THREAD

**Issue by MrChadMWood** [pubkey/rxdb#6248]
When the frontend RxDB instance uses a collection `pushHandler` to submit changed documents to the backend `/push` endpoint, there is a problem (in my case) with how the frontend is notified about the new `updatedAt` values for those documents. This is due to the server not trusting any `updatedAt` value provided by the client, as described in the RxDB documentation on [security](https://rxdb.info/replication.html#security).

### Current Issue:
Assume there is only one client and one server. Given, an application loads for the first time and successfully replicates all server-side data to the client-side. When pushing updates from the client to the server:
1. For the first update (`n=1`), the update is pushed with no conflicts because the most recent `/pull` cycle made sure all `updatedAt` values matched between server and client. The server responds with an empty array, but the server-side `updatedAt` value is then updated. However, this new `updatedAt` value is not sent back to the client. The server only responded with an empty conflicts array.
2. For subsequent updates (`n>1`), the client documents still use the outdated `updatedAt` value. The server then responds with all documents in the conflict array, because none of the clients `updatedAt` values matched the servers.

### Documentation Reference:
The RxDB documentation on [push-from-the-client-to-the-server](https://rxdb.info/replication-http.html#push-from-the-client-to-the-server) suggests that the server should only respond with an array of conflicts. This does not provide the client with the updated `updatedAt` values. The documentation does however mention attaching the `newDocumentState` to the `pullStream` event.
```javascript
let lastEventId = 0;
const pullStream$ = new Subject();

app.get('/push', (req, res) => {
    ...
    const event = {
        id: lastEventId++,
        documents: [],
        checkpoint: null
    };
    for(const changeRow of changeRows){
        ...
            event.documents.push(changeRow.newDocumentState);
            event.checkpoint = { id: changeRow.newDocumentState.id, updatedAt: changeRow.newDocumentState.updatedAt };
        ...
    }
    if(event.documents.length > 0){
        myPullStream$.next(event);
    }
    ...
});
```

### Questions and Concerns:
- The example code from the documentation uses a `pullStream` to notify the client of changes.  Does this mean that the `pullStream` is required in order to notify the client of new `updatedAt` values?
- I assumed `pullStream` was optional, used only if "event observation mode" is required to maintain current state on various clients. Please confirm if it is actually required, even in the scenario where only one client exists.

### Proposed Solution:
To ensure the client receives the updated `updatedAt` values, I am considering the following approach:
- Store the client-provided `updatedAt` value in the server-side database for comparison during `/push` runs. However, use the independantly tracked server-side `updatedAt` value for `/pull` operations.
- Alternatively, implement the `pullStream` if that is the right call.
- Alternatively, stop relying on the `updatedAt` value for comparisons during `/push` handling.

### Request for Clarification:
1. Is the `pullStream` implementation necessary to update the client with the new `updatedAt` values?
2. Can `/pull` rely on the server-side `updatedAt` value while `/push` relies on the client-side `updatedAt` value, without causing inconsistencies?
3. Whats your recommended approach to overcoming this issue where I can not submit `n>1` pushes?

Thank you for your assistance.

**Comment by pubkey** [comment]
Normally people use two fields. A client-timestamp and a server-timestamp.

I will check your proposal tomorrow.

**Comment by MrChadMWood** [comment]
Thanks! In that case, it would make sense to have two fields like `serverUpdatedAt` and `clientUpdatedAt`. The `clientUpdatedAt` gets used only for comparisons to determine if a pushed document is a conflict during `/push`, while the `serverUpdatedAt` gets used for ordering and determinism during `/pull`. I believe this will work for me! I was worried there might be scenarios that lead to inconsistencies.

In the meantime, I already implemented the third solution: "stop relying on the `updatedAt` value for comparisons during `/push` handling." Right now, I'm checking equality of every field except `updatedAt` (this also seems to work).

Let me know if you think both of these options should be fine.
