### ISSUE TITLE
Wrong typing of query.$

### ISSUE THREAD

**Issue by mbret** [pubkey/rxdb#6285]
The query observable $ is typed as `BehaviorSubject` while it's a simple `Observable` and will crash when trying to call `asObservable()`

https://github.com/pubkey/rxdb/blob/d72ff905d51e4cb12b7f37375c1d3b73dd3ba0c3/src/rx-query.ts#L114

**Comment by pubkey** [comment]
yes, this should be of type Observable, not BehaviorSubject.
