### ISSUE TITLE
HTTP sync with multiple clients

### ISSUE THREAD

**Issue by M-Tarasov** [pubkey/rxdb#6292]
Hello, I need some clarification, how the HTTP sync described [here](https://rxdb.info/replication-http.html) could work with multiple clients.

Let suppose, we have 2 clients synced with remote db and go offline, then
0. initial state in all databases [{id: X, updateAt: 0}], the checkpoint would be (1, X).
1. being still offline, the client 1 creates a new document {id: A, updatedAt: 1}.
2. client 2 creates a new document {id: Y, updatedAt: 2} and syncs it with server and goes offline, so that server's state now is [{id: X, updatedAt:0}, {id: Y, updatedAt: 2}]. After sync, the last checkpoint for client 2 would be (2, Y).
3. client 1 goes online and do sync, the server's state after that would be [{id: X, updatedAt:0}, {id: A, updatedAt:1}, {id: Y, updatedAt: 2}].
4. client 2 goes online again, its checkpoint is still (2, Y).

The question is, how the document A finds its way to client 2? According to the server's pull logic from link above, updatedAt 2 > 1 is false, (updatedAt 2 == 1 && id A < Y) is also false. And so the document A will not be sent to the client 2.

**Comment by pubkey** [comment]
There are two checkpoints stored, a pull- and a push-checkpoint.
