### ISSUE TITLE
Question about usage with React.js

### ISSUE THREAD

**Issue by xzecakular** [pubkey/rxdb#6303]
Hi everyone,

What is the recommended approach for using RxDB with React.js? For example, how can one effectively use CRUD methods of `RxCollection` or `RxDocument` in a React app? I know about [rxdb-hooks](https://github.com/cvara/rxdb-hooks) package that provides sort of a bridge between RxJS and React. This package is even mentioned in [one of the articles](https://rxdb.info/articles/react-database.html#using-rxdb-react-hooks), but it seems unmaintained lately - the [last commit](https://github.com/cvara/rxdb-hooks/commit/119bd327ce1c13dde6ff1e9df83f75e26c790357) was on _Mar 17, 2023_, more than 16 months ago at the time of writing. Also, as I understand it, it is not one of the official RxDB packages, correct?

Another thing that caught my eye is Custom reactivity, mentioned [here](https://rxdb.info/rx-state.html#rxstate-with-signals-and-hooks) and [here](https://rxdb.info/reactivity.html). Can this feature help with "integrating" RxDB with React?

Many thanks for your replies.

**Comment by pubkey** [comment]
Yes it is not an official package.
Yes, the custom reactivity enables you to use react hooks or preact signals to get non-rxjs stuff out of RxDB if you do not need observables.

**Comment by xzecakular** [comment]
Could you elaborate on how to set up custom reactivity for hooks?

**Comment by pubkey** [comment]
No I think the docs explain it pretty good. If something is missing please read the code.
