### ISSUE TITLE
There is an error when sync from CouchDB 2.1.1

### ISSUE THREAD

**Issue by ChristosGeorgiou** [pubkey/rxdb#632]
## Case
Bug (or question)

## Issue
When sync from couchdb, there is an error
````
Uncaught TypeError: Cannot read property 'charAt' of undefined
    at eval (replication.js:151)
    at FilterSubscriber._next (filter.js:78)
    at FilterSubscriber.Subscriber.next (Subscriber.js:93)
    at Changes.handler (fromEvent.js:132)
    at Changes.EventEmitter.emit (events.js:89)
    at tryCatchInChangeListener (index.es.js:17)
    at Object.Changes.opts.onChange (index.es.js:55)
    at Changes.eval (index-browser.es.js:442)
    at Changes.EventEmitter.emit (events.js:89)
    at tryCatchInChangeListener (index.es.js:17)
````

The sync is done although as I can confirm the latest _rev at the idb. The rxdb, however, is not working and the Find() function not fetching the fresh data.

## Info
rxdb: 7.5.0
couchdb: 2.1.1

## Code
I set a breakpoint at `replication.js` at `line:151` which is `return c.id.charAt(0) !== '_';`

The incoming event ( c ) is an array and in my case is:
````
[{
  "id": "18499d373226c3f1de02f719d601d438",
  "changes": [{
    "rev": "2-f159b9d9fde518b8e0c36544eee12677"
  }],
  "doc": {
    ...
    "_id": "18499d373226c3f1de02f719d601d438",
    "_rev": "2-f159b9d9fde518b8e0c36544eee12677"
  },
  "seq": 2
}, null, null]
````

The array contains 3 items, so it will work if the line was `return c[0].id.charAt(0) !== '_';`

The `bulk-get` although seems to fetch one result

````
Request URL: https://.../_bulk_get?revs=true&latest=true
Request Method: POST
Status Code: 200 OK
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Expose-Headers: content-type, cache-control, accept-ranges, etag, server, x-couch-request-id, x-couch-update-newrev, x-couchdb-body-time
Cache-Control: must-revalidate
Content-Type: application/json
Date: Sun, 06 May 2018 18:53:52 GMT
Server: CouchDB/2.1.1 (Erlang OTP/18)
Transfer-Encoding: chunked
X-CouchDB-Body-Time: 0
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,el;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 95
Content-Type: application/json
Origin: http://localhost:4200
Pragma: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
revs=true&latest=true
{"docs":[{"id":"18499d373226c3f1de02f719d601d438","rev":"2-f159b9d9fde518b8e0c36544eee12677"}]}
````

**Comment by pubkey** [comment]
Hi @ChristosGeorgiou 
I [now added](https://github.com/pubkey/rxdb/commit/4aa333a912ac70a599a87e7a79e2c6c4977fb39d) and couchdb integration test but could not reproduce this.

Can you modifiy [this file](https://github.com/pubkey/rxdb/blob/master/test/unit/couch-db-integration.test.js) to reproduce the problem?
You can run it local via `npm run test:couchdb`. Ensure you have a couchdb spawned at port 5984. `docker run -d -p 5984:5984 --rm --name rxdb-couchdb couchdb:2.1.1`

**Comment by ChristosGeorgiou** [comment]
I can not ether replicate it in your test. I even extend you test-code with `await AsyncTestUtil.wait(20 * 1000);` to give me time so I will manually change the couchdb-doc but with no luck.

I will further investigate my code and I will report back when I found why this:
````
fromEvent(
    this.pouch.changes({
        since: 'now',
        live: true,
        include_docs: true
    }),
    'change'
)
````
sends and array of 3 events

**Comment by ChristosGeorgiou** [comment]
Sorry wasting your time [I feel a little stupid now]
The issue was that I have upgraded rxjs to experiment to v6
Reverted back to 5.5.8 and now is working

(a good night sleep solves problems)

**Comment by pubkey** [comment]
No problem :)
