### ISSUE TITLE
Question regarding memory use of RxCollection

### ISSUE THREAD

**Issue by alexisskodak** [pubkey/rxdb#6361]
I am having trouble understanding why long lived `RxCollection`  instances store all of the data in memory.

The documentation states that the `RxCollection` instance should be destroyed with the` .destroy()` method in order to free up memory, and it works. However it is still unclear to me why the `RxCollection` instances load all of the data into memory in the first place.

here's a basic flow explaining how I am currently using it:

- RxDB is created at the entrypoint main.js file of the app and the collections are added using the schemas declaration
- On app mounted, data is fetched from the servers (if needed) and inserted into each collection. This is all done in a web worker.
- On entry to specific routes, stored data is retrieved in the main thread and shown in the page.

Without destorying the RxCollections, the JS Heap is reaching around 1.5GB on certain pages which makes the app crash on certain devices.

is this something that can be adjusted through configuration ? If not, what is the intended use of this ?
Maybe I'm using RxDB incorrectly ?

Thanks

**Comment by pubkey** [comment]
When documents are fetched from the storage, their RxDocument instance is cached and reused. We use a WeakRef for that and the documents get cleared from cache after some time if they are no longer used.
If that does not work, you likely created a memory leak my referencing to all these documents somehow.

**Comment by pubkey** [comment]
yes
