### ISSUE TITLE
Add rxdb to the JSR package repository

### ISSUE THREAD

**Issue by algoflows** [pubkey/rxdb#6362]
Yes, please add rxdb to the **JSR** package repository, thanks for this legendary tech.

https://jsr.io/

**Comment by pubkey** [comment]
What is the benefit? RxDB publishes its own typings directly and jsr is just a superset of npm.

**Comment by algoflows** [comment]
Because is superior to npm and would be handy for Deno developers. Also RXDB supports DenoKV so it would be a perfect match.

**Comment by algoflows** [comment]
Did I mention that RXDB is awesome, Deno is awesome, JSR is awesome. You are awesome. Awesomeness sticks together.

**Comment by pubkey** [comment]
No sorry. If I  add RxDB there I will have to maintain that until eternity. JSR seems to be able to install from npm anyway.

**Comment by algoflows** [comment]
Okay if you want to remain old school, your level of awesomeness has dropped by 2%. You were level 100, now only 98%.
