### ISSUE TITLE
Question about conflict resolution

### ISSUE THREAD

**Issue by Mytrill** [pubkey/rxdb#6439]
We are currently using rxdb on an app where multiple people can contribute to the same project.
We implemented a manual replication (as described in https://rxdb.info/replication.html) with pull/push and stream handler to get live updates from the backend.

We are having issues to manage conflicts; our requirements are:
- multiple users should be able to edit the same resource
- a user should be able to edit the same resource multiple times consecutively faster than the server can process the push and not get a conflict

I saw on #6248 that the recommended approach is to have 2 updated_at fields for each resource on the server, one from the server to order during pull, and one coming from clients to detect conflicts during push.
This solution seems unreliable as multiple clients may have different local times.

Are there any other common solutions? Maybe using version/sequence numbers to detect conflicts?

Thank you.

**Comment by pubkey** [comment]
Conflict detection for the pushes is solely handled on the server. So you can implement any logic there like having other revisions or storing the "old data" inside of a special field in the document.

**Comment by Mytrill** [comment]
Thank you for your reply.

Would you know which validation logic is commonly used on the server? The logic we currently use does not allow clients to do multiple fast updates, the server reject updates after the first one.
Thank you

**Comment by pubkey** [comment]
Most people do just a deep-equal check. If the asssumed master state is not equal to what is stored on the server, it is a conflict.

**Comment by Mytrill** [comment]
Thank you!
