### ISSUE TITLE
Compare with more products?

### ISSUE THREAD

**Issue by beorn** [pubkey/rxdb#6457]
Hi,

I think the <https://rxdb.info/alternatives.html> page is great, but it would be good to see a comparison of more recent alternatives:

 - <https://instantdb.com>
 - <https://electric-sql.com>
 - <https://sqlsync.dev>
 - <https://signaldb.js.org>
 - <https://powersync.com>

For the future, these projects also look related by are WIP:

- <https://zerosync.dev>
- <https://github.com/livestorejs>

**Comment by pubkey** [comment]
Hi @beorn 
Please make a PR to the alternatives article. I have no problem with adding more of these.

For all of your mentioned alternatives, please check the download counts on npm. Most of these are cool and stuff but noone is using them in production. Also most of your list is dependend on WASM-SQLite which has a bad performance and I do not see a future for these. Electric-SQL for example is [dead already](https://www.npmjs.com/package/electric-sql)

**Comment by beorn** [comment]
Electric-SQL is undergoing a big rewrite.  It's not dead.

I've created a PR with information to the best of my knowledge (but could of course be wrong).

See https://npmtrends.com/@electric-sql/react-vs-@instantdb/react-vs-rxdb-vs-signaldb-vs-sqlsync

**Comment by pubkey** [comment]
Closing this. This is not a place for advertisement. I think we should only accept stuff that is widely used.

**Comment by beorn** [comment]
I had never heard of Evolu, but looks interesting!
