### ISSUE TITLE
MigrationSchemaPlugin not working under firefox 129

### ISSUE THREAD

**Issue by agateblue** [pubkey/rxdb#6460]
I have the following code:

```javascript
import {
  createRxDatabase,
  type RxCollection,
  type RxDatabase,
  addRxPlugin
} from 'rxdb';

import { RxDBMigrationSchemaPlugin } from 'rxdb/plugins/migration-schema';
import { getRxStorageDexie } from 'rxdb/plugins/storage-dexie';
import { RxDBDevModePlugin } from 'rxdb/plugins/dev-mode';
addRxPlugin(RxDBDevModePlugin);
addRxPlugin(RxDBMigrationSchemaPlugin);

export async function getDb() {
  let db = await createRxDatabase({
    name: 'main',
    storage: getRxStorageDexie()
  });

  const fragmentSchema = {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: {
        type: 'string',
        maxLength: 40
      },
    },
    required: ['id']
  };

  await db.addCollections({
    fragments: {
      schema: fragmentSchema,
    },
  });
  return db;
}
```

I'm trying to add a `title` property to the `fragment` schema, with a corresponding migration strategy and version number increment, like this:

```javascript
 const fragmentSchema = {
    version: 1,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: {
        type: 'string',
        maxLength: 40
      },
      title: {
        type: ['string', 'null'],
      },
    },
    required: ['id', 'title']
  };

  await db.addCollections({
    fragments: {
      schema: fragmentSchema,
      migrationStrategies: {
        1: (oldDoc) => {
          oldDoc.title = null
          return oldDoc;
        }
      }
    },
  });
```

Unfortunately, the migration does not seem to run at all under Firefox. I get the following message:

> RxDatabase.addCollections(): another instance created this collection with a different schema. Read this https://rxdb.info/questions-answers.html?console=qa#cant-change-the-schema 
> You can find out more about this error here: https://rxdb.info/errors.html?console=errors#DB6 
> Given parameters: {
> database:"main"
> collection:"fragments"
> previousSchemaHash:"c25541d63134e2a80e24654dbbfc89d89b47b3e282c98975a8277a585c96fc0f"
> schemaHash:"0013990eb22f103d263513f5223e15dde6b574f2896b0dd5ee604c481ae17115"

The error link points to an explanation about missing migration strategies, which I have.

After spending a couple hours on this, the same code seems to work perfectly fine on Chromium, with the migration being run properly. I suspect a Firefox compatibility issue with the migration plugin, but I don't know how to even debug this.

**Comment by pubkey** [comment]
Can you make sure you clean up the whole storage with the devtools and test again on your firefox?
Likely you have something stored there already but not on chrome, which is why it does not work on firefox for you.
The unit test runs on firefox also, so you can make a PR with a test case.

**Comment by agateblue** [comment]
That's weird, I can confirm it works after wiping the indexeddb storage and retrying from scratch. Thank you for your time.
