### ISSUE TITLE
RxDB Discord invitation is invalid

### ISSUE THREAD

**Issue by robinduerhager** [pubkey/rxdb#6477]
This is an issue aside from the RxDB Project.

I wanted to join the Discord Server, but the Discord Invitation seems to be invalid. If i click on any Discord Link on https://rxdb.info/ or on the Link in the README, i get a "Invitation Invalid" Discord error.

**Comment by pubkey** [comment]
Hmm. I asked two friends to test it and it worked.

**Comment by lunedam-git** [comment]
Invalid for me, too. I was wanting to ask why when syncing with CouchDB RXDB removes any attachments that are on documents in CouchDB? I get that RXDB doesn't handle attachments when syncing with CouchDB, but actually removing them is a bit much. Is there a way to set RXDB to not overwrite the '_attachments' property?

**Comment by pubkey** [comment]
@robinduerhager @lunedam-git Can you post a screenshot from the error message?
Which country are you located in?
Does this only happend when already logged in to discord or is it the same error on an incognito window?

**Comment by pubkey** [comment]
> Still wondering about that _attachments deletion problem with CouchDB sync though ;-)

Make your own issue for that.

Thank you for the screenshot. @robinduerhager  which browser are you using?

**Comment by robinduerhager** [comment]
Hey, sorry for the late response. I think this is a Browserspecific Discord issue.

Firefox 131.0.3 gave me the same error as @lunedam-git, but after trying Safari (which worked), my Firefox displayed a different error:

<img width="554" alt="grafik" src="https://github.com/user-attachments/assets/53d543fb-5a7b-4b09-9ad0-b064f4636a0b">

The System used:
MacBook Air with M3 Chip
OS: macOS Sonoma 14.6.1
Browser: Firefox 131.0.3 (and Safari Version 17.6 (19618.3.11.11.5))

**Comment by pubkey** [comment]
I am not sure how to fix this or even reproduce.
I tried several browser/os combinations with browserstack and they each work. I even installed brave but it worked for me.

Discord says this might be because you reached the "100 server limit" and cannot join any more servers.
