### ISSUE TITLE
Websocket hangs after connection is closed by the server

### ISSUE THREAD

**Issue by brunovinicius** [pubkey/rxdb#6515]
GraphQL Websocket Plugin hangs and does not retry connection when server closes connection right after a successful 101 Upgrade. On my scenario this manifests itself as the client try to resume conection after refreshing auth token. WS connection is restablished way before the token is refreshed so it tries to connect using the old, expired token. After this, it gets stuck in this limbo as the server closes connection as soon as it validates the token.

Sequence of events looks similar to this:

=> GET wss://... 
<= 101 Switching Protocols
=> WS Message: connection_init (with the expired token)
<= Server Closes connection

It seems like the client its not expecting this behavior and stays hanging in wait for the server to respond "connection_ack" which will never come. This scenario might arise due to a unfortunately timed network issue, but any directions on how my server could deal with this appropreately would be very much appreciated.

RxDB Version: 15.17

Thanks in advance and sorry for not providing a PR with a test case right away.

**Comment by brunovinicius** [comment]
up

**Comment by pubkey** [comment]
Do you think it is possible to build a unit test to reproduce this?

**Comment by brunovinicius** [comment]
Hey @pubkey hope you are feeling better! 

We went live with our project a couple weeks ago and we are sorting out issues so not a lot of time available for creating this test, but I expect to put some focus on it soon. 

We developed a patch using patch-package that helped a bit, but didnt fully resolve the issue. We can make a PR of this change really quickly if you want to take a look at it. Let me know.

**Comment by cayres** [comment]
Hi @pubkey, I'm working on the same project as @brunovinicius. Our patch is really simple and based on the ws client events we found here: https://the-guild.dev/graphql/ws/docs/modules/client#event.
```
diff --git a/node_modules/rxdb/dist/esm/plugins/replication-graphql/index.js b/node_modules/rxdb/dist/esm/plugins/replication-graphql/index.js
index 56d6c7b..65e8e0e 100644
--- a/node_modules/rxdb/dist/esm/plugins/replication-graphql/index.js
+++ b/node_modules/rxdb/dist/esm/plugins/replication-graphql/index.js
@@ -123,6 +123,17 @@ export function replicateGraphQL({
       wsClient.on('connected', () => {
         pullStream$.next('RESYNC');
       });
+
+      wsClient.on('closed', (error) => {
+        pullStream$.error(error);
+        graphqlReplicationState.cancel()
+      });
+
       var query = ensureNotFalsy(pull.streamQueryBuilder)(mutateableClientState.headers);
       wsClient.subscribe(query, {
         next: async streamResponse => {
@@ -138,7 +149,7 @@ export function replicateGraphQL({
         },
         complete: () => {
           pullStream$.complete();
-        }
+        },
       });
     }
     return startBefore();

```
And now we are subscribing to the replication errors and any close event sent we handle to renew our authorization and restart replications.

We also had to stop the graphql replication because only the web socket is closing at this point, but pull and push are still working. So each time we restart the replication, we increase the number of requests per each operation.

**Comment by brunovinicius** [comment]
up
