### ISSUE TITLE
Compatibility with Sylviejs

### ISSUE THREAD

**Issue by joelbqz** [pubkey/rxdb#6522]
I'm really happy working with RxDB on a personal project that will be open source, unfortunately I can't use premium plugins. I've forked the LokiJS storage adapter and replaced it with https://github.com/cfu288/SylvieJS which seems working well. 

However I think @pubkey mentioned that there are some failing tests of RxDB for LokiJS, I'm wondering if you can provide me a little of guidance/more context in this regard so I can contribute in the SylvieJS and attempt to fix them.

Is here where I should be looking to? https://github.com/pubkey/rxdb/blob/master/test/unit/rx-storage-lokijs.test.ts

**Comment by joelbqz** [comment]
I just tried running:

`test:node:lokijs` and `test:query-correctness-fuzzing:lokijs:node`

both are passing ✅ 🤔

**Comment by pubkey** [comment]
If it works it works. I am not sure what exactly failed at the time I wrote that.
I will not migrate the current loki storage to siliviejs. Instead it will be removed in the next major version.
I think the best option would be if you have the silvie storage in your own repo/package and link to it from the RxDB docs here: https://rxdb.info/third-party-plugins.html

**Comment by pubkey** [comment]
Closing this.

I think most issues with LokiJS have been in the query correctness which made me add many workarounds like [this one](https://github.com/pubkey/rxdb/blob/master/src/plugins/storage-lokijs/rx-storage-instance-loki.ts#L259). If your storage is working without these, you should be fine.
