### ISSUE TITLE
RxServer cors settings seem to only apply to OPTIONS when using ExpressAdapter

### ISSUE THREAD

**Issue by snimmagadda1** [pubkey/rxdb#6523]
I've been fiddling with RxServer in node, trying to replicate data from an angular app, and chose the `rxdb-server` package + ExpressAdapter for a QuickStart. I've verified the rest/replication endpoints working via CURL 👍  ; however, I'm noticing that when trying to make requests from my client (localhost:4200) the CORS settings seem to only be set on the OPTIONS responses:

![CORS_express_network](https://github.com/user-attachments/assets/194ad8d9-b4d8-4fcd-8de8-cdf420c4ab37)

Looking at the `RxServerAdapterExpress` class, it seems `setCors` is indeed only setting OPTIONS. Is this intended? [The docs here](https://rxdb.info/rx-server.html#cors) are a bit ambiguous on this point:

```
export const RxServerAdapterExpress: RxServerAdapter<Express, Request, Response> = {
    async create() {
        const app = express();
        app.use(express.json());
        return app;
    },
    setCors(serverApp, path, cors) {
        serverApp.options('/' + path + '/*', expressCors({
            origin: cors,
            // some legacy browsers (IE11, various SmartTVs) choke on 204
            optionsSuccessStatus: 200
        }));
    },
```

My server setup:

```
DB_INSTANCE = await _createDb();

const rxServer = await createRxServer({
  database: DB_INSTANCE as unknown as RxDatabase,
  port: 3000,
  adapter: RxServerAdapterExpress,
  cors: "http://localhost:4200",
});

// events endpoint 
const endpoint = await rxServer.addRestEndpoint({
  name: "events",
  collection: DB_INSTANCE.events,
  cors: "http://localhost:4200",
});

console.log("RxServer: endpoint created ", endpoint.urlPath);

// replication endpoint 
const replicationEndpoint = await rxServer.addReplicationEndpoint({
  name: "events-rpl",
  collection: DB_INSTANCE.events,
  cors: "http://localhost:4200",
});
console.log("RxServer: rpl endpoint created ", replicationEndpoint.urlPath);

await rxServer.start();
```

**Comment by snimmagadda1** [comment]
fwiw for my testing, I fixed this by forking the server and changing to `serverApp.use('/' + path + '/*', expressCors({ ` as opposed to `serverApp.options('/' + path + '/*', expressCors({` . Not sure if this is a change wanted in main

**Comment by pubkey** [comment]
Hi @snimmagadda1 you fix looks good. Please make a PR with your fix. Also make sure to include a test case.

**Comment by snimmagadda1** [comment]
sure here's a quick one.. https://github.com/pubkey/rxdb-server/pull/160

**Comment by pubkey** [comment]
Thank you, merged.
