### ISSUE TITLE
Documentation inaccessible at rxdb.info (404)

### ISSUE THREAD

**Issue by agateblue** [pubkey/rxdb#6534]
As of today, all documentation pages shows a 404 error. It worked fine a couple days ago, which leads me to think there was a change or breakage with the documentation deployment? I've reproduced on different devices and browsers.

Below is an example with the quick start page at https://rxdb.info/quickstart:

![Screenshot_20241103-224948_Vivaldi (1)](https://github.com/user-attachments/assets/539fdf69-8af8-48eb-a17f-bd7f7d103836)

**Comment by olivercoad** [comment]
It works fine if you navigate by clicking links in the menus. As soon as you reload or click a link to an anchor point in the right hand side panel, the page shows briefly for a split second before showing the 404.

**Comment by pubkey** [comment]
Yesterday I moved the docs from github pages to cloudflare pages. This likely has caused the problems.
I am not sure what is going wrong at the moment.

**Comment by pubkey** [comment]
This seems to be an unsolved problem with cloudflare pages: https://community.cloudflare.com/t/cloudflare-pages-get-rid-of-redundat-308-redirect/324582?page=2

**Comment by pubkey** [comment]
@agateblue  Thank you for reporting. I will stay on github pages until I found a better and working solution.
