### ISSUE TITLE
bulkInsert with primary keys set in preInsert hook broken in v15.38.3

### ISSUE THREAD

**Issue by kpala** [pubkey/rxdb#6599]
I have a setup where the primary keys are generated in a `preInsert` hook. Using this setup with `bulkInsert` worked fine in v15.38.2.

Upgrading to v15.38.3 produces `RxError (COL22)`.

It seems the recently introduced check for duplicates collects primary keys too early, before the `preInsert` hook has been run: https://github.com/pubkey/rxdb/commit/dcc329731e4330fce6ea9bf3f69958279b660e40

(I don't know how many are using the `preInsert` hook for setting the primary key, but at least to me that seemed like the correct place to do so.)

**Comment by pubkey** [comment]
From the code it looks like it runs after the pre-insert hook: https://github.com/pubkey/rxdb/blob/dcc329731e4330fce6ea9bf3f69958279b660e40/src/rx-collection.ts#L410

**Comment by kpala** [comment]
> From the code it looks like it runs after the pre-insert hook

Correct, the check itself runs after the pre-insert hook, but gathering primary keys happens before the hook:

```ts
                docsData.map(docData => {
                    ids.add((docData as any)[primaryPath]);       <----------- collects ids too early
                    const useDocData = fillObjectDataBeforeInsert(this.schema, docData);
                    return this._runHooks('pre', 'insert', useDocData)    <------------ pre-insert
                        .then(() => {
                            return { document: useDocData };
                        });
                })
```

Therefore, the `ids` will contain only undefined values, if the primary keys are set in the pre-insert hook.

**Comment by pubkey** [comment]
I see. You can make a PR with a change for that. Please ensure that you do not run additional loops.
