### ISSUE TITLE
Document vs LocalDocument in 1 Collection

### ISSUE THREAD

**Issue by LeTienHanh** [pubkey/rxdb#663]
I have a schema as below:
```
const boundaryMgmtSchema = {
  version: 0,
  type: "object",
  properties: {
    boudariesGrp: {
      type: 'array',
      uniqueItems: "false",
      item: {
        type: 'object',
        properties: {
          bndrPlnId: {
            type: "string",
          },
          bndrPlnNm: {
            type: "string",
          }
        }
      },
      default: [],
    },
  }
};

await boundaryMgmtCol.insert({
      boudariesGrp: boundaryGroups
 });

```
and I have one localDocument with id = 'metadata'
```
 await boundaryMgmtCol.insertLocal('metadata', {
      userData: {},
      selectedBndrPlnId: LOCAL_METADATA.NONE,
      actionRev: 0,
      bndrId: LOCAL_METADATA.NONE,
      direction: LOCAL_METADATA.NONE,
    });
```
 The problem raise when I update 1 filed in localDocument
```
const metadata = await boundaryMgmtCol.getLocal('metadata');
metadata.set('selectedBndrPlnId', grpId);
await metadata.save();
```
and I select data again
```
const data = await boundaryMgmtCol.findOne().exec();
=>>>> data.boudariesGrp
```

but **boudariesGrp** value is undefined. 
Please help me check this case and please let me know if I have any wrong. Thank you.

**Comment by pubkey** [comment]
Queries like findOne do not return local documents. [See here](https://pubkey.github.io/rxdb/rx-local-document.html)

**Comment by LeTienHanh** [comment]
I mean after I updated data for LocalDocument, data in normal Document is changed to undefined => I don't why ✌️

**Comment by pubkey** [comment]
Sry. didn't see that from the sample-code. Can you make a PR with a failing test?

**Comment by pubkey** [comment]
I tried to reproduce this in the attached commit, but could not. Please reopen with a test.
