### ISSUE TITLE
Collection size

### ISSUE THREAD

**Issue by skycult** [pubkey/rxdb#665]
Hi,

I use the awesome RxDb with the pouchdb-adapter-idb plugin inside a Cordova App. How I can read the size of every collection?
Thank you!
All the best

**Comment by pubkey** [comment]
I do not think this is possible. Each collection has it's own pouchdb-instance, so you could try [this](https://www.npmjs.com/package/pouchdb-size).

For common questions please use the gitter-channel, as described in the issues-template.
