### ISSUE TITLE
LOCK: No such file or directory

### ISSUE THREAD

**Issue by esindger** [pubkey/rxdb#677]
## Case
Bug

## Issue
Error occur if a collection has a slash `/` in the name `folder/collection`:
```
OpenError: IO error: /path/to/store/data/db-rxdb-0-folder/collection/LOCK: No such file or directory
    at /path/to/node_modules/levelup/lib/levelup.js:91:23
    at /path/to/node_modules/deferred-leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
    at /path/to/node_modules/deferred-leveldown/deferred-leveldown.js:19:21
    at /path/to/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```
I guess the problem is here: https://github.com/pubkey/rxdb/blob/master/src/rx-database.js#L545 and the next code can fix the error:

```
const pouchLocation = dbName + '-rxdb-' + schemaVersion + '-' + collectionName.replace(/\//g, '');
```

## Info
  - Environment: Node.js
  - Adapter: LevelDB
  - Stack: JavaScript

**Comment by esindger** [comment]
Done.

**Comment by pubkey** [comment]
@esindger 
If you use a fs-adapter, set the folder starting with `./`. So in the test you should use `./folder/crawlstate`
The proposed fix will will remove all backslashes. This is not an option.
Can you ensure that the folder you specifiy as adapter-location, exists.

**Comment by esindger** [comment]
I am using the `pouchdb-adapter-leveldb` adapter. I've tried to replace `folder/crawlstate` to `./folder/crawlstate` in the test and got an error:
`OpenError: IO error: vfqttsdjmk-rxdb-0-./folder/crawlstate/LOCK: No such file or directory`

What I do wrong? Can you provide complete example?

**Comment by pubkey** [comment]
Does the `folder/` exist or do you assume that it will be created when the database is spawned?

**Comment by pubkey** [comment]
@esindger sry for the late answer. I understood this now, this is a bug. Fix will come soon.
