### ISSUE TITLE
how to use sqlite instead of asyncstorage in react native ???

### ISSUE THREAD

**Issue by kunaldodiya** [pubkey/rxdb#678]
how to use sqlite instead of asyncstorage in react native ??? It seems that sqlite perform much faster than asyncstorage.. please help me integrating sqlite plugin :)

https://github.com/craftzdog/react-native-sqlite-2 this is the plugin i want to use :)

**Comment by pubkey** [comment]
I'm sorry but this is not a wishlist. Also we have an issue-template for a reason.

If you want to use any adapter with rxdb, get it working with pouchdb first and then you can use it with rxdb.

**Comment by hjonac** [comment]
I did it following these steps: [source](https://dev.to/craftzdog/hacking-pouchdb-to-use-on-react-native-1gjh)

Install SQLite3 engine modules:

`yarn add pouchdb-adapter-react-native-sqlite react-native-sqlite-2`

`react-native link react-native-sqlite-2`

Create polyfills:

`yarn add base-64 events`

```
import {decode, encode} from 'base-64'

if (!global.btoa) {
    global.btoa = encode;
}

if (!global.atob) {
    global.atob = decode;
}

// Avoid using node dependent modules
process.browser = true
```

Import it at the first line of your index.js

Use with RxDB

```
import * as RxDB from 'rxdb';
import SQLite from 'react-native-sqlite-2'
import SQLiteAdapterFactory from 'pouchdb-adapter-react-native-sqlite'

const SQLiteAdapter = SQLiteAdapterFactory(SQLite)

RxDB.plugin(SQLiteAdapter);
RxDB.plugin(require('pouchdb-adapter-http'));

```

**Comment by Unforgiven-wanda** [comment]
Hello @hjonac 
Could you please share  a repo with a working example? Because I get the following error myself:
```
RxError: RxError:
RxDatabase.create(): Adapter not added. Use RxDB.plugin(require('pouchdb-adapter-[adaptername]');
Given parameters: {
adapter:"SQLiteAdapter"}
RxError: RxError:
RxDatabase.create(): Adapter not added. Use RxDB.plugin(require('pouchdb-adapter-[adaptername]');
```

SQLiteAdapter also shows this:
```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
```
