### ISSUE TITLE
Define `_id` as `primary` in the schema

### ISSUE THREAD

**Issue by will118** [pubkey/rxdb#681]
## Issue
I wish to define `_id` as `primary` in the schema.

We have (legacy) reasons for wanting to use `_id` as the `primary`.

We could instead use `id` and let `RxDB` set `_id`. This passes our sync_gateway validator function but it doesn't work with our Typescript model definitions.

Is there a reason why the following is not possible?

## Code

```js
const RxDB = require("rxdb");
RxDB.plugin(require("pouchdb-adapter-memory"));

async function test() {
  const db = await RxDB.create({
    name: 'testdb',
    adapter: 'memory',
    multiInstance: false
  });

  const mySchema = {
    version: 0,
    disableKeyCompression: true,
    type: 'object',
    properties: {
      _id: {
        type: 'string',
        primary: true
      },
      name: {
        type: 'string'
      }
    }
  };

  const collection = await db.collection({
    name: 'person',
    schema: mySchema
  });

  const doc = {
    _id: "foobar",
    name: "abc"
  };

  await collection.insert(doc);
}
test();
```

**Comment by will118** [comment]
I am happy to work on a PR if there is no reason for the current limitation

**Comment by pubkey** [comment]
Hi @will118 
Sorry for the late answer.
I thought a lot about this, and yes, using `_id` as primary should be possible to make migrations from and to pouchdb easier. We should also make sure that `_id` is not allowed as non-primary field because this would cause many strange bugs.

**Comment by will118** [comment]
@pubkey This is great news.

I got started writing some tests and changing code, but ran into an issue with field names with leading underscores.

I looked through the history and it goes all the way back to the initial commit (at least on GitHub): https://github.com/pubkey/rxdb/blob/db92c863ec3350b08653e22a89a55a1b9bb3c092/lib/RxSchema.js#L218-L219

I understand why there [cannot be a property with a trailing underscore](https://pubkey.github.io/rxdb/population.html), but I am unsure about why no leading underscores.

Is the issue that the getters defined on `RxDocument` could clash with internal properties?

**Comment by pubkey** [comment]
@will118 we disallowed private (=leading underscore) fields, so when some internal methods are introduced, it would never happen that someone uses the method-name as fieldname and then have a problem using rxdb which could only be solved by migrating the data.
With your change, the check should still persist but not match `_id` as exception.

**Comment by pubkey** [comment]
Any update on this?

**Comment by pubkey** [comment]
I am closing this. A PR is still welcomed, please reopen if you plan to create one.
I will not do the change by myself because I think this is an edge-cast and I do not need it, but it would be helpful for others.

**Comment by SuperKirik** [comment]
Hello !
@pubkey @will118 
For some reason I'm getting 
`fieldnames do not match the regex` for _id field which is set as primary.

My schema:
```
{
  title: 'schema',
  version: 0,
  primaryKey: '_id',
  properties: {
    _id: {
      type: 'string',
      primary: true,
     },
    contractId: {
      type: 'string',
    },
  },
};
```

Is it a bug ?

**Comment by SuperKirik** [comment]
It looks like a bug considering what I'm reading here... So maybe I supposed to post a new issue

**Comment by pubkey** [comment]
@SuperKirik looks like a bug, create a PR with a failing test.

**Comment by SuperKirik** [comment]
I tried to run bug-report.test.ts, but I faced some error 
`ReferenceError: performance is not defined`

**Comment by SuperKirik** [comment]
@pubkey PR  with test is done
