### ISSUE TITLE
How to initialise database instance in different react native component ?

### ISSUE THREAD

**Issue by kunaldodiya** [pubkey/rxdb#687]
I am using RXDB with ReactNative, for one component it's working fine. 

example:- App.js

```
async componentWillMount(){
 const db = await RXDB.create({
   name: "test"
 })

this.db = db;
}

async insertData(){
const insert_data = await this.db.posts.create({
title: "some title"
})
}
```

above example working fine with one component.. but if i have one more component let say, Home.js

then How can i get Database instance ?? cause if i again do something like...

```
async componentWillMount(){
 const db = await RXDB.create({
   name: "test"
 })

this.db = db;
}

async getData(){
const get_data = await this.db.posts.find({
_id: "document id"
})
}
```

it says database already exists.. how can i get this created database instance in every component ???

**Comment by pubkey** [comment]
Hi @kunaldodiya 
Use a service that creates the database at the first call and returns the single instance on following calls.
This is also done in the examples, [see here](https://github.com/pubkey/rxdb/blob/master/examples/react/src/Database.jsx#L67)
