### ISSUE TITLE
maybe we can choose a better jsonschema lib?

### ISSUE THREAD

**Issue by xialvjun** [pubkey/rxdb#69]
there is a (json schema benchmark repo](https://github.com/ebdrup/json-schema-benchmark)...

maybe we can choose between them for a faster validate time and a smaller bundle size.

**Comment by pubkey** [comment]
Great idea. I will investigate.
Previously we used ajv but it's hard to get it working for everyone using webpack.

**Comment by pubkey** [comment]
I switched from jsonschema to is-my-json-valid
Speed on pure validation went from 433ms to 3.5ms on nodejs. (5000 validations)

The other libs in the benchmarks had some problems when either used with webpack or babel or nodejs.

See [this commit](https://github.com/pubkey/rxdb/commit/f0ffd0bc7725a94e3d6537b06332cb85352fc0a2)

**Comment by xialvjun** [comment]
That's cool...
