### ISSUE TITLE
Populate relationship in subscription ???

### ISSUE THREAD

**Issue by kunaldodiya** [pubkey/rxdb#692]
Hello there,
I am using RxDB in ReactNative, and i have posts subscription in componentWillMount section

```
class Posts extends React.Component {
  constructor(props) {
        super(props);

        this.state = {
            posts: []
        }
  }

  async componentWillMount() {
        this.db.posts.find().$.subscribe(posts => {
            this.setState({ posts })
        });
  }

   // render function

   // showPosts function
 }
```

Each posts has a owner that reference to user collection:-

```
const PostSchema = {
version: 0,
    title: 'post schema',
    description: 'describes a simple post',
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        owner: {
            ref: "users",
            type: 'string'
        }
    }
}
```
now in render method I am using FlatList to show all posts, but i can not access post's owner

```
    render() {
        <FlatList
            data={this.state.posts}
            renderItem={(data) => this.showPosts(data)}
            keyExtractor={(item, index) => index.toString()} />
    }
    
    showPosts(data) {
        const post = data.item;

        return (
            <View>
                <Text>title:- {post.title}</Text>
                <Text>owner:- {post.owner_.name}</Text>
            </View>
        )
     }
```

*post.owner_.name* is undefined cause it is a promise but i can not use async/await in showPosts

How can i get direct object instead of promise ???

**Comment by pubkey** [comment]
Hi @kunaldodiya 
The resolving of relations will always be async. It is not possible that it returns the directy value instead of a promise.

In react you do not have an async-pipe and so cannot magically add the relation into the template.

In your use-case you should resolve all relations in the `componentWillMount` and remember them in a seperate object in your state. Then you can later add this as template-variable.
