### ISSUE TITLE
Same query producing a different result?

### ISSUE THREAD

**Issue by devfelipereis** [pubkey/rxdb#698]
## Case
BUG

## Issue
Same query producing a different result.

## Info
  - Environment: Ionic 3
  - Adapter: IndexedDB
  - Stack: Typescript, Angular, Ionic

@ionic/app-scripts : 3.1.8
Cordova Platforms  : android 7.0.0
Ionic Framework    : ionic-angular 3.9.2

"pouchdb-adapter-http": "^6.4.3"
"pouchdb-adapter-idb": "^6.4.3"
"rxdb": "^7.4.4"
"rxjs": "5.5.8"

## Code

```js
  db.collections['post']
      .find({
        $and: [
          { event_id: { $eq: 2 } },
          { user_id: { $eq: '6' } },
          { created_at: { $gt: null } },
        ],
      })
      .sort({ created_at: 'desc' })
      .exec().then(data => console.log(data));
```

```js
 db.collections['post']
      .find().where('event_id').eq(2).where('user_id').eq('6').where('created_at').gt(null)
      .sort({ created_at: 'desc' })
      .exec().then(data => console.log(data));
```

I'm new with rxdb but I think that this queries do the same thing, right?

In the first query I also get results that "event_id" is equals 1. In the second query this does't happen. 
Any ideia?

**Comment by pubkey** [comment]
Your queries are correct. This looks like a bug. Can you submit a failing PR to reproduce this? You can start by editing this file: https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js

**Comment by pubkey** [comment]
I could not reproduce this with the attached test. Please reopen this with a reproducing test-case

**Comment by gvuyk** [comment]
I've been tracking this bug/feature? for a little while now and I think I found it.
When you make 2 equal queries, the second just returns the cached results from the first (that is, if the cache wasn't invalidated by an insert or something else), now, if you alter the results array from the first query, the second returns the same altered results

**How to reproduce**
```js
docs = await collection.find({}).exec()    // docs.length == x
docs.splice(0, 1);                         // docs.length == x-1
docs = await collection.find({}).exec()    // docs.length == x-1
```
Is this your case @devfelipereis?

**Comment by pubkey** [comment]
@gvuyk that might be the case. I think `exec()` then should always return a new array to prevent this.

**Comment by pubkey** [comment]
@devfelipereis have you enabled the query-change-detection?

**Comment by pubkey** [comment]
@gvuyk I fixed the problem with mutating result-arrays.
@devfelipereis Please create a test, screenshots do not really help. I believe you that there is a problem, you do not have to create further evidence. We need something that I can use to reproduce and fix this.
