### ISSUE TITLE
Avoid monkey-patching localstorage-down?

### ISSUE THREAD

**Issue by nolanlawson** [pubkey/rxdb#7]
Hi! :wave: I just read through the README and love this concept!

Anyway, I noticed you're monkey-patching localstorage-down [here](https://github.com/pubkey/rxdb/blob/db92c863ec3350b08653e22a89a55a1b9bb3c092/plugins/adapter-localstorage/localstorage-down/lib/localstorage.js#L44-L49). I can see how the in-memory keys would cause problems for multi-tab; I think this is just a bug in [localstorage-down](https://github.com/No9/localstorage-down) that should probably be fixed in that library. Most likely it should also be applied to fruitdown and fsdown as well since they're based on localstorage-down. Would you be so kind as to open up a PR? :D

**Comment by pubkey** [comment]
Hi @nolanlawson .Maybe you have seen my [issue](https://github.com/pouchdb/pouchdb/issues/5965) describing the problem.

I dont know how much performance it costs to regrap the keys every time. Do you think my monkey-patch is a valid solution?

**Comment by pubkey** [comment]
I created a [pull-request](https://github.com/No9/localstorage-down/pull/82)
