### ISSUE TITLE
jsnext entrypoint is processed with regenerator

### ISSUE THREAD

**Issue by ghost** [pubkey/rxdb#718]
## Case

Other

## Issue

I'm loading this library with Webpack babel-loader, and all of my desired targets support `async/await`.
I want to configure Webpack to load the non-transpiled version of rxdb.

It picks up the `module` field in `package.json` and loads `./dist/es/index.js`, however this file has been transpiled with regenerator.  Regenerator adds bloat to the webpack bundle and also obfuscates stack traces.

If I update the `mainFields` in my `webpack.config.js` to look at `jsnext:main`, it still loads the transpiled source because `jsnext:main` uses the same value as `module`.

I would assume "jsnext" means: use all JS features available (or "I'll transpile it myself.")

Please either change it to `./src/index.js` or add another entry so I can reference that main field.

Currently I am working around the issue with:
```js
{ resolve: { alias: { rxdb$: path.resolve( __dirname, 'node_modules', 'rxdb', 'src', 'index.js' ) } } }
```

**Comment by pubkey** [comment]
Hi @errorx666 
As far as I understand, `jsnext:main` is just an old version of the `module` attribute. `jsnext:main` is not used to declare es8-files. See [here](https://github.com/jsforum/jsforum/issues/5) and [here](https://www.reddit.com/r/javascript/comments/5jwg9c/confused_about_fields_module_and_jsnextmain_in/dbjjt6x/).

If you want to use the non-transpiled version of rxdb, you can always directly require the source like

```js
import RxDB from 'rxdb/src/index.js';
```
