### ISSUE TITLE
Collection name validation is too strict

### ISSUE THREAD

**Issue by errorx666** [pubkey/rxdb#720]
## Case

Bug

## Issue
The regular expression here:

https://github.com/pubkey/rxdb/blob/41cb52e490194deda2f8da1cc2e6aafc5708002b/src/util.js#L194

The link here:
https://github.com/pubkey/rxdb/blob/41cb52e490194deda2f8da1cc2e6aafc5708002b/src/util.js#L171

Is 404 Not Found, but an older version of it says:

> A database must be named with all lowercase letters (a-z), digits (0-9), or any of the ''_$()+-/'' characters and must end with a slash in the URL. The name has to start with a lowercase letter (a-z).

This suggests that a more accurate regex would be `^[a-z][_$a-z0-9]*$` (excluding `()+-/` because they are not valid in JavaScript identifiers).

**Comment by errorx666** [comment]
If you don't want to allow $ and _ in the terminal position because it's reserved, I can amend the regex in my PR for that.
I really just want an underscore in the middle of a name.

**Comment by pubkey** [comment]
Hi @errorx666 thank for the PRs and Issues. I am currently working hard on rxdb v8.0. The review will take a while but will come. Just that you know..
