### ISSUE TITLE
find() does not find all matching documents

### ISSUE THREAD

**Issue by errorx666** [pubkey/rxdb#724]
## Case
I've been able to reproduce this issue on Node 10.7.0 and in the browser (Chrome), both in Windows and in Linux.  It happens with both the 'idb' and 'memory' adapters (at least).

I'm defining a cross-reference entity for a many-to-many relationship.  When I search for one ID in the relationship, I get a result, but when I search for the other ID, I get no result!

I've managed to reduce the repro down to this:

```ts
import RxDB from 'rxdb';
import adapter from 'pouchdb-adapter-idb';
import assert from 'assert';

( async () => {
  RxDB.plugin( adapter );
  const dbName = 'repro';
  RxDB.removeDatabase( dbName, 'idb' );
  const db = await RxDB.create( { name: dbName, adapter: 'idb' } );
  const roomsession = await db.collection( { name: 'roomsession', schema: {
    version: 0,
    type: 'object',
    properties: {
      roomId: { type: 'string' },
      sessionId: { type: 'string' }
    }
  } } );

  const roomId = 'roomId';
  const sessionId = 'sessionID';
  const inserted = await roomsession.insert( { roomId, sessionId } );
  const foundByRoomId = await roomsession.findOne( { roomId } ).exec();
  const foundByRoomAndSessionId = await roomsession.findOne( { roomId, sessionId } ).exec();
  const foundBySessionId = await roomsession.findOne( { sessionId } ).exec();
  
  assert( foundByRoomId != null ); // fail
  assert( foundByRoomAndSessionId != null ); // fail
  assert( foundBySessionId != null ); // pass
  assert( foundBySessionId.roomId === roomId && foundBySessionId.sessionId === sessionId ); // pass
} )();
```

Shown above, I insert a record with two known ID values.  I then fetch with the left ID, the right ID, and both IDs.  Only one succeeds, but I would expect all three to give the same result.  At the end, I verify that the found record matches both IDs searched for.

This happens both with `find` and with `findOne`.

I've tried adding a surrogate primary keys and a compound index, to no effect.

**Comment by doriandrn** [comment]
Hello there,

_Jumping in to throw a helping hand_

I think you should be indexing the two IDs by adding (```{ index: true }``` to properties):
In your schema:

```js
const roomsession = await db.collection( { name: 'roomsession', schema: {
    version: 0,
    type: 'object',
    properties: {
      roomId: { type: 'string', index: true },
      sessionId: { type: 'string', index: true }
    }
  } } );```

**Comment by errorx666** [comment]
@doriandrn After changing the above to add `index: true` (with no other changes), all three variables are null, so the first three asserts fail and the fourth throws on null.

**Comment by doriandrn** [comment]
Hi there,

My bad, that was incorrect.
You actually need a *primary* just for the roomId key and sessionId should use '$eq' operator to do the string comparission. Here's how it should be:

```js
import RxDB from 'rxdb';
import adapter from 'pouchdb-adapter-idb';

function assert(v) {
  console.log(v ? 'pass' : 'fail');
}

(async () => {
  RxDB.plugin(adapter);
  const dbName = 'repro';
  RxDB.removeDatabase(dbName, 'idb');
  const db = await RxDB.create({ name: dbName, adapter: 'idb' });
  const roomsession = await db.collection({
    name: 'roomsession',
    schema: {
      version: 0,
      type: 'object',
      properties: {
        roomId: { type: 'string', primary: true },
        sessionId: { type: 'string' }
      }
    }
  });
  const roomId = 'roomId';
  const sessionId = 'sessionID';
  const inserted = await roomsession.insert({ roomId, sessionId });
  const foundByRoomId = await roomsession.findOne({ roomId }).exec();
  const foundByRoomAndSessionId = await roomsession.findOne({ roomId, sessionId: { $eq: sessionId } }).exec();
  const foundBySessionId = await roomsession.findOne({ sessionId }).exec();

  assert(foundByRoomId != null);
  assert(foundByRoomAndSessionId != null);
  assert(foundBySessionId != null);
  assert(foundBySessionId && foundBySessionId.roomId === roomId && foundBySessionId.sessionId === sessionId);
})();

**Comment by pubkey** [comment]
I do not think the primary is necessary, but the queries are not correct mango-queries.
As @doriandrn  said, you need to use `$eq` for comparisons.
To find by primary you can do `...findOne(roomId)`

**Comment by errorx666** [comment]
The primary key is { roomId, sessionId }.  Neither is unique, so neither is suitable as a primary key.

**Comment by pubkey** [comment]
I added a test to ensure this works.
Your problem was likely caused by #741
