### ISSUE TITLE
rxdb idb adapter doesn't work on ios platform

### ISSUE THREAD

**Issue by cw196** [pubkey/rxdb#725]
rxdb idb adapter doesn't work on ios platform, it's working on private mode though.

The problem is due to https://github.com/pouchdb/pouchdb/issues/7057.

Can you guys fix it? thanks!

**Comment by pubkey** [comment]
Hi @cw196 
This seems to be fixed in `pouchdb@7.0.0`
RxDB version 8.0.0 will soon be released, there this will be solved.
