### ISSUE TITLE
sort doesn't work in websql adapter.

### ISSUE THREAD

**Issue by cw196** [pubkey/rxdb#726]
The sort function will return nothing when using websql adapter, the idb is working fine.

ex. 
    db.heroes.find().sort({name: 1})

**Comment by pubkey** [comment]
Hi @cw196 
Can you produce a test-case?
You can start by [editing this file](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js).

Please use the issue-template for further problems.

**Comment by pubkey** [comment]
I think this is a duplicate of by #741
