### ISSUE TITLE
Is it possible to export a single document to JSON?

### ISSUE THREAD

**Issue by rmisio** [pubkey/rxdb#731]
Is there anyway to dump a single document instance into JSON, basically get the flat data without any of the internal methods?

![image](https://user-images.githubusercontent.com/794517/43162677-a3ca528a-8f40-11e8-9b45-2c6a3378c068.png)

So that is what I get via `document.get()` and I'd like to have the data up to an including `peerId`, but none of the remaining internal stuff.

**Comment by pubkey** [comment]
Hi @rmisio 
You can use `myDocument.toJSON()`. I have seen that it is not documented, a PR would be welcomed.
For other missing functions, check [the typings](https://github.com/pubkey/rxdb/blob/master/src/typings/rx-document.d.ts#L44)
