### ISSUE TITLE
Possible bug using pouchdb in conjunction with find() of RxDB

### ISSUE THREAD

**Issue by Celludriel** [pubkey/rxdb#733]
Consider the following two code pieces

```
        const data = JSON.parse(fs.readFileSync(appPath + '/data/data.json', 'utf-8'));

        this.db = await this.createDatabase();

        let card;
        for(card in data.cards){
            if(card !== undefined){
                await this.db.cards.insert(data.cards[card]);
            }
        }

        await this.db.cards.find()
            .where('name')
            .eq('Deoxys ex')
            .exec()
            .then(documents => this.setState({
                    documents: Object.assign({}, this.state.documents, documents)
                }));
```
This one works and gives me my card with name 'Deoxys ex' as it is supposed to do.  Now consider this next one.

```
        const data = JSON.parse(fs.readFileSync(appPath + '/data/data.json', 'utf-8'));

        this.db = await this.createDatabase();

        await this.db.cards.pouch.bulkDocs(data.cards);

        await this.db.cards.find()
            .where('name')
            .eq('Deoxys ex')
            .exec()
            .then(documents => this.setState({
                    documents: Object.assign({}, this.state.documents, documents)
                }));
```
This time I get no results.

I wanted to use bulkDocs since my data.json is 10 mb large with over 9500 objects in it.  Inserting this object by object was killing performance.  I'm building a desktop app with electron and react, having to wait 5 mins to load in the json file as a database is to long so I wanted to leveraged bulkDocs.  However I can't seem to query after it

**Comment by pubkey** [comment]
Hi @Celludriel 
Have you disabled the keyCompression? If no, please do so.
Whenever you use a pouchdb-function directly, there will be no key-compression and also no encryption on your data. Therefore you would have to do this first, or disable keyCompression and encryption.

**Comment by Celludriel** [comment]
Hi @pubkey ,

I haven't done any special setup, so I assume I didn't.  I'll consult the manual how to do so and get back to you after my workday

Thanks for the speedy response

**Comment by Celludriel** [comment]
Hi @pubkey ,

adding the line keyCompression false to the Schema did the trick, so no bug working as intended

Sincerely
