### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by z3214965** [pubkey/rxdb#738]
![1](https://user-images.githubusercontent.com/18589356/43433128-9a66cee0-94a8-11e8-92db-a875e000a986.PNG)
![4](https://user-images.githubusercontent.com/18589356/43435392-5e06f7e0-94b2-11e8-93b0-c22cf68d1d02.PNG)
![2](https://user-images.githubusercontent.com/18589356/43433135-a08040c2-94a8-11e8-8408-a74840b10651.PNG)
![3](https://user-images.githubusercontent.com/18589356/43433139-a47e51aa-94a8-11e8-8992-815b2550cd2b.PNG)
hi
when i use rxdb，i have a question about global is not defined，I don't know what's going on，Can you help me see what's going on，thank you，

**Comment by pubkey** [comment]
Hi @z3214965 
 This is a pouchdb-problem [see here](https://github.com/pouchdb/pouchdb/issues/7299). It is fixed with `pouchdb@7.0.0` which will come with `rxdb@8.0.0` which will come in a few weeks.

.Please do [never screenshot code](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by z3214965** [comment]
@pubkey 
you mean i want use rxdb，i must use angular5？

**Comment by pubkey** [comment]
@z3214965 
@fuerst wrote at gitter:
```
For people who are plaqued by Electron 2/Angular 6 compiling errors like: node_modules/@types/core-js/index.d.ts(355,48): error TS2304: Cannot find name 'PropertyKey'. Reason is RxDB installs a @types/core-js in it's node_modules subdirectory which may conflict with your own @types/core-js. You can define which will be used by the TypeScript compiler at the command line: tsc --typeRoots ["node_modules/@types"] main.ts. Note: tsconfig.json files get ignored once you specify input files when calling tsc. So defining typeRoots or excludes in the tsconfig.json file does not help. See this issue for details: maximegris/angular-electron#216
```
