### ISSUE TITLE
Some ideas and suggestions

### ISSUE THREAD

**Issue by CrashyBang** [pubkey/rxdb#74]
## Case

Request

## Issue

Currently everything is stored in one place and all issues are going to be logged against the main repo.

I think it would be a good idea to split the main repo, the docs, and the examples into 3 individual repo's and possibly create a public RxDB organisation.

I would also like to move the docs over to a dedicated documentation platform a couple of good options are:

* [Gitbook](https://github.com/GitbookIO/gitbook)
* [Docute](https://github.com/egoist/docute)
* [Docpress](https://github.com/docpress/docpress)
* [Docsify](https://github.com/QingWei-Li/docsify)

Personally I would recommend Gitbook as it has been around a long time and matured really nicely, I would be happy to move the docs over I just want your thoughts before I start :).

Cheers.

**Comment by pubkey** [comment]
Hi @CrashyBang 
RxDB is currently in a monorepo on [purpose](https://github.com/babel/babel/blob/master/doc/design/monorepo.md).
The problem with splitting docs from code is, that very often you change code and docs in the same commit because they belong together. This would not be possible on seperated repos.

We have currently about 10 issues per week, so I don't think its a problem to manage them all in this repo.

Using a creator-lib for the documentation is a good idea, I will think about it and write you here in the next days.

**Comment by CrashyBang** [comment]
@pubkey Good resource I will consider that for my future projects :).

Is that including the examples or do you think we could still benefit from moving these?

Awesome will wait for a response.

Cheers.

**Comment by pubkey** [comment]
I thought a lot about it and yes, we need something to generate a static page for our docs.
The thing is, that if something get's merged into the master, the code is equal to the documentation. But this is not true for the published version on npm. If you `npm i rxdb`, it can happen that features are in the docs which are not already published to the newest release.

The solution I have in my mind would be a npm-script which runs `prepublish`, generates a static page and puts it into the dist-folder. Github-pages should always display the newest version in the dist-folder.

@CrashyBang Which of the mentioned platforms can you recommend?

**Comment by CrashyBang** [comment]
Hey @pubkey,

I will need a little bit of time to dig into this and see which one fits the bill best I may be able to get onto that this weekend is that okay?

Cheers.

**Comment by pubkey** [comment]
Nice to hear. Don't hurry, we have time :)

**Comment by pubkey** [comment]
DONE. Docs are now online via gitbooks [here](https://pubkey.github.io/rxdb/)
