### ISSUE TITLE
Feature request: sync on remote queries

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#745]
## Case
As outlined in #543 , we must set up new pouch instances for each RxCollection in order to sync them. It's currently possible, though, to sync documents of a collection that show up in a specific query, but only for local queries. It would be amazing to have the same feature for remote documents - so only documents on a specific query on that pouchdb instance sync down with that collection. This way, we could add some unique identifier of each collection to documents pertaining to it, and sync all of our RxCollections with the same remote instance.

Is this something that would be possible to accomplish?

**Comment by pubkey** [comment]
As far as I know, this is possible atm. The queried sync uses the query on up and downstream.

**Comment by rafamel** [comment]
It's not happening. This should be treated as a bug report then. I'll investigate the issue keeping this in mind, open a bug report, and close this issue when I do. Sounds good?

Rafa

**Comment by rafamel** [comment]
Closing as I opened #758 as per this thread.
