### ISSUE TITLE
RxQuery subscription returns null as first result when ran immediately after another subscription or exec()

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#749]
## Case
This seems to be a bug in the way queries are subscribed to.

## Issue
A query subscription will return `null` as its first result when run immediately after another subscription to that same query or an `exec()`. This doesn't seem to happen when two `exec()`'s are followed by each other for that same query, or if some undetermined space of time is left between the two `exec()` + subscription  /  subscription + subscription.

## Info
  - Environment: browser
  - Adapter: idb & memory
  - RxDB: 7.7.1

## Code

```js
const RxDB = require('rxdb');
RxDB.plugin(require('pouchdb-adapter-memory'));

async function test() {
  const db = await RxDB.create({
    name: 'testdb',
    adapter: 'memory',
    multiInstance: false
  });

  const schema = {
    version: 0,
    type: 'object',
    primaryPath: '_id',
    properties: {
      name: {
        type: 'string'
      }
    }
  };

  const collection = await db.collection({
    name: 'person',
    schema: schema
  });

  await collection.insert({ name: 'some name' });

  let first1, first2, second2, first3, second3, prom1;
  const subs1 = collection.find().$.subscribe((x) => {
    first1 = x;
    subs1.complete();
  });

  let i2 = 0;
  const subs2 = collection.find().$.subscribe((x) => {
    if (i2 === 0) {
      first2 = x;
      return i2++;
    }
    second2 = x;
    subs2.complete();
  });

  // Let's try with a different query
  collection
    .find()
    .sort('_id')
    .exec()
    .then((x) => (prom1 = x));

  let i3 = 0;
  const subs3 = collection
    .find()
    .sort('_id')
    .$.subscribe((x) => {
      if (i3 === 0) {
        first3 = x;
        return i3++;
      }
      second3 = x;
      subs3.complete();
    });

  const interval = setInterval(() => {
    if (
      first1 !== undefined &&
      first2 !== undefined &&
      first3 !== undefined &&
      second2 !== undefined &&
      second3 !== undefined &&
      prom1 !== undefined
    ) {
      clearInterval(interval);
      // All queries have executed and returned
      console.log('-'.repeat(20));
      console.log('Query .find()');
      console.log('First subscription 1st result', first1);
      console.log('Second subscription 1st result', first2);
      console.log('Second subscription 2nd result', second2);
      console.log('-'.repeat(20));
      console.log('Query .find().sort()');
      console.log('Promise exec', prom1);
      console.log('Subscription 1st result', first3);
      console.log('Subscription 2nd result', second3);
      console.log('-'.repeat(20));
    }
  }, 20);
}
test();
```

**Comment by pubkey** [comment]
I do not fully understand the test-case. Could you minimalize it to only show the error? This would help a lot.

**Comment by rafamel** [comment]
Essentially, if you subscribe to to a query and then subscribe to that same query, the second subscription will have a first result of `null`. Equally, if you call `.exec()` and then you subscribe to the same query, that subscription will have a first result of `null`.

Let's see if this makes things clearer:

```javascript
const RxDB = require('rxdb');
RxDB.plugin(require('pouchdb-adapter-memory'));

async function test() {
  const db = await RxDB.create({
    name: 'testdb',
    adapter: 'memory',
    multiInstance: false
  });

  const schema = {
    version: 0,
    type: 'object',
    primaryPath: '_id',
    properties: {
      name: {
        type: 'string'
      }
    }
  };

  const collection = await db.collection({
    name: 'person',
    schema: schema
  });

  await collection.insert({ name: 'some name' });

  const subs1 = collection.find().$.subscribe((x) => {
    console.log('First subscription', x);
    subs1.complete();
  });

  const subs2 = collection.find().$.subscribe((x) => {
    console.log('Second subscription', x);
    subs2.complete();
  });

  // Let's try with a different query
  collection
    .find()
    .sort('_id')
    .exec()
    .then((x) => console.log('First promise', x));

  const subs3 = collection
    .find()
    .sort('_id')
    .$.subscribe((x) => {
      console.log('Subscription after query.exec()', x);
      subs3.complete();
    });
}
test();
```

**Comment by pubkey** [comment]
This might sound strange, but it is intentional behavior. The RxQuery.$ should behave like a rxjs-BehaviorSubject which always has a value on subscribe and the emits changes.
I did this to allow async pipes with if-selectors in the angular-app which shows the loading spinner as long as the BehaviorSubject emitted `null`.

Overthinking this now, it is confusing because when you do `findOne()` then `null` means that no document was found.

I will change that for `8.0.0`

**Comment by rafamel** [comment]
That makes sense. Though I'm still not sure this happens for the second and not for the first subscription.

I would go with the solution you last proposed (it does make more sense for me, as there is a guarantee of an initial valid resolution), but if this is something you're using, it might make some sense to emit `undefined` instead of `null` in these cases, as it doesn't imply an actual result, and map them to `null` in your app (not sure what you are referring to as I'm not proficient in Angular).

**Comment by pubkey** [comment]
I refactored the whole `rx-query.js` for `8.0.0` and also added your test-case which passes now.

**Comment by rafamel** [comment]
Sounds great! Thanks for addressing this so quickly!

**Comment by gustavomick** [comment]
@pubkey FYI this still happening to me for 8.7.5 with await atomicUpsert then findOne(..).$ i dont have time to properly provide you context (sorry) anyway wanted to know if this is possible or your tests are covering findOne as well. thanks

**Comment by pubkey** [comment]
I am not aware of any bugs. Please provide some context or test to reproduce, otherwise I cannot help.
Also notice that findOne will return null if no document was found.
