### ISSUE TITLE
Uncaught (in promise) Error: cannot populate because path has no ref (name)

### ISSUE THREAD

**Issue by CrashyBang** [pubkey/rxdb#75]
## Case

Bug

## Issue

Receiving the following error when trying to add to retrieve collection:
![selection_001](https://cloud.githubusercontent.com/assets/2978850/23600863/886eab4c-02ad-11e7-9e59-1196a6685aeb.png)

## Info
- Environment: Electron
- Adapter: IndexedDB

## Code
I have the following `listing` component in vue (derived from example code):
```js
import * as Storage from '../storage';
import Banner from '../components/Banner';
import Preview from '../components/Preview';

export default {
    name: 'Listing',
    components: {
        Banner,
        Preview
    },
    data() {
        return {
            title: 'Please select Assignment',
            assignments: []
        };
    },
    mounted: async function() {
        const db = await Storage.get();
        let filter = [];
        filter.push(
            db.assignments
                .find().$
                .filter(x => x != null)
                .subscribe(assignments => {
                    console.log('results:');
                    this.assignments = assignments;
                })
        );
    },
    beforeDestroy() {
        this.assignments.forEach(sub => sub.unsubscribe());
    },
    methods: {
        // removeHero(hero) {
        //     hero.remove();
        // },
        // editHero(hero) {
        //     this.$emit('edit', hero);
        // }
    },
    template: require('./Listing.html')
}
```

**Comment by pubkey** [comment]
Hi @CrashyBang 
I'm aware of this problem. It looks like vuejs is calling every getter on it's change-detection.
I'm still trying to figure out if this is something vuejs should do or if RxDB is the problem.

A workarround would be to only set the lodash-getter (for populate()) if the `ref` is set. But this would still have a bad performance when `ref` exists, since vuejs would call the population-trigger every time.

Do you know if something like angular2's [async-pipe](https://angular.io/docs/ts/latest/api/common/index/AsyncPipe-pipe.html) exists in vuejs?

**Comment by CrashyBang** [comment]
Hey @pubkey,

I don't but I might know someone who does, either way I will do some exploring and see if I can find you a promising fix :),

Cheers.

**Comment by CrashyBang** [comment]
Hey @pubkey,

I have had a look into the [Vue Async Update Queue](https://vuejs.org/v2/guide/reactivity.html#Async-Update-Queue) as well as [vue-rx](https://github.com/vuejs/vue-rx) but I am having trouble understanding the problem.

I am not overly familiar with RxJS other than knowing it is used for observable streams and reactivity.

I might not be the best person to fix this, but perhaps if I can get a clearer understanding I can be more help?

Cheers.

**Comment by CrashyBang** [comment]
Noticed you closed this issue has it been resolved?

**Comment by pubkey** [comment]
Yes its resolved. I will push a patch-version to npmjs after the tests have run in windows-vms

**Comment by CrashyBang** [comment]
Hey @pubkey awesome I was just about to install the specific commit but will wait for the patch :).

**Comment by pubkey** [comment]
@CrashyBang patch is published.
