### ISSUE TITLE
Bug when using two way sync with a query

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#758]
## Case
Bug when using two way sync with a query.

## Issue
As stated in #745 , I've further investigated two way sync with queries so as to sync all collections with the same pouchdb instance.

I'm using a property on the schema to identify each collection (`rx_model`), equivalent to the name of the collection, then, for each collection I'm doing:

```js
collection.sync({
  remote: 'http://localhost:5984/mydb/'
  query: db.collections[name].find().where({ rx_model: { $eq: name } }),
})
```

With this configuration, rxdb will successfully send up documents to the pouchdb instance, however:
* It won't sync down changes for existing local documents.
* it won't sync down new documents, non existing locally. Therefore, if we were to delete local data or open up a different browser and sync down from the server, we would get no documents.

RxDB seems to be continuously querying an non existent endpoint (404): `http://localhost:5984/mydb/_changes?style=all_docs&seq_interval=100&filter=_selector&since=0&limit=100`

## Info
  - Environment: Browser
  - Adapter: idb, memory
  - RxDB: 7.7.1

**Comment by rafamel** [comment]
Regarding this one, it's likely the `_selector` filter doesn't exist because the query filter hasn't let it sync with the remote database. This is documented [here](https://pouchdb.com/2015/04/05/filtered-replication.html).

**Comment by pubkey** [comment]
As mentioned in the docs, local documents will not get replicated.

Can you try this again while ensuring that your adapter version is the same as `pouchdb-core` of rxdb?

**Comment by rafamel** [comment]
`pouchdb-core` is the same version as `rxdb`'s currently.

I'm sorry, I probably wasn't as clear as I would have liked when explaining the issue. When I said local documents, I didn't refer to `RxLocalDocument`s, but rather to documents stored in the local copy of rxdb/pouch, instead of the remote pouchdb/couchdb instance we're syncing the collections to.

The point is, when doing a queried sync, it tries to reach an endpoint that doesn't exist for a `_selector` filter. This filter doesn't exist (hence the 404 error), and it's likely it doesn't because, as per the query, it's not replicating the document for that filter to the remote instance. [The replication query should allow for the filter document to pass so it's in sync in the remote instance too](https://pouchdb.com/2015/04/05/filtered-replication.html) - though this is nothing but my speculation of where the problem lies.

I can also see an issue with naming that filter `_selector`, as if we did multiple filtered replications, the latest filter doc would overwrite the previous.

Again, I'm coming at this with not a lot of knowledge about how RxDB handles this internally, but I'm rather speculating based on how pouch/couch handles it.

**Comment by rafamel** [comment]
This is an issue with `pouchdb-server` and should not appear when using any CouchDB 2.x compatible instance. Closing the issue.
