### ISSUE TITLE
[Question] How to open an existing database?

### ISSUE THREAD

**Issue by tindecken** [pubkey/rxdb#759]
## Case
How to open an existing database?
## Issue
I already create one database with RxDB.create(), and created some collections, put some documents in it
So, in another script, i want to open that database to execute some queries, but I dont know how to do it.
I tried to use RxDB.create() with same database name, but it create new database and override the created database above.

## Info
  - Environment: Electron
  - Adapter: LevelDB
  - Stack: VueJS

## Code

```js
 
```

**Comment by rafamel** [comment]
database.js
```javascript
import * as RxDB from 'rxdb';

export default RxDB.create({
  // ...object
}).then(db => {
  db.collection({ 
    // ...object
  });
  // register other collections
});
```
Other file
```javascript
import dbPromise from './database';

dbPromise.then((db) => {
  // ...do stuff
});
```
Ideally you would have some sort of gate so all your db-dependent components don't mount until the db promise resolves and passes the resolved db as context (or you use closure on the `database.js` to export it synchronously after resolution) so you don't have to deal with async resolution of the db on each single component you use it with.

**Comment by pubkey** [comment]
This is solved. Please ensure that your adapter-version is the same as the pouch-core version of the package.json
