### ISSUE TITLE
[FR] Document _deleted property can't be modified

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#761]
## Case
`doc.remove()` removes document data, making the document not pass replication filters. There should be a way of directly setting the `_deleted` property.

## Issue
With filtered replication, empty documents will not synchronize as they won't pass the filters. Therefore, when removing a document locally, its removal won't be synced remotely. This is documented [here](https://pouchdb.com/api.html#filtered-replication) and [here](https://pouchdb.com/2015/04/05/filtered-replication.html), and it's the case [when syncing all collections with one single remote db for a one db per user setup](https://github.com/rafamel/rxdb-utils#replication).

Right now, as `_deleted` is not part of the document schema, it cannot be modified via RxDB. Provisionally, in order to achieve this, I'm directly `put`ting the changes on the underlying pouchdb instance of the collection, though RxDB won't receive these changes unless it is synced with another database (so I'm creating an additional local db to sync with just in order to be able to do this).

It might even be worth it to think about creating an additional set of methods for setting the `_deleted` property as `true` without removing the document data, or have `doc.remove()` do it automatically when filtered replication is active. This way documents would go through the removal/new method hooks instead of the save hooks when deleting the doc.

## Info
  - Environment: Browser
  - Adapter: idb, memory
  - RxDB: 7.7.1

**Comment by pubkey** [comment]
As described [here](https://github.com/pubkey/rxdb/issues/754#issuecomment-414460526) calling remove will now only set the deleted-flag instead of removing all data. I think this can be closed now.

**Comment by rafamel** [comment]
Sound great. It would also be convenient to document this behavior so there's notice of it - and how it differs from pouchdb removals.

**Comment by pubkey** [comment]
I added the docs [here](https://github.com/pubkey/rxdb/commit/0d77b15dcaffa009170949db17cd54a47d748fdf)
