### ISSUE TITLE
RxDB automatic observe and change data in Vuex

### ISSUE THREAD

**Issue by tindecken** [pubkey/rxdb#762]
## Case
RxDB automatic observe and change data in Vuex
## Issue
1. Create new database, schemas, collections
2. Insert some documents
3. Get documents and store it into store (using Vuex)

**Error**: Vuex throw error: 
**[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers**

It looks like Rxdb always observe and automatically change the data so Vuex throw above error (conflict with Vuex)

![image](https://user-images.githubusercontent.com/4727197/44329910-e4c20800-a48f-11e8-88cc-e8d3bba7e788.png)

**More information:** this issue didn't happen on other DB (PouchDB, Postgresql)
**Question**: How to stop Observe in RxDB?

## Info
  - Environment: Electron
  - Adapter:LevelDB
  - Stack: VueJS, Vuex

## Code
Line 20:  `store.dispatch('testplan/changeTreeViewData', result)`
```js
import * as Database from '../../../backend/Database'
import _ from 'lodash'
import store from '../../store'

async function getTestPlanTree () {
    var result
    const db = await Database.get();
    let categoriesCollection = await db['categories']
	await categoriesCollection.find({
	}).exec().then(async (categories) => {
        result = categories
        for(var i in categories){
            result[i].children = []
        }
        _.forEach(categories, async (category, index) => {
            result[index].children = await category.testsuites_
        })
    }).catch((err) => { console.log('error', err) })
    // console.log('result', result)
    store.dispatch('testplan/changeTreeViewData', result)
    return result
}
export default {
    getTestPlanTree
}
```

**Comment by rafamel** [comment]
At first sight I it could be that you're pouring the documents themselves into the store, whose data will change.

I haven't run it, so take with a grain of salt:
```javascript
import * as Database from '../../../backend/Database';
import _ from 'lodash';
import store from '../../store';

async function getTestPlanTree() {
  const categories = await Database.get().then((db) =>
    db.categories
      .find()
      .exec()
      .catch((e) => console.log('error', e))
  );

  const result = await Promise.all(
    categories.map(async (category) => ({
      ...category._data,
      children: await category.testsuites_
    }))
  );

  store.dispatch('testplan/changeTreeViewData', result);
  return result;
}

export default { getTestPlanTree };
```

**Comment by tindecken** [comment]
Thank you for the help
But it still throw error

![image](https://user-images.githubusercontent.com/4727197/44333710-d0830880-a499-11e8-9f4b-c3c73ce54935.png)

**Comment by tindecken** [comment]
The code i did with postgresql db (use sequelize), it just different above how to get the `result`
```js
import axios from '../../../backend/vue-axios/axios'
import _ from 'lodash';
import store from '../../store'

/**
 * Replace name of key in an object (nested)
 * @param {string} obj - Object need to rename key
 * @param {string} keysMap - keymap contains old and new key
 */
function replaceKeysDeep(obj, keysMap) { // keysMap = { oldKey1: newKey1, oldKey2: newKey2, etc...
    return _.transform(obj, function(result, value, key) { // transform to a new object
  
      var currentKey = keysMap[key] || key; // if the key is in keysMap use the replacement, if not use the original key
  
      result[currentKey] = _.isObject(value) ? replaceKeysDeep(value, keysMap) : value; // if the key is an object run it through the inner function - replaceKeys
    });
  }

async function getTestPlanTree () {
    var results
    await axios({
        method:'get',
        url:`category/testsuite/all`
    }).then((result) => {
        console.log('Result before:', result.data)
        results = result
    }).catch((err) => {
        console.log('Error', err)
        results = null
    })

    // Process result to correct with treeview format of Element UI component (tutorial here: https://stackoverflow.com/questions/39123461/how-to-change-object-keys-in-deeply-nested-object-with-lodash)
    results = replaceKeysDeep(results, {
        TestSuite: 'children',
        TestGroup: 'children'
    })

    _.forEach(results.data, function(category){ //duyệt qua Category[]
        _.forEach(category.children, function(testSuite){ //duyệt qua TestSuite[]
            _.forEach(testSuite.TestCase, function(testCase){ //duyệt qua TestCase --> add vô children
                testSuite.children = _.concat(testSuite.children, testCase)
            })
            delete testSuite.TestCase
            
            _.forEach(testSuite.children, function(tsChild, index){
                if(tsChild.type === "TestGroup"){
                    tsChild.children = tsChild.TestCase
                    delete tsChild.TestCase
                }else if(tsChild.type === "TestCase"){
                    console.log('TestCase', index, tsChild)
                }
            })
        }) 
    })

    console.log('Result after:  ',results.data)
    store.dispatch('testplan/changeTreeViewData', results.data)
    return results
}

export default {
    getTestPlanTree
}
```

**Comment by tindecken** [comment]
More information: if I change `strict: false`, in store, it will not throw the error, but i can't tracked by debugging tools

![image](https://user-images.githubusercontent.com/4727197/44334166-ff4dae80-a49a-11e8-820b-0e0ae5a2a8ad.png)

**Comment by tindecken** [comment]
Sorry @rafamel , i've checked again, your code is works well
Could you please explain for me what i'm doing wrong, much appreciated

**Comment by ngohuunam** [comment]
_data

**Comment by rafamel** [comment]
As I said, you were pouring the document object itself into the store, which will change. As vuex doesn't allow objects to mutate without using its own handlers, you got the error. Instead of putting the whole `RxDocument`, you should be getting the data fields of the document. Calling `toJSON()` on the document like Daniel pointed out instead of what I did getting its `_data` object would be best, though, as `_data` is not public api material (and depending on how RxDB handles changes, could have inner-objects mutations for inner object properties).

**Comment by tindecken** [comment]
Let me open this issue
I'm store the result object with your way (only take data in `_data`), but it still display **Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers** when I create new new data in result object

```js
import * as Database from '../../../backend/Database'
import _ from 'lodash'

async function getTestPlanTree () {
  var result
  try {
    var categories = await Database.get().then((db) =>
      db.categories.find().exec().then()
    )
    result = await Promise.all(
      categories.map(async (category, index, categories)=> ({
        ...category._data, //category
        children: await category.testsuites_.then(async (testsuites) => {
          return await Promise.all(testsuites.map(async (testsuite) => ({
            ...testsuite._data, //testsuite
            children: _.flatten([
              ...await testsuite.testcases_.then(arr => arr.map(({ _data }) => ({ ..._data }))),
              await testsuite.testgroups_.then(async (testgroups) => {
                return await Promise.all(testgroups.map(async(testgroup) => ({
                  ...testgroup._data, //testgroup
                  children: await testgroup.testcases_.then(arr => arr.map(({ _data }) => ({ ..._data })))
                })))
              })
            ])
          })))
        })
      }))
    )
  } catch (e) {
    console.log('error', e);
  }
  return result
}
export {
    getTestPlanTree
}
```
The result is able to store in Vuex without error, but when I try to change the result, it still generate Vuex error above

Below is my simple code to change/create the result

![image](https://user-images.githubusercontent.com/4727197/44637156-c8672380-a9d9-11e8-8a11-13664f1215d5.png)

**Comment by ngohuunam** [comment]
tlTreeViewData của bác là gì đấy

**Comment by ngohuunam** [comment]
bác push vào, vậy là nó là data của component à

**Comment by tindecken** [comment]
yes, below is `TestPlanTree.vue`
https://paste.ofcode.org/5SPiDVM3gakx3cGxgpGmns

**Comment by ngohuunam** [comment]
log result xem là gì được ko bác

**Comment by rafamel** [comment]
On the result piece of the code, substitute for this and let me know afterwards.

```javascript
const result = await Promise.all(
  categories.map(async (category) => ({
    ...category.toJSON(),
    children: await category.testsuites_.then(arr => arr.map(x => x.toJSON()))
  }))
);
```

**Comment by tindecken** [comment]
@rafamel thank for the help, but it still display the same error message

![image](https://user-images.githubusercontent.com/4727197/44666120-9cff2b80-aa0f-11e8-98f2-229e1bc000d2.png)

Result object:

![image](https://user-images.githubusercontent.com/4727197/44666139-a7b9c080-aa0f-11e8-9c0e-8cc74b1b49cf.png)

**Comment by ngohuunam** [comment]
lạ nhỉ? bác có store rxdb object nào khác trong state ko?

**Comment by tindecken** [comment]
@ngohuunam không bạn ơi, hiện tại mình chỉ store cái tlTreeviewData là của DB vô Vuex, mấy cái Vuex khác đều là biến.

**Comment by ngohuunam** [comment]
![error](https://user-images.githubusercontent.com/3610240/44700771-3af90180-aab5-11e8-8bd9-e2a4e612740e.gif)
thế những cái bác log ra đây là gì? có lưu lại trong state ko?

**Comment by tindecken** [comment]
mấy cái này là khi khởi tạo mockdata test thôi

https://paste.ofcode.org/PNZaFP3K6aRUANij8237Kz

**Comment by pubkey** [comment]
I am closing this. As @rafamel said, do never put non-plain-json-objects inside of any store/vuex/redux.

Also I do not think this will be solved here because most of the comments are not in english.

**Comment by tindecken** [comment]
I tried to use deepClone (use lodash library), but the issue is still there

```js
async function getTestPlanTree () {
  var result
  try {
    var categories = await Database.get().then((db) =>
      db.categories.find().exec().then()
    )
    result = _.cloneDeep(await Promise.all(
      categories.map(async (category, index, categories)=> ({
        ...category._data, //category
        children: await category.testsuites_.then(async (testsuites) => {
          return await Promise.all(testsuites.map(async (testsuite) => ({
            ...testsuite._data, //testsuite
            children: _.flatten([
              ...await testsuite.testcases_.then(arr => arr.map(({ _data }) => ({ ..._data }))),
              await testsuite.testgroups_.then(async (testgroups) => {
                return await Promise.all(testgroups.map(async(testgroup) => ({
                  ...testgroup._data, //testgroup
                  children: await testgroup.testcases_.then(arr => arr.map(({ _data }) => ({ ..._data })))
                })))
              })
            ])
          })))
        })
      })))
    )
    // store.dispatch('testplan/changeTreeViewData', result)
  } catch (e) {
    console.log('error', e);
  }
  return result
}
```

**Comment by ngohuunam** [comment]
share vuex code?
