### ISSUE TITLE
Feature request: collection.length (as numeric getter)

### ISSUE THREAD

**Issue by doriandrn** [pubkey/rxdb#783]
## Case
Feature request

## Issue
There is no way of getting the totaling number of documents in a collection.
This is an important thing for various scenarios that come in my mind:
- displaying this for end-user purposes;
- paginating a set of results;
- maintaining limits on certain collections;
- ...

## Info
  - Environment: (Node.js/browser/electron/etc..) all
  - Adapter: (IndexedDB/Localstorage/LevelDB/etc..) all
  - Stack: (Typescript, Babel, Angular, React, etc..) all

## Code

```js
  // Assuming we already have 1337 existing documents in this collection:
  const collection = await myDatabase.collection(/* ... */);
  collection.length // 1337
  await collection.insert({...})
  collection.length // 1338
  const oneRandomDoc = await collection.findOne().exec()
  await oneRandomDoc.remove()
  collection.length // 1337
  /* ... */
```

**Comment by pubkey** [comment]
I thought a lot about this. It would be a nice feature but might have some problem when used in replications because simple counting based on the events will not work.
This should be implemented as RxDB plugin, but this will not be done by me.
