### ISSUE TITLE
The way to inspect the data structure and records from in-memory storage.

### ISSUE THREAD

**Issue by KevinYaoooooo** [pubkey/rxdb#786]
Hi,

RxDB is awesome, can't wait to try it, but I need to ask a question, do we have a tool or extension to the chrome to inspect the data for debugging during the development, just like the Redux chrome extension?

**Comment by pubkey** [comment]
From the issues-template:
```
<!-- IMPORTANT:
  If you have a common question which cannot be solved with a PR, ask it here https://gitter.im/pubkey/rxdb
-->
```

And no, there is no such tool. Maybe there is some pouchdb-tooling that could help you with that. Or you create one :blush:
