### ISSUE TITLE
[FR] Client side conflict resolution

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#789]
It would be really interesting to have a built in way to define conflict resolution for each specific collection on the client side, by specifying the strategy on creation, that would execute whenever replication is denied due to conflicts. Any thoughts?

**Comment by rafamel** [comment]
Sounds great. Having this would be beautiful. Let's leave it open then?

**Comment by pubkey** [comment]
It's in the backlog because noone planned to implement this. I want to prevent that there are thousands of open issues without a plan to solve them, like I see it on many other projects.
If you find the time to create a PR for this in the near future, we can leave it open.

**Comment by rafamel** [comment]
Yeah, I didn't mention it as I've been pretty pressed for time lately, but was thinking of implementing it at some point. I'm not sure of when I'd get to it, so feel free to close it if you don't want too many issues here.

**Comment by pubkey** [comment]
So I'm closing this. Just ping me if you prepare a PR for this so I could help you maybe.

**Comment by rafamel** [comment]
Sounds like a plan.
