### ISSUE TITLE
Plugin hooks error

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#790]
I'm getting an `Uncaught TypeError: Cannot read property 'push' of undefined` when adding certain plugin hooks on 8 beta 6. The error is coming from [plugin.js](https://github.com/pubkey/rxdb/blob/8.0.0/src/plugin.js):

```javascript
        Object
            .entries(plugin.hooks)
            .forEach(([name, fun]) => HOOKS[name].push(fun));
```

Essentially, there is no property such as `HOOKS[name]`. It seems like some hooks I was previously using are not present in v8 (ex. `postCreateRxDocument`). Is this a bug or is it just lacking documentation in the changelog?

Regardless, it would probably be good to add some error notice such as `The hook ${hookname} doesn't exist`.

**Comment by pubkey** [comment]
Thanks for reporting, this is a bug.
`postCreateDocument` was [here](https://github.com/pubkey/rxdb/blob/master/src/rx-collection.js#L260) but it was wrong because it was async. I accidentially removed it instead of running it sync.

**Comment by rafamel** [comment]
Sounds great, so I'm assuming the whole plugin api remains unchanged, then?

**Comment by pubkey** [comment]
Yes. But `postCreateDocument` will no longer await the result of async-hooks.

**Comment by rafamel** [comment]
I wasn't using `postCreateRxDocument` as async, but if that's a breaking change, it should probably be put in the changelog?

**Comment by pubkey** [comment]
Yes
