### ISSUE TITLE
disableKeyCompression discussion

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#799]
Just making a suggestion on this. Since key compression is disabled by default as of v8, wouldn't it be more fitting to rename the field to `enableKeyCompression`?

Just a thought.

**Comment by pubkey** [comment]
Yes it would be a better name.
The benefits of keeping the old name are:
- When you have explicitly set `disableKeyCompression`, you do not have to change anything when migrating to v8.0
- It is not required to run a migration on an existing database, because the schema will still have the same hash in v8.0

**Comment by rafamel** [comment]
Not particularly invested in this. I think making it disabled by default makes sense, but am unsure on whether the benefits of not changing it now (after all, it is a major version bump) outweight the confusion down the road for new users on future versions. I was tinkering with it when writing some tests for plugins and it was definitely weird to do `disableKeyCompression: false` to get the opposite of the default. I would personally switch, but I definitely get the point of backwards compatibility on this.

**Comment by rafamel** [comment]
Also, thinking further about this, it's a pretty big change for most people (changing the default will force most to change their schema and/or migrate their data anyhow), so I don't think the backwards compatibility should be a concern here.

**Comment by pubkey** [comment]
When changing the default, most user must change the json-schema.
When the attribute is renamed, **everyone** must do a migration.

When I changed the default some weeks a ago, I thought a lot about changing the name, but feared to do so.

Note to future me: Never prefix a config-option with `disable`

**Comment by rafamel** [comment]
Hahahaha, yeah, you're right. Both `disable` and `enable` sound like a bad idea.

You're also right in that, leaving things as they are, not everyone must migrate. Though it's probably safe to assume most just went with the default -particularly since there was no clear documentation detailing exactly what `disableKeyCompression` did. So my assumption would be only a small subset of people won't actually need to migrate. Since the vast majority would, it seems like the perfect opportunity to rectify that past issue, and rename to something like `keyCompression`. Particularly since, if it's not changed now, that means we'll probably be stuck with `disableKeyCompression` and the associated confusion that comes with the name forever? - it seems unlikely that we'd go on to cause the same disruption twice. So it'd probably be better to change now than anytime in the future. 

More over, by leaving the name as is, since as you say the schema hash won't change, for those who didn't include the setting in their schemas the default change will probably cause way more confusion than if we just forced a schema migration. With the proper documentation for migration in the changelog that should be painless for everyone. It might make sense to elaborate on something like: "if you didn't have `disableKeyCompression` in your schemas, add `keyCompression: true` and create a migration strategy incrementing the current version by one that does nothing" (and example), "if you did, change it for `keyCompression: !previousValue`"

On that note, it would also be good to add some more info in the docs as to what does `keyCompression` do.

What do you think?

**Comment by pubkey** [comment]
Ok you are right. The burden of the bad naming should be removed now.
