### ISSUE TITLE
Ionic App  

### ISSUE THREAD

**Issue by michiel1995** [pubkey/rxdb#8]
how do you add a plugin to rxdb? because in ionic/angular you dont have access to require. what you use in al the examples? like you do here `RxDB.plugin(require('rxdb-adapter-localstorage'));`

**Comment by pubkey** [comment]
You can add plugins via es6-import like [here](https://github.com/pubkey/rxdb/blob/master/src/PouchDB.js)

```js
import * as IndexedDB from 'pouchdb-adapter-idb';
RxDB.plugin(IndexedDB);
```
