### ISSUE TITLE
createDocument error with rapid deletes over a remotely synced collection

### ISSUE THREAD

**Issue by rafamel** [pubkey/rxdb#801]
## Case
Probably a bug.

## Issue
I'm finding it hard to reproduce for tests, so I'll try to give all the info I can.

This is happening on 8.0.0-beta.8 over a remotely synced collection, and I haven't been able to reproduce it with locally synced ones. 

When there's a succession of rapid document deletes on one of the synced collections, the other one will update and try to create a document that doesn't exist anymore - it'll be between updates, or at least that's my assumption.

```
..\node_modules\rxdb\dist\es\rx-collection.js:319 Uncaught (in promise) TypeError: Cannot read property '_id' of undefined
    at RxCollection._createDocument (..\node_modules\rxdb\dist\es\rx-collection.js:319)
    at ..\node_modules\rxdb\dist\es\rx-collection.js:343
    at Array.map (<anonymous>)
    at RxCollection._createDocuments (..\node_modules\rxdb\dist\es\rx-collection.js:342)
    at RxQuery._setResultData (..\node_modules\rxdb\dist\es\rx-query.js:78)
    at ..\node_modules\rxdb\dist\es\rx-query.js:570
```

Specifically, it seems to come from:
```javascript
  _proto._createDocument = function _createDocument(json) {
    // return from cache if exsists
    var id = json[this.schema.primaryPath];
    //....
  }
```

Alas, when `_createDocument()` is fired, `json` is undefined. Some simple check when we get here for the removal/existence of the document should probably suffice.

**Comment by pubkey** [comment]
I do not think it's that easy.
When `_createDocument` is called with undefined, we should dig deeper.
From your error I assume that `rxQuery._execOverDatabase()` returns and array with and `undefined`-value.
This internally calls `RxCollection._pouchFind()` which should never return an array with `undefined`.

**Comment by rafamel** [comment]
Closing this, @pubkey. I've done quite a bit of debugging and it's all pointing towards my own mistake. So good news ;)
