### ISSUE TITLE
Allow null value for strings and propagate undefined fields to subscribers

### ISSUE THREAD

**Issue by bkniffler** [pubkey/rxdb#815]
Hey there,
Querying for `stringField=null` works nicely and will find documents with `stringField==undefined` and `stringField==null`, but changes are not propagated to subscribers if new items are added without setting the stringField. Setting stringField to null will throw an error since, according to schema validation, it is not a valid value.

```
const query = db.col1.find({ text: { $eq: null } });
query.$subscribe(docs => console.log(2, docs));
query.exec().then(docs => console.log(1, docs));
db.col1.insert({ name: "hi" });
// this will throw an error: db.col1.insert({ name: "hi", text: null })
```

This will output your docs with text=null once, but will not output further when new docs are inserted.

I would expect are query to consistently work the same way across .exec() and .$subscribe(). I would also expect null to be a valid value for strings.

**Comment by pubkey** [comment]
If you want to set a string-field to null, you must allow the null-type in your schema. Sth like `"type": ["string", "null"]`.

The second problem sounds like a bug. `exec()` should always return the same values as subscribing.
Please edit the [bug-report-template](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js) with a reproduction.

**Comment by bkniffler** [comment]
Okay, I did some testing. Your suggestion for string/null works. My initial observation wasn't completely accurate.

A query like `collection.find({ lastName: null })` will only find entries whose lastName equals null, no matter if subscribe or exec. PouchDB and MongoDB meanwhile will search for lastName equals null AND lastName undefined. More info here: https://docs.mongodb.com/manual/tutorial/query-for-null-fields/

Bug Report with failing test: https://github.com/pubkey/rxdb/pull/821

**Comment by pubkey** [comment]
I added a test that shows that the result of RxDB is exactly the same as what you get from pouchdb. I do not think this is a bug.

**Comment by pubkey** [comment]
Please reopen with more information or a test to reproduce

**Comment by rmisio** [comment]
@pubkey Is there any way to set an object field with a default of null? I'm trying this:

```
    colors: {
      type: ['object', 'null'],
      encrypted: true,
      default: null,
      properties: {
        primary: {
          type: 'string',
        },
        secondary: {
          type: 'string',
        },
        text: {
          type: 'string',
        },
        highlight: {
          type: 'string',
        },
        highlightText: {
          type: 'string',
        },
      }
    }
```

but then:

```
await Promise.all(collections.map(data => db.collection(data)));
```

bombs with:

```
Uncaught (in promise) TypeError: Cannot read property 'hasOwnProperty' of null
    at checkField (schema-check.js:47)
    at traverse (schema-check.js:130)
    at traverse (schema-check.js:135)
    at traverse (schema-check.js:135)
    at validateFieldsDeep (schema-check.js:139)
    at checkSchema (schema-check.js:163)
    at hooks.js:70
    at Array.forEach (<anonymous>)
    at runPluginHooks (hooks.js:69)
    at Object.create (rx-schema.js:362)
    at RxDatabase._callee$ (rx-database.js:201)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:282)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/29.chunk.js:152027:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at RxDatabase.<anonymous> (asyncToGenerator.js:21)
    at RxDatabase.collection (rx-database.js:313)
    at database.js:38
    at Array.map (<anonymous>)
    at _callee$ (database.js:24)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:288)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/29.chunk.js:878:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

**Comment by GanganiSon97** [comment]
@rmisio any solution for this error?

**Comment by pubkey** [comment]
Please create a PR with a test case then I can fix this

**Comment by baryon** [comment]
> @pubkey Is there any way to set an object field with a default of null? I'm trying this:
> 
> ```
>     colors: {
>       type: ['object', 'null'],
>       encrypted: true,
>       default: null,
>       properties: {
>         primary: {
>           type: 'string',
>         },
>         secondary: {
>           type: 'string',
>         },
>         text: {
>           type: 'string',
>         },
>         highlight: {
>           type: 'string',
>         },
>         highlightText: {
>           type: 'string',
>         },
>       }
>     }
> ```
> 
> but then:
> 
> ```
> await Promise.all(collections.map(data => db.collection(data)));
> ```
> 
> bombs with:
> 
> ```
> Uncaught (in promise) TypeError: Cannot read property 'hasOwnProperty' of null
>     at checkField (schema-check.js:47)
>     at traverse (schema-check.js:130)
>     at traverse (schema-check.js:135)
>     at traverse (schema-check.js:135)
>     at validateFieldsDeep (schema-check.js:139)
>     at checkSchema (schema-check.js:163)
>     at hooks.js:70
>     at Array.forEach (<anonymous>)
>     at runPluginHooks (hooks.js:69)
>     at Object.create (rx-schema.js:362)
>     at RxDatabase._callee$ (rx-database.js:201)
>     at tryCatch (runtime.js:63)
>     at Generator.invoke [as _invoke] (runtime.js:282)
>     at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/29.chunk.js:152027:21)
>     at asyncGeneratorStep (asyncToGenerator.js:3)
>     at _next (asyncToGenerator.js:25)
>     at asyncToGenerator.js:32
>     at new Promise (<anonymous>)
>     at RxDatabase.<anonymous> (asyncToGenerator.js:21)
>     at RxDatabase.collection (rx-database.js:313)
>     at database.js:38
>     at Array.map (<anonymous>)
>     at _callee$ (database.js:24)
>     at tryCatch (runtime.js:62)
>     at Generator.invoke [as _invoke] (runtime.js:288)
>     at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/29.chunk.js:878:21)
>     at asyncGeneratorStep (asyncToGenerator.js:3)
>     at _next (asyncToGenerator.js:25)
> ```

same issue, if you set default : null, got error

**Comment by Sheethalpatil** [comment]
is this thing you solved ?
