### ISSUE TITLE
atomicUpsert is slow.

### ISSUE THREAD

**Issue by cw196** [pubkey/rxdb#834]
Hi there,

I have a request is that inserting a large amount of data into indexeddb. for like upserting 1 thousand records, it may take 20s, but in Android/iOS may take 5s only.

Is there a way to solve this problem? 
Thanks

**Comment by pubkey** [comment]
Yes. you can use the pouchdb-instance of the collection and do a bulk-operation. See here https://pouchdb.com/guides/bulk-operations.html

For common questions that cannot be solved with a PR, please do not create issues, like written in the issues_template.
