### ISSUE TITLE
authorization error due to pouchdb change

### ISSUE THREAD

**Issue by barbalex** [pubkey/rxdb#840]
## Case
This is an issue in PouchDB and https://github.com/pouchdb-community/pouchdb-authentication that raises issues for people using rxdb.

I am raising this here to inform others that may run into this.

There is a workaround described here: https://github.com/pouchdb-community/pouchdb-authentication/issues/239#issuecomment-410489376 that could maybe be applied to rxdb for as long as the issues in PouchDB and pouchdb-authentication are not resolved.

Related issues:
- https://github.com/pouchdb/pouchdb/issues/7390
- https://github.com/pouchdb/pouchdb/pull/7395
- https://github.com/pouchdb-community/pouchdb-authentication/pull/238

## Issue
Authorization using cookies does not work.

## Info
  - Environment: browser
  - Adapter: http
  - Stack: rxdb using https://github.com/pouchdb-community/pouchdb-authentication to create a cookie to authenticate users

## Code

this sync:
```js
userDb.user.sync({
      remote: `http://localhost:5984/user_test_at_test_p_ch/`,
      options: {
        live: true,
        retry: true,
      },
      query: userDb.user
        .find()
        .where('type')
        .eq('user'),
    })
```
results in:
```js
http://localhost:5984/user_test_at_test_p_ch/ 401 (Unauthorized)
```
after logging in:
```js
import PouchDB from 'pouchdb-browser'
import pouchdbAuthentication from 'pouchdb-authentication'

PouchDB.plugin(pouchdbAuthentication)

const authDb = new PouchDB(couchUrl())
await authDb.logIn(email, password)
```

**Comment by barbalex** [comment]
I tried forcing pouchdb and rxdb to always include credentials:

```js
PouchDB.defaults({
  fetch(url: any, opts: any) {
    opts.credentials = 'include'
    return (PouchDB as any).fetch(url, opts)
  },
} as PouchDB.Configuration.RemoteDatabaseConfiguration)
```

and:
```js
 await userDb.collection({
  name: 'user',
  schema: userDocSchema,
  pouchSettings: {
    fetch(url: any, opts: any) {
      opts.credentials = 'include'
      return (PouchDB as any).fetch(url, opts)
    },
  } as PouchDB.Configuration.RemoteDatabaseConfiguration,
})
```

but that does not solve the issue.

**Comment by pubkey** [comment]
A quick workaround could be to remove rxdbs pouchdb-folder and install an older version of pouchdb.

**Comment by barbalex** [comment]
even though it would be a breaking change before? (v6.x versus v7)

**Comment by barbalex** [comment]
I tried installing pouchdb@6.4.3 and enforcing it's use by adding it as resolution in package.json (using yarn). But cookies are still not sent.

**Comment by barbalex** [comment]
Went back to pouchdb@6.4.1 and pouchdb-authentication@1.0.0. Still no cookies sent.

Then I deleted the pouchdb-js file in node_modules/rxdb/dist/lib/ and also in the src folder. Still no cookies sent.

My only temporary but horrible hack is to _not_ write members into the security docs of the databases I am working with. Hoping that this will all work, once pouchdb and pouchdb-authentication update.

This is now o.k. for me as this app is in development and not used in real life yet.

**Comment by pubkey** [comment]
I'm closing this. It should be fixed by the authentication-plugin, not by RxDB.

**Comment by servocoder** [comment]
@barbalex have you found a workaround?

**Comment by barbalex** [comment]
@servocoder nope, sadly not. I'm waiting for pouchdb and the authentication-plugin to solve it.

**Comment by hubgit** [comment]
I've been able to work around this, not by setting `pouchSettings.fetch` as the `RxDatabaseCreator` types would suggest (which had no effect), but by setting `fetch` as a sync option:

```js
this.collection.sync({
    options: {
        fetch: (url, opts) => PouchDb.fetch(url, {
            ...opts,
            credentials: 'include',
        })
    },
})
```
