### ISSUE TITLE
Adding a property to documents after querying [Question]

### ISSUE THREAD

**Issue by megaed** [pubkey/rxdb#842]
**This is not a feature request nor a bug report.**

I have been _**trying to add a property to every document**_ that has been pulled from the database. This property I'm trying to add is _**mostly utilized by the front-end UI**_ (used in an if-else situation) so I believe it shouldn't be added to the schema of the document but should be added only after pulling the array of data from the DB (_**using a map function**_ to add the property). Whenever I add the property, _**it doesn't seem like the frontend can see it**_; the _**properties that are specified in the schema is printed fine**_ but not the ones I have added dynamically.

I'm not entirely sure how to implement this in RxDB. I have tried adding a getter and setter & adding it like a normal property for an object using the dot notation and bracket notation but still no good.

I'm using vuejs to render the front end UI which is merely consuming the JSON from RxDB.

Hopefully, I didn't mess up in explaining my situation. English isn't my first language.

Thanks in advance!

**Comment by bansawbanchee** [comment]
Without you providing some code I have to assume you are not aware that RxQuery's are immutable. Please refer to this page of the documentation for examples https://pubkey.github.io/rxdb/rx-query.html#notice-rxquerys-are-immutable
