### ISSUE TITLE
can't find variable WeakSet

### ISSUE THREAD

**Issue by Julious1994** [pubkey/rxdb#851]
## Issue
Hi, when i am installing rxdb in react-native app it gives me an error on import of rxdb that can't find variable WeakSet. Please give me a solution.
I attached screenshot of an error page.

![longscreenshot_2018-11-08-21-48-16](https://user-images.githubusercontent.com/16513909/48217480-79604600-e3ad-11e8-9d3d-ef934cfe1571.png)

**Comment by pubkey** [comment]
You need the polyfills, depending on where you use your react-native. [See here](https://github.com/facebook/react-native/issues/11368)

**Comment by Julious1994** [comment]
Thanks @pubkey  it works.
