### ISSUE TITLE
updated function is inserting new data

### ISSUE THREAD

**Issue by diegomolinavera** [pubkey/rxdb#856]
## Issue
When I try to update the content of the document, it is added a new document to the collection

## Info
  - Environment: (Node.js/React)
  - Adapter: IndexedDB
  - Stack: React - 16.6.3

## Code

```js
// get all the documents. In this case there's just one document
const documents = db[collectionName]
    .find()
    .exec();

const [document] = documents;
await document.update({
    $set: {
        data: JSON.stringify(data)
    }
});
```

**Comment by pubkey** [comment]
Hi @diegomolinavera 
please add a test by editing [this file](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js)

**Comment by diegomolinavera** [comment]
Ok. It is working fine. The thing was that the structure of the tables is not clear in beginning. It would be great to see this documented. 👍
