### ISSUE TITLE
Does not allow full core spec of jsonSchema 

### ISSUE THREAD

**Issue by codingmatty** [pubkey/rxdb#86]
## Case
This is a bug.

## Issue
I am trying to use the full features of Json Schema, but rxSchema does it's own checks and throws errors on a valid schema, because of the "`fieldName`"s.

## Info
- Environment: (browser)
- Adapter: (IndexedDB)

## Code
The schema looks like this (you can also see it in the JSON Schema Linter [here](https://jsonschemalint.com/#/version/draft-04/markup/json?gist=3f0a048cf12cc22bd7b0c2934eb8fcab)): 
```json
{
  "title": "Transaction Schema",
  "version": 0,
  "description": "Structure of Transaction Data",
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "format": "date-time"
    }
  },
  "patternProperties": {
    "^credit|debit$": {
      "type": "number",
      "multipleOf": 0.01
    }
  },
  "oneOf": [
    { "required": [ "date", "credit" ] },
    { "required": [ "date", "debit" ] }
  ],
  "additionalProperties": false
}
```
The problems arise with both the `^credit|debit$` property in the `patternProperties` object, but _also_ within the `oneOf` property because it's an array, and the "`fieldName`" of `0` does not match the "valid regex".

I feel like you should be using a 3rd party library to validate the schema to avoid problems like this, unless you only allow part of the spec, which then you should specify that in the docs.

Thanks!

**Comment by codingmatty** [comment]
This is the culprit function btw: https://github.com/pubkey/rxdb/blob/master/src/RxSchema.js#L242

**Comment by pubkey** [comment]
@codingmatty 
The schema is used by rxdb in 2 ways:
1. for schema validation
2. to map the plain data to the RxDocument and create the right getters for streams and population.

Therefore we need a custom validator on the schema-definition to make sure it does not overwrite the existing properties of RxDocument or the names of ORM-methods.

You are right, we should better explain this in the docs. I will investigate and write again in a few hours.

**Comment by pubkey** [comment]
I added a paragraph to the docs which describes what is allowed and why.
For the schema above you can still workaround like:
```json
"patternProperties": {
    "debit": {
      "type": "number",
      "multipleOf": 0.01
    },
    "credit": {
      "type": "number",
      "multipleOf": 0.01
    }
  },
```

**Comment by cedvdb** [comment]
@pubkey is the data we put in a collection obligated to obey to the schema representation ?
say I have a custom columns in an object coming from the server and want to put it to into rxdb. How do I make it so I don't have the error `object does not match schema` ?

**Comment by pubkey** [comment]
@cedvdb use a schema with a `data` field, where the data is only defined as `type: "object"`.
Then put your document into this field.
