### ISSUE TITLE
Issue with index on nested array

### ISSUE THREAD

**Issue by GeekEdem** [pubkey/rxdb#876]
Hello. Some issue with index on nested array.

Schema:
```
{
  title: "requests schema",
  version: 0,
  type: "object",
  properties: {
    requests: {
      type: "array",
      item: {
        properties: {
          id: {
            type: "string",
            regex: /[a-f0-9]{24}/i,
            index: true,
          },
          requestType: {
            type: "string",
          },
        },
      },
    },
  },
  required: ["requests"],
}
```

Check #697 :
`const schemaObj = objectPath.get(jsonID, 'properties.' + key.replace(/\./g, '.properties.'));`

schemaObj become like `requests.properties.item.properties.id` but must be `requests.[].id`.

**Comment by pubkey** [comment]
I think you forgot the `type` inside of `item:`
But still looks like a valid bug. Could you PR a test to reproduce the problem?
