### ISSUE TITLE
Multi User App

### ISSUE THREAD

**Issue by kethan** [pubkey/rxdb#88]
Imagine if i have multi-user app all data related to the user is stored in the DB. What will happen when i sync will it sync all the DB or only specific parts of the user?

**Comment by pubkey** [comment]
Closed. Please ask common questions in [gitter](https://gitter.im/pubkey/rxdb)

The synchronisation works `per collection` which means by default you will sync everything which is contained in one collection. But you can also use [filtered replication](https://pouchdb.com/2015/04/05/filtered-replication.html)
