### ISSUE TITLE
Support for syncing via WebSockets?

### ISSUE THREAD

**Issue by hubgit** [pubkey/rxdb#886]
## Case

Feature request

## Issue

Due to the browser limit on HTTP connections to a single server, I'd like to sync collections with a remote Sync Gateway endpoint using WebSockets.

The [leader election docs](https://github.com/pubkey/rxdb/blob/master/docs-src/leader-election.md) mention an open websocket, but I can't find anything else in the RxDB code or documentation.

There are some relevant implementations as PouchDB adapters, but none of them seem like something that could be dropped into an RxDB collection:

* https://github.com/pouchdb-community/socket-pouch
* https://github.com/pgte/pouch-websocket-sync
* https://github.com/genglefr/my-gallery/blob/master/app/pouch-ws-adapter.js

## Info

  - Environment: Browser
  - Adapter: IndexedDB
  - Stack: Typescript, Babel, React

**Comment by hubgit** [comment]
This may turn out to not be possible, given the warning that Couchbase/Sync Gateway's WebSocket-based communication protocol is "incompatible with CouchDB-based databases".

https://docs.couchbase.com/couchbase-lite/2.1/swift.html#compatibility

**Comment by pubkey** [comment]
Hi @hubgit have you found a solution or why did you close this?

**Comment by pubkey** [comment]
Btw have you tested [rxdb-utils](https://github.com/rafamel/rxdb-utils#replication)

**Comment by hubgit** [comment]
I closed the issue so as not to waste anyone's time looking into it when as far as I can tell PouchDB isn't compatible with Sync Gateway's latest WebSocket-based sync protocol. Of course if anyone does come up with a solution it would still be useful.

I've had a look at the replication feature of `rxdb-utils`, but it wouldn't work for my case as it blocks use of the `filter` sync param.
