### ISSUE TITLE
Get names of all the collection and subscribe for changes

### ISSUE THREAD

**Issue by Julien76** [pubkey/rxdb#894]
## Case
Help

## Issue
Is it possible to list the name of all the collections in a database and subscribe to get notify when a collection has been added?

## Info
  - Environment: electron
  - Adapter: memory
  - Stack: Vuejs

## Code

This does not work for example:

```
const collectionQuery = db.collections
collectionQuery.$.subscribe(changeEvent => console.dir(changeEvent))
```
Nor this:

```
const collectionQuery = db.collections.find()
collectionQuery.$.subscribe(changeEvent => console.dir(changeEvent))
```

**Comment by pubkey** [comment]
From the issues template: **  If you have a common question which cannot be solved with a PR, ask it at one of these places..**

When you create a collection, an event is fired, see [here](https://github.com/pubkey/rxdb/blob/master/src/rx-database.js#L242). You can subscribe and filter so you have a stream that only emits the collection-create-events.
