### ISSUE TITLE
Document _deleted can't be set back to false

### ISSUE THREAD

**Issue by alanctkc** [pubkey/rxdb#911]
## Case
Possible bug

## Issue
`RxDocument.remove()` rightly sets `_deleted` to `true` to remove documents.

However, in my app, I give users a little window of time after deletion for "undo." On undo, I'd like to be able to perform an `update()` to set `_deleted` back to `false` and restore the document with original data, but this bit of code prevents it:

https://github.com/pubkey/rxdb/blob/79c257b2dc84503e5f800c0508c4f3d5550b741e/src/rx-document.js#L309-L315

I also can't just re-insert the data as a new document, because the `id` conflicts with the previously deleted document.

Is that a deliberate decision, or just an oversight? To be honest, I'm not familiar enough with pouch to know if it would even allow it under the hood.

If possible, could the behavior be changed to disallow updates to deleted documents _unless_ the update also sets `_deleted` to `true`?

## Info
RxDB 8.0.4

**Comment by pubkey** [comment]
I recommend to use a different flag if you want to undo the delete. For example use a boolean `deleted` (without the lodash) and then you can change it back and forward. 
Do you know if you can undelete with pouchdb when you do not already have the _rev of the deleted document?

**Comment by alanctkc** [comment]
Good point about needing to have the `_rev` even if undelete is possible. I'll try tinkering with raw pouch and see what it will let me do—maybe not even possible.

I did think about doing a soft-delete in the document data. I liked, however, that I wouldn't have to fiddle with filtering on it everywhere and the little layer of abstraction I'd have to add to maintain it. It's nice that pouch/couch automatically treat `_deleted: true` documents as deleted with expected behavior, so no matter what client (in whichever language, using both python/javascript), they wouldn't have to think about it.

Let me work up a fiddle with pouchdb and attempt undelete and post back here.

**Comment by alanctkc** [comment]
There's some indication, at least with couch, that you can get the `_rev` from the changes feed:

https://stackoverflow.com/a/10857330

Digging in.

**Comment by pubkey** [comment]
Any update on this?

**Comment by alanctkc** [comment]
Feel free to close for now to keep issues clean. Still on my todos, but didn't get around to it as quickly as I hoped!

**Comment by pubkey** [comment]
Ok I'm closing this, no problem. I will reopen when you/me find the time..

**Comment by ospfranco** [comment]
Hey, I just ran into the same issue? I'm guessing there are no plans no change current behavior?

**Comment by pubkey** [comment]
There are no plans, but I am open to change this. But we should find a 'correct' way to handle this, similar to couchdb pouchdb.

**Comment by Unforgiven-wanda** [comment]
Could we somehow leverage [pouchdb-undo](https://github.com/FlamingTempura/pouchdb-undo)?

**Comment by emil14** [comment]
any updates?

**Comment by yudhishthir-siterecon** [comment]
any updates?

**Comment by pubkey** [comment]
RxDB no longer conflicts when re-inserting a deleted document since version 12 or so. Just re-insert to undelete.
