### ISSUE TITLE
does rxdb support null values ?

### ISSUE THREAD

**Issue by goodbeysr** [pubkey/rxdb#923]
i defined my schema as follow :
`
export const testSchema: RxJsonSchema = {
  title: 'test schema',
  description: 'Store Test',
  version: 0,
  keyCompression: false,
  type: 'object',
  properties: {
    id: {
      type: 'string',
      primary: true,
    },
    name: {
      type: 'string',
      default: ''
    }
  },
  required: ['id']
};`

when i try to insert a new doc with a null name field , i get this error : 
errors:[
  {
    "field": "data.name",
    "message": "is the wrong type"
  }
]

even when i define default value for name field i get the same error.
is it possible to insert null values ?

**Comment by pubkey** [comment]
You have to define a nullable type, see [here](https://stackoverflow.com/a/22565006)
