### ISSUE TITLE
Migration Strategies not running

### ISSUE THREAD

**Issue by Njinu** [pubkey/rxdb#936]
## Case
BUG 

## Issue
Cannot run migration strategies as suggested in docs

## Info
  - Environment: browser
  - Adapter: IndexedDB
  - Stack: React, Redux, Gatsby

-Error: I get this error when providing migration strategies to the collection: 
A migrationStrategy is missing or too much
Given parameters: {
have:[
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6"
]
should:[]}

## Code
```
import * as RxDB from "rxdb"
import { QueryChangeDetector } from "rxdb"
import { schema, schema2 } from "../src/schema"
import { Component } from "react"
import * as moment from "moment"
import React from "react"

// QueryChangeDetector.enable()
// QueryChangeDetector.enableDebugging()
RxDB.plugin(require("pouchdb-adapter-idb"))
RxDB.plugin(require("pouchdb-adapter-http"))
const syncURL = "http://localhost:8000/"
const dbName = "master"
export const schema = {
  title: "Cookie",
  description: "Database schema for a cookie",
  version: 0,
  type: "object",
  properties: {
    id: {
      type: "string",
      primary: true,
    },
    flavor: {
      type: "string",
    },
  },
  required: ["flavor"],
}

export const schema2 = {
  title: "Cookie",
  description: "Database schema for a cookie",
  version: 6,
  type: "object",
  properties: {
    id: {
      type: "string",
      primary: true,
    },
    flavour: {
      type: "string",
    },
    someNewProperty: {
      type: "string",
    },
    flavor: {
      type: "string",
    },
  },
  required: ["someNewProperty", "flavour"],
}

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      newCookie: "",
      cookies: [],
    }
    this.subs = []
    this.addCookie = this.addCookie.bind(this)
    this.handleCookieChange = this.handleCookieChange.bind(this)
  }

  async createDatabase() {
    const db = await RxDB.create({
      name: dbName,
      adapter: "idb",
      password: "12345678",
    })
    db.waitForLeadership().then(() => {
      document.title = "â™› " + document.title
    })
    const cookieJar = await db.collection({
      name: "cookies",
      schema: schema,
      autoMigrate: false,
      migrationStrategies: {
        0: function(oldDoc) {
          return oldDoc
        },
        // 1 means, this transforms data from version 0 to version 1
        1: function(oldDoc) {
          return oldDoc
        },
        2: function(oldDoc) {
          return oldDoc
        },
        3: function(oldDoc) {
          return oldDoc
        },
        4: function(oldDoc) {
          return oldDoc
        },
        5: function(oldDoc) {
          oldDoc.someNewProperty = oldDoc.flavor
          oldDoc.flavour = oldDoc.flavor
          return oldDoc
        },
        6: function(oldDoc) {
          oldDoc.anotherOne = oldDoc.someNewProperty
          return oldDoc
        },
      },
    })

    return db
  }

  async componentDidMount() {
    this.db = await this.createDatabase()
    debugger
    const sub = this.db.cookies
      .find()
      .sort({ id: 1 })
      .$.subscribe(cookies => {
        if (!cookies) return
        this.setState({ cookies: cookies })
      })
    this.subs.push(sub)
  }
  componentWillUnmount() {
    this.subs.forEach(sub => sub.unsubscribe())
  }
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h2>Welcome to React</h2>
        </div>

        <div>{this.renderCookies()}</div>

        <div id="add-message-div">
          <h3>Add Cookie</h3>
          <input
            type="text"
            placeholder="Cookie Flavor"
            value={this.state.newCookie}
            onChange={this.handleCookieChange}
          />
          <button onClick={this.addCookie}>Add cookie</button>
        </div>
      </div>
    )
  }
  renderCookies() {
    console.log("test", this.state)
    return this.state.cookies.map(
      ({ id, flavor, flavour, someNewProperty }) => {
        return (
          <div key={id}>
            {/* <p>{date}</p> */}
            <p>flavor: {flavor}</p>
            <p>flavour:{flavour}</p>
            <p>new prop: {someNewProperty}</p>
            <hr />
          </div>
        )
      }
    )
  }
  handleCookieChange(event) {
    this.setState({ newCookie: event.target.value })
  }
  async addCookie() {
    const id = Date.now().toString()

    const newCookie = { id, flavor: this.state.newCookie }

    await this.db.cookies.insert(newCookie)

    this.setState({ newCookie: "" })
  }
}

```

**Comment by Njinu** [comment]
My database current version is 5

**Comment by pubkey** [comment]
`schema2` is unused. You only use `schema` which has `version: 0` and therefore should not have migration-strategies.

**Comment by Njinu** [comment]
hi there, i was trying to move from schema1 to schema 2, but whenever i provide migrationStrategies parameter to my collection i get the following error message: 

A migrationStrategy is missing or too much
Given parameters: {
have:[
"0",
"1",
"2",
"3",
"4",
"5",
"6"
]
should:[]}

I cant figure out what this means.

**Comment by Njinu** [comment]
@pubkey 

hi there, i was trying to move from schema1 to schema 2, but whenever i provide migrationStrategies parameter to my collection i get the following error message:

Uncaught (in promise) RxError: RxError:
A migrationStrategy is missing or too much
Given parameters: {
have:[
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7"
]
should:[]}
    at Object.newRxError (http://localhost:8000/commons.js:81093:10)
    at checkMigrationStrategies (http://localhost:8000/commons.js:79112:61)
    at Object.create (http://localhost:8000/commons.js:79319:3)
    at RxDatabase._callee$ (http://localhost:8000/commons.js:79651:77)
    at tryCatch (http://localhost:8000/commons.js:71699:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/commons.js:71925:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8000/commons.js:71751:21)
    at asyncGeneratorStep (http://localhost:8000/commons.js:6297:24)
    at _next (http://localhost:8000/commons.js:6319:9)

**Comment by pubkey** [comment]
Can you add a PR with a test that reproduces your problem? You can start with editing [this file](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js)

**Comment by Njinu** [comment]
@pubkey 
Having issues running the tests with the template above, it seems like it is deleting the files in: rxdb\dist\lib when transpiling, then the test fails because those files are deleted. 

Is there another method i can use to replicate?

 Or alternatively if you could point me to some code that is utilizing the migrationStrategies that would be very helpful because i cant find anything online
