### ISSUE TITLE
Migration Strategies should be a function / object

### ISSUE THREAD

**Issue by Njinu** [pubkey/rxdb#937]
## Case

Bug

## Issue

Cannot implement migration strategies due to error

## Info
  - Environment: Browser (Chrome)
  - Adapter: IndexedDB/ idb
  - Stack: React/Redux
   -DB Version: 5

## Code
``` 
import * as RxDB from "rxdb"
import { Component } from "react"
import React from "react"
RxDB.plugin(require("pouchdb-adapter-idb"))
RxDB.plugin(require("pouchdb-adapter-http"))
const dbName = "master"

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      newCookie: "",
      cookies: [],
    }
    this.subs = []
    this.addCookie = this.addCookie.bind(this)
    this.handleCookieChange = this.handleCookieChange.bind(this)
  }

  async createDatabase() {
    const db = await RxDB.create({
      name: dbName,
      adapter: "idb",
      password: "12345678",
    })
    db.waitForLeadership().then(() => {
      document.title = "â™› " + document.title
    })
    await db.collection({
      name: "cookies",
      schema: {
        title: "Cookie",
        description: "Database schema for a cookie",
        version: 6,
        type: "object",
        properties: {
          id: {
            type: "string",
            primary: true,
          },
          flavour: {
            type: "string",
          },
          someNewProperty: {
            type: "string",
          },
          flavor: {
            type: "string",
          },
        },
        required: ["someNewProperty", "flavour"],
      },
      autoMigrate: true,
      migrationStrategies: {
        0: function(oldDoc) {
          return oldDoc
        },
        // 1 means, this transforms data from version 0 to version 1
        1: function(oldDoc) {
          return oldDoc
        },
        2: function(oldDoc) {
          return oldDoc
        },
        3: function(oldDoc) {
          return oldDoc
        },
        4: function(oldDoc) {
          return oldDoc
        },
        5: function(oldDoc) {
          oldDoc.someNewProperty = oldDoc.flavor
          oldDoc.flavour = oldDoc.someNewProperty
        },
      },
      // 6: function(oldDoc) {
      //   oldDoc.someNewProperty = oldDoc.flavor
      //   return oldDoc
      // },
      // 7: function(oldDoc) {
      //   oldDoc.flavour = oldDoc.someNewProperty
      //   return oldDoc
      // },
    })

    return db
  }

  async componentDidMount() {
    this.db = await this.createDatabase()
    debugger
    const sub = this.db.cookies
      .find()
      .sort({ id: 1 })
      .$.subscribe(cookies => {
        if (!cookies) return
        this.setState({ cookies: cookies })
      })
    this.subs.push(sub)
  }
  componentWillUnmount() {
    this.subs.forEach(sub => sub.unsubscribe())
  }
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <h2>Migration Strategies test</h2>
        </div>

        <div>{this.renderCookies()}</div>

        <div id="add-message-div">
          <h3>Add Cookie</h3>
          <input
            type="text"
            placeholder="Cookie Flavor"
            value={this.state.newCookie}
            onChange={this.handleCookieChange}
          />
          <button onClick={this.addCookie}>Add cookie</button>
        </div>
      </div>
    )
  }
  renderCookies() {
    console.log("test", this.state)
    return this.state.cookies.map(
      ({ id, flavor, flavour, someNewProperty }) => {
        return (
          <div key={id}>
            {/* <p>{date}</p> */}
            <p>flavor: {flavor}</p>
            <p>flavour:{flavour}</p>
            <p>new prop: {someNewProperty}</p>
            <hr />
          </div>
        )
      }
    )
  }
  handleCookieChange(event) {
    this.setState({ newCookie: event.target.value })
  }
  async addCookie() {
    const id = Date.now().toString()

    const newCookie = { id, flavor: this.state.newCookie }

    await this.db.cookies.insert(newCookie)

    this.setState({ newCookie: "" })
  }
}

```

EXPECTED OUTPUT: 

Runs the migrations and sets new properties (flavour & someNewProperty)

ACTUAL RESULT : 

Error in console:  RxError: RxError:
migrationStrategies must be a function

Uncaught (in promise) RxError: RxError:
migrationStrategy must be a function
Given parameters: {
version:5
type:"object"
schema:{
  "jsonID": {
    "title": "Cookie",
    "description": "Database schema for a cookie",
    "version": 6,
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "primary": true
      },
      "flavour": {
        "type": "string"
      },
      "someNewProperty": {
        "type": "string"
      },
      "flavor": {
        "type": "string"
      },
      "_rev": {
        "type": "string",
        "minLength": 1
      },
      "_attachments": {
        "type": "object"
      }
    },
    "required": [
      "someNewProperty",
      "flavour",
      "id"
    ],
    "additionalProperties": false,
    "keyCompression": false,
    "compoundIndexes": []
  },
  "compoundIndexes": [],
  "indexes": [],
  "primaryPath": "id",
  "finalFields": [
    "id"
  ],
  "_normalized": {
    "additionalProperties": false,
    "compoundIndexes": [],
    "description": "Database schema for a cookie",
    "keyCompression": false,
    "properties": {
      "_attachments": {
        "type": "object"
      },
      "_rev": {
        "minLength": 1,
        "type": "string"
      },
      "flavor": {
        "type": "string"
      },
      "flavour": {
        "type": "string"
      },
      "id": {
        "primary": true,
        "type": "string"
      },
      "someNewProperty": {
        "type": "string"
      }
    },
    "required": [
      "flavour",
      "id",
      "someNewProperty"
    ],
    "title": "Cookie",
    "type": "object",
    "version": 6
  },
  "_hash": "2be159496392dec24c2a70e26094c600"
}}
    at Object.newRxTypeError (http://localhost:8000/commons.js:76483:10)
    at http://localhost:8000/commons.js:74514:61
    at Array.forEach (<anonymous>)
    at checkMigrationStrategies (http://localhost:8000/commons.js:74513:6)
    at Object.create (http://localhost:8000/commons.js:74706:3)
    at RxDatabase._callee$ (http://localhost:8000/commons.js:75038:77)
    at tryCatch (http://localhost:8000/commons.js:67086:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/commons.js:67312:22)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:8000/commons.js:67138:21)
    at asyncGeneratorStep (http://localhost:8000/commons.js:6297:24)
    at _throw (http://localhost:8000/commons.js:6323:9)

NOTE: If i pass in migration strategies as a fn. i.e. 

```
  migrationStrategies: () => {
        return {
          0: function(oldDoc) {
            return oldDoc
          },
          // 1 means, this transforms data from version 0 to version 1
          1: function(oldDoc) {
            return oldDoc
          },
          2: function(oldDoc) {
            return oldDoc
          },
          3: function(oldDoc) {
            return oldDoc
          },
          4: function(oldDoc) {
            return oldDoc
          },
          5: function(oldDoc) {
            oldDoc.someNewProperty = oldDoc.flavor
            oldDoc.flavour = oldDoc.someNewProperty
          },
        }
        // 6: function(oldDoc) {
        //   oldDoc.someNewProperty = oldDoc.flavor
        //   return oldDoc
        // },
        // 7: function(oldDoc) {
        //   oldDoc.flavour = oldDoc.someNewProperty
        //   return oldDoc
        // },
      },
```
Then i get the following error message: RxError: RxError:
migrationStrategies must be an object

construct.js:30 Uncaught (in promise) RxError: RxError:
migrationStrategies must be an object
Given parameters: {
schema:{
  "jsonID": {
    "title": "Cookie",
    "description": "Database schema for a cookie",
    "version": 6,
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "primary": true
      },
      "flavour": {
        "type": "string"
      },
      "someNewProperty": {
        "type": "string"
      },
      "flavor": {
        "type": "string"
      },
      "_rev": {
        "type": "string",
        "minLength": 1
      },
      "_attachments": {
        "type": "object"
      }
    },
    "required": [
      "someNewProperty",
      "flavour",
      "id"
    ],
    "additionalProperties": false,
    "keyCompression": false,
    "compoundIndexes": []
  },
  "compoundIndexes": [],
  "indexes": [],
  "primaryPath": "id",
  "finalFields": [
    "id"
  ],
  "_normalized": {
    "additionalProperties": false,
    "compoundIndexes": [],
    "description": "Database schema for a cookie",
    "keyCompression": false,
    "properties": {
      "_attachments": {
        "type": "object"
      },
      "_rev": {
        "minLength": 1,
        "type": "string"
      },
      "flavor": {
        "type": "string"
      },
      "flavour": {
        "type": "string"
      },
      "id": {
        "primary": true,
        "type": "string"
      },
      "someNewProperty": {
        "type": "string"
      }
    },
    "required": [
      "flavour",
      "id",
      "someNewProperty"
    ],
    "title": "Cookie",
    "type": "object",
    "version": 6
  },
  "_hash": "2be159496392dec24c2a70e26094c600"
}}
    at Object.newRxTypeError (http://localhost:8000/commons.js:76483:10)
    at checkMigrationStrategies (http://localhost:8000/commons.js:74492:61)
    at Object.create (http://localhost:8000/commons.js:74706:3)
    at RxDatabase._callee$ (http://localhost:8000/commons.js:75038:77)
    at tryCatch (http://localhost:8000/commons.js:67086:40)
    at Generator.invoke [as _invoke] (http://localhost:8000/commons.js:67312:22)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:8000/commons.js:67138:21)
    at asyncGeneratorStep (http://localhost:8000/commons.js:6297:24)
    at _throw (http://localhost:8000/commons.js:6323:9)

**Comment by pubkey** [comment]
I think this is a synthactical error but I dont have time to play arround with your code. Please create a PR which reproduces your problem. Then I can fix it if it'S a bug.

**Comment by Njinu** [comment]
@pubkey 

Hi there

I completely understand, I will work on getting a PR in, 

We are currently using RxDb for an offline application for a major insurance company in South Africa. 
I have been tasked with investigating the migration strategies when changing schema/ adding reducers as we are persisting redux state to the RxDb instance. 

Do you mind pointing me to any implementations of migrationStrategies being used that I can look at as a reference as I cant find any online.

**Comment by pubkey** [comment]
No sorry, I do not really have an example project.
There is the test suite with some tests for the [migration-strategies](https://github.com/pubkey/rxdb/blob/master/test/unit/data-migration.test.js) maybe this helps.

**Comment by wtoalabi** [comment]
Well @Njinu, you are not the only one.
I just hit this bug too.
Any idea on how you fixed it?

**Comment by Njinu** [comment]
Yes, I removed the migration with index 0 and it fixed my problem.
