### ISSUE TITLE
upsert will throw an error

### ISSUE THREAD

**Issue by dingchaoyan1983** [pubkey/rxdb#938]
## Info
  - Environment: (browser)
  - Adapter: (IndexedDB)
  - Stack: (Babel, React, etc..)
  -rxdb: 8.0.6

## Code

```js
  const collection = await myDatabase.colleciton(/* ... */);
  await collection.upsert(/* ... */);
  /* ... */
```

when I exec `upsert` it will tell me below errors:
```
TypeError: Object(...) is not a function
    at RxQuery.get (rx-query.js?c233:372)
    at eval (rx-query.js?c233:140)TypeError: Object(...) is not a function
    at RxQuery.get (rx-query.js?c233:372)
    at eval (rx-query.js?c233:140)
```

**Comment by pubkey** [comment]
Sorry but this does not help. Please add a PR with some code to reproduce your problem. You can start by editing [this file](https://github.com/pubkey/rxdb/blob/master/test/unit/bug-report.test.js)
